### ISSUE TITLE
Unable to create invoice after our recent git pull

### ISSUE THREAD

**Issue by CryptoDeity** [lnbits/lnbits#1032]
Everything else seems to be working fine
Message received only when trying to create an invoice.

CLN method 'invoice' failed with 'unknown parameter: amount_msat, this may be caused by a failure to autodetect key=value-style parameters. Please try using the -k flag and explicit key=value pairs of parameters.'.
520

**Comment by callebtc** [comment]
Hey, it sounds like your pyln-client version (the lib that talks to CLN) doesn't match your CLN version but this should be easy to fix:

If you're using CLN 0.X, you need pyln 0.X so for CLN 0.12.0 please install pyln 0.12.0, same goes for CLN 0.11.x, you need pyln 0.11.0.

If you have troubles updating pyln, please share how you installed LNbits (using poetry?) and which CLN version you're running! Thanks 👍

**Comment by talvasconcelos** [comment]
Can it be closed?
