### ISSUE TITLE
How to Update Fly.io instance?

### ISSUE THREAD

**Issue by HamishMacEwan** [lnbits/lnbits#1036]
Managed to follow the instructions and get a working LNbits instance in Fly.io and would now like to upgrade that, hopefully without going through the whole process again.

Is there a short-cut?

Git pulling after stashing local changes and reapplying them, then repeating the `fly deploy` command failed with:

`Error failed to fetch an image or build from source: error connecting to docker: failed building options: failed probing "personal": context deadline exceeded`

Which may be related to limits of the free offer, and will require manual removal of the running instance.  Reading the fly.io documentation hasn't revealed how this might be done.

**Comment by jchames** [comment]
Just  checking are you logged into fly.io via flyctl before issuing 'fly deploy' command? e.g command 'fly auth login'? I am also on the fly hobby package and have no issues deploying upgrades.

**Comment by dni** [comment]
@HamishMacEwan did you figure it out?

**Comment by HamishMacEwan** [comment]
From other comments in the LNbits channel and the one above it seems the answer is to do the initial install/deployment process again, after updating the source.

Had problems with `fly auth login` in that it didn't have a GUI browser, IIRC, but eventually the tokens were found and put in the right place.

I see someone else is having problems with the generated LNURL schemas not being `https://` even when that is the request schema https://t.me/lnbits/49396

I'll give it a crack and leave some documentation here before closing the

**Comment by HamishMacEwan** [comment]
1. cd /home/user/bin/lnbits/lnbits-legend
2. rm pyproject.toml
3. git pull
4. poetry lock
5. fly deploy
6. `--> v4 deployed successfully`

Thank you linesmen, thank you ball boys.
