### ISSUE TITLE
Canceled ATM withdrawal is considered as claimed

### ISSUE THREAD

**Issue by BugerDread** [lnbits/lnbits#1039]
Hi all, 

playing with fossa (offline version) https://github.com/lnbits/fossa
I created LNURL device on legend.lnbits.com, paired it with fossa, I'm able to withdraw to Wallet of Satoshi and Phoenix without problems... 

BUT

- when user scans the QR from fossa to WoS/Phoenix, screen telling him "YOU WILL RECEIVE XYZsats - CANCEL / OK" pops up
- if he press CANCEL here (for example by mistake), he will NOT get any sats of course
- now he have no way to get the funds, because when he scans the QR again he gets "error - payment already claimed"

Thats odd, because if user at the ATM click CANCEL by mistake he have no option how to get his money again...

Is it possible to solve this somehow? Eg. consider the payment claimed only if sats really leave LNbits?

For example when there are not enough funds in the LNbits wallet (eg trying to withdraw 1000sats but there are just 100 on that lnbits account fossa is connected to) it lets me to use the same QR again.

Thank you.

**Comment by callebtc** [comment]
I think this is an issue related to fossa, not lnbits. Closing, feel free to reopen should I've misunderstood.

**Comment by BugerDread** [comment]
I think this is lnbits issue not a FOSSA issue - also discussed this with Ben Arc on telegram

**Comment by BugerDread** [comment]
it seems I don't have permissions to reopen

**Comment by arcbtc** [comment]
This is race condition insulation in lnurldevices lnurl-withdraw logic. Currently its preferred, until I get more time to make more sophisticated, or someone else PRs a more sophisticated approach
