### ISSUE TITLE
Why do we require multiple kinds of keys (admin, invoice etc.) for each backend?

### ISSUE THREAD

**Issue by fiatjaf** [lnbits/lnbits#104]
For example, for `lndrest` we require an admin macaroon, an invoice macaroon and a readonly macaroon; for `lnpay` we require an admin key, an invoice key and a readonly key; for `opennode` we require an admin key and an invoice key; and so on.

If my understanding is correct, this is weird and only makes things harder for a user setting up his LNbits. Since we _do_ require an admin key/macaroon all the times, why don't we just ask for that single one and use it in place of the others?

**Comment by arcbtc** [comment]
I vote for dumping all the keys apart from admin

**Comment by arcbtc** [comment]
Although, We should keep the keys, for the users who want to use LNbits only for invoice creation, and dont want to expose their admin keys.

**Comment by fiatjaf** [comment]
Ok, that makes sense.

**Comment by fiatjaf** [comment]
Wait, wait.

I think that if the user wants to give LNbits credentials without admin capabilities they could still do it if we only required one environment variable, right? It's still less confusing, so if they don't want LNbits to be able to do payments they just use an invoices macaroon for example, and then we'll try to use that to make payments but lnd will complain -- exactly like it is today if they provide one but leave the other blank.

I think we should also rename the environment variables from `LND_REST_ADMIN_MACAROON` to `LND_REST_MACAROON` (with backwards-compatibility to the previous names).
