### ISSUE TITLE
LNbits - logo redesign proposal

### ISSUE THREAD

**Issue by designsats** [lnbits/lnbits#1049]
Hello, 
I use and love LNbits, so I wanted to contribute. I have redesigned its logo to move away from the "Free open source" look and make it seem like a professional commercial project. 

![lnbits](https://user-images.githubusercontent.com/17384787/195208209-702f22d0-0233-4fba-887c-2e6759a65e84.png)

### Downloadable zip with files and guidelines:
https://drive.google.com/drive/folders/1Z53G83ROzVjscp_igLE9V4mOlDinkhOd?usp=sharing

![yellendegen](https://user-images.githubusercontent.com/17384787/195208249-7e57c041-0327-4741-96c0-c98f190d55c7.png)

### My contact
https://twitter.com/AndrejCibik

### Tips
andrejcibik@getalby.com

**Comment by talvasconcelos** [comment]
@arcbtc @blackcoffeexbt

**Comment by arcbtc** [comment]
Ooooo, didnt see this. lovely looking logos. I think we are stuck with one we have for now, but great design!
