### ISSUE TITLE
Fees + remove reserve

### ISSUE THREAD

**Issue by arcbtc** [lnbits/lnbits#107]
Its time we represent fees properly in the UI, and get rid of the depletion attack reserve thing.

To do so would mean also having to go sub-satoshi for the balance, which I think looks ugly as it includes decimals, but if we make the decimal smaller, greyed out, maybe it wont look too bad!

Ideas welcome.

**Comment by fiatjaf** [comment]
What about this?

![2020-10-05-231107_679x661_scrot](https://user-images.githubusercontent.com/1653275/95151052-14abf280-0760-11eb-82c8-387b1583e528.png)

**Comment by arcbtc** [comment]
Ooooo, thats nice

**Comment by arcbtc** [comment]
But dont we need sub sats to show fees? So like a 
<strong>104,175</strong><small>.325</small><strong>sats</strong>

**Comment by arcbtc** [comment]
Or if we need the reserve still we could try and educate folks as to why
![image](https://user-images.githubusercontent.com/33088785/95176125-523a6b00-07b4-11eb-896d-d366fea69e37.png)

**Comment by fiatjaf** [comment]
Are you saying we don't need the reserve? I don't know if we can get rid of it. Maybe we can make it configurable through an environment variable so each host decides.

Maybe someone wants to subsidize, and someone else is using a provider that won't charge fees so it doesn't make sense to have a reserve.
