### ISSUE TITLE
LND_REST_ENDPOINT doesn't connect if specified as hostname

### ISSUE THREAD

**Issue by tehelsper** [lnbits/lnbits#1070]
I've been trying to connect run lnbits as a docker container and connect to the local LND wallet via the REST interface, but I'm having an issue when REST endpoint is a hostname. To handle varying docker networks, it's better to not assume the local gateway is 172.17.01 which you can do by adding '--add-host=host.docker.internal:host-gateway' when launching the container. Then, the hostname can be used and docker sets it to the proper gateway IP.

However, when I use the hostname in the LND_REST_ENDPOINT I get connection error messages. These have actually been seen by a few users for varying reasons and I'm not really sure why in some cases, but I think that's a different issue.

The log looks like this:
```
Oct 22 17:35:36 myNode lnbits[5220]: 2022-10-22 22:35:36.85 | INFO | Retrying connection to backend in 5 seconds...
Oct 22 17:35:41 myNode lnbits[5220]: 2022-10-22 22:35:41.88 | INFO | Retrying connection to backend in 5 seconds...
Oct 22 17:35:46 myNode lnbits[5220]: 2022-10-22 22:35:46.90 | INFO | Retrying connection to backend in 5 seconds...
```

This config fails. I can use curl within the container to get a response from the hostname and it is specified in the /etc/hosts file properly.
```
# LndRestWallet
LND_REST_ENDPOINT=https://host.docker.internal:10080/
LND_REST_CERT="/app/tls.cert"
LND_REST_MACAROON="/app/admin.macaroon"
```

And this works just fine.
```
# LndRestWallet
LND_REST_ENDPOINT=https://172.17.0.1:10080/
LND_REST_CERT="/app/tls.cert"
LND_REST_MACAROON="/app/admin.macaroon"
```

**Comment by callebtc** [comment]
Is the hostname `host.docker.internal` accessible for other apps? For example, can you curl on that port?

**Comment by tehelsper** [comment]
Yeah, the hostname accessible from within the lnbits container. I can get into the container, install curl, and access the mynode webui running on port 80. However, if I set it in the lnbits config file as a rest url, I get access errors. It works fine with a static IP.

```
root@6b30a258693c:/app# curl host.docker.internal:80/login
<!DOCTYPE html lang="en">
    <head>
        <title>myNode Login</title>
        <link rel="apple-touch-icon" sizes="180x180" href="/static//favicons/apple-touch-icon.png">
<link rel="shortcut icon" type="image/png" sizes="32x32" href="/static//favicons/favicon-32x32.png">
...
```

I've tried various hostnames as well in case it was some sort of parsing issue, but it didn't seem to help. Does the app somehow require a signed cert if a hostname is used?

**Comment by arcbtc** [comment]
Sounds like a devops complication beyond our scope

**Comment by tehelsper** [comment]
Not really sure how that's the case - within the LNBits container everything else can use the hostname just fine. The only issue is with lnbits when the connection to LND fails. It's not a big deal though since the IP address works fine. It would just be more failure-resistant to not have hardcoded IP addresses and instead pick up on what docker assigns.

**Comment by callebtc** [comment]
> Does the app somehow require a signed cert if a hostname is used?

If you use https, it depends on your system's python afaik. From my experience, yes. Usually it wants a working cert. Internal communication can be / should be? http, so you might try that without `https`.

**Comment by tehelsper** [comment]
Can you access the LND REST API without https? I thought the API was https-only. Maybe I need to set another tlsextradomain in the lnd config.

**Comment by PraiaBitcoin** [comment]
Thank you very much for this discussion. We have five local nodes depending on this update.

**Comment by callebtc** [comment]
> Can you access the LND REST API without https? I thought the API was https-only. Maybe I need to set another tlsextradomain in the lnd config.

Afaik yes. Could you try to uncomment your CERT in your .env file to test?

**Comment by tehelsper** [comment]
So, I've figured it out. LNBits must be checking for a cert that includes a domain name that matches the one in the config file. IIRC, Zeus and some other wallets have stopped doing this (or at least make is configurable) to avoid this issue.

I was able to get the hostname to work by adding this line to the LND config and then regenerating my TLS certificate and restarting LNBits.

```
tlsextradomain=host.docker.internal
```

**Comment by HamishMacEwan** [comment]
The host private IP works and is already in the cert IIRC.

```
X509v3 Subject Alternative Name:
                DNS:myNode, DNS:localhost, DNS:mynode.local, DNS:mynode.macewan.nz, DNS:rdv3h3ywdnjx34unf4zplnl4e5bcgckmsqdaomhslwvemyyuw7bbi2ad.onion, DNS:rdv3h3ywdnjx34unf4zplnl4e5bcgckmsqdaomhslwvemyyuw7bbi2ad.onion, DNS:unix, DNS:unixpacket, DNS:bufconn, IP Address:127.0.0.1, IP Address:0:0:0:0:0:0:0:1, IP Address:192.168.1.50, IP Address:172.17.0.1, IP Address:FE80:0:0:0:D029:4145:A1C0:D16F, IP Address:0.0.0.0
```
Not sure how the duplicate on the .onion address occurred.  Lot's of tweaks done a long time ago.

And I'd not that in the past, hostnames with terminal `/` did cause some problems.
