### ISSUE TITLE
Scan feature not working

### ISSUE THREAD

**Issue by ssurfertuga** [lnbits/lnbits#1072]
Scan feature not working on fresh install. LNbits installed using method 1 (Poetry) on Ubuntu 20.04 and running as a daemon on a private network IP address (10.0.1.x) on port 5000. The interface is accessed over VPN to the local network without any kind of firewall restrictions.

Screenshot below. That's what happens. The small window pops up and no request on Chrome to use the webcam and also the video image doesn't show up.

<img width="2049" alt="Screenshot 2022-10-23 at 18 46 11" src="https://user-images.githubusercontent.com/8077390/197427281-92a6fdd7-f742-4f6e-8789-b1cfe7110def.png">

**Comment by dni** [comment]
it should be working wit ha camera, on firefox and brave i tested it,

![jojojo](https://user-images.githubusercontent.com/1743657/197488476-dbff1c22-02b5-4af8-9d3e-931452f985b6.png)


does it show you camera here? https://gruhn.github.io/vue-qrcode-reader/demos/DecodeAll.html
