### ISSUE TITLE
LNURLs need to be delivered over a publically accessible https domain or Tor. [After updating]

### ISSUE THREAD

**Issue by eddieoz** [lnbits/lnbits#1079]
Hello,

In previous versions, before the implementation of User Manager, it was possible to recognise the redirected SSL by adding the parameter `--forwarded-allow-ips '*'` at the end of `uvicorn lnbits.__main__:app --port $LNBITS_PORT --host $LNBITS_HOST` line of Dockerfile, when using containers.

I've seen it changed from `uvicorn` to `poetry` for running the platform, and now I got the error back when trying to run LNURLw extension. Seems poetry hasn't the same parameter or support to allow forwarded IPs.

Is out there any workaround for this issue?

Thanks in advance.

**Comment by leesalminen** [comment]
I ran into the same issue today. Check out this PR: https://github.com/lnbits/lnbits/pull/1077

When I add the `FORWARDED_ALLOW_IPS="*"` env var to my LNBits installation, LNURLs start working again as expected.

Hope this helps!

**Comment by HamishMacEwan** [comment]
This variable can be set in the environment as well as the command line according to:

https://docs.gunicorn.org/en/stable/settings.html#forwarded-allow-ips

A number of users of the fly.io service have succeeded by adding 

`FORWARDED_ALLOW_IPS="*"`

To `fly.toml` then performing `fly deploy`

This also solves part 2 of https://github.com/lnbits/lnbits/issues/1050#issuecomment-1276918847

**Comment by eddieoz** [comment]
Thanks @HamishMacEwan 

I can confirm it is solved, by setting it on env in Dockerfile (as you can see below). 

For anyone who found this issue, after modifying `Dockerfile` it is needed to run `docker build` again.

```
FROM python:3.9-slim

RUN apt-get clean
RUN apt-get update
RUN apt-get install -y curl pkg-config build-essential
RUN curl -sSL https://install.python-poetry.org | python3 -

ENV PATH="/root/.local/bin:$PATH"

WORKDIR /app

COPY . .

RUN poetry config virtualenvs.create false
RUN poetry install --no-dev --no-root
RUN poetry run python build.py

ENV LNBITS_PORT="5000"
ENV LNBITS_HOST="0.0.0.0"
ENV FORWARDED_ALLOW_IPS="*"

EXPOSE 5000

CMD ["sh", "-c", "poetry run lnbits --port $LNBITS_PORT --host $LNBITS_HOST"]
```

**Comment by jjmmbb** [comment]
I'm experiencing the same issue as described. My setup is as follows:

LNBITS <-> NGINX PROXY <-> CLOUDFLARE TUNNEL (SSL)

The URL is https://, but I am still receiving this message.
