### ISSUE TITLE
Errors when trying to create invoice

### ISSUE THREAD

**Issue by misovan** [lnbits/lnbits#108]
I installed lnbits on Ubuntu VPS running a testnet LND lightning node, setting up .env file and installed necessary grpc libraries. After running the lnbits server I am able to create wallet, however this is what I get when trying to create an invoice:
`table apipayments has no column named checking_id`

At the same time, check pending payments endpoint returns an error as well:
`no such column: bolt11`

I checked my data directories for database files and they are created.
Is there something I might have ommitted? Is there any way to check whether the connection to lnd node has been established (like calling lnd's getinfo call)? Thank you for help & guidance!

**Comment by fiatjaf** [comment]
It seems the database migrations only run partially, which is odd. Did you just install from `master`? Or did you have an old installation and updated to `master` now and then run it again?

What command are you using to run the LNbits server?

Running `quart migrate` should help you anyway (you must run that inside the virtualenv, or `./venv/bin/quart migrate`).

If nothing helps, can you please run `sqlite3 <your-lnbits-db-path>/database.sqlite3 'select * from dbversions'`?

**Comment by misovan** [comment]
Hi thank you for quick answer. This is how I am running the server alongside the output:

```
lnd-testnet@sfc:~/lnbits-0.1.1$ pipenv run python -m lnbits
Loading .env environment variables…
/home/lnd-testnet/.local/share/virtualenvs/lnbits-0.1.1-3p68qwXV/lib/python3.7/site-packages/scss/selector.py:54: FutureWarning: Possible nested set at position 329
  ''', re.VERBOSE | re.MULTILINE)
running migration core.1
running migration core.2
running migration lnurlp.1
running migration usermanager.1
running migration events.1
running migration events.2
running migration tpos.1
running migration withdraw.1
running migration withdraw.2
running migration paywall.1
running migration paywall.2
running migration lnticket.1
running migration lnticket.2
Running on http://127.0.0.1:5000 (CTRL + C to quit)
```
And this is the return from sqlite3 select statement:
```
core|2
lnurlp|1
usermanager|1
events|2
tpos|1
withdraw|2
paywall|2
lnticket|2
```
As a sidenote to installation - After cloning master from github I could not get installation of dependencies done using lnbits.org docs (with python venv) as it complained about non existing version of hypercorn in requirements.txt. So I went with downloading the release archive and did pipenv installation described on github. I as well tried `pipenv run quart migrate`, however I got back '`No such command: migrate`'

**Comment by fiatjaf** [comment]
That seems correct, are you sure you're accessing the same LNbits server that outputted all those migration lines and was running on http://127.0.0.1:5000? I can't imagine anything wrong.

By the way, this has nothing to do with lnd connection. But indeed I think we should output debug information about connection status, database status etc. when starting LNbits, it will be helpful.

**Comment by fiatjaf** [comment]
`sqlite3 <your-lnbits-db-path>/database.sqlite3 '.schema apipayments'` will confirm that the columns `checking_id` and `bolt11` do exist. But at this point it's gotta be something else.

What is the value of `LNBITS_DATA_FOLDER` in your `.env` file?

**Comment by fiatjaf** [comment]
I just pushed a commit to `master` that will print your data folder when starting LNbits with `python -m lnbits`.

**Comment by misovan** [comment]
Hi, I cleaned the environment and data folder, cloned the current master and I send you my install process and ouputs step by step (comments behind hashes are added as explanations):

```
lnd-testnet@sfc:~/lnbits$ pipenv install --dev
Creating a virtualenv for this project…
Pipfile: /home/lnd-testnet/lnbits/Pipfile
Using /usr/bin/python3.7m (3.7.5) to create virtualenv…
⠏ Creating virtual environment...created virtual environment CPython3.7.5.final.0-64 in 494ms
  creator CPython3Posix(dest=/home/lnd-testnet/.local/share/virtualenvs/lnbits-wqECVPIq, clear=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/lnd-testnet/.local/share/virtualenv)
    added seed packages: pip==20.2.3, setuptools==50.3.0, wheel==0.35.1
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
✔ Successfully created virtual environment!
Virtualenv location: /home/lnd-testnet/.local/share/virtualenvs/lnbits-wqECVPIq
Installing dependencies from Pipfile.lock (ca7309)…
  🐍   ▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉▉ 64/64 — 00:00:52
To activate this project's virtualenv, run pipenv shell.
Alternatively, run a command inside the virtualenv with pipenv run.

pipenv run pip install lndgrpc
pipenv run pip install lnd-grpc ### not mentioned in docs but required
pipenv run pip install purerpc  ### mentioned in docs with typo

pipenv run python -m lnbits

lnd-testnet@sfc:~/lnbits$ pipenv run python -m lnbits
Loading .env environment variables…
running migration core.1
running migration core.2
running migration lnurlp.1
running migration lnurlp.2
running migration usermanager.1
running migration events.1
running migration events.2
running migration tpos.1
running migration withdraw.1
running migration withdraw.2
running migration paywall.1
running migration paywall.2
running migration lnticket.1
running migration lnticket.2
Starting LNbits with
  - site title: Sfc-LNbits
  - debug: True
  - data folder: /home/lnd-testnet/lnbitsdata
  - funding source: LndWallet
  - service fee: 0.0

Running on http://127.0.0.1:5000 (CTRL + C to quit)
Running on 127.0.0.1:5000 over http (CTRL + C to quit)
[2020-10-06 21:57:05 +0200] [32310] [INFO] Running on 127.0.0.1:5000 over http (CTRL + C to quit) 

### I can create the wallet but app then fails to get/post payments endpoint with above mentioned errors. Same from frontend ### as with curl

lnd-testnet@sfc:~/lnbits$ sqlite3 /home/lnd-testnet/lnbitsdata/database.sqlite3 '.schema apipayments'
CREATE TABLE apipayments (
            payhash TEXT NOT NULL,
            amount INTEGER NOT NULL,
            fee INTEGER NOT NULL DEFAULT 0,
            wallet TEXT NOT NULL,
            pending BOOLEAN NOT NULL,
            memo TEXT,
            time TIMESTAMP NOT NULL DEFAULT (strftime('%s', 'now')),

            UNIQUE (wallet, payhash)
        );
```

**Comment by fiatjaf** [comment]
> ### not mentioned in docs but required

This is an indication that you're running an old version as it shouldn't be required.

But mysteriously your migration logs indicate you are running a new version.

Can you paste the output of `git rev-parse HEAD` in the lnbits folder?

**Comment by fiatjaf** [comment]
Just pushed a thing to include current version in that which I hope will become helpful debugging information next time: 24c82019205137e8d0128c17066620385d3ec309

**Comment by misovan** [comment]
Head: 9a16dfa96092dbd185780cb7cf65d6584b660806

It might not be required in current master. I got the error when I used archive of 0.1.1 release and I automatically repeated the install it after cloning master, not aware it might not be needed anymore.

**Comment by misovan** [comment]
After cleaning & installing from master:

```
Loading .env environment variables…
Starting LNbits with
  - git version: 24c82019205137e8d0128c17066620385d3ec309
  - site title: Surfcity-LNbits
  - debug: True
  - data folder: /home/lnd-testnet/lnbitsdata
  - funding source: LndWallet
  - service fee: 0.0

Running on http://127.0.0.1:5000 (CTRL + C to quit)
```

**Comment by fiatjaf** [comment]
I just ran the following (on a blank directory):

```
git clone git@github.com:lnbits/lnbits.git
cd lnbits
pipenv install --dev
cp .env.example .env
pipenv run python -m lnbits
```

Got the same migration outputs as you:

```
Loading .env environment variables…
running migration core.1
running migration core.2
running migration tpos.1
running migration withdraw.1
running migration withdraw.2
running migration lnurlp.1
running migration lnurlp.2
running migration paywall.1
running migration paywall.2
running migration usermanager.1
running migration lnticket.1
running migration lnticket.2
running migration events.1
running migration events.2
Starting LNbits with
  - git version: 0b1f3c22e05786a5894f4a2e02f4b3c905f0acda
  - site title: LNbits
  - debug: True
  - data folder: .
  - funding source: VoidWallet
  - service fee: 0.0

Running on http://127.0.0.1:5000 (CTRL + C to quit)
```

But `sqlite3 database.sqlite3 '.schema apipayments'` shows the correct output:

```
CREATE TABLE apipayments (
            checking_id TEXT NOT NULL,
            amount INTEGER NOT NULL,
            fee INTEGER NOT NULL DEFAULT 0,
            wallet TEXT NOT NULL,
            pending BOOLEAN NOT NULL,
            memo TEXT,
            time TIMESTAMP NOT NULL DEFAULT (strftime('%s', 'now')), hash TEXT, preimage TEXT, bolt11 TEXT, extra TEXT,

            UNIQUE (wallet, checking_id)
        );
CREATE INDEX by_hash ON apipayments (hash);
```

I have no idea of what is going on with your setup.

**Comment by misovan** [comment]
Hi I tried to put lnbits into isolated LXD container. After setting up networking to/from container, lnbits works as expected and connects to LND. Closing the issue, seems like quite weird special case. Thanks for your support.
