### ISSUE TITLE
Nix flake error with `pyScss`

### ISSUE THREAD

**Issue by afilini** [lnbits/lnbits#1088]
**Describe the bug**

Trying to use lnbits with the nix flake file I'm getting the error:

```
building the system configuration...
error: unsupported build system requirement pyScss
```

**To Reproduce**
1. Run `nix build github:lnbits/lnbits` and you should get the error

I'm not sure why `pyScss` was added, but maybe it's not perfectly standard-compliant since [poetry2nix](https://github.com/nix-community/poetry2nix) fails on it.

**Comment by arcbtc** [comment]
Our nix build is broken. The issue is dependencies installed in poetry not being used in the poetry build file, seems to be a poetry update. Our plan is to get the application built as we want then use nix as our quality standard as we come out of beta. I'll make a note in the install guide.

**Comment by prusnak** [comment]
This should have been left open, since the issue was not fixed and I spent 1 hour today trying to figure out what's wrong with my setup. Please reopen ...

**Comment by arcbtc** [comment]
Reopened. Sorry about that 😬. I owe you 1hr.

**Comment by arcbtc** [comment]
Chill. This is an issue for later, as noted in the install guide. Post-beta we will some nix whizz a bounty for fixing our nix build
![image](https://user-images.githubusercontent.com/33088785/222207776-231bff64-05b7-450a-bb1b-05595e3258aa.png)

**Comment by afilini** [comment]
I think the pyScss error is caused by the fact that in nixpkgs it is published under `pythonPackages.pyscss` (note the un-capitalized `s`). Changing `pyproject.toml` to use `pyscss` instead fixes that error, but now I'm getting a different issue about infinite recursion caused by setuptools...

**Comment by prusnak** [comment]
> Changing `pyproject.toml` to use `pyscss` instead fixes that error, but now I'm getting a different issue about infinite recursion caused by setuptools...

You can try removing `pyScss` from `pyproject.toml:57`:

``` patch
--- a/pyproject.toml
+++ b/pyproject.toml
@@ -54,7 +54,7 @@ flake8 = { version = "^6.0.0", python = ">=3.8.1" }
 pylint = { version = "^2.15.10", python = ">=3.7.2" }
 
 [build-system]
-requires = ["poetry-core>=1.0.0", "pyScss"]
+requires = ["poetry-core>=1.0.0"]
 build-backend = "poetry.core.masonry.api"
 
 [tool.poetry.scripts]
```

**Comment by prusnak** [comment]
Coincidentally, I was playing with the issue earlier today and being not able to crack it once again, I opened an issue on NixOS community forum. Maybe someone can help us: https://discourse.nixos.org/t/help-with-flake-poetry2nix-unsupported-build-system-requirement-pyscss/26137

**Comment by dni** [comment]
> > Changing `pyproject.toml` to use `pyscss` instead fixes that error, but now I'm getting a different issue about infinite recursion caused by setuptools...
> 
> You can try removing `pyScss` from `pyproject.toml:57`:
> 
> ```diff
> --- a/pyproject.toml
> +++ b/pyproject.toml
> @@ -54,7 +54,7 @@ flake8 = { version = "^6.0.0", python = ">=3.8.1" }
>  pylint = { version = "^2.15.10", python = ">=3.7.2" }
>  
>  [build-system]
> -requires = ["poetry-core>=1.0.0", "pyScss"]
> +requires = ["poetry-core>=1.0.0"]
>  build-backend = "poetry.core.masonry.api"
>  
>  [tool.poetry.scripts]
> ```
> 
> But in any case, if something needs patching it's poetry2nix and not `pyproject.toml`. Let's see if we are able to crack the code :D

if you remove it like that poetry install will fail :D

**Comment by afilini** [comment]
Yeah you shouldn't remove it, just change it to `pyscss` without the capital S

**Comment by afilini** [comment]
Btw I understand nix support is not a priority right now, but keep in mind that with nix you can't modify the source code directory because it's in the nix store which is read-only.

So the new thing where you can install extensions will have to be changed quite a bit, you'll have to install the extensions in a separate writable path and then load them from there. Just a heads up.
