### ISSUE TITLE
[BUG] sqlite3.OperationalError: duplicate column name: branch_index

### ISSUE THREAD

**Issue by ChuckNorrison** [lnbits/lnbits#1092]
**Describe the bug**
Exception in the logs at startup lnbits 

**To Reproduce**
Start lnbits

**Expected behavior**
No Exception

**Desktop (please complete the following information):**
 - LNbits version: 0.9.1

**Additional context**

> Oct 27 22:57:25 raspberrypi sh[2742335]: 2022-10-27 22:57:25.91 | INFO | Uvicorn running on http://127.0.0.1:5000 (Press CTRL+C to quit)
> Oct 27 22:57:25 raspberrypi sh[2742335]: Task exception was never retrieved
> Oct 27 22:57:25 raspberrypi sh[2742335]: future: <Task finished name='Task-2' coro=<migrate_databases() done, defined at ./lnbits/commands.py:56> exception=OperationalError('(sqlite3.OperationalError) duplicate column name: branch_index')>
> Oct 27 22:57:25 raspberrypi sh[2742335]: Traceback (most recent call last):
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
> Oct 27 22:57:25 raspberrypi sh[2742335]:     self.dialect.do_execute(
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
> Oct 27 22:57:25 raspberrypi sh[2742335]:     cursor.execute(statement, parameters)
> Oct 27 22:57:25 raspberrypi sh[2742335]: sqlite3.OperationalError: duplicate column name: branch_index
> Oct 27 22:57:25 raspberrypi sh[2742335]: The above exception was the direct cause of the following exception:
> Oct 27 22:57:25 raspberrypi sh[2742335]: Traceback (most recent call last):
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "./lnbits/commands.py", line 114, in migrate_databases
> Oct 27 22:57:25 raspberrypi sh[2742335]:     await run_migration(ext_conn, ext_migrations)
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "./lnbits/commands.py", line 76, in run_migration
> Oct 27 22:57:25 raspberrypi sh[2742335]:     await migrate(db)
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "./lnbits/extensions/watchonly/migrations.py", line 44, in m002_add_columns_to_adresses
> Oct 27 22:57:25 raspberrypi sh[2742335]:     await db.execute(
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "./lnbits/db.py", line 81, in execute
> Oct 27 22:57:25 raspberrypi sh[2742335]:     return await self.conn.execute(self.rewrite_query(query), values)
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy_aio/base.py", line 291, in execute
> Oct 27 22:57:25 raspberrypi sh[2742335]:     rp = await self._run_in_thread(
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy_aio/base.py", line 234, in _run_in_thread
> Oct 27 22:57:25 raspberrypi sh[2742335]:     return await _self._worker.run(_func, args, kwargs)
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy_aio/asyncio.py", line 70, in run
> Oct 27 22:57:25 raspberrypi sh[2742335]:     return request.response.unwrap()
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/outcome/_impl.py", line 138, in unwrap
> Oct 27 22:57:25 raspberrypi sh[2742335]:     raise captured_error
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1003, in execute
> Oct 27 22:57:25 raspberrypi sh[2742335]:     return self._execute_text(object_, multiparams, params)
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1172, in _execute_text
> Oct 27 22:57:25 raspberrypi sh[2742335]:     ret = self._execute_context(
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1316, in _execute_context
> Oct 27 22:57:25 raspberrypi sh[2742335]:     self._handle_dbapi_exception(
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1510, in _handle_dbapi_exception
> Oct 27 22:57:25 raspberrypi sh[2742335]:     util.raise_(
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 182, in raise_
> Oct 27 22:57:25 raspberrypi sh[2742335]:     raise exception
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
> Oct 27 22:57:25 raspberrypi sh[2742335]:     self.dialect.do_execute(
> Oct 27 22:57:25 raspberrypi sh[2742335]:   File "/home/lnbits/lnbits/venv/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
> Oct 27 22:57:25 raspberrypi sh[2742335]:     cursor.execute(statement, parameters)
> Oct 27 22:57:25 raspberrypi sh[2742335]: sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) duplicate column name: branch_index
> Oct 27 22:57:25 raspberrypi sh[2742335]: [SQL: ALTER TABLE watchonly.addresses ADD COLUMN branch_index INTEGER NOT NULL DEFAULT 0;]
> Oct 27 22:57:25 raspberrypi sh[2742335]: (Background on this error at: http://sqlalche.me/e/13/e3q8)
> 
>

**Comment by callebtc** [comment]
This looks like a migration error. Are you in a position to delete your database to start from scratch? That would be an easy fix but we should have a look.

**Comment by motorina0** [comment]
> This looks like a migration error
  - 💯 

I do not see any obvious cause. Lets see what @ChuckNorrison responds to your question.

**Comment by ChuckNorrison** [comment]
maybe we can get it updated to the current lnbits version and migrate from sqlite to postgresql. This was never migrated and is a very old installation of LNBits on Raspiblitz.

I tested to delete a extension database file and let it created automatically. But it is 0 bytes and empty. if i connect to the database file there are no tables found. 

Recently i was able to fix lnurlp extensions by manually create a missing column [here](https://github.com/lnbits/lnbits/issues/1047). With watchonly extension i was able to fix it with manually create the database and tables.

> admin@192.168.8.160:/mnt/hdd/app-data/LNBits ₿ ls -laht
> total 580K
> drwxr-xr-x  2 lnbits  lnbits  4.0K Nov  2 10:00 .
> -rw-r--r--  1 lnbits  lnbits  172K Nov  1 15:40 database.sqlite3
> -rw-r--r--  1 lnbits  lnbits   16K Nov  1 15:40 ext_lnurlp.sqlite3
> -rw-r--r--  1 lnbits  lnbits   20K Oct 30 09:21 ext_usermanager.sqlite3
> -rw-r--r--  1 lnbits  lnbits     0 Oct 28 11:59 ext_lnaddress.sqlite3
> -rw-r--r--  1 lnbits  lnbits   28K Oct 28 00:13 ext_watchonly.sqlite3
> drwxr-xr-x 20 bitcoin bitcoin 4.0K Oct 27 23:41 ..
> -rw-r--r--  1 lnbits  lnbits   12K Oct 27 22:50 ext_scrub.sqlite3
> -rw-r--r--  1 lnbits  lnbits     0 Oct  6 19:52 ext_scrub.sqlite3__
> -rw-r--r--  1 lnbits  lnbits     0 Oct  6 19:52 ext_splitpayments.sqlite3
> -rw-r--r--  1 lnbits  lnbits     0 Sep 18 21:17 ext_lnurlpos.sqlite3
> -rw-r--r--  1 lnbits  lnbits   20K Sep 18 21:17 ext_lnurldevice.sqlite3
> -rw-r--r--  1 lnbits  lnbits   56K Nov  9  2021 ext_offlineshop.sqlite3
> -rw-r--r--  1 lnbits  lnbits   20K Oct 17  2021 ext_livestream.sqlite3
> -rw-r--r--  1 lnbits  lnbits   12K Oct 17  2021 ext_satspay.sqlite3
> -rw-r--r--  1 lnbits  lnbits   24K Oct  7  2021 ext_paywall.sqlite3
> -rw-r--r--  1 lnbits  lnbits   12K Oct  6  2021 ext_tpos.sqlite3
> -rw-r--r--  1 lnbits  lnbits   28K Apr 11  2021 ext_bleskomat.sqlite3
> -rw-r--r--  1 lnbits  lnbits   36K Apr 11  2021 ext_withdraw.sqlite3
> -rw-r--r--  1 lnbits  lnbits   20K Apr 11  2021 ext_subdomains.sqlite3
> -rw-r--r--  1 lnbits  lnbits   24K Apr 11  2021 ext_captcha.sqlite3
> -rw-r--r--  1 lnbits  lnbits   28K Dec 14  2020 ext_lnticket.sqlite3
> -rw-r--r--  1 lnbits  lnbits   28K Oct 31  2020 ext_events.sqlite3
> -rw-r--r--  1 lnbits  lnbits     0 Oct 31  2020 ext_lndhub.sqlite3
> -rw-r--r--  1 lnbits  lnbits     0 Oct 31  2020 ext_example.sqlite3
> -rw-r--r--  1 lnbits  lnbits   12K Aug 12  2020 ext_amilk.sqlite3
> 

here the scrub extension was fixed manually. now i stuck on lnaddress. Permissions looks fine to me. The related Service file is using the same user. Once a database and tables exists, the extension works and new entries gets created.

**Comment by ChuckNorrison** [comment]
i did a setup of a brand new environment for testing. Maybe this is related to https://github.com/lnbits/lnbits/issues/1101
