### ISSUE TITLE
[BUG] Custom QR Template LNURLw misplaced

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/lnbits#1097]
Wanted to insert an own png as custom design to a voucher and tried to find out how the png should look like. 
A DIN A4 sized png input is not filled correctly. 
Prints are again different.

lnbits/extensions/withdraw/templates/withdraw/print_qr_custom.html

Input File 
![AVOT_test](https://user-images.githubusercontent.com/63317640/198846182-ac8567ef-9ba3-400c-996f-8adcd2fc5f5b.png)

output shown before printing
<img width="429" alt="Bildschirmfoto 2022-10-29 um 19 56 04" src="https://user-images.githubusercontent.com/63317640/198846201-699fd311-78c7-4ab1-b461-e1c06c395ab3.png">

print
![photo_2022-10-29_20-00-43](https://user-images.githubusercontent.com/63317640/198846366-cb2773b6-31ed-4707-8760-4afe5df597f9.jpg)

Smth wrong with a DINA4 Input ? 

Is there a png somewhere, that people can easily change to their needs ?

**Comment by callebtc** [comment]
Is this a bug with the image or with the printer?

**Comment by arbadacarbaYK** [comment]
With two ppl we each tried different printers, both same same

**Comment by talvasconcelos** [comment]
What is the file your trying to use as custom design?
Unless you mess with the html/css you should use this design as your template! https://www.figma.com/file/GdrmgnSg27VmhnvVZlkXz7/LNVoucher_Template?node-id=0%3A1

https://github.com/lnbits/lnbits/blob/main/lnbits/static/images/default_voucher.png

https://github.com/lnbits/lnbits/blob/main/lnbits/static/images/voucher_template.svg

**Comment by talvasconcelos** [comment]
@arbadacarbaYK have you tried the files listed above? Is this issue still relevant or can it be closed?

**Comment by arbadacarbaYK** [comment]
This worked, thanks for the links! My assumption that this must be a DINA4 template was just wrong 😅

**Comment by arbadacarbaYK** [comment]
🙈 stopped working for whatever reason on legend and on own lnbits :( 
Templates are not used when linked. Not your links and not mine.

Tried a few ways
1) Downloaded the voucher.svg from above link, saved as png in the size of the .png in above link
2) Used above figma and copied it to ps, saved 1:1 as .png in the size of the github .png, linked from drive
3) downloaded the png from above github link and linked from my drive
https://drive.google.com/file/d/1Vki5V5Xaw31PLUdbkOQTYKGCw0K8FVum/view?usp=sharing
4) Used above figma and copied it to ps, saved with changed design as .png in the size of above .png, linked from drive
https://drive.google.com/file/d/1zHrXT4CWoLgC1xnyIlS8JFt1AzTVcg7e/view?usp=sharing
5) inserted the github link to above file 

None of this did work. 

It should show up on clicking "the eye" and then "print", right ? 
The QR is shown (to be exact two with an overlay which itself is an error) but no design t is shown.
https://legend.lnbits.com/withdraw/print/9fzXTnquqN9xBkYpm24xFk

**Comment by talvasconcelos** [comment]
Github does some weird thing to the images, if using an image from github try and add `?raw=true` to the end of the link:

`https://github.com/lnbits/lnbits/blob/main/lnbits/static/images/default_voucher.png?raw=true`

Best bet, upload image to imgur, or something similar, and use an URL that opens the image in the browser, not a page with the image inside!

**Comment by arbadacarbaYK** [comment]
worked thanks! Would be nice to have that as a hint to the URL-Input-field
