### ISSUE TITLE
[BUG] "Commit version: unknown"

### ISSUE THREAD

**Issue by HamishMacEwan** [lnbits/lnbits#1099]
**Describe the bug**
The `Commit version` on the main page sometimes appears as **unknown**

**To Reproduce**
This seems to be the result of putting `lnbits` in a container without access to `git`

LNBITS_VERSION is LNBITS_COMMIT which is set by a call to `git`
https://github.com/lnbits/lnbits/blob/d64feec2a54437d70bf43b8cd9f544bcf143c8c9/lnbits/settings.py#L71

**Expected behavior**
That the commit information be available even within containers.

**Additional context**

Tracked this down by replacing the unhelpful **unknown** value with the more informative 
```
except:
    LNBITS_COMMIT = LNBITS_PATH
```

**Comment by callebtc** [comment]
Good catch, thanks! Would you consider submitting a PR with a fix?

**Comment by HamishMacEwan** [comment]
Would be happy to, but I'm kind of a mostly read-only code person.

**Comment by HamishMacEwan** [comment]
Isn't there some way to get Github to instantiate some git.related constants, what else is .git for?

**Comment by dni** [comment]
i think this was refactoered some time ago, is this issue still relevant?

**Comment by arbadacarbaYK** [comment]
> i think this was refactored some time ago, is this issue still relevant?

Not seen since 0.10 anylonger. Xan be closed, right @HamishMacEwan ?

**Comment by dni** [comment]
yes, commit version is also removed on latest
