### ISSUE TITLE
conv.py raises exception "integer out of range"

### ISSUE THREAD

**Issue by ssurfertuga** [lnbits/lnbits#1105]
While migrating SQLite to PostgreSQL (LNbits has a few wallets already) this exception is raised:

`Traceback (most recent call last):
  File "/home/ramosh/lnbits-legend/tools/conv.py", line 95, in insert_to_pg
    cursor.execute(query, d)
psycopg2.errors.NumericValueOutOfRange: integer out of range`

Any ideas?

**Comment by ChuckNorrison** [comment]
on the main branch there is a bigint fix for large amount of sat in wallets. 
https://github.com/lnbits/lnbits/pull/1030

**Comment by motorina0** [comment]
> on the main branch there is a bigint fix for large amount of sat in wallets. #1030

@ssurfertuga does this PR solve your problem? can the issue be closed?

**Comment by ssurfertuga** [comment]
Yes, all good. It can be closed.Thanks—Hugo ***@***.***@_Hugo_Ramos_www.hugoramos.eu“Nobody expects the Spanish Inquisition!” - Monty PythonsOn 14 Nov 2022, at 12:04, Vlad Stan ***@***.***> wrote:﻿

on the main branch there is a bigint fix for large amount of sat in wallets. #1030

@ssurfertuga does this PR solve your problem? can the issue be closed?
