### ISSUE TITLE
[BUG] problem getting wallets in user manager

### ISSUE THREAD

**Issue by SovereignCraft** [lnbits/lnbits#1113]
Issue getting wallets with User Manager

Running MyNode build, most recent update.
 
When using the API call to get wallets in user manager, it is returning Admin Key Required. I have tried re-making users and it seems to make no difference. I cannot seem to find any way to pull the wallets info. All other features seem to work that I've tried thus far. 

**Desktop (please complete the following information):**
 - LNbits version: 0.9.4
 - Database default

**Comment by SovereignCraft** [comment]
The format of the get request is not specified correctly in that case and when I include the admin_id it then says wallet not found. 
I literally cannot find any way to pull the wallets, so at minimum, the documentation needs updating and I still can't get it to work.

**Comment by SovereignCraft** [comment]
The format of the get request is not specified correctly in that case and when I include the admin_id it then says wallet not found.
I literally cannot find any way to pull the wallets, so at minimum, the documentation needs updating and I still can't get it to work.

**Comment by talvasconcelos** [comment]
just tried this... it works:

`curl -X GET https://your_lnbits_URL/usermanager/api/v1/wallets -H "X-Api-Key: admin_key"`

**Comment by SovereignCraft** [comment]
Okay so you use the users' admin key but still send the header with the value of "X-Api-Key"? That's something I did not try 🤪.
Thank you for your support. Can't wait to get my project done. (My avatar is a big hint) ⚡💪

**Comment by talvasconcelos** [comment]
don't add anything to `.../wallet` the user is not needed!! 
it should b: `curl -X GET http://192.168.1.10:5000/usermanager/api/v1/wallets -H "X-Api-Key: c96992***********59d79d4e9"`

Anyway, a PR is in that fixes the curl examples!

**Comment by SovereignCraft** [comment]
okay. I tried that and am still getting "wallet does not exist", but perhaps there's another issue with my build. I'm unfortunately running MyNode and I didn't want to get into the weeds, but I'm realizing how early we are😝. Guess I may need to go custom. 
`curl -X GET http://192.168.1.10:5000/usermanager/api/v1/wallets -H "X-Api-Key: c96992f26**************79d4e9"`
{"detail":"Wallet does not exist."}
