### ISSUE TITLE
Documentation Error on Wallet API "Decode an Invoice", incorrect Body

### ISSUE THREAD

**Issue by thebrandonlucas** [lnbits/lnbits#1119]
It appears the documentation for the lnbits wallet api "decode an invoice" (`POST /api/v1/payments/decode`) is wrong.

Under `Body (application/json)`, it lists `{"invoice": <string>}`, while the `curl` example uses `'{"data": <bolt11/lnurl, string>}'`.

`Body (application/json)` should list `'{"data": <bolt11/lnurl, string>}'` to match the correct `curl` example.

**Comment by talvasconcelos** [comment]
That's just the way `curl` works, i think... If you're using fetch/axios whatever, you don't do `{data: ...}`
