### ISSUE TITLE
Extension to turn an LNbits wallet into a paper Lightning wallet

### ISSUE THREAD

**Issue by fiatjaf** [lnbits/lnbits#112]
The idea is stupid but I like it, it could be interesting for example as "card" to be used in closed environments, or as a toy wallet for kids. Basically you generate two QR codes that represent a wallet:

- one is an lnurl-pay code that can be used to deposit any amount to the wallet.
- the other is an lnurl-withdraw code that can be used to withdraw any amount, so it can be used to pay for stuff (this is very naïve and a malicious payee can withdraw all sats from the wallet, so only use it to pay trusted actors... just like you do with your card in real world stores by the way).
- the lnurl-pay code can also be used to read the wallet balance from other places (LNbits will naïvely display the full balance to everyone who scans it).

**Comment by cj-chua** [comment]
This actually sounds kinda cool. To your second point maybe the qrcode can be made smaller, so that others couldn't snipe it from afar

**Comment by talvasconcelos** [comment]
I really like this idea. Like having a pre-paid card that you can take with you to make payments. Even cooler if tpos had a scan feature to allow merchants to scan a lnurl-withdraw to receive the payment (may try to implement this...)

**Comment by talvasconcelos** [comment]
It can be used with creating multiple LNURL-withdraw QR codes, that can only be used once. This would reduce the malicious action of someone reusing the LNURLw to keep withdrawing funds!

**Comment by taxmeifyoucan** [comment]
I made this manually but it would be nice to have an extension which does it automatically. Check https://github.com/taxmeifyoucan/HCPP2021-Badge
