### ISSUE TITLE
Transaction list api's 

### ISSUE THREAD

**Issue by sawrubgupta** [lnbits/lnbits#1128]
/usermanager/api/v1/transactions/
This above api is giving 11 records and it takes 30ms 

This /api/v1/payments?limit=100&offset=0
This above api is giving me 41 records and it takes 31 seconds

Can you please make core api faster ? 
and user manager api is returning only pending = true records. 
Maybe a bug

**Comment by motorina0** [comment]
1. Is this bug report for for the demo server (https://legend.lnbits.com/)
2. does it happen all the time, or just occasionally?

**Comment by dni** [comment]
can you try again, payments endpoint was improved, the rest is related to usermanager endpoint?

**Comment by talvasconcelos** [comment]
Closed for inactivity
