### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'name'

### ISSUE THREAD

**Issue by pseudozach** [lnbits/lnbits#1132]
I have this error in my lnbits logs that I want to log here so it can be checked. I have created only 1 wallet, it's not a complicated setup, I don't even have many extensions enabled, just scrub.

>  File "/root/lnbits-legend/lnbits/core/views/api.py", line 72, in api_wallet
    return {"name": wallet.wallet.name, "balance": wallet.wallet.balance_msat}
AttributeError: 'NoneType' object has no attribute 'name'
2022-11-16 18:53:07.71 | INFO | 73.53.57.46:0 - "GET /api/v1/wallet HTTP/1.0" 200
2022-11-16 18:53:07.71 | ERROR | Exception in ASGI application

**To Reproduce**
1. Run a default lnbits installation
2. Have a browser window open to view the wallet transactions.
3. This error comes every minute so I think it's thrown every time the browser refreshes the view.

**Desktop (please complete the following information):**
 - LNbits version: Commit version: 28b43786f1bb2ad53d6c2ea3267019be798680d0
 - Database sqlite

**Comment by pseudozach** [comment]
lndrestwallet

**Comment by talvasconcelos** [comment]
Can you access the wallet / use lnbits (receive and pay invoices)? 

Maybe related to #1095 ?

**Comment by pseudozach** [comment]
this is not on an umbrel, it's on debian 10. I'll do some more checks but it's difficult to troubleshoot because node is in production.

**Comment by callebtc** [comment]
Hey. This error means that something is trying to access your wallet with a wrong invoice/admin key for that user. Are you running some sort of script that uses LNbits in the background?

**Comment by talvasconcelos** [comment]
Closed for inactivity.
