### ISSUE TITLE
[Feature request] Splitpayments: show all wallets of user in dropdown menu instead of manual input of keys

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#1137]
**Is your feature request related to a problem? Please describe.**
For larger splits, it takes a lot of effort to add many destination wallets.

**Describe the solution you'd like**
A dropdown menu that shows all wallets of the user for fast adding. 

**Additional context**
@Egge7 uses this for Plebrap.space

**Comment by talvasconcelos** [comment]
What if I'm splitting to wallets that i do not own (not associated with my user)?

**Comment by Egge7** [comment]
It would be interesting to learn how most people use this (splitting of payments between wallets owned by one user vs. different users).

The last item of the drop down could be "WALLET/INVOICE Key" which makes another input box show up
