### ISSUE TITLE
[BUG] Scrub plugin not working (Umbrel)

### ISSUE THREAD

**Issue by decentropy** [lnbits/lnbits#1142]
Scrub plugin not doing anything

**To Reproduce**
1. Enable Scrub plugin
2. Add new scrub, with lightning address
3. Created an invoice and paid it.
4. The sats are in my lnbits wallet, and were not forwarded to lightning address

**Comment by talvasconcelos** [comment]
Hi, to account for LN fees, the wallet must have a residual amount of sats! 

Can you try it with the wallet having a small amount of sats ? 10 sats, for example...

**Comment by decentropy** [comment]
I tried 100 sat payment with 100 sats already in my wallet, but nothing happened.  (I.e. I now have 200 sats).
The scrub is pointed to my lnmarkets lightning address.

**Comment by talvasconcelos** [comment]
Ok, I'll investigate, what's the backend wallet BTW?

**Comment by decentropy** [comment]
Its LND on Umbrel

**Comment by talvasconcelos** [comment]
I've tested it... with lntxbot as backend and sending to Wallet of Satoshi:
![alt](https://i.imgur.com/neqtKMk.png)

and on WoS everything went as expected! I don't have an LND to test it! Can't really reproduce your issue.

@callebtc do you have any insight on this?

**Comment by callebtc** [comment]
Which backend are you using, LndWallet or LndRestWallet

**Comment by talvasconcelos** [comment]
Can this be closed?
