### ISSUE TITLE
Importing lnbits wallet to bluewallet fails sporadically

### ISSUE THREAD

**Issue by cj-chua** [lnbits/lnbits#115]
I get errors when trying to import lnbits wallet to bluewallet by scanning the lndhub admin url. After 2-3 tries it would magically work. I've encountered this problem on two occasions so far. See the screenshot below.

This is a wallet running on testnet. I'm not sure if this is a lnbits problem, or a bluewallet one?

![IMG_2474](https://user-images.githubusercontent.com/43709958/96003993-77585a80-0e00-11eb-922c-52894a8feb5b.PNG)

**Comment by fiatjaf** [comment]
Where are you running this LNbits installation? Does it have a stable IP that is publicly reachable from the external internet?

**Comment by cj-chua** [comment]
It was running on a friend's local machine served to me via ngrok. Unfortunately that's as much as I know atm...
