### ISSUE TITLE
Allow an LNbits wallet to make itself a default handler for URLs with `lightning:...` scheme

### ISSUE THREAD

**Issue by fiatjaf** [lnbits/lnbits#116]
So when you click on an invoice or lnurl on another website it should open LNbits with that invoice already loaded.

**Comment by talvasconcelos** [comment]
I think this browser extension solves part this partially: 
https://github.com/bitcoincoretech/lnbits-link

**Comment by fiatjaf** [comment]
Yes, but we don't need that. Just https://github.com/fiatjaf/etlapps/blob/7f8f9da593ea01590f34b6823edb37a566cee8c9/chainmarket/src/main.js#L11-L19

**Comment by dni** [comment]
is this still relevant? :) sounds interesting
