### ISSUE TITLE
[BUG] Bluewallet API failure after LNbits admin changes wallet balance.

### ISSUE THREAD

**Issue by Xiphid** [lnbits/lnbits#1172]
I can import a LNbits wallet into Bluewallet and use it, but after the LNbits admin changes the account balance Bluewallet can no longer sync the account and throws an API error.

1 Be a LNbits admin user.
2 Create wallet in LNbits webinterface.
3 Receive some sats.
4 Add LNDhub extension.
5 Import wallet into Bluewallet using the LNDhub admin URL, this works, the wallet shows up in Bluewallet and can sync and refresh normal transaction data, received sats are displayed.
6 Use admin powers in LNbits webinterface to click the "+" and change the wallet balance.
7 Refresh Bluewallet, it now throws an API error.

Expected behavior
Changing the wallet balance with admin power does not break Bluewallet sync.

LNbits version 0.9.4
Database: sqlite
Bluewallet 6.3.2

**Screenshots**
My domain name is blacked out for scary privacy reasons.
![Screenshot_20221206_222848_BlueWallet](https://user-images.githubusercontent.com/9660062/206028810-bc9ee471-4eb5-4cba-8b7b-c32467db5b11.jpg)

**Comment by dni** [comment]
thank you very much, for the report i occasionally stumbled upon this issue and did not know how to reproduce it.

can you, also put the log from lnbits inside here? it should also throw an error.

**Comment by Xiphid** [comment]
When I refresh the troubled LNbits account in Bluewallet these are the lines that are added to LNbits log, hope this helps.
```
Dec 07 09:53:12 NUC uvicorn[918814]: 2022-12-07 09:53:12.73 | INFO | 192.168.178.1:0 - "GET /lndhub/ext/balance HTTP/1.0" 200
Dec 07 09:53:12 NUC uvicorn[918814]: 2022-12-07 09:53:12.87 | INFO | 192.168.178.1:0 - "GET /lndhub/ext/gettxs?limit=10&offset=0 HTTP/1.0" 200
Dec 07 09:53:12 NUC uvicorn[918814]: 2022-12-07 09:53:12.90 | INFO | 192.168.178.1:0 - "GET /lndhub/ext/getpending HTTP/1.0" 200
Dec 07 09:53:12 NUC uvicorn[918814]: 2022-12-07 09:53:12.94 | ERROR | handled error
Dec 07 09:53:12 NUC uvicorn[918814]: 2022-12-07 09:53:12.94 | ERROR | ERROR:
Dec 07 09:53:12 NUC uvicorn[918814]: Traceback (most recent call last):
Dec 07 09:53:12 NUC uvicorn[918814]:   File "/bitcoin/source/lnbits0.9.4/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
Dec 07 09:53:12 NUC uvicorn[918814]:     await self.app(scope, receive, _send)
Dec 07 09:53:12 NUC uvicorn[918814]:   File "/bitcoin/source/lnbits0.9.4/venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
Dec 07 09:53:12 NUC uvicorn[918814]:     await responder(scope, receive, send)
Dec 07 09:53:12 NUC uvicorn[918814]:   File "/bitcoin/source/lnbits0.9.4/venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 43, in __call__
Dec 07 09:53:12 NUC uvicorn[918814]:     await self.app(scope, receive, self.send_with_gzip)
Dec 07 09:53:12 NUC uvicorn[918814]:   File "/bitcoin/source/lnbits0.9.4/venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
Dec 07 09:53:12 NUC uvicorn[918814]:     await self.app(scope, receive, send)
Dec 07 09:53:12 NUC uvicorn[918814]:   File "/bitcoin/source/lnbits0.9.4/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
Dec 07 09:53:12 NUC uvicorn[918814]:     raise exc
Dec 07 09:53:12 NUC uvicorn[918814]:   File "/bitcoin/source/lnbits0.9.4/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
Dec 07 09:53:12 NUC uvicorn[918814]:     await self.app(scope, receive, sender)
Dec 07 09:53:12 NUC uvicorn[918814]:   File "/bitcoin/source/lnbits0.9.4/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
Dec 07 09:53:12 NUC uvicorn[918814]:     raise e
Dec 07 09:53:12 NUC uvicorn[918814]:   File "/bitcoin/source/lnbits0.9.4/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Dec 07 09:53:12 NUC uvicorn[918814]:     await self.app(scope, receive, send)
Dec 07 09:53:12 NUC uvicorn[918814]:   File "/bitcoin/source/lnbits0.9.4/venv/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
Dec 07 09:53:12 NUC uvicorn[918814]:     await route.handle(scope, receive, send)
Dec 07 09:53:12 NUC uvicorn[918814]:   File "/bitcoin/source/lnbits0.9.4/venv/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
Dec 07 09:53:12 NUC uvicorn[918814]:     await self.app(scope, receive, send)
Dec 07 09:53:12 NUC uvicorn[918814]:   File "/bitcoin/source/lnbits0.9.4/venv/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
Dec 07 09:53:12 NUC uvicorn[918814]:     response = await func(request)
Dec 07 09:53:12 NUC uvicorn[918814]:   File "/bitcoin/source/lnbits0.9.4/venv/lib/python3.9/site-packages/fastapi/routing.py", line 227, in app
Dec 07 09:53:12 NUC uvicorn[918814]:     raw_response = await run_endpoint_function(
Dec 07 09:53:12 NUC uvicorn[918814]:   File "/bitcoin/source/lnbits0.9.4/venv/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
Dec 07 09:53:12 NUC uvicorn[918814]:     return await dependant.call(**values)
Dec 07 09:53:12 NUC uvicorn[918814]:   File "./lnbits/extensions/lndhub/views_api.py", line 182, in lndhub_getuserinvoices
Dec 07 09:53:12 NUC uvicorn[918814]:     return [
Dec 07 09:53:12 NUC uvicorn[918814]:   File "./lnbits/extensions/lndhub/views_api.py", line 184, in <listcomp>
Dec 07 09:53:12 NUC uvicorn[918814]:     "r_hash": to_buffer(invoice.payment_hash),
Dec 07 09:53:12 NUC uvicorn[918814]:   File "./lnbits/extensions/lndhub/utils.py", line 7, in to_buffer
Dec 07 09:53:12 NUC uvicorn[918814]:     return {"type": "Buffer", "data": [b for b in unhexlify(payment_hash)]}
Dec 07 09:53:12 NUC uvicorn[918814]: binascii.Error: Non-hexadecimal digit found
Dec 07 09:53:12 NUC uvicorn[918814]: 2022-12-07 09:53:12.94 | ERROR | Exception in ASGI application
Dec 07 09:53:12 NUC uvicorn[918814]: 2022-12-07 09:53:12.94 | INFO | 192.168.178.1:0 - "GET /lndhub/ext/getuserinvoices HTTP/1.0" 500
```

**Comment by Xiphid** [comment]
Updated to lnbits 0.9.5.3 and the issue is better but not resolved.

![Screenshot_20221227_204618_BlueWallet](https://user-images.githubusercontent.com/9660062/209717313-bb6bcfaf-2773-4166-a4c5-7cb5f66156f8.jpg)

'''
Dec 27 20:47:04 NUC uvicorn[45551]: 2022-12-27 20:47:04.74 | INFO | 192.168.2.254:0 - "GET /lndhub/ext/balance HTTP/1.0" 200
Dec 27 20:47:04 NUC uvicorn[45551]: 2022-12-27 20:47:04.78 | INFO | 192.168.2.254:0 - "GET /lndhub/ext/gettxs?limit=10&offset=0 HTTP/1.0" 200
Dec 27 20:47:04 NUC uvicorn[45551]: 2022-12-27 20:47:04.81 | INFO | 192.168.2.254:0 - "GET /lndhub/ext/getpending HTTP/1.0" 200
Dec 27 20:47:04 NUC uvicorn[45551]: binascii.Error: Non-hexadecimal digit found
Dec 27 20:47:04 NUC uvicorn[45551]: 2022-12-27 20:47:04.84 | ERROR | Exception: Non-hexadecimal digit found
Dec 27 20:47:04 NUC uvicorn[45551]: 2022-12-27 20:47:04.84 | INFO | 192.168.2.254:0 - "GET /lndhub/ext/getuserinvoices HTTP/1.0" 500
Dec 27 20:47:04 NUC uvicorn[45551]: 2022-12-27 20:47:04.84 | ERROR | Exception in ASGI application
'''

**Comment by Xiphid** [comment]
Updated to lnbits 0.10.
I'm no longer able to import an LNbits wallet into Bluewallet by scanning the LNDhub admin QR or invoice QR.
After scanning the QR Bluewallet reports: "import error, undefined is not a function".

Trying to sync or generate an invoice for the same wallet that was previously imported into Bluewallet under LNbits 0.9.7 throws an error in the LNbits log:

'''
Mar 05 21:05:09 NUC uvicorn[675860]: Traceback (most recent call last):
Mar 05 21:05:09 NUC uvicorn[675860]:   File "/bitcoin/lnbits/venv/lib/python3.9/site-packages/starlette/middleware/errors.py", line 162, in __call__
Mar 05 21:05:09 NUC uvicorn[675860]:     await self.app(scope, receive, _send)
Mar 05 21:05:09 NUC uvicorn[675860]:   File "./lnbits/middleware.py", line 73, in __call__
Mar 05 21:05:09 NUC uvicorn[675860]:     await self.app(scope, receive, send)
Mar 05 21:05:09 NUC uvicorn[675860]:   File "./lnbits/middleware.py", line 52, in __call__
Mar 05 21:05:09 NUC uvicorn[675860]:     await self.app(scope, receive, send)
Mar 05 21:05:09 NUC uvicorn[675860]:   File "/bitcoin/lnbits/venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 24, in __call__
Mar 05 21:05:09 NUC uvicorn[675860]:     await responder(scope, receive, send)
Mar 05 21:05:09 NUC uvicorn[675860]:   File "/bitcoin/lnbits/venv/lib/python3.9/site-packages/starlette/middleware/gzip.py", line 43, in __call__
Mar 05 21:05:09 NUC uvicorn[675860]:     await self.app(scope, receive, self.send_with_gzip)
Mar 05 21:05:09 NUC uvicorn[675860]:   File "/bitcoin/lnbits/venv/lib/python3.9/site-packages/starlette/middleware/cors.py", line 84, in __call__
Mar 05 21:05:09 NUC uvicorn[675860]:     await self.app(scope, receive, send)
Mar 05 21:05:09 NUC uvicorn[675860]:   File "/bitcoin/lnbits/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 93, in __call__
Mar 05 21:05:09 NUC uvicorn[675860]:     raise exc
Mar 05 21:05:09 NUC uvicorn[675860]:   File "/bitcoin/lnbits/venv/lib/python3.9/site-packages/starlette/exceptions.py", line 82, in __call__
Mar 05 21:05:09 NUC uvicorn[675860]:     await self.app(scope, receive, sender)
Mar 05 21:05:09 NUC uvicorn[675860]:   File "/bitcoin/lnbits/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
Mar 05 21:05:09 NUC uvicorn[675860]:     raise e
Mar 05 21:05:09 NUC uvicorn[675860]:   File "/bitcoin/lnbits/venv/lib/python3.9/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
Mar 05 21:05:09 NUC uvicorn[675860]:     await self.app(scope, receive, send)
Mar 05 21:05:09 NUC uvicorn[675860]:   File "/bitcoin/lnbits/venv/lib/python3.9/site-packages/starlette/routing.py", line 670, in __call__
Mar 05 21:05:09 NUC uvicorn[675860]:     await route.handle(scope, receive, send)
Mar 05 21:05:09 NUC uvicorn[675860]:   File "/bitcoin/lnbits/venv/lib/python3.9/site-packages/starlette/routing.py", line 266, in handle
Mar 05 21:05:09 NUC uvicorn[675860]:     await self.app(scope, receive, send)
Mar 05 21:05:09 NUC uvicorn[675860]:   File "/bitcoin/lnbits/venv/lib/python3.9/site-packages/starlette/routing.py", line 65, in app
Mar 05 21:05:09 NUC uvicorn[675860]:     response = await func(request)
Mar 05 21:05:09 NUC uvicorn[675860]:   File "/bitcoin/lnbits/venv/lib/python3.9/site-packages/fastapi/routing.py", line 231, in app
Mar 05 21:05:09 NUC uvicorn[675860]:     raw_response = await run_endpoint_function(
Mar 05 21:05:09 NUC uvicorn[675860]:   File "/bitcoin/lnbits/venv/lib/python3.9/site-packages/fastapi/routing.py", line 160, in run_endpoint_function
Mar 05 21:05:09 NUC uvicorn[675860]:     return await dependant.call(**values)
Mar 05 21:05:09 NUC uvicorn[675860]:   File "./lnbits/extensions/lndhub/views_api.py", line 181, in lndhub_getuserinvoices
Mar 05 21:05:09 NUC uvicorn[675860]:     return [
Mar 05 21:05:09 NUC uvicorn[675860]:   File "./lnbits/extensions/lndhub/views_api.py", line 183, in <listcomp>
Mar 05 21:05:09 NUC uvicorn[675860]:     "r_hash": to_buffer(invoice.payment_hash),
Mar 05 21:05:09 NUC uvicorn[675860]:   File "./lnbits/extensions/lndhub/utils.py", line 5, in to_buffer
Mar 05 21:05:09 NUC uvicorn[675860]:     return {"type": "Buffer", "data": [b for b in bytes.fromhex(payment_hash)]}
Mar 05 21:05:09 NUC uvicorn[675860]: ValueError: non-hexadecimal number found in fromhex() arg at position 2
Mar 05 21:05:09 NUC uvicorn[675860]: 2023-03-05 21:05:09.56 | ERROR | Exception: non-hexadecimal number found in fromhex() arg at position 2
Mar 05 21:05:09 NUC uvicorn[675860]: 2023-03-05 21:05:09.56 | INFO | 192.168.2.254:0 - "GET /lndhub/ext/getuserinvoices?limit=20 HTTP/1.0" 500
Mar 05 21:05:09 NUC uvicorn[675860]: 2023-03-05 21:05:09.56 | ERROR | Exception in ASGI application
'''

**Comment by dni** [comment]
i think this PR should fix the issue: https://github.com/lnbits/lnbits/pull/1588

**Comment by callebtc** [comment]
Merged!
