### ISSUE TITLE
[BUG] LNDhub extension return unusable `getinfo` response

### ISSUE THREAD

**Issue by dennisreimann** [lnbits/lnbits#1182]
**Describe the bug**
The [getinfo call](https://github.com/lnbits/lnbits/blob/main/lnbits/extensions/lndhub/views_api.py#L22) simply returns `bad auth` everytime, which breaks integrations like for us in BTCPay Server (see btcpayserver/btcpayserver#4414).

**Expected behavior**
Return [valid information](https://github.com/BlueWallet/LndHub/blob/master/doc/Send-requirements.md#get-getinfo), which we can use to connect. For us that would mean having a list of `uris` and a `block_height` being set.

**Comment by callebtc** [comment]
Hi @dennisreimann thanks for the report, I've fixed it in #1183. Do you wanna give it a try?

**Comment by dennisreimann** [comment]
As mentions, for the BTCPay Server integration the response would also need at least one URI and the block_height, so we know the node is synched. (See the linked [API reference for LNDhub](https://github.com/BlueWallet/LndHub/blob/master/doc/Send-requirements.md#get-getinfo))

**Comment by callebtc** [comment]
What is the the URI supposed to include? We can't deliver a block height without jumping through hoops because we don't have universal access to it (different backends etc).

**Comment by callebtc** [comment]
Since LNbits works with many different backends, we don't have that info universally. Example: People using LNTXBOT or Opennode as a backend.

**Comment by dennisreimann** [comment]
@callebtc Would it be an option to add the info for the implementations that support it? We'd need block height and and at least one of the node URIs.

Now that BlueWallet will turn of their custodial solution it'd be great if we could give people the opton to switch to their own LNbits or use lnbits.com as a custom node in BTCPay Server.

**Comment by callebtc** [comment]
@dennisreimann can I lie about block height and URI? What value would be ok?

**Comment by dennisreimann** [comment]
@callebtc We check against the block height, but you could fetch it from one of the public explorers maybe? Or use the one provided by an internal node if available?

**Comment by dni** [comment]
we working on a node management ui right now. should be trivial in the future to get the blockheight. https://github.com/lnbits/lnbits/pull/1702

**Comment by jackstar12** [comment]
This information will be provided by the new node implementations (`get_info`). LNDhub extension will be able to use that

**Comment by petzsch** [comment]
Thanks to all participants of this issue: I'm now able to create bolt11 invoices with BTCPay Server on an lnbits lndhub interface. (using LND as lightning node for lnbits)

Only thing that doesn't play nicely at the moment is the creation of top-up invoices (without amount) via LNURL. (getting a DescriptionHash ('h' error.

From my end this issue could be closed. 👍

**Comment by prusnak** [comment]
> Only thing that doesn't play nicely at the moment is the creation of top-up invoices (without amount) via LNURL. (getting a DescriptionHash ('h' error.

Could you please create a new issue with steps to reproduce? Thanks!

**Comment by tlindi** [comment]
> > Only thing that doesn't play nicely at the moment is the creation of top-up invoices (without amount) via LNURL. (getting a DescriptionHash ('h' error.
> 
> Could you please create a new issue with steps to reproduce? Thanks!

Here you are:
https://github.com/lnbits/lndhub/issues/25

**Comment by tlindi** [comment]
- [X] Working now: https://github.com/lnbits/lndhub/issues/25
