### ISSUE TITLE
API to retrieve wallets with balances

### ISSUE THREAD

**Issue by misovan** [lnbits/lnbits#119]
Hi, is there an api that allows for retrieval of wallets details alongside with balances for main / admin user? Something like /usermanager/api/v1/wallets/<user_id> in user manager extension. I am trying to programatically fund wallets created within usermanager from admin wallet, but I can not figure out the way how to check for balance of that one.
Thanks for help!

**Comment by fiatjaf** [comment]
`/api/v1/wallet` with the wallet admin or invoice key will do it (unrelated to the usermanager extension).

**Comment by misovan** [comment]
Thank you, it is the first endpoint in the core/views/api source file and I somehow missed it.
