### ISSUE TITLE
U

### ISSUE THREAD

**Issue by BigDaddylyons** [lnbits/lnbits#1191]
https://github.com/BigDaddylyons/BigDaddylyons/files/10105320/52d72db5-f547-49fb-9ebe-02d84e3537db.pdf

**Comment by talvasconcelos** [comment]
Is it possible to a bit more specific about your issue?

**Comment by BigDaddylyons** [comment]
mine ready

**Comment by BigDaddylyons** [comment]
lol

**Comment by BigDaddylyons** [comment]
hey up
