### ISSUE TITLE
#scrubed? Payment I didn't initiate... am I getting hacked?

### ISSUE THREAD

**Issue by decentropy** [lnbits/lnbits#1196]
I'm trying the LNBits API (hosted on my Umbrel).. I generated an invoice by calling the 'create invoice' API from another server.
I then paid that (from my lntxbot wallet).  This worked fine:

Payment Received
Date: 2022-12-14 01:04 (a minute ago)
Description: my-payment
Amount: 2807.000 sats
Fee: 0.000 sats
Payment hash: aa9d12e80704d404c2e968044f9eef5448030cba8c3a1e174777aa09cbfdf441

However... immediately after, this outbound payment showed up (with yellow hashtag #scrubed)
I did not send a payment to LN Markets. Why did this happen and where did my sats go?

Payment Sent
#scrubed
Date: 2022-12-14 01:04 (a minute ago)
Description: LN Markets Deposit
Amount: -2807.000 sats
Fee: 1.282 sats
Payment hash: bc76683bc2d74519aaead658fb7e778d64dad430aeefd8efb0d3910285fbe3f1
Payment proof: cf9bfa2086fe8a111f885555c7e3e9dbef0128ac3bc6a4fbd39a0f1d6940c190

Thanks for any advice or insights.

**Comment by talvasconcelos** [comment]
Do you have Scrub extension enabled?

**Comment by decentropy** [comment]
Yes, thats it... thanks.

I'd been sending dozens of payments without that extension working (per #1142) so my bad, I totally forgot I still had it on...
