### ISSUE TITLE
Configure LNURL withdrawal links to specific public domain / IP

### ISSUE THREAD

**Issue by misovan** [lnbits/lnbits#120]
Hi, I am using LNBits as a kind of backend service, calling its apis from another server on the same private network. It is therefore deployed inside a container, HOST in .env is set to 0.0.0.0 thus accessible on container ip address 10.x.x.x.x. 
I generate lnurl withdrawal links calling links api from another server, however encoded callback uris have 10.x.x.x.x addresses and are of course not reachable from public internet. At the same time I would like to avoid as much as possible to expose full lnbits container to public.

Would it be possible to configure ip/port/domain for generated LNURLs? 
I could then set it to public domain/ip address and proxy them using nginx to the container private IPs.
Thanks

**Comment by fiatjaf** [comment]
It should work if your proxy is sending the X-Forwarded-Host and X-Forwarded-Port headers, which is expected from normal reverse proxies.

Caddy does it automatically, nginx I think requires a directive, but I don't remember what is it.

**Comment by misovan** [comment]
Thanks, finally I ended up with having nginx as an internal apigw for all lnbits apis - I terminate self signed TLS there that is itself needed for lnurl links creation and I as well reset the Host header to public domain. Finally seeing testnet lnurls :) 

Thanks for help and for well-crafted product!

![Screenshot_20201028-232402](https://user-images.githubusercontent.com/1290973/97503574-9107af00-1975-11eb-9f7c-a819b805fa47.jpg)
