### ISSUE TITLE
[BUG] LNURLw callback errors don't match LUD-03 spec

### ISSUE THREAD

**Issue by ok300** [lnbits/lnbits#1203]
**Describe the bug**
LNURLw callback errors are not in the expected format.

[LUD-03](https://github.com/lnurl/luds/blob/luds/03.md) in step 6 says errors should look like:
```json
{"status": "ERROR", "reason": "error details..."}
```

A wallet on https://legend.lnbits.com returned:
```json
{"detail":"withdraw not working. Insufficient balance."}
```

**To Reproduce**
1. Create a new wallet on https://legend.lnbits.com
2. Enable the LNURLw extension
3. In the LNURLw extension, create a withdraw link of any amount
4. From a mobile wallet, try to scan the QR and withdraw

**Expected behavior**
Since no funds are in the wallet, I expect the withdraw to fail.

However, the error response should be in a format matching the spec. This helps the calling wallet be able to properly parse the error reason and show it in the UI in a user-friendly way.

Some wallets have issues parsing the response, so they show a generic LNURL error and not the message included in the LNbits payload. See Wallet of Satoshi screenshot below.

Other wallets don't know how to interpret it, show they show the raw JSON in the user interface. See the BlueWallet screenshot below.

**Screenshots**

Wallet of Satoshi:

![image0](https://user-images.githubusercontent.com/106775972/208099442-2342196e-80dc-48a1-a6f1-2894b3213446.jpeg)

BlueWallet:

![image1](https://user-images.githubusercontent.com/106775972/208099475-d91fc52c-ddfc-445c-9061-7a2fb6dd451c.jpeg)

**Desktop (please complete the following information):**
 - LNbits version: `b00757266faa8acbfee77bef0ae3c0479566b24b`

**Comment by callebtc** [comment]
Thank you for this excellent bug report. Will tackle this.

**Comment by ok300** [comment]
Any updates? Tried it with the latest lnbits@cb1616f809db3abf339719b8ed9276827e458161 , looks like it's still there.

We're using LNbits extensively for testing at Breez. When we're getting a LNURLw error from a LNbits wallet, we're showing a generic error, but if the payload matched the spec then we could show the actual error message to the user, which would be more helpful and informative.

Thanks!
