### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Eternumkr** [lnbits/lnbits#1214]
**Describe the bug**
"--only main" isnt an option recognized in "poetry install"

**To Reproduce**
1.run poetry install --only main

**Expected behavior**
error states --only main isnt a valid option

**Comment by dni** [comment]
make sure you are using poetry version > 1.2.

```poetry --version```

--only main is definitly a valid flag

**Comment by Eternumkr** [comment]
oh. poetry v1.1.15 doesnt like --only main
