### ISSUE TITLE
LNURL withdraw extension issue with number of link uses

### ISSUE THREAD

**Issue by misovan** [lnbits/lnbits#123]
Hi,
I encountered an issue when using lnurl withdrawal links. In current implementation, number of uses of (non unique) link is incremented at the time, when callback link is generated and returned to the wallet:

  [ ` link = update_withdraw_link(link.id, used=link.used + 1, usescsv=usescsv)`](https://github.com/lnbits/lnbits/blob/4456dd6f59a7c84cd99e6c5afae5c2738986f133/lnbits/extensions/withdraw/views_api.py#L128)

It is then checked when actual callback is called to process the withdrawal and in case there is 1 remaining use withdrawal fails as if the link has already been spent:

`if link.is_spent:`
   [`return jsonify({"status": "ERROR", "reason": "Withdraw is spent."}), HTTPStatus.OK`](https://github.com/lnbits/lnbits/blob/4456dd6f59a7c84cd99e6c5afae5c2738986f133/lnbits/extensions/withdraw/views_api.py#L174)

**Comment by fiatjaf** [comment]
Thank you very much.
