### ISSUE TITLE
[Feature request] LNURLp links should have a random ID, not sequential

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#1230]
**Problem**
LNURLp links look like this right now: https://legend.lnbits.com/lnurlp/**123456** and the number goes up with every new link. 

**Solution**
Use a UUID instead of a counter.

**Comment by arcbtc** [comment]
THis is a feature not an issue

**Comment by arcbtc** [comment]
Did someone complain about it?

**Comment by fiatjaf** [comment]
What is the problem with sequential numbers? Is that because we're exposing the number of lnurlpay links that exist in the server?

**Comment by fiatjaf** [comment]
Maybe that is really an issue since in a public LNbits server one will be able to query all the metadata from any user who has ever created an lnurlp link.

I didn't think that was an issue since this data is public anyway, but who knows.
