### ISSUE TITLE
[BUG] QR codes with invoices are missing lightning: prefix

### ISSUE THREAD

**Issue by prusnak** [lnbits/lnbits#1245]
**Describe the bug**

- QR codes that encode LN invoices are missing "lightning:" prefix
- this happens in Wallet, Events, TPoS, Cashu, ..., literally everywhere
- when QR code is missing the prefix, the generic QR code scanner (in iOS camera) does not now what app should it open and by default it tries to open Google Search

**To Reproduce**
1. Generate invoice QR code
2. Try to scan with iOS Camera
3. Observe that the scanned link leads to browser search not to a lightning wallet

**Expected behavior**
I expect the link will lead to an app that can pay the invoice

**Screenshots**

<img src="https://user-images.githubusercontent.com/42201/209802771-735ba7f8-da73-4a8c-9ef2-4baae4bc8909.jpeg" width="400">

**Desktop (please complete the following information):**
 - LNbits version: https://legend.lnbits.com/ => 0df81e5aaf6ea74487356cd0c4b1b2774cefad0c

**Comment by iWarpBTC** [comment]
Besides adding the prefix I thought it could be also nice to make the QR content upper case. It saves space for some reason.

**Comment by prusnak** [comment]
> Besides adding the prefix I thought it could be also nice to make the QR content upper case. It saves space for some reason.

Yes, QR encoding is more efficient when only using upper-case. That said, this opens another can of worms, because lots of wallets do not understand/register the "LIGHTNING:" prefix, they only understand/register the "lightning:" prefix. So you either use "lightning:lnbc1..." or "lightning:LNBC1..." but not "LIGHTNING:LNBC1..."

**Comment by prusnak** [comment]
I think this got fixed in https://github.com/lnbits/lnbits/pull/1253 - thanks @iWarpBTC!
