### ISSUE TITLE
Move funds internally from one wallet to another (API)

### ISSUE THREAD

**Issue by bezysoftware** [lnbits/lnbits#1249]
Hi, is there a way to move funds from one wallet to another? Possibly draining the source wallet to zero? I tried creating an invoice in target wallet and then paying it in source wallet, but when I try to train the source it won't let me due to minimal fee reserve. Is there a way to dynamically (via API) bypass this fee reserve, or is there another way to do this via API?

**Comment by iWarpBTC** [comment]
In case of an internal payment no fee reserve is applied. Aren’t you running some very old version? 

![image](https://user-images.githubusercontent.com/80261724/209860095-40f1c782-41fa-4a83-95f5-ddb68d68bfc1.jpeg)

**Comment by bezysoftware** [comment]
Aha I finally found my issue - the UI is showing the balance rounded to sats, but the actual balance is less by sub-satoshi amount. 
![image](https://user-images.githubusercontent.com/6108688/209876026-29c35df4-6cf4-496a-a4ae-de86d2a364ad.png)
![image](https://user-images.githubusercontent.com/6108688/209876069-f94aec8a-037f-4d80-8987-dd056200017f.png)
So it's not the reserve as I assumed. It's an issue of presenting the actual amount. I'll close this and open a new issue
