### ISSUE TITLE
[Feature request] Generate invoices with sub satoshi amounts

### ISSUE THREAD

**Issue by bezysoftware** [lnbits/lnbits#1251]
This is slightly related to #1249 where I noticed the UI is showing a balance rounded to nearest satoshi, while the API returns the actual balance in milisatoshis. This is an issue for multiple reasons, one of the being I have no way to fully move funds between wallets (internally in LNBits) because the API doesn't allow me to create an invoice in milisatoshis. 

I think the API should be extended to allow this, since the resulting invoice actually contains the amount in milisats, and not sats. Or, for my specific use case, I could use a dedicated API endpoint to move milisats amounts between wallets, internally.

**Comment by callebtc** [comment]
No all backends support millisatoshi invoices. This would be impossible to implement consistently. If this is an issue for sweeping one wallet to another, we could maybe add that feature specifically for internal payments via FakeWallet.
