### ISSUE TITLE
[Feature request] [User Manager] Allow specifying custom ID when creating users/wallets

### ISSUE THREAD

**Issue by bezysoftware** [lnbits/lnbits#1252]
It would be very handy to be able to specify a custom ID when creating users/wallets via User Manager's API. 

The use case: we have a system in place where have our own users / "groups" with their respective IDs. When creating related entities in LNBits we would like the preserve those IDs for easier lookup.

What we do now is we have a lookup table for our ID -> LNBits ID. It's not terrible, it's just inconvenient. Being able to set our own IDs when creating those entities would just make things easier for us

**Comment by talvasconcelos** [comment]
I had an old PR that addressed this. Would this be a good fit for what you're asking?

https://github.com/lnbits/lnbits/pull/269/files

**Comment by callebtc** [comment]
Hi! I would highly go against generating your own user IDs since their randomness protects the wallets right now. 

What you can do in user manager though is to add a name or an email address, both of which are not used right now. You could store your "community IDs" there with every generated user (through usermanager) and so have the link inside the lnbits database.

Hope that helps.

Closing issue as not planned, happy to further discuss!

**Comment by bezysoftware** [comment]
I'm generally ok with this, it's actually what I do with wallets - I set the wallet's name as my "group id". Here's my flow:

1) I have *my* user id & "group id", which I need to transform to resulting lnbits wallet id
2) I have a lookup table for user ids -> this gives me a lnbits user id
3) I get all wallets for a user and find the one with name == "group id"

What I'm missing is better API surface - be able to find a wallet by a combination of user email and the wallet name. That would work perfectly for me. Or at least be able to find a lnbits user based on email and get all wallets of this user (3. point - find the wallet by name on my end).

What is a bit concerning:
1) LNBits could add email validation for this field in the future release, breaking my API integration (it would be perfectly valid for LNBits, since the field is literally called "email" and I would be basically misusing it)
2) Lookup by email could return multiple users (in theory)
3) What would lookup by email+wallet name return? Would that be an array of users + their wallets with given name?
