### ISSUE TITLE
[Feature request] Add comment to LNURL-p

### ISSUE THREAD

**Issue by Darth-Coin** [lnbits/lnbits#1268]
**Option to attach a comment to a LNURL-pay**

We used to share the LNbits LNURL-p QR code, so people can send us sats very easy.
Would be nice to have also the option to add a comment attached to the payment.
Not sure which LUD is in this case, 12 or 20 https://github.com/lnurl/luds
I think is linked also to #1267 

**Actual behavior**
- Go to LNBits, open LNURL-p
- Scan the QR with a LN wallet
- you can choose the amount if the LNURL is variable but you can't put a comment. I tried with various LN wallets.

**Comment by talvasconcelos** [comment]
LNbits has the hability to allow for comments for LNURLp! You can see which wallets actually support it in LUD12. But you need to "activate" the comments when creating the LNURLp

![https://i.imgur.com/PpsfAeZ.png](allow comment)

**Comment by Darth-Coin** [comment]
Ah shit, my mistake then. I misunderstood that field with adding a comment myself not that I have to input the number of max characters for the comment.

**Comment by Darth-Coin** [comment]
@talvasconcelos I tried on legend.lnbits a lnurl-p with 250 chars set in the form.
In the received payment comes without comment. That "tips for Darthcoin" is the description of the lnurl-p
![image](https://user-images.githubusercontent.com/56997124/212403011-d03c3032-e72a-4046-9c53-f9d3680ab44c.png)

Maybe something changed in this last release?

**Comment by talvasconcelos** [comment]
If you click the green arrow, can you see the comment?
