### ISSUE TITLE
Handling of Expired Invoice

### ISSUE THREAD

**Issue by HamishMacEwan** [lnbits/lnbits#127]
Hi,

I'm using a gRPC lnd funding source.

When I present an expired invoice, or any invoice, the "Expire Date" is blank:
![chrome_aSDmJlMc00](https://user-images.githubusercontent.com/388061/101218493-09396100-36e8-11eb-8c53-1a3ee5fbc870.png)

If I pay the invoice I get only:
![chrome_OqTXsPv0AR](https://user-images.githubusercontent.com/388061/101218556-2837f300-36e8-11eb-95bc-a19caa688ae1.png)

while the log reports:

```
Dec 05 10:12:30 myNode lnbits[1476]:     raise _InactiveRpcError(state)
Dec 05 10:12:30 myNode lnbits[1476]: grpc._channel._InactiveRpcError: <_InactiveRpcError of RPC that terminated with:
Dec 05 10:12:30 myNode lnbits[1476]:         status = StatusCode.UNKNOWN
Dec 05 10:12:30 myNode lnbits[1476]:         details = "invoice expired. Valid until 2020-12-05 09:36:43 +1300 NZDT"
Dec 05 10:12:30 myNode lnbits[1476]:         debug_error_string = "{"created":"@1607116350.068511508","description":"Error received from peer ipv4:127.0.0.1:10009","file":"src/core/lib/surface/call.cc","file_line":1062,"grpc_message":"invoice expired. Valid until 2020-12-05 09:36:43 +1300 NZDT","grpc_status":2}"

```
and the account reads:
![chrome_dSHJTumuU4](https://user-images.githubusercontent.com/388061/101218676-659c8080-36e8-11eb-8920-fbcfcc47ff44.png)

No harm, but it's a bit confusing.

**Comment by arcbtc** [comment]
I can not reproduce with other funding sources, and the invoice is decoded in LNbits so doesn't touch LND, so LND is not the issue
