### ISSUE TITLE
Backup LndHub Wallets/Clients

### ISSUE THREAD

**Issue by Tanki90** [lnbits/lnbits#128]
Hello guys

I have set up a Node (Raspiblitz) with LNBits and added some Clients (friends using BlueWallet) via the LndHub Plugin,...
Is there a way to Backup the Wallets with their current balcance in case my lnd setup breaks and replicate/restore everything on a new installation?

**Comment by fiatjaf** [comment]
Yes, you can copy the LNbits database, which should be somewhere @rootzoll will know.

**Comment by rootzoll** [comment]
the LNbits database can be found under `LNBITS_DATA_FOLDER=/mnt/hdd/app-data/LNBits`

**Comment by Tanki90** [comment]
ah ok... thx

**Comment by rootzoll** [comment]
@seinzfiction I would recommend stopping LNBits service before copying the database.
