### ISSUE TITLE
[BUG] Site Description not retaining html after server restart

### ISSUE THREAD

**Issue by replayshot** [lnbits/lnbits#1340]
**Describe the bug**

Site Description does not retain raw html tags when lnbits is restarted

**To Reproduce**

- running lnbits on my server and enabling the admin extension, so the .env file is ignored
- I go to Manage Server > Theme > Site Description (there it says I can input raw html)
- input some raw html (for example a link)
- press save button and refresh main lnbits page (html shows up as expected), Site Description also retains html tags as expected
- press the restart server button - all html is lost from main page and Site Description also does not have the html tags visible

 
**Expected behavior**

- restarting the sever should not cause the html tags to disappear

**Screenshots**

**Desktop (please complete the following information):**
 - LNbits version: just did a git pull (not sure how to check the version) - in the source code of the root page it says: 
 Commit version: docker
 - Database - sqlite

**Comment by dni** [comment]
this was solved couple of versions ago, can you try again?, closes for now.
