### ISSUE TITLE
"database or disk is full (Sqlite code 13 SQLITE_FULL), (OS error - 2:No such file or directory)"

### ISSUE THREAD

**Issue by HamishMacEwan** [lnbits/lnbits#137]
This error:

![image](https://user-images.githubusercontent.com/388061/103492114-acb79600-4e8d-11eb-9daf-f853ec285c2e.png)

Arose after paying this LNURL:

`lightning:lnurl1dp68gurn8ghj7ctsdyh85etzv4jx2efwd9hj7a3s9aex2ut4v4ehgttnw3shg6tr943ksctjvajhxtmrxgekxepkxu6z6dry8qcz6dphxsej6cfsxuej6d3h8ymrwepnxyergcnpqmk8ha`

With a BlueWallet account using the LndHub extension of LNbits, running on myNode using lnd gRPC as a funding source.  

The payments appear to have succeeded:
![image](https://user-images.githubusercontent.com/388061/103492066-5ba7a200-4e8d-11eb-9159-41eae9d4d319.png)

Happy to find further information if required.

**Comment by arcbtc** [comment]
Interesting. 
Are you using LNDHUB connected to LNBits to pay an LNbits LNURL pay?

**Comment by fiatjaf** [comment]
Is the disk full?

**Comment by BigDaddylyons** [comment]
Hey up BigDaddylyonsjr/kevin-m-lyons-jr
