### ISSUE TITLE
Balance is not updated after failed/pending LN transactions (from LNURLw vouchers)

### ISSUE THREAD

**Issue by Yasoj** [lnbits/lnbits#138]
After creating a wallet on lnbits.com (Windows 10, Firefox browser), I funded it with 1000 sats.
I then created vouchers using the LNURLw extension. 
I tried to claim some of these vouchers to test the feature (using Phoneix on an Android mobile phone).
I then got an error message on my Phoenix wallet: 'lnbits.com responded with an error: null' and I didn't receive the sats.
On my hosted lnbits.com wallet, the transactions are shown as pending and the balance corresponds to the amount if the vouchers were claimed (see picture below).

Someone on Reddit suggested that the lightning payment might have failed, the underlying funding LNbits wallet (LND) returned an error to lnbits, but for some reason it could not rollback its own transaction and that the money remained in underlying funding wallet.

![image](https://user-images.githubusercontent.com/42089406/103538919-079dbd00-4e8f-11eb-9777-8964293bc9ca.png)

**Comment by arcbtc** [comment]
Seems to be a bug in lnbits.com. I'll fix and get back to you. Thanks for reaching out!
