### ISSUE TITLE
[BUG] ERROR | No module named 'boltz_client' on main branch commit ffb5a91

### ISSUE THREAD

**Issue by bitkarrot** [lnbits/lnbits#1389]
**Describe the bug**
poetry run lnbits for current main branch commit ffb5a91f6747c0150e0bafe9e322e6f20964fbd0

Yields the following error: 
2023-01-20 23:40:41.96 | ERROR | No module named 'boltz_client'
Process Process-1:
ImportError: Please make sure that the extension `boltz` follows conventions.

Was running fine on main from Jan 14, 2023, commit 2eb76d0e26916f0ec9ad40806a9f9fe5bf3dc55e 

**Desktop (please complete the following information):**
 - OSX m1 Ventura
 - Database  sqlite

**Comment by dni** [comment]
running ```poetry install``` should install the client!

**Comment by bitkarrot** [comment]
resolved! closing this issue
