### ISSUE TITLE
[BUG] Decode endpoint requires the key "data" instead of "invoice"

### ISSUE THREAD

**Issue by timkaebisch** [lnbits/lnbits#1390]
**Describe the bug**
The endpoint "/api/v1/payments/decode" requires the key of the body to be "data". The docs reads "invoice". I was trying it with "invoice" and was wondering why I'm receiving an error.

**Expected behavior**
The docs should be updated to "data" instead of "invoice" at this point.

**Screenshots**
<img width="456" alt="image" src="https://user-images.githubusercontent.com/61691177/213863207-a292dc1f-287b-4eb9-94ee-5512bb6c56e4.png">

**Comment by dni** [comment]
hi! you should look into the Swagger API, https://legend.lnbits.com/docs#/default/api_payments_decode_api_v1_payments_decode_post
those API docs are just manually managed by the extension developer and tbh. i think it is a pain and we should probably remove it from there and just rely on swagger
