### ISSUE TITLE
Use payment `expiry` to clean payments table

### ISSUE THREAD

**Issue by eillarra** [lnbits/lnbits#14]
When deleting payments, we remove the payments older than a day that are pending.

We could be more precise because invoices have a `expiry` value... if we force an `expiry` time for the invoices we create on any backend wallet (let's say, 30 minutes), then we can clean the database faster: it would improve the "Checking pending transactions..." step when you enter a wallet.

**Comment by Kixunil** [comment]
I'd also suggest adding a (maybe  configurable) buffer to the timeout that can be useful when investigating payment issues. Possibly with a way to temporarily disable cleanups.

**Comment by ChuckNorrison** [comment]
different use cases needs different expiry times, i would like to see a default value and the optional possibility to set a custom expiry value on invoice creation.

**Comment by Kixunil** [comment]
The default should be sufficiently long IMO. 24 hours, maybe even more.

**Comment by fiatjaf** [comment]
This apparently was done on 4855e2cd.

This is how it looks like now:
https://github.com/lnbits/lnbits/blob/2dfae9ecc1f7f1ac6bd4210f6c841da26914b4ec/lnbits/core/crud.py#L200-L224
