### ISSUE TITLE
LNBits does not have a favicon

### ISSUE THREAD

**Issue by we-do-it-lu** [lnbits/lnbits#140]
Hi. We love your software. I noticed that LNBits does not have a favicon. It's a shame! I use Safari. I wish I could do anything about it but I am not that technical on web layout stuff.
![2021-01-10_01-11-00](https://user-images.githubusercontent.com/26678816/104111380-6628c800-52e1-11eb-8295-9cd672512aea.jpeg)

**Comment by PresidentNick** [comment]
![image](https://user-images.githubusercontent.com/8160053/104829981-45132a80-583f-11eb-9de7-5113532abd9f.png)
@we-do-it-lu the favicon appears fine on my browser. I'm using chrome.

**Comment by we-do-it-lu** [comment]
🤔 that's odd. I can reproduce on other computers:
- Mac BigSur + Brave Version 1.18.77 Chromium: 87.0.4280.101 (Official Build) (x86_64)
- Mac BigSur + Chrome Version 87.0.4280.141 (Official Build) (x86_64)

**Comment by arcbtc** [comment]
It'll be a favicon size thing, will do tomorrow
