### ISSUE TITLE
URL Signing Scheme to Support Offline Apps/Devices

### ISSUE THREAD

**Issue by chill117** [lnbits/lnbits#143]
I would like to see lnbits add support for offline apps and devices (e.g [Bleskomat](https://github.com/samotari/bleskomat)). I've developed a secure URL signing scheme (described [here](https://github.com/chill117/lnurl-node#how-to-implement-url-signing-scheme)) in the [lnurl-node](https://github.com/chill117/lnurl-node) project. We run an instance of the server provided by lnurl-node to support our current testers' ATMs. But it could be nice to suggest lnbits as an alternative to Bleskomat ATM operators.

Is this something that you would be interested in adding to lnbits? If yes, I could start work on a pull-request that implements it.

Thanks for your attention!

**Comment by fiatjaf** [comment]
Yes, this is very cool. If you can implement it will be awesome!

So the idea is that the LNbits wallet owner will share this key with a Bleskomat device, then it will fulfill all withdrawal requests that come from that Bleskomat (as they will be signed) no matter the amount?

I think this should be a new extension called Bleskomat. Sounds relatively simple:

1. a screen to view your keys, delete them or generate new keys;
2. each key is tied to an LNbits wallet and have a unique base URL (e.g. `https://lnbits.com/bleskomat/withdraw/<wallet_id>`);
3. For every withdraw request that comes at these URLs fetch the key, check the signature then attempt to fulfill them using the given wallet.

Right?

**Comment by chill117** [comment]
Super! Yes, that sounds about right. As I start to dig into the lnbits code, I will probably have some questions. I will keep you updated with my progress here.

**Comment by chill117** [comment]
I've opened a pull request (#146), but I've marked it as work-in-progress. I am not able to test the full UX flow at the moment because of failing database migrations. I will try to run it on a VPS with latest sqlite3.

**Comment by arcbtc** [comment]
Can I close this issue, and you keep us updated in the pr?
