### ISSUE TITLE
[Feature request] Dropdown for Topup LNbits walletID

### ISSUE THREAD

**Issue by Darth-Coin** [lnbits/lnbits#1436]
## Description
Yes, kind of problem.
Right now the topup module is based on the copy/paste walletID by the super admin.
So if the LNbits owner have hundreds of users, would be quite hard to identify the specific waleltID for each user.
Also users usually don't remember or write down their walletID, so when the super amin will ask them "which is your walletID" to be able to topup they wouldn't know it.

## Solution proposal
Make a dropdown in that topup module, that will list all the walletID available on that LNbits instance and also listed in alphabetical order, by the alias name of the wallet.

The super admin should be able to manage all the walletIDs in that LNbits instance.

![lnbits-topup.jpg](https://i.postimg.cc/SNcCfW1h/lnbits-topup.jpg)

**Comment by arbadacarbaYK** [comment]
pls include the usr in dropdown like

usr
/_ alias 1
/_ alias 2

**Comment by motorina0** [comment]
> What's the standpoint on this? @callebtc , @arcbtc , @motorina0 , @dni ?

Sounds like a good idea.

**Comment by callebtc** [comment]
> What's the standpoint on this? @callebtc , @arcbtc , @motorina0 , @dni ?
> 
> 

UI and implementation: This is not possible with a dropdown list if there are thousands of users. It would require paginated Database access and rendering in a real list (not a dropdown).

Use case: Not sure how to best approach this. If I set up hundreds of wallets that want to top up (likely use case!), do I really need a dedicated button for that? I'd guess the person who creates hundreds of wallets did it with a script and can also use that script to top up these wallets.

@Darth-Coin can you specify your use case more precisely? Maybe we'll figure it out.

**Comment by Darth-Coin** [comment]
@callebtc I didn't think of thousands of accounts, but yes several almost hundred. Indeed for a LNbits with thousands of accounts this is not so handy to manage.
Maybe a search bar where admin could input the user name / walletID and get a suggested result based on a search in the database? Something to find easy one specific user to be topped up.
Or....
In the User Manager, where is the list of all users, walletIDs, just add a simple button on each line, "top-up".
But yeah, in some way it must be mandatory that all users must be created by the admin to be listed there.
Or make a function or option that all users could be listed there, so the admin can manage all easily.

**Comment by dni** [comment]
i like the idea with the user manager! @jackstar12

**Comment by motorina0** [comment]
Implemented by @dni in https://github.com/lnbits/lnbits/issues/1400


https://github.com/user-attachments/assets/3085d6d6-5e1c-48bb-a056-745e3dd9949b
