### ISSUE TITLE
[BUG] Invalid OpenAPI definition

### ISSUE THREAD

**Issue by titusz** [lnbits/lnbits#1442]
The generated OpenAPI definition at https://legend.lnbits.com/openapi.json is invalid.

To reproduce load the OpenAPI definition into an editor like https://editor.swagger.io/ or use a command line tool like https://pypi.org/project/openapi-spec-validator/

For example the `CreatePayLinkData` schema has the following property:

```json
"comment_chars": {
  "title": "Comment Chars",
  "exclusiveMaximum": 800.0,
  "minimum": 0.0,
  "type": "integer",
  "default": 0
}
```
`exclusiveMaximmum` must be a boolean and not a number.

The OpenAPI spec needs to be valid to support generating API client libraries from the spec. Due to the spec errors I failed to generate a python client library with https://github.com/openapi-generators/openapi-python-client

Best case would be to validate the OpenAPI spec during GitHub CI testing.

**Comment by dni** [comment]
damn ther are more issues than this, i have no idea what is going on there? can you take i look? https://github.com/lnbits/lnbits/actions/runs/4280189161/jobs/7451668700

**Comment by dni** [comment]
i think i finally figured it out 
https://github.com/lnbits/lnbits/pull/1551
