### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by downet** [lnbits/lnbits#145]
Hi,

I am trying to get lnbits up and running, but getting following error:

```
Collecting hypercorn==0.11.1 (from -r requirements.txt (line 18))
  Cache entry deserialization failed, entry ignored
  Could not find a version that satisfies the requirement hypercorn==0.11.1 (from -r requirements.txt (line 18)) (from versions: 0.1.0, 0.2.0, 0.2.1, 0.2.2, 0.2.3, 0.2.4, 0.3.0, 0.3.1, 0.3.2, 0.4.0, 0.4.1, 0.4.2, 0.4.3, 0.4.4, 0.4.6, 0.5.0, 0.5.1, 0.5.2, 0.5.3, 0.5.4)
No matching distribution found for hypercorn==0.11.1 (from -r requirements.txt (line 18))
``` 

Even on this page looks that version exists - https://pypi.org/project/Hypercorn/

Python version used: Python 3.6.8

Btw. is there any way how to run it in docker? I tried to build the image from Dockerfile, but it just exit without any error.
Btw 2: is there any support group where I can ask some questions or only issues here? :)

**Comment by fiatjaf** [comment]
There is a group on Telegram: https://t.me/lnbits
We require a minimum Python version of 3.7: https://github.com/lnbits/lnbits/blob/88eb8e0e78b8c7bdd4d7888841197a82ed891b48/Pipfile#L7, but I don't know if that is the issue.

Have you tried to install lnd_grpc or other optional dependencies mixed up with these?

**Comment by ronnicek** [comment]
Working well in python:3.7-slim, thanks!

**Comment by downet** [comment]
Working well with python:3.9-slim, thanks!
