### ISSUE TITLE
Unable to find image 'lnbits-legend:latest' locally

### ISSUE THREAD

**Issue by ming-iox** [lnbits/lnbits#1483]
```
Feb 12 01:08:55 myNode lnbits[12207]: See 'docker run --help'.
Feb 12 01:08:55 myNode lnbits[12207]: docker: Error response from daemon: pull access denied for lnbits-legend, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
Feb 12 01:08:53 myNode lnbits[12207]: Unable to find image 'lnbits-legend:latest' locally
Feb 12 01:08:52 myNode systemd[1]: Started LNBits.
```
I got above errors with mynodebtc bundle.
And I thought that is because the lnbits-legend image is private for mynodebtc bundle and seemed a "docker login" with correct permission is required to fetch the image, but I don't know the docker username & password. I'm stuck now.

**Comment by lollenderrofler** [comment]
Same for me. I also did ssh into myNode, did docker pull lnbitsdocker/lnbits-legend:latest and thereafter specified the version which myNode should install in the application tab to 0.9.7 (which is latest right now), but the error persists. Is this a lnbits or myNode issue?

**Comment by dni** [comment]
i think that a is mynode issue 
you somehow dont have pull access for lnbits-legend image, i guess mynode has their own docker image?
```
Feb 12 01:08:55 myNode lnbits[12207]: docker: Error response from daemon: pull access denied for lnbits-legend, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
```

**Comment by 12hourdrive** [comment]
I have the same issue. Following

**Comment by johandegrieck** [comment]
I'm having this same issue for a while now.  Tried restart, uninstall, reinstall. Also updated to newer versions without success.  Running v0.9.5.3 now and updating to latest 0.9.7 will likely not help.

```
-- Logs begin at Wed 2023-03-01 08:12:40 CST, end at Wed 2023-03-01 15:49:30 CST. --
Mar 01 15:49:06 myNode systemd[1]: lnbits.service: Failed with result 'exit-code'.
Mar 01 15:49:06 myNode systemd[1]: lnbits.service: Main process exited, code=exited, status=125/n/a
Mar 01 15:49:06 myNode lnbits[25543]: See 'docker run --help'.
Mar 01 15:49:06 myNode lnbits[25543]: docker: Error response from daemon: pull access denied for lnbits-legend, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
Mar 01 15:49:04 myNode lnbits[25543]: Unable to find image 'lnbits-legend:latest' locally
Mar 01 15:49:04 myNode systemd[1]: Started LNBits.
```

**Comment by ming-iox** [comment]
0.3.11 resolved docker image issue.

**Comment by johandegrieck** [comment]
Got it fixed.  I switched to a 64bit OS, updated to the latest version of MyNode and now LNBits is working again.
