### ISSUE TITLE
Creating an invoice doesn't work on legend.lnbits.com Paywall extension SOLVED - the endpoint URL in the docs is just wrong

### ISSUE THREAD

**Issue by Jared-Dahlke** [lnbits/lnbits#1497]
**Describe the bug**
I am building an app using `legend.lnbits.com` as the backend to make a lightning paywall. Everything up until this point is working perfectly. The problem is that I cannot seem to create an invoice in the Paywall extension. I am  receiving  `{"detail":"Not Found"}` when I run `curl -X POST https://legend.lnbits.com/paywall/api/v1/paywalls/<paywall_id>/invoice -d '{"amount": <integer>}' -H "Content-type: application/json"`

**To Reproduce**
1. create a paywall using: `curl -X POST https://legend.lnbits.com/paywall/api/v1/paywalls -d '{"url": "https://www.test.com", "memo": "test memo", "description": "test desc", "amount": 100, "remembers": true}' -H "Content-type: application/json" -H "X-Api-Key: 788b......8656ed"` 
2. Try to create an invoice for that paywall using `curl -X POST https://legend.lnbits.com/paywall/api/v1/paywalls/<paywall_id from step 1>/invoice -d '{"amount": 100}' -H "Content-type: application/json"`
3. observe that the result of step 2 is  `{"detail":"Not Found"}`

**Expected behavior**
invoice is created after doing the command from step 2

**Screenshots**
I'm just using the Paywall extension in legend.lnbits, here is a screenshot of my screen:
![image](https://user-images.githubusercontent.com/32936978/218903521-eb8979d6-78f3-45a3-bdb2-67369c9caa36.png)

**Desktop (please complete the following information):**
 - LNbits version: 9467a8da07bdf19bc9146d890098268b8979a9cf
 - Database: na

**Additional context**
Note I have the same problem (receiving "Not Found") when I try to check invoice status: `curl -X POST https://legend.lnbits.com/paywall/api/v1/paywalls/<paywall_id>/check_invoice -d '{"payment_hash": <string>}' -H "Content-type: application/json"`

**Comment by Jared-Dahlke** [comment]
if i could figure out how to programmatically check to see if a paywallId has been paid or not then i'd be unblocked.

**Comment by Jared-Dahlke** [comment]
I figured out the problem. It looks like the API documentation on lnbits site is wrong.

Here is the documentation that doesn't work on legend.lnbits.com:
![image](https://user-images.githubusercontent.com/32936978/218908633-e5872d7b-81ba-4d84-9883-f1e32037c121.png)


And here is the documentation in swagger docs that works:
https://legend.lnbits.com/docs#/Paywall/api_paywall_create_invoice_paywall_api_v1_paywalls_invoice__paywall_id__post
![image](https://user-images.githubusercontent.com/32936978/218908569-e7ec0dae-96db-42aa-ac15-4d431b1cd7be.png)


Notice how the URLs are different

**Comment by dni** [comment]
thanks for the report! fixed it here: https://github.com/lnbits/paywall/commit/a7530a04f85c3f79b20bb284a38939b332b3d846
