### ISSUE TITLE
Potential depletion attack

### ISSUE THREAD

**Issue by sgeisler** [lnbits/lnbits#15]
When sending from lnbits accounts fees aren't taken into account. If an attacker connects to the instance as a routing node they can deposit money for a low fee/free while receiving fees on withdrawal. I tested it on lnbits.com and it seems to work (I also donated more than I "stole" that way to test my hypothesis, so please don't sue me :sweat_smile:).

Since I couldn't find a disclosure policy I'm just opening this issue. The project is still in beta so I hope the fallout won't be too big if this turns out to be an actual issue. I hope I just overlooked something.

**Comment by arcbtc** [comment]
Looking into this. Thank you so much!
