### ISSUE TITLE
Admin top up adds sats to wrong wallet

### ISSUE THREAD

**Issue by Xiphid** [lnbits/lnbits#1506]
When using the Admin top up function sats are not added to the selected wallet but to the top wallet displayed in albabetical order.
Step to reproduce:

- Use the webinterface using the super user, no other users exist.
- Create a second wallet (wallet withou... in screenshot).
- Select the second wallet.
- Click + and add sats, hit enter to confirm.
- The new sats are displayed on the second wallet.
- Refresh the page, the sats are now added to the first wallet (LNbits wallet in screenshot), second wallet is now back to 0 sats.
- Create a third wallet named "3" which is displayed at the top because of alphabetical order.
- Adding sats to one of the other wallets has them ending up in the "3" wallet after refreshing the page.

![3](https://user-images.githubusercontent.com/9660062/219020929-7ffeb536-4b56-4c26-9a66-09352cee078b.png)

**Comment by dni** [comment]
thank you for the bugreport this issue is fixed here: https://github.com/lnbits/lnbits/pull/1541 and will be merged asap
