### ISSUE TITLE
Would be cool to have an Auth extension [Feature request]

### ISSUE THREAD

**Issue by Jared-Dahlke** [lnbits/lnbits#1508]
**Is your feature request related to a problem? Please describe.**
I'm using the paywall extension and its APIs which are amazing! Thanks for the incredible project. I was just thinking it would be nice if there was also an extension to easily do lightning login / auth for devs

**Describe the solution you'd like**
Auth extension
**Describe alternatives you've considered**
right now i'm running a separate server to do this using [lnurl-passport-react](https://www.passportjs.org/packages/passport-lnurl-auth/)

**Comment by motorina0** [comment]
Auth logic now on `main` branch
