### ISSUE TITLE
The withdrawal failed. lnbits.com returned a 500 HTTP error code. Try again later, or contact their support.

### ISSUE THREAD

**Issue by blankscreengithub** [lnbits/lnbits#153]
I created a Quick Voucher and an Advanced Withdraw Link.

When I scan the withdrawal QR code with BlueWallet lightning (BlueWallet custodial wallet setup), the sats are withdrawn and deposited as expected.

When I tried it with Phoenix wallet, I get the following error:

"The withdrawal failed. lnbits.com returned a 500 HTTP error code. Try again later, or contact their support."

![attachment](https://user-images.githubusercontent.com/66571264/110227435-24ba3080-7ebe-11eb-9982-9348adc46107.jpeg)

**Comment by arcbtc** [comment]
Could be a bunch of things;
Is your lnbits server over https? (lnurl needs https)
Does the LNURL account for the reserve fee?
Have you got channels, etc setup to your node?

**Comment by arcbtc** [comment]
Is this issue resolved, did it magically fix itself?

**Comment by blankscreengithub** [comment]
> Is this issue resolved, did it magically fix itself?

I will have to try again. I haven't interacted with my LNbits wallet since then.

**Comment by blankscreengithub** [comment]
> Is this issue resolved, did it magically fix itself?

Yes, everything works now.
