### ISSUE TITLE
user manager transaction history not showing pending invoices[BUG]

### ISSUE THREAD

**Issue by sawrubgupta** [lnbits/lnbits#1531]
Bug is I am hitting usermanager/transaction api and in this api, pending invoices are not coming.
But is GET /payments --- pending invoices are coming. please check the bug !

**Comment by jackstar12** [comment]
https://github.com/lnbits/usermanager/blob/e632669d94cf00b982ee39372d6b86bba004926a/crud.py#L111-L114

It seems intentional this way. It could be changed to a query parameter or pending ones could be included by default
