### ISSUE TITLE
settings.lnbtis_disabled_extensions use case

### ISSUE THREAD

**Issue by jackstar12** [lnbits/lnbits#1547]
I was wondering about the usage of `settings.lnbits_disabled_extensions` in the `ExtensionManager`

I assume the use to be manually disabling an extension in the extensions folder (because it is never assigned in the code, just through env)

https://github.com/lnbits/lnbits/blob/f943ca7d5127c92bd7c796d76bcfb5f1e66abfbd/lnbits/extension_manager.py#L55-L99

However, the iteration here seems wrong, because it is iterating through the paths and checking it against extension codes.
https://github.com/lnbits/lnbits/blob/f943ca7d5127c92bd7c796d76bcfb5f1e66abfbd/lnbits/extension_manager.py#L70-L72

A fix for this would be to instead add an if statement before the line
https://github.com/lnbits/lnbits/blob/f943ca7d5127c92bd7c796d76bcfb5f1e66abfbd/lnbits/extension_manager.py#L84
Something like:
`if extension_code not in self._disabled:`

Maybe also rename it in the process? Somethign like `lnbits_ignored_extensions` could suit better as disabled might be misleading with the per user active state of the extension

**Comment by dni** [comment]
LGTM

**Comment by jackstar12** [comment]
> Good catch!
> 
> * `settings.lnbits_disabled_extensions` is now redundant
> * admin users can disable (deactivate) any extension from the `Manage Extensions` UI (the install screen)
> * I think this setting can be removed (@dni please confirm)

I've actually found it useful for disabling an extension that is not installed through a repository.

**Comment by dni** [comment]
:thinking: hm, is it really useful though? i would remove it aswell, because as a non-developer you should never need it, and a a developer its simply enought to mv or remove the extensions from the directory.

can you make a PR removing that setting :)?
