### ISSUE TITLE
[BUG] Error installing pip requirements at secp256k1

### ISSUE THREAD

**Issue by zx9r** [lnbits/lnbits#1548]
**Describe the bug**

pip throws an error when trying to install secp256k1==0.14.0

> Collecting secp256k1==0.14.0
>   Using cached secp256k1-0.14.0.tar.gz (2.4 MB)
>   Preparing metadata (setup.py) ... error
>   error: subprocess-exited-with-error
> 
>   × python setup.py egg_info did not run successfully.
>   │ exit code: 1
>   ╰─> [57 lines of output]
>       0.29.2
>       /home/pi/lnbits/venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
>         warnings.warn(
>       WARNING: The wheel package is not available.
>         error: subprocess-exited-with-error
> 
>         × python setup.py bdist_wheel did not run successfully.
>         │ exit code: 1
>         ╰─> [12 lines of output]
>             /home/pi/lnbits/venv/lib/python3.10/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
>               warnings.warn(
>             WARNING: The wheel package is not available.
>             WARNING: The wheel package is not available.
>             WARNING: The wheel package is not available.
>             WARNING: The wheel package is not available.
>             usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
>                or: setup.py --help [cmd1 cmd2 ...]
>                or: setup.py --help-commands
>                or: setup.py cmd --help
> 
>             error: invalid command 'bdist_wheel'
>             [end of output]
> 
>         note: This error originates from a subprocess, and is likely not a problem with pip.
>         ERROR: Failed building wheel for pytest-runner
>       ERROR: Failed to build one or more wheels
>       Traceback (most recent call last):
>         File "/home/pi/lnbits/venv/lib/python3.10/site-packages/setuptools/installer.py", line 82, in fetch_build_egg
>           subprocess.check_call(cmd)
>         File "/usr/lib/python3.10/subprocess.py", line 369, in check_call
>           raise CalledProcessError(retcode, cmd)
>       subprocess.CalledProcessError: Command '['/home/pi/lnbits/venv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpndm03rz_', '--quiet', 'pytest-runner==2.6.2']' returned non-zero exit status 1.
> 
>       The above exception was the direct cause of the following exception:
> 
>       Traceback (most recent call last):
>         File "<string>", line 2, in <module>
>         File "<pip-setuptools-caller>", line 34, in <module>
>         File "/tmp/pip-install-go72plwx/secp256k1_4b4d8a653531497ca325100de8616f74/setup.py", line 265, in <module>
>           setup(
>         File "/home/pi/lnbits/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 86, in setup
>           _install_setup_requires(attrs)
>         File "/home/pi/lnbits/venv/lib/python3.10/site-packages/setuptools/__init__.py", line 80, in _install_setup_requires
>           dist.fetch_build_eggs(dist.setup_requires)
>         File "/home/pi/lnbits/venv/lib/python3.10/site-packages/setuptools/dist.py", line 874, in fetch_build_eggs
>           resolved_dists = pkg_resources.working_set.resolve(
>         File "/home/pi/lnbits/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 789, in resolve
>           dist = best[req.key] = env.best_match(
>         File "/home/pi/lnbits/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1075, in best_match
>           return self.obtain(req, installer)
>         File "/home/pi/lnbits/venv/lib/python3.10/site-packages/pkg_resources/__init__.py", line 1087, in obtain
>           return installer(requirement)
>         File "/home/pi/lnbits/venv/lib/python3.10/site-packages/setuptools/dist.py", line 944, in fetch_build_egg
>           return fetch_build_egg(self, req)
>         File "/home/pi/lnbits/venv/lib/python3.10/site-packages/setuptools/installer.py", line 84, in fetch_build_egg
>           raise DistutilsError(str(e)) from e
>       distutils.errors.DistutilsError: Command '['/home/pi/lnbits/venv/bin/python3', '-m', 'pip', '--disable-pip-version-check', 'wheel', '--no-deps', '-w', '/tmp/tmpndm03rz_', '--quiet', 'pytest-runner==2.6.2']' returned non-zero exit status 1.
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> error: metadata-generation-failed
> 
> × Encountered error while generating package metadata.
> ╰─> See above for output.
> 
> note: This is an issue with the package mentioned above, not pip.
> hint: See above for details.

**To Reproduce**

I followed this steps:

sudo apt install -y pkg-config libpq-dev
git clone https://github.com/lnbits/lnbits.git
cd lnbits
python -m venv venv
source venv/bin/activate
pip install -r requirements.txt

**Additional context**
System is a Raspberry Pi with Ubuntu Server

¿ May be dont exist a wheel package for Raspberry ?

**Comment by zx9r** [comment]
Solved with pip install wheel as suggested by @callebtc here: https://github.com/rustyrussell/secp256k1-py/issues/7

**Comment by zx9r** [comment]
It seems I talked too early. Now it fails trying to compile the source:

> /usr/bin/mkdir -p '/tmp/pip-install-makef_ik/secp256k1_36cfb78c086043f6bae12c8c39ad657d/build/temp.linux-aarch64-cpython-310/include'
>        /usr/bin/install -c -m 644 /tmp/pip-install-makef_ik/secp256k1_36cfb78c086043f6bae12c8c39ad657d/libsecp256k1/include/secp256k1.h /tmp/pip-install-makef_ik/secp256k1_36cfb78c086043f6bae12c8c39ad657d/libsecp256k1/include/secp256k1_preallocated.h /tmp/pip-install-makef_ik/secp256k1_36cfb78c086043f6bae12c8c39ad657d/libsecp256k1/include/secp256k1_ecdh.h /tmp/pip-install-makef_ik/secp256k1_36cfb78c086043f6bae12c8c39ad657d/libsecp256k1/include/secp256k1_recovery.h /tmp/pip-install-makef_ik/secp256k1_36cfb78c086043f6bae12c8c39ad657d/libsecp256k1/include/secp256k1_extrakeys.h /tmp/pip-install-makef_ik/secp256k1_36cfb78c086043f6bae12c8c39ad657d/libsecp256k1/include/secp256k1_schnorrsig.h '/tmp/pip-install-makef_ik/secp256k1_36cfb78c086043f6bae12c8c39ad657d/build/temp.linux-aarch64-cpython-310/include'
>        /usr/bin/mkdir -p '/tmp/pip-install-makef_ik/secp256k1_36cfb78c086043f6bae12c8c39ad657d/build/temp.linux-aarch64-cpython-310/lib/pkgconfig'
>        /usr/bin/install -c -m 644 libsecp256k1.pc '/tmp/pip-install-makef_ik/secp256k1_36cfb78c086043f6bae12c8c39ad657d/build/temp.linux-aarch64-cpython-310/lib/pkgconfig'
>       make[1]: Leaving directory '/tmp/tmpa9nleye4'
>       running build_ext
>       generating cffi module 'build/temp.linux-aarch64-cpython-310/_libsecp256k1.c'
>       building '_libsecp256k1' extension
>       creating build/temp.linux-aarch64-cpython-310/build
>       creating build/temp.linux-aarch64-cpython-310/build/temp.linux-aarch64-cpython-310
>       aarch64-linux-gnu-gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O2 -Wall -g -fstack-protector-strong -Wformat -Werror=format-security -g -fwrapv -O2 -fPIC -DCFFI_ENABLE_RECOVERY -I/home/pi/lnbits/venv/include -I/usr/include/python3.10 -Ibuild/temp.linux-aarch64-cpython-310/include -I/tmp/pip-install-makef_ik/secp256k1_36cfb78c086043f6bae12c8c39ad657d/build/temp.linux-aarch64-cpython-310/include -c build/temp.linux-aarch64-cpython-310/_libsecp256k1.c -o build/temp.linux-aarch64-cpython-310/build/temp.linux-aarch64-cpython-310/_libsecp256k1.o
>       build/temp.linux-aarch64-cpython-310/_libsecp256k1.c:50:14: fatal error: pyconfig.h: No such file or directory
>          50 | #    include <pyconfig.h>
>             |              ^~~~~~~~~~~~
>       compilation terminated.
>       error: command '/usr/bin/aarch64-linux-gnu-gcc' failed with exit code 1
>

**Comment by prusnak** [comment]
You need `python3-dev` installed to be able to build native Python modules.

**Comment by zx9r** [comment]
Thank you @prusnak it is working now. I should have read that in the troubleshoting section
