### ISSUE TITLE
[Feature request] Copy-Button next to payment hash

### ISSUE THREAD

**Issue by LightRider5** [lnbits/lnbits#1552]
It would be very helpful to have a simple copy button (where the red square is placed)  to copy the payment hash.

<img width="439" alt="Screenshot 2023-02-27 at 15 30 56" src="https://user-images.githubusercontent.com/48626097/221593208-90353e79-1869-4623-a02f-844ab1b02fe3.png">

**Comment by dni** [comment]
pull request open :) and hopefully merged soon!
