### ISSUE TITLE
Handy backup tool

### ISSUE THREAD

**Issue by Darth-Coin** [lnbits/lnbits#156]
Feature request (for dumb normal users)
Can we have a simple button in LNbits interface, that make a full image backup of the docker repository/folder and database?
Users need simple tools for backup / restore, no complicated command lines and digging up into how to find the data to be restored etc.

**Comment by fiatjaf** [comment]
But if they don't know to do the backup how will they restore it?

It could be done in a foolproof way, but I think it will be very hard and likely to introduce too much complexity. Let's think about it. Maybe it's better to post the database to Telegram or something.

**Comment by arcbtc** [comment]
Thats something for the admin extension I thinks. When Admin extension universe? 🤷

**Comment by talvasconcelos** [comment]
Something that can be implemented in the forecoming Admin extension... @arcbtc noted!
