### ISSUE TITLE
Unsupported upgrade request nginx

### ISSUE THREAD

**Issue by Surenic** [lnbits/lnbits#1561]
Hey there,

I was using lnbits integrated on a raspiblitz before and am now trying to get it to run on a seperate machine. Installation (0.10) went successful and I am able to reach it on 127.0.0.1:5000 (or 0.0.0.0:5000, if configured).

Now I put this machine and my lightning node in a VPS VPN together running nginx. Pointing my domain to the lnbits servers VPN IP gets me an "unsupported upgrade request".

So I installed nginx to the lnbits machine instead with the following config file:

```
## lnbits_ssl.conf

server {
    listen 5001 ssl http2;
    listen [::]:5001 ssl http2;
    server_name _;

    access_log /var/log/nginx/access_lnbits.log;
    error_log /var/log/nginx/error_lnbits.log;

    location /static {
        root /home/lnbits/lnbits/lnbits;
    }

    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header X-Forwarded-Proto https;
        proxy_set_header Host $host;
        proxy_http_version 1.1; # headers to ensure replies are coming back and forth through your domain

    }
    ssl_certificate /home/lnbits/certs/lnbits-ssl.crt;
    ssl_certificate_key /home/lnbits/certs/lnbits-ssl.key;
}
```

Same result: Calling 0.0.0.0:5001 gets me an "unsupported upgrade request"

If I comment out `proxy_set_header Connection 'upgrade'`, it works, but with a lot of visual errors

Can anyone help me, please? I am not an nginx expert. Used this conf a lot to reach several services

**Comment by Surenic** [comment]
Thank you! Already tried that... status now: reinstalled LNbits on a debian VM (errors on adding deadsnake ppa, don't know if this is a problem).

Now the unsupported upgrade request message is gone but calling LNbits over nginx->VPN_IP:5000 results in several errors: Admin UI hidden, exention logos grey, paying lnurlp not possible, extensions not installable (no manage button), whether I am admin or not.

Local on LOCAL_IP:5000 everything works perfectly.

This is making me nuts. I have no idea how to proceed

**Comment by schneimi** [comment]
Looks like the static files cannot be loaded. What does the browser show in the network console?

Maybe you find something in my setup that can help, for one I don't have the /static location and I had a CORS issue with the fonts:
```
    location / {
        proxy_pass http://127.0.0.1:3007;

        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";

        proxy_http_version 1.1;

        include uwsgi_params;
    }

    location ~* \.(woff2)$ {
        proxy_pass http://127.0.0.1:3007;
        add_header Access-Control-Allow-Origin *;
    }
```

**Comment by Surenic** [comment]
You, sir, took me one step forward!!!

I replaced my location settings with yours. I received the "unsupported upgrade request" again and uncommented `proxy_set_header Connection "upgrade";` and now logo images show up, extensions are available. tpos extension works, invoices are payable. The only thing still not working is lnurlp. Damn it, I have been perfectly happy already.

**Comment by schneimi** [comment]
Happy to help. About lnurlp, you could have a look with https://lightningdecoder.com/ into the details of the LNURL. There may be something wrong with the host.

**Comment by Surenic** [comment]
Meanwhile I put the whole setup to a new VPS, handling the Wireguard Server. I installed LNbits directly on top, reverse proxy is handled by Caddy. Everything is working too, except lnurlp... https://lightningdecoder.com/ shows no errors. An invoice on my node gets created on request and can be manually paid.

I tried paying the lnurlp with legend.lnbits and receive
![grafik](https://user-images.githubusercontent.com/70470874/223040778-968aef80-755e-4da1-971c-a3fc287d1880.png)


With alby I get
![grafik](https://user-images.githubusercontent.com/70470874/223040829-e7d1c147-bd6b-4979-87da-723812fc128a.png)

I do have enough inbound, as I said the invoice gets manually paid in a sec :/

**Comment by dni** [comment]
can you put copy the LNURL here?

**Comment by Surenic** [comment]
of course

LNURL1DP68GURN8GHJ7CM0WFJKYARR9EKXUCNFW3EJUMN9WSHKCMN4WFK8QT63GV6XSJMXKPTQVF

**Comment by Surenic** [comment]
Ah yes sure, it's a fixed 50.000msat lnurlp

**Comment by dni** [comment]
if you decode it youll get this URL. https://corebtc.lnbits.net/lnurlp/QC4hKf it show you can min and max send only 50k sats. it looks correct.

**Comment by dni** [comment]
i tried it myself and everything looks good, it really seems like you do not have inbound liquidity / path for lnbits.com.

now after paying it from my lnbits instance i get following error 
```Payment failed: CLN method 'pay' failed with 'bolt11 uses description_hash, but you did not provide description parameter'.```
500 INTERNAL SERVER ERROR

**Comment by dni** [comment]
i think i reproduced it on my instance i know the issue, can you try settings a comment allow value inside your lnurlp?

![screenshot-1678086762](https://user-images.githubusercontent.com/1743657/223042669-d04b7d1f-3f69-4262-b6da-de6e049a602a.jpg)

**Comment by dni** [comment]
i seems like CLN does not like it when you dont have the commentAllow set... for some reason, looks like a recent PR messed that up.

**Comment by Surenic** [comment]
legend.LNbits as a backend works perfectly, so it is a CLN/Spark issue here

I put in a comment allow, but no difference

**Comment by dni** [comment]
i see there is something very wrong here, i dont think it is your setup

**Comment by Surenic** [comment]
I can't think of anything wrong on my setup too. No idea what to try next. Thank you anyway for your help! Guess I'll have to think about switching to LND again 😆

**Comment by dni** [comment]
no, legend is running core lightning aswell, this need to be fixed asap

**Comment by Surenic** [comment]
Closing this as the "unsupported upgrade request" seemed to be a misconfiguration and could be solved by caddy. Furthermore the payment issue is CLN v23.02 related as this version doesn't support description hashes anymore (https://github.com/ElementsProject/lightning/pull/5747#issuecomment-1454955649) resulting in LNURL problems
