### ISSUE TITLE
[Feature request] Enable stripe like functionality via Hyperswitch

### ISSUE THREAD

**Issue by mysticaltech** [lnbits/lnbits#1562]
Hey folks, to enable the use of lnbits on the web as an alternative to stripe or other payment solutions, it would be super interesting if you integrated with Hyperswitch https://github.com/juspay/hyperswitch, which lets users connect with multiple payment processors and route traffic effortlessly, all with a single API integration.

**Comment by motorina0** [comment]
1. What employments are there in the whiled for Hyperswitch?
2. Is Hyperswitch a KYC-ed solution?

**Comment by bitkarrot** [comment]
To a certain degree LNbits already appears to be doing the basics of Hyperswitch but for Lightning only, in that there are almost 15 backend integrations to both self sovereign lightning nodes or to custodial lightning providers. This is what hyperswitch appears to do but with credit card payments. 

https://docs.hyperswitch.io/

**Comment by motorina0** [comment]
@bitkarrot that's also my understanding

@mysticaltech can you please describe an end-to-end use-case where `LNbits` and `Hyperswitch` work together

**Comment by mysticaltech** [comment]
@motorina0 The simplest way I can explain is that I'm planning to support both fiat payment gateways and lnbits, so hyperswitch fits perfectly, and I was imagining lnbits as just one other payment provider in the image below.

<img width="751" alt="switch" src="https://github.com/user-attachments/assets/a220596b-d5a8-48b9-bfe1-d45d1c02c413">

**Comment by motorina0** [comment]
> it would be super interesting if you integrated with Hyperswitch
 - how can LNbits integrate into Hyperswitch? From the description above it looks like Hyperswitch should call LNbits APIs
 - APIs for user, wallets and payments are already in place

Closing this issue until a specific feature-request is articulated.

**Comment by mysticaltech** [comment]
Correct, they should be able to call your API, but first they need to hear of your service first.
