### ISSUE TITLE
LNBits Wiki and Install Guide are 404 pages now

### ISSUE THREAD

**Issue by CryptoDeity** [lnbits/lnbits#1567]
Tried to set up a new LNBits Server and I'm getting 404 pages!
![Screenshot (285)](https://user-images.githubusercontent.com/62268768/223623290-6f62bffb-738e-4b5a-9a31-10f4cf8bafc1.png)

**Comment by prusnak** [comment]
This was fixed via https://github.com/lnbits/lnbits/pull/1572
