### ISSUE TITLE
Support ticket - flat rate

### ISSUE THREAD

**Issue by Darth-Coin** [lnbits/lnbits#157]
The support ticket app is handy and can be used in many situations.
But the "amount per word" not sure if can be applied very well.
Users can put just a word (to save in payment) and sometimes that can't cover the effort to answer the ticket. Maybe in other situations.

I suggest to add another option as "flat rate".
Another additional way could be to have a drop-down box in the form where the "client" can select types of support (editable in another table by the admin) and each type with a specific flat rate. In that way one form can be used for multiple types of requests, so no need to make one form for each type.

**Comment by fiatjaf** [comment]
What about charging less for more words? Just kidding.

Yes, this is a good idea.

**Comment by arcbtc** [comment]
I concur, good idea!
