### ISSUE TITLE
[BUG]: Cryptic UNIQUE constraint failed error when paying same invoice twice.

### ISSUE THREAD

**Issue by JssDWt** [lnbits/lnbits#1571]
**Describe the bug**
When the lnurlw callback of the boltcards extension is invoked multiple times with the same invoice, lnbits shows a cryptic error in the form of `(sqlite3.IntegrityError) UNIQUE constraint failed: apipayments.wallet, apipayments.checking_id SQL: INSERT INTO apipayments (wallet, checking_id, bolt11 [etc...]`. This is a race condition I think where the payment for that invoice is already in progress, but not yet completed (because when it's completed you see something like 'invoice already paid').

**To Reproduce**
1. Invoke boltcards lnurlw callback multiple times with the same invoice quickly.
2. lnbits will show and return that error.

**Expected behavior**
lnbits should give a proper error instead of this cryptic one for non-developers. Something like 'payment already in progress'

**Desktop (please complete the following information):**
 - LNbits version: 0.9.7.x
 - Boltcards extension 0.9.2.x 
 - Database [e.g. sqlite, postgres]

**Additional context**
Posting this issue here in the main repo, because it's the `pay_invoice` call that's returning the error, where the `checking_id` is the invoice payment hash. This error was seen by @tlindi in an interaction with Breez (it was Breez scanning the bolt card and invoking the lnurlw endpoint multiple times with the same invoice). Issue for Breez is tracked [here](https://github.com/breez/breezmobile/issues/1081).

I suggest catching that UNIQUE constraint error there and returning the payment already in progress error instead.

Note that I reported this as a bug, but nothing is not working. Nothing is being paid twice and there are no state inconsistencies. Just the error is cryptic and scary for users.

**Comment by tlindi** [comment]
Does PR https://github.com/lnbits/lnbits/pull/1594 fix also this issue?

**Comment by dni** [comment]
yes, thanks
