### ISSUE TITLE
Display LN Payment Failure Reason [Feature request]

### ISSUE THREAD

**Issue by alltheseas** [lnbits/lnbits#1585]
**Is your feature request related to a problem? Please describe.**
As a LNURL user who is looking to send a payment over LN, I sometimes run into payment failures. LNBits does not always display a reason for lightning payment failure.

**User Story**
As a LNBits LNURL user who is looking to send a payment over LN, when a LN payment fails, I want to know that the LN payment failed, AND the reason for the LN payment failure, so that I can troubleshoot and/or change my payment approach.

_Acceptance Criteria_
1. LNBits displays payment failure state clearly
2. LNBits displays payment failure reason clearly
3. LNBits displays intermittent payment state clearly (e.g. trying, sending, routing / similar), in order to show to LNBits user that LNBits is attempting payment, and that payment has not yet failed

**Describe alternatives you've considered**
Do nothing.

**Additional context**
Example possible failure reasons:
> 1. Insufficient funds
> 2. No route found
> 3. Routing time-out reached etc.

origin:  @danielabrozzoni

<img width="615" alt="Screenshot 2023-03-21 at 11 46 57 AM" src="https://user-images.githubusercontent.com/64376233/226697118-3b51c9c9-2a52-40e0-9fd3-4acce0332958.png">

iris.to/note1wu5kwk2a32c9uw3letlh0mxnak8q53xj474sp5t54nxx2km2q4assd3gxr

Possibly related to https://github.com/lnbits/lnbits/issues/717.

**Comment by dni** [comment]
in this case i think it is not really clear if the invoice is even failed, maybe the invoice just got requested and not paid. so it will stay pending until the timeout is hit.

i think this is  a very interesting issue! i will follow up on that one after some research.

**Comment by alltheseas** [comment]
What was the outcome of this limbo state @dni ?
