### ISSUE TITLE
[BUG] Disabled extension in adminUI still remain active

### ISSUE THREAD

**Issue by Darth-Coin** [lnbits/lnbits#1587]
### Description
Disabled extension still remain active for users

**To Reproduce**
1. Go to "manage server" - "disabled extensions" - add user manager or any other extension
2. Click on "Save" then click on "restart server".
3. Open normal user lnbits page, go to extensions - try to install disabled extension. It works and also you can use it if you open it.

Also after a hard restart of lnbits (from command line) is still active.

**Expected behavior**
Extension should not be visible anymore or at least not possible to be installed /used by the user

**Screenshots**
![image](https://user-images.githubusercontent.com/56997124/226943100-0c49feab-86d5-4563-8544-f8ae478ad8a8.png)

**Comment by goodc0re** [comment]
To add to this issue, I have added the User Manager extension to "Admin Extensions" and my users are still able to use the User Manager extension. 

From the description "Extensions only user with admin privileges can use" I would also think that my users should not be able to access the extension.

**Comment by dni** [comment]
i think the disabled extension got obsoleted, because now we handle extensions differently, its pretty much a relic and i think there is a PR open addressing this which i cannot find right now.

**Comment by motorina0** [comment]
This is now done by the admin user from the extensions page:

![image](https://github.com/user-attachments/assets/6bdc39ec-f586-4b24-bbef-ba3942c3b7e0)
