### ISSUE TITLE
Opening OfflineShop extension results in 500 error

### ISSUE THREAD

**Issue by cryptoteun** [lnbits/lnbits#159]
When I try to open the Offline Shop it returns a 500 error.
- I'm not able to insert a product
- I'm not able to insert a word

**Steps to reproduce:** 
1. enable extension
2. open offlineshop

Logs:
`sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) NOT NULL constraint failed: shops.method`
`[SQL:  
    INSERT INTO shops (wallet, wordlist)
    VALUES (?, ?)
]`

**Comment by fiatjaf** [comment]
Fixed on 1a460a2ce57dbd63094bc415cdcaa34239827b6b.

**Comment by cryptoteun** [comment]
Great, working now!
