### ISSUE TITLE
[BUG] lnaddress extensions doesn't respond at .well-known/lnurlp/username

### ISSUE THREAD

**Issue by akovalenko** [lnbits/lnbits#1592]
**Describe the bug**

After setting up a fresh lnbits instance, installing and activating lnaddress extension, I get 404 not found at http://127.0.0.1:5000/.well-known/lnurlp/username instead of "user not found"

**To Reproduce**
1. git clone https://github.com/lnbits/lnbits.git
2. poetry install 
3. cp .env.example .env
4. poetry run lnbits
5. create a fresh user & wallet at http://127.0.0.1:5000
6. ^C stop lnbits, edit LNBITS_ADMIN_USERS in .env, adding a fresh user
7. poetry run lnbits
8. install & activate lnaddress extension at http://127.0.0.1:5000
9. curl http://127.0.0.1:5000/.well-known/lnurlp/nosuchuser
10. get HTTP 404 `{"detail":"Not Found"}`

**Expected behavior**
HTTP 500 with `{"detail":"User not found"}`

**Desktop (please complete the following information):**
 - LNbits version: 239f166a141fa9347ba7ab958c80cbc8804bd8b8
 - Database sqlite

**Additional context**
I'm preparing to move my old installation to new lnbits with poetry and installable extensions. My "real", more complicated problem is an existing lnaddress on a migrated db not working as expected.  The problem with fresh installation not responding as expecting seems to be the root cause (or a part of it), so I report it instead of the whole migration problem.

I see instances of lnbits everywhere correctly responding to `.well-known/lnurlp/unknownuser`, so I expect a problem with my environment, installation or the way of starting lnbits, not a bug in a proper sense.

**Comment by callebtc** [comment]
Could this be because you have the latest LNURLP extension installed? That one could conflict with the lnaddress extension because both want to respond to the same path.

**Comment by akovalenko** [comment]
I tested lnaddress without lnurlp to prevent exactly that.

When I install lnurlp it does answer for its lnurl addresses successfully. I actually decided to switch to lnurlp (because all I need is ln addresses on my own domain, and lnurlp is more suitable for it than my "dummy cloudflare" hack over lnaddress). However, the problem with bare lnaddress manifests itself without lnurlp, and it might be important for some other users.

I've also noticed that lnurlp uses another technique to hook into .well-known/lnurlp (lnurlp_redirect_paths instead of `@core_app.get...`), compared to lnaddress. Seems like lnurlp's way of doing it is now the only way.

**Comment by callebtc** [comment]
This might have to do with the fact that route registration has changed in the mean time and maybe lnaddress wasn't updated properly. @motorina0 maybe you have some insights into this.

**Comment by skrafft** [comment]
Hi, I just submitted a pull request that solves this bug here: https://github.com/lnbits/lnaddress/pull/2. Without it, the lnaddress plugin is currently unusable.

**Comment by dni** [comment]
merged
