### ISSUE TITLE
migration to postgress : tool conv not successful

### ISSUE THREAD

**Issue by xtophe632** [lnbits/lnbits#1596]
I followed the migration instruction 
https://docs.lnbits.org/guide/installation.html#sqlite-to-postgresql-migration
with a fresh install of postgresSQL, started and stopped lnbits to initiate the Postgres DB, and got the error message 

pgport = db_url.split("@")[1].split(":")[1].split("/")[0]
IndexError: list index out of range

**Comment by talvasconcelos** [comment]
it seems the URL wasn't correctly formatted. Can you share the DB url, with sensitive info replaced with `xxx` ?

**Comment by xtophe632** [comment]
here you are. 

LNBITS_DATABASE_URL=postgres://postgres:xxx@localhost/lnbits

**Comment by talvasconcelos** [comment]
enclose it with " "

***@***.***/lnbits"

**Comment by xtophe632** [comment]
sorry, I think I did, I will retry and let you know.

**Comment by santyr** [comment]
LNbits version: 0.10.8, Commit version: 8ed2422ade4fa63eaf51cbcff9a07b85a23cc1f2

I've been attempting migration, and have this issue.   I do have the db url enclosed in quotes like: LNBITS_DATABASE_URL="postgres://postgres:xxx@localhost/lnbits".

Traceback (most recent call last):
  File "/home/lnbits/lnbits/tools/conv.py", line 28, in <module>
    pgport = db_url.split("@")[1].split(":")[1].split("/")[0]

**Comment by dni** [comment]
you are missing the port `:5000`

**Comment by santyr** [comment]
The documentation should be updated, since this is where the issue is arising.

  https://docs.lnbits.org/guide/installation.html#sqlite-to-postgresql-migration  doesn't mention a port, and this seems like a bug, or is misleading..

**Comment by dni** [comment]
thanks! can you try if it owrks for you?
i update the docs accordingly, `.env.example` uses this format `LNBITS_DATABASE_URL="postgres://user:password@host:port/databasename"`

**Comment by santyr** [comment]
Thanks works perfectly.  Thanks.
