### ISSUE TITLE
NPM lnbits create TPOS currency error

### ISSUE THREAD

**Issue by gitnonymous** [lnbits/lnbits#160]
There seems to be an issue with creating a TPOS from the NPM lnbits createTPoS(). The issue i think is the 3 letter currency is "lowercase". OpenNode currency is all uppercase. Creating a TPOS from the admin addon uses an uppercase currency code and works.
The browser debug is faulting at :

   var self = this
        axios.get('https://api.opennode.co/v1/rates').then(function (response) {
          self.exchangeRate =
            response.data.data['BTC' + **self.currency][self.currency]**
        })

Thanks in advance.

**Comment by arcbtc** [comment]
Thats an issue to post here https://github.com/MiguelMedeiros/lnbits-js
As the npm library is a seperate project not maintained by ourselves, but thanks a lot for flagging the issue 👍
