### ISSUE TITLE
[BUG] Missing port on the url generated from "Export to Phone with QR Code"

### ISSUE THREAD

**Issue by bota87** [lnbits/lnbits#1602]
**Describe the bug**
The QR Code generated from "Export to Phone with QR Code" dosen't have the port set

**Screenshots**
![image](https://user-images.githubusercontent.com/52842374/229294055-a0db8354-3722-4176-8984-ab7157029782.png)

**Desktop (please complete the following information):**
 - LNbits version: lnbitsdocker/lnbits-legend:0.10.3

**Additional context**
My wallet is accessible from https://192.168.x.x:3000/wallet?usr=xxx but on the QR Code I read https://192.168.x.x/wallet?usr=xxx

**Comment by talvasconcelos** [comment]
Just tested this on localhost:5000 and the correct URL:PORT scheme is displayed on the QR

**Comment by bota87** [comment]
this QR code don't have the 4002 port
https://serverpi/wallet?usr=....
![image](https://user-images.githubusercontent.com/52842374/232136210-b006dcd9-edec-45cd-85bd-63aec48e7651.png)

**Comment by dni** [comment]
the qrcode was fixed recently can you try again with `0.12.4` and reopen if it fails.

it also seems to me it might have been docker related.
