### ISSUE TITLE
[Feature request] Allow user to swap onchain sats into LN sats.

### ISSUE THREAD

**Issue by Xiphid** [lnbits/lnbits#1603]
**Is your feature request related to a problem? Please describe.**
There is no (easy) way for a user who has onchain sats in a different wallet to spend them on LN using LNbits.

The original implementation of LNDhub has a feature where the user of the custodial Lightning wallet can send funds to an onchain address (presented in Bluewallet als the refill option) belonging to the custodian's lightning node.
The user's custodial LN balance is then increased by the amount received onchain by the LN node, thus letting the user refill his wallet.
I think it would be nice for LNbits to also have this feature.

**Describe the solution you'd like**
- Add a refill button to the LNbits wallet, when clicked it should request the next unused onchain address from the LN node and present the address in text and QR form for the user.
- The user can send funds to the address.
- LNbits monitors if funds have been received.
- When funds have been sent and ~6 confirmations have passed the same amount of sats is added to the user's LNbits wallet.
- If the user clicks refill but does not send funds, another user who also clicks refill should have a different address generated so LNbits can track which user actually used the refill option.
- If a user clicks refill but does not send funds, the next time he clicks refill he should be presented with the same address.
- If a user clicks refill and sends funds which receive 6 confirmations should have a new address generated the next time he uses the refill option.

Downsides:
LNbits needs to monitor the onchain wallet of the LN node.

Upsides:
A user who already knows how to make onchain transactions can easily (re)fill his LNbits wallet and spend sats on LN.
The LN node does not need to trust the user.

**Describe alternatives you've considered**
The user could contact the LNbits admin to swap onchain sats for LN sats by calling him from the nearest phonebooth.

**Comment by dni** [comment]
have you seen, https://github.com/lnbits/boltz-extension/ ?

**Comment by talvasconcelos** [comment]
@Xiphid can the issue be closed? Boltz and Deezy extensions seem to do what you want.
