### ISSUE TITLE
Describe the configuration when using docker image

### ISSUE THREAD

**Issue by tomichec** [lnbits/lnbits#161]
Hi, I have build and launched the docker image using:
```
docker build -t lnbits .
docker run --publish 5000:5000 --detach --name lnbits lnbits
```
which works for the default configuration (with `LNBITS_BACKEND_WALLET_CLASS=VoidWallet`).

However, I would like to change the configuration as it is done using `lnbits/.env` file without docker. I have tried to run the image mounting the `.env` file to the docker's working directory directly as

```
docker run --publish 5000:5000 --detach --volume ${PWD}/.env:/app/.env --name lnbits lnbits
```
but it fails with error (last line, full error output attached as file):
```
sqlalchemy.exc.OperationalError: (sqlite3.OperationalError) unable to open database file
```

What is the correct way to configure lnbits running in the docker container?

Thanks!

[lnbits_error.txt](https://github.com/lnbits/lnbits/files/6158867/lnbits_error.txt)

**Comment by arcbtc** [comment]
What os are you running, I think Ubuntu changed their version of sqlite in 20.04, so a lot of people have this issue running on lower

**Comment by tomichec** [comment]
I'm running Ubuntu, but the Dockerimage is based on python:3.7-slim, which is based on Debian.

**Comment by chill117** [comment]
@tomichec I was able to run lnbits in docker using the following as inspiration:
https://github.com/louneskmt/docker-lnbits

**Comment by tomichec** [comment]
Thanks.

Finally, the problem was that the lnbits runs as user ID 1000, while the working directory is owned by root.

I am going send a PR fixing this issue by creating a data directory owned by UID 1000.

**Comment by fiatjaf** [comment]
Fixed by https://github.com/lnbits/lnbits/pull/163.
