### ISSUE TITLE
Code: Harmonize `get_payments` with filter

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#1620]
Continuation of discussion in #1618 about breaking changes introduced in #1557 - paging @jackstar12 @dni 

- The function `get_payments` does not need to remain backwards compatible, we can fix calls to it across the code and the extensions (see https://github.com/lnbits/lndhub/issues/7)
- `/api/v1/payments` must remain 100% backwards compatible, meaning it MUST still accept `limit, offset` arguments
- If the response of `/api/v1/payments` needs to change (as argued here: #1613), we need to add a new endpoint (`v2` or rename to something more explicit)

**Comment by jackstar12** [comment]
`/api/v1/payments` is still backwards compatible. The current state of https://github.com/lnbits/lnbits/pull/1613 reintroduces the `limit` and `offset` on `get_payments` function for convenience / backwards compatibility, so usage of the function doesn't have to be necessarily patched.

**Comment by callebtc** [comment]
> `/api/v1/payments` is still backwards compatible

Yep, I know. But there was confusion in the previous thread. I'm just outlining the boundary conditions. Do you agree with the rest?
