### ISSUE TITLE
[BUG] CoreLightning: paying invoice returns error but payment goes through

### ISSUE THREAD

**Issue by pabpas** [lnbits/lnbits#1640]
**Describe the bug**
With CLN v23.05rc1 as funding source, paying an invoice returns an error but the payment goes through.
```
'msatoshi_sent'
500 INTERNAL SERVER ERROR
```
**Additional context**
Probably related to msats being strings is now deprecated.
https://github.com/ElementsProject/lightning/pull/5986

**Desktop (please complete the following information):**
 - LNbits version: Commit version: 6f194fe2f8efa13d67bfb5fd3e18d91d896699cd
 - Database: sqlite

**Comment by callebtc** [comment]
Which version of CLN are you using this with?

**Comment by pabpas** [comment]
CLN v23.05rc1
