### ISSUE TITLE
Update LNbits in RaspiBlitz

### ISSUE THREAD

**Issue by rootzoll** [lnbits/lnbits#165]
At the moment the RaspiBlitz is installing LNbits based on the "raspiblitz" tag. That is the same as the latest 0.2.0 release from december 2020. There were a lot of new commits on that project ... @fiatjaf will we see a new release soon that we can include in final RaspiBlitz v1.7 (targeted beginning/mid April)?

see also issue on RaspiBlitz repo here https://github.com/rootzoll/raspiblitz/issues/2106

**Comment by fiatjaf** [comment]
I'll move the `raspiblitz` tag and keep moving it if new fixes appear until the day you launch. Is that reasonable?

Or should we use version tags instead of moving the `raspiblitz` tag?

**Comment by rootzoll** [comment]
As long LNbits is fast interating we can still work with you moving the `raspiblitz` tag. At one point I would like to change it to releases so that we can fix on a certain commit on your side for security reasons ... but for now thats fine :) Give me a ping when you move the tag so I can do final testing for the upcomming v1.7 release of RaspiBlitz.

**Comment by fiatjaf** [comment]
Ok, moved the tag. Some very good fixes for old and annoying issues were included in the last days, but I didn't test with LND, so you might spot some weird bugs. Let me know.

Raspiblitz is using `lndrest`, right? Not `lndgrpc`.

**Comment by arcbtc** [comment]
Yes, rest. Grpc was its own special nightmare, but there was the intention to switch at some point
