### ISSUE TITLE
[BUG] Switching funding sources from adminUI hangs

### ISSUE THREAD

**Issue by Darth-Coin** [lnbits/lnbits#1654]
**Describe the bug**
Trying a live scenario with switching funding sources between accounts of legend.lnbits, lntips, lnpay.
Once you switch the funding source in adminUI, and restart the server, it hangs and get errors in lnbits console.

**To Reproduce**
Let's say you start without adminUI, you just add legend.lnbits account as funding source in .env file. All works fine, then you need to activate adminUI.
1. activate adminUI
2. Click on 'funding sources'. You will see that the lnbits account is there saved correctly and also is displaying the total balance available.
3. Delete all the lnbits legend account details
4. Go to LNpay line and add all details requested: 
Endpoint: https://api.lnpay.co/v1
APIKey: sak_xxxxxxxx
WalletKey: waka_xxxxxx
(is strange that in the database.sqlite - settings is listed also WalletAdminKey, so not sure which one should be used)
5. Save settings and click on "Restart server". It will show up the green alert that server is restarted.
6. Go to LNbits console logs and see the errors. It says that cannot start and all hell break lose, lnbits is not starting anymore.

To restore LNbits starting I did the following:
1. Go to .env file and switch manually the funding source to LNpay or LnTips, disable adminUI
2. restart lnbits and works, but adminUI is not usable anymore.
3. Stop Lnbits, edit .env file activating again adminUI
4. open database.sqlite with editor and in "settings" table edit the funding sources corresponding to the one you put in the .env file
5. Restart lnbits. Sometimes is starting but is saying that lnbits funding source could not start and fallback to voidwalelt. So still can enter into LNbits page and do changes, but again are not taken in consideration.

**Expected behavior**
It should just restart with the new funding source details. If the details are wrong, it should fallback to FakeWallet.

**Desktop (please complete the following information):**
 - LNbits version: 10.0.3
 - Database sqlite

**Additional information**
Playing around editing the database and env file, the only way to make it work again is to reset totally the adminUI, but that means all your other settings are gone (users, wallets, etc). Yes, those users and wallets are still in the database, but you cannot manage them anymore from LNbits UI.
It must be a way to be able to use adminUI correctly being able to switch easily between funding sources.

**Comment by talvasconcelos** [comment]
Does this still happens on latest release? Consider closing the issue.

**Comment by motorina0** [comment]
Does not reproduce anymore. Closing issue.
