### ISSUE TITLE
NoneType exception occured on payment

### ISSUE THREAD

**Issue by ChuckNorrison** [lnbits/lnbits#166]
As i try to paste a payment invoice into my LNBits interface and click pay, red notification is displayed with "500"

Some logs from service found:
![image](https://user-images.githubusercontent.com/2964146/113560021-9f33b880-9602-11eb-9556-e12085e2cef2.png)

The invoice was created by a BTCPay Server behind TOR. The payment is displayed as pending in LNBits.

Another payment to an eclair invoice was recently successful. Lntxbot gets payed too via my lnbits wallet. So my node seems basically work. 

// My BTCPay Server does not have a working channel open, so no route to host seems legit?

**Comment by fiatjaf** [comment]
Can you help us debug by adding a line specifically before that `preimage = base64.b64decode(...)` line?

Just add `print('DATA', data)` there, then restart LNbits and try again. View the logs again and tell us what the new logs show.

**Comment by ChuckNorrison** [comment]
added as line 103 and restarted lnbits service. i cant find your print here even the line is now 104. Maybe its not part of journal logging? 

```admin@raspberrypi:/var/log $ sudo journalctl -f -u lnbits -n 200
-- Logs begin at Mon 2021-04-05 21:17:59 BST. --
Apr 06 07:49:21 raspberrypi systemd[1]: Stopping lnbits...
Apr 06 07:49:21 raspberrypi systemd[1]: lnbits.service: Main process exited, code=killed, status=15/TERM
Apr 06 07:49:21 raspberrypi systemd[1]: lnbits.service: Succeeded.
Apr 06 07:49:21 raspberrypi systemd[1]: Stopped lnbits.
Apr 06 07:49:21 raspberrypi systemd[1]: Started lnbits.
Apr 06 07:49:25 raspberrypi sh[18959]: [2021-04-06 07:49:25 +0100] [18961] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
Apr 06 07:51:02 raspberrypi sh[18959]: [2021-04-06 07:51:02,687] ERROR in app: Exception on request POST /api/v1/payments
Apr 06 07:51:02 raspberrypi sh[18959]: Traceback (most recent call last):
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 143, in handle_request
Apr 06 07:51:02 raspberrypi sh[18959]:     return await self.full_dispatch_request(request_context)
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 165, in full_dispatch_request
Apr 06 07:51:02 raspberrypi sh[18959]:     result = await self.handle_user_exception(error)
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 178, in handle_user_exception
Apr 06 07:51:02 raspberrypi sh[18959]:     return await super().handle_user_exception(error)
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/app.py", line 1076, in handle_user_exception
Apr 06 07:51:02 raspberrypi sh[18959]:     raise error
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 163, in full_dispatch_request
Apr 06 07:51:02 raspberrypi sh[18959]:     result = await self.dispatch_request(request_context)
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/app.py", line 1882, in dispatch_request
Apr 06 07:51:02 raspberrypi sh[18959]:     return await handler(**request_.view_args)
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 55, in wrapped_view
Apr 06 07:51:02 raspberrypi sh[18959]:     return await view(**kwargs)
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/lnbits/core/views/api.py", line 139, in api_payments_create
Apr 06 07:51:02 raspberrypi sh[18959]:     return await api_payments_pay_invoice()
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 28, in wrapped_view
Apr 06 07:51:02 raspberrypi sh[18959]:     return await view(**kwargs)
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 55, in wrapped_view
Apr 06 07:51:02 raspberrypi sh[18959]:     return await view(**kwargs)
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/lnbits/core/views/api.py", line 121, in api_payments_pay_invoice
Apr 06 07:51:02 raspberrypi sh[18959]:     raise exc
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/lnbits/core/views/api.py", line 114, in api_payments_pay_invoice
Apr 06 07:51:02 raspberrypi sh[18959]:     payment_hash = await pay_invoice(wallet_id=g.wallet.id, payment_request=g.data["bolt11"])
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/lnbits/core/services.py", line 131, in pay_invoice
Apr 06 07:51:02 raspberrypi sh[18959]:     payment: PaymentResponse = WALLET.pay_invoice(payment_request)
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/home/lnbits/lnbits/lnbits/wallets/lndrest.py", line 104, in pay_invoice
Apr 06 07:51:02 raspberrypi sh[18959]:     preimage = base64.b64decode(data["payment_preimage"]).hex()
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/usr/lib/python3.7/base64.py", line 80, in b64decode
Apr 06 07:51:02 raspberrypi sh[18959]:     s = _bytes_from_decode_data(s)
Apr 06 07:51:02 raspberrypi sh[18959]:   File "/usr/lib/python3.7/base64.py", line 46, in _bytes_from_decode_data
Apr 06 07:51:02 raspberrypi sh[18959]:     "string, not %r" % s.__class__.__name__) from None
Apr 06 07:51:02 raspberrypi sh[18959]: TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'
```

**Comment by fiatjaf** [comment]
Ok, since you said that I think the issue is that we're not capturing the error properly.

**Comment by fiatjaf** [comment]
Can you upgrade to `master` or apply [this change](https://github.com/lnbits/lnbits/commit/59aaea47fdefa4dac8dc2695f44334fe09841a56) manually and see what happens?

**Comment by ChuckNorrison** [comment]
> Can you upgrade to `master` or apply [this change](https://github.com/lnbits/lnbits/commit/59aaea47fdefa4dac8dc2695f44334fe09841a56) manually and see what happens?

here we go :+1: 

```Apr 06 14:26:53 raspberrypi systemd[1]: Started lnbits.
Apr 06 14:27:02 raspberrypi sh[11994]: [2021-04-06 14:27:02 +0100] [11998] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
Apr 06 14:28:48 raspberrypi sh[11994]: [2021-04-06 14:28:48,575] ERROR in app: Exception on request POST /api/v1/payments
Apr 06 14:28:48 raspberrypi sh[11994]: Traceback (most recent call last):
Apr 06 14:28:48 raspberrypi sh[11994]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 143, in handle_request
Apr 06 14:28:48 raspberrypi sh[11994]:     return await self.full_dispatch_request(request_context)
Apr 06 14:28:48 raspberrypi sh[11994]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 165, in full_dispatch_request
Apr 06 14:28:48 raspberrypi sh[11994]:     result = await self.handle_user_exception(error)
Apr 06 14:28:48 raspberrypi sh[11994]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 178, in handle_user_exception
Apr 06 14:28:48 raspberrypi sh[11994]:     return await super().handle_user_exception(error)
Apr 06 14:28:48 raspberrypi sh[11994]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/app.py", line 1076, in handle_user_exception
Apr 06 14:28:48 raspberrypi sh[11994]:     raise error
Apr 06 14:28:48 raspberrypi sh[11994]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 163, in full_dispatch_request
Apr 06 14:28:48 raspberrypi sh[11994]:     result = await self.dispatch_request(request_context)
Apr 06 14:28:48 raspberrypi sh[11994]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/app.py", line 1882, in dispatch_request
Apr 06 14:28:48 raspberrypi sh[11994]:     return await handler(**request_.view_args)
Apr 06 14:28:48 raspberrypi sh[11994]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 55, in wrapped_view
Apr 06 14:28:48 raspberrypi sh[11994]:     return await view(**kwargs)
Apr 06 14:28:48 raspberrypi sh[11994]:   File "/home/lnbits/lnbits/lnbits/core/views/api.py", line 139, in api_payments_create
Apr 06 14:28:48 raspberrypi sh[11994]:     return await api_payments_pay_invoice()
Apr 06 14:28:48 raspberrypi sh[11994]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 28, in wrapped_view
Apr 06 14:28:48 raspberrypi sh[11994]:     return await view(**kwargs)
Apr 06 14:28:48 raspberrypi sh[11994]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 55, in wrapped_view
Apr 06 14:28:48 raspberrypi sh[11994]:     return await view(**kwargs)
Apr 06 14:28:48 raspberrypi sh[11994]:   File "/home/lnbits/lnbits/lnbits/core/views/api.py", line 121, in api_payments_pay_invoice
Apr 06 14:28:48 raspberrypi sh[11994]:     raise exc
Apr 06 14:28:48 raspberrypi sh[11994]:   File "/home/lnbits/lnbits/lnbits/core/views/api.py", line 114, in api_payments_pay_invoice
Apr 06 14:28:48 raspberrypi sh[11994]:     payment_hash = await pay_invoice(wallet_id=g.wallet.id, payment_request=g.data["bolt11"])
Apr 06 14:28:48 raspberrypi sh[11994]:   File "/home/lnbits/lnbits/lnbits/core/services.py", line 141, in pay_invoice
Apr 06 14:28:48 raspberrypi sh[11994]:     raise Exception(payment.error_message or "Failed to pay_invoice on backend.")
Apr 06 14:28:48 raspberrypi sh[11994]: Exception: no_route
```

**Comment by fiatjaf** [comment]
Ok, got rid of that. Now it should fail more cleanly.

**Comment by ChuckNorrison** [comment]
I would like to reopen this issue basically. After a long time i tried to use my lnbits on clearnet to pay a coingate lightning invoice. I received some funds via lightning from an eclair wallet successful but as i want to pay my coingate invoice it stucks. Second try ends on 500.

Here are some logs:

> Aug 19 16:12:29 raspberrypi sh[12206]: [2021-08-19 16:12:29 +0100] [12207] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
Aug 19 16:14:13 raspberrypi sh[12206]: [2021-08-19 16:14:13,749] ERROR in app: Exception on request POST /api/v1/payments
Aug 19 16:14:13 raspberrypi sh[12206]: Traceback (most recent call last):
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 131, in handle_request
Aug 19 16:14:13 raspberrypi sh[12206]:     return await self.full_dispatch_request(request_context)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 153, in full_dispatch_request
Aug 19 16:14:13 raspberrypi sh[12206]:     result = await self.handle_user_exception(error)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 166, in handle_user_exception
Aug 19 16:14:13 raspberrypi sh[12206]:     return await super().handle_user_exception(error)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/app.py", line 1104, in handle_user_exception
Aug 19 16:14:13 raspberrypi sh[12206]:     raise error
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 151, in full_dispatch_request
Aug 19 16:14:13 raspberrypi sh[12206]:     result = await self.dispatch_request(request_context)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/app.py", line 1933, in dispatch_request
Aug 19 16:14:13 raspberrypi sh[12206]:     return await handler(**request_.view_args)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 55, in wrapped_view
Aug 19 16:14:13 raspberrypi sh[12206]:     return await view(**kwargs)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/core/views/api.py", line 149, in api_payments_create
Aug 19 16:14:13 raspberrypi sh[12206]:     return await api_payments_pay_invoice()
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 28, in wrapped_view
Aug 19 16:14:13 raspberrypi sh[12206]:     return await view(**kwargs)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 55, in wrapped_view
Aug 19 16:14:13 raspberrypi sh[12206]:     return await view(**kwargs)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/core/views/api.py", line 131, in api_payments_pay_invoice
Aug 19 16:14:13 raspberrypi sh[12206]:     raise exc
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/core/views/api.py", line 124, in api_payments_pay_invoice
Aug 19 16:14:13 raspberrypi sh[12206]:     payment_request=g.data["bolt11"],
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/core/services.py", line 153, in pay_invoice
Aug 19 16:14:13 raspberrypi sh[12206]:     payment: PaymentResponse = await WALLET.pay_invoice(payment_request)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/wallets/lndrest.py", line 116, in pay_invoice
Aug 19 16:14:13 raspberrypi sh[12206]:     preimage = base64.b64decode(data["payment_preimage"]).hex()
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/usr/lib/python3.7/base64.py", line 80, in b64decode
Aug 19 16:14:13 raspberrypi sh[12206]:     s = _bytes_from_decode_data(s)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/usr/lib/python3.7/base64.py", line 46, in _bytes_from_decode_data
Aug 19 16:14:13 raspberrypi sh[12206]:     "string, not %r" % s.__class__.__name__) from None
Aug 19 16:14:13 raspberrypi sh[12206]: TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

**Comment by ChuckNorrison** [comment]
@fiatjaf can you take a look on this or any ideas to test some code? I think i can easy reproduce this issue here
