### ISSUE TITLE
[BUG]Error code: PR_END_OF_FILE_ERROR using EmbassyOS with LNbits service

### ISSUE THREAD

**Issue by OmniEdge** [lnbits/lnbits#1665]
**Describe the bug**
Launching UI of LNbits using the start9 EmbassyOS LNbits service doesnt load the page and result with Error code: PR_END_OF_FILE_ERROR

**To Reproduce**
1. Go to EmbassyOS
2. Click on LNbits service
3. Launch UI button
4. See Error code: PR_END_OF_FILE_ERROR

**Expected behavior**
Normally, the LNbits dashboard should open in the browser

**Screenshots**

![Screenshot from 2023-04-25 20-00-58](https://user-images.githubusercontent.com/7707354/235322295-778053b6-d97f-4126-a65f-a58b46c232d9.png)

![Screenshot from 2023-04-25 20-01-28](https://user-images.githubusercontent.com/7707354/235322312-8cb0cc22-d592-44c2-9d54-4a2cb2390636.png)
)

**Laptop (please complete the following information):**
 - LNbits version: 0.10.0~2
 - LND 0.16.2~1
 - Bitcoin Core 24.0.1
 - EmbassyOS Version 0.3.4~1

**Comment by gStart9** [comment]
This can happen in embassyOS (now called StartOS) if the https connection is interrupted.  We've noticed this can happen if you haven't properly trusted the CA certificate generated on the StartOS server.

See the guides here for the process for your specific client OS / browser:
https://docs.start9.com/latest/user-manual/connecting/connecting-lan/index

**Comment by dni** [comment]
i think this is fixed! reopen if not!
