### ISSUE TITLE
legend.lnbits.com returned an error or invalid response [BUG]

### ISSUE THREAD

**Issue by CSEEEE** [lnbits/lnbits#1669]
**Describe the bug**
legend.lnbits.com returned and error or invalid response. Try again later, or contact their support

**To Reproduce**
1. Create an LNURLw
2. Use LNURL to receive payment in lightning wallet
3. Error occurs

**Expected behavior**
The LNURLw should process

**Screenshots**
![image](https://user-images.githubusercontent.com/49599721/235559750-1cd1a1f4-b0c4-4e39-8ff4-b31ae7e5793a.png)

**Desktop (please complete the following information):**
 - Commit version: bfb27020ee1508a27439b0f73ac530d582567559

**Additional context**

**Comment by pjw65** [comment]
Same for me on legend and on local version 0.10.9, Commit version: 88cd50df2bf0798f625f6e20f832ac2cc
Same link on legend was working before.

**Comment by pjw65** [comment]
After restarting lnbits it works fine locally.

**Comment by dni** [comment]
fixed in latrest withdraw extension
