### ISSUE TITLE
Outgoing Payment Stuck In Pending [BUG]

### ISSUE THREAD

**Issue by CSEEEE** [lnbits/lnbits#1676]
**Describe the bug**
I tried to transfer btc lightning from one LNBits wallet to another LNBits wallet. It has now been over an hour and the payment is still saying that it is pending even though the invoice has now expired. No additional payments from this wallet will send either, all just end up pending and will not return the funds. 

When will the funds be returned to my wallet?
Is there a way to cancel the payment?

This is currently on legend.lnbits.com So there is no way for me to reset the server. 

Any suggestions or advice on how I should approach this?

**Comment by motorina0** [comment]
legend.lnbits.com has been retired (now replaced by demo.lnbits.com)

Please keep in mind that this is a demo servers. Sometimes we deploy experimental features on it. Please only keep none very low amounts of sats on them.
