### ISSUE TITLE
[Feature request] Hide the superuser UI URL from logs that are visible to all Unix system users

### ISSUE THREAD

**Issue by Perlover** [lnbits/lnbits#1682]
### Summary

When I start LNBits in logs I see by command `journalctl -u lnbits.service`:

```
SUCCESS | ✔️ Access super user account at: http://127.0.0.1:5000/wallet?usr=XXXXXXXXXXXXXXXX
```

But! Logs are viewed by any user in system by command:

`journalctl -u lnbits.service`

I think it's very bad. Any user in Unix can see logs, to see admin account and after to send all funds from lightning node to other wallet or to see macaroon admin files and etc.

It's easy to protect files with file permissions (for example `.env` file with `chmod 600 ...`), but we can't protect a view of logs of systemd. It is very dangerous to write authorization data there.

### Impact

Any instances with admin account when made as database setup

From doc:

> The LNbits Admin UI lets you change LNbits settings via the LNbits frontend. It is disabled by default and the first time you set the enviroment variable LNBITS_ADMIN_UI=true in the .env the settings are initialized and saved to the database and will be used (as long the UI is enabled). From there on the according settings from the database instead those of the .env file are used. If you want to return to those settings you can just set LNBITS_ADMIN_UI=false and restart LNbits to take the .env again.

> **On restart of LNbits you will find the link to the superuser-AdminUI in your terminal resp**. in your logs. Save if good and never share it. When the AdminUI is opened we can move on.

**Comment by Perlover** [comment]
I would like to suggest a way to solve this problem. Instead of writing to the log, you can open a file for creation with 600 rights from the lnbits user and write the admin URL there.  In advance, in advance, add the name of such a file to `.gitignore`

**Comment by dni** [comment]
we recently added this... https://github.com/lnbits/lnbits/pull/1651

**Comment by Perlover** [comment]
I want to make a clarification. As the user Hamish suggested to me in the Telegram chat, the logs are not always visible to everyone. I created a test user and really, I can't view the log from under it

I think I see logs either because my user is in the adm group, and I see logs from under `lnbits` user because the lnbits process is started from the lnbits user himself.

From `man journalctl`:

> All users are granted access to their private per-user journals. However, by default, only root and users who are members of a few **special groups are granted access to the system journal and the journals of other users**. Members of the groups "systemd-journal", "**adm**", and "**wheel**" can read all journal
> files. Note that the two latter groups traditionally have additional privileges specified by the distribution. Members of the "wheel" group can often perform administrative tasks.

But still, it is very dangerous to write such important data to logs, if only because [you can accidentally disclose them (how it was with me)](https://github.com/lnbits/lnbits/issues/1635#issuecomment-1514233755) through contacting developers on the forum (when they bring pieces of logs). Therefore, in any case, it is necessary to delete the output of this data to the console.

**Comment by Perlover** [comment]
The admin user ID is still viewed in the logs. Although the logs are really not visible to everyone, but only to the lnbits user and the administrator, I suggest removing this as soon as possible. Because you can accidentally reveal the administrator ID by publishing logs, for example, here (I did it already :))

**Comment by Perlover** [comment]
I used my branch and it looks like:

```
May 31 19:56:22 fuckedbitcoin poetry[208729]: 2023-05-31 19:56:22.28 | INFO | ✔️ All migrations done.
May 31 19:56:22 fuckedbitcoin poetry[208729]: 2023-05-31 19:56:22.29 | SUCCESS | ✔️ Access super user account at: http://127.0.0.1:5000/wallet?usr=<ID from ".super_user" file>
May 31 19:56:22 fuckedbitcoin poetry[208729]: 2023-05-31 19:56:22.29 | INFO | Starting LNbits
May 31 19:56:22 fuckedbitcoin poetry[208729]: 2023-05-31 19:56:22.29 | INFO | Version: 0.10.8
May 31 19:56:22 fuckedbitcoin poetry[208729]: 2023-05-31 19:56:22.29 | INFO | Baseurl: http://127.0.0.1:5000/
May 31 19:56:22 fuckedbitcoin poetry[208729]: 2023-05-31 19:56:22.29 | INFO | Host: 127.0.0.1
May 31 19:56:22 fuckedbitcoin poetry[208729]: 2023-05-31 19:56:22.29 | INFO | Port: 5000
May 31 19:56:22 fuckedbitcoin poetry[208729]: 2023-05-31 19:56:22.29 | INFO | Debug: False
May 31 19:56:22 fuckedbitcoin poetry[208729]: 2023-05-31 19:56:22.29 | INFO | Site title: FuckedBitcoin LNBits
May 31 19:56:22 fuckedbitcoin poetry[208729]: 2023-05-31 19:56:22.29 | INFO | Funding source: LndRestWallet
May 31 19:56:22 fuckedbitcoin poetry[208729]: 2023-05-31 19:56:22.30 | INFO | Data folder: ./data
May 31 19:56:22 fuckedbitcoin poetry[208729]: 2023-05-31 19:56:22.30 | INFO | Git version: f5343791e4366b7c3461073caab2bd133982a98c
May 31 19:56:22 fuckedbitcoin poetry[208729]: 2023-05-31 19:56:22.30 | INFO | Database: SQLite
```

The patch works ;-)
