### ISSUE TITLE
[Feature request] File permissions for SQLite and backup file are very not safu!

### ISSUE THREAD

**Issue by Perlover** [lnbits/lnbits#1683]
**Is your feature request related to a problem? Please describe.**

If I use Admin UI and have SQLite DB - I have database folder `./data` with permissions `drwxrwxr-x` for `lnbits:lnbits` (user:group), files inside the directory have `-rw-r--r--` for `lnbits:lnbits`

This all means that any user in the system can read any database file, find out the admin ID of the user / lightning settings of node software and actually empty the node after that. And the users of the group `lnbits` have the ability to delete any database file. The same goes for the `lnbits-backup file.zip`, which is created when the admin user makes a backup - it is readable by all users of the Unix system (including system services in which there may be a hypothetical vulnerability to run a script or read any file of the file system).

**Describe the solution you'd like**

It is enough to set `umask` as `027` at the beginning of the LNBits code

**Comment by Perlover** [comment]
I think I found a simpler solution via `UMask` inside the `systemd` unit file, which [I reflected in the wiki](https://github.com/lnbits/lnbits/wiki/LNbits-Documentation#additional-guides)

**Comment by dni** [comment]
thanks!
