### ISSUE TITLE
[Feature request] Hide API-Key only for non-admins

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/lnbits#1685]
**Is your feature request related to a problem? Please describe.**
The setting Manage Server - Server - Hide API Key
disables the API Info credentials in the right context menue of each wallet.
For admins this should still be visible.

**Describe the solution you'd like**
For admins this should still be visible since anyone anyhow can open it with console.log(window.wallet).

**Describe alternatives you've considered**
-

**Additional context**
<img width="1245" alt="Bildschirm­foto 2023-05-06 um 11 51 27" src="https://user-images.githubusercontent.com/63317640/236617724-f3066d08-c995-41de-b53a-571fc1523577.png">
<img width="1421" alt="Bildschirm­foto 2023-05-06 um 11 23 36" src="https://user-images.githubusercontent.com/63317640/236617739-a3eb8c6e-c945-48ff-89cd-5746e3527407.png">
<img width="1435" alt="Bildschirm­foto 2023-05-06 um 11 23 19" src="https://user-images.githubusercontent.com/63317640/236617741-7794e8d0-c99b-4585-bb0c-888bad32c8f1.png">

**Comment by dni** [comment]
is this feature useful at all? i never knew HIDE_API does that.

**Comment by arbadacarbaYK** [comment]
Maybe if you want your users to not add any devices or external features to their wallets by invoice-key/wallet-id, not sure who made it why. 
I dont see the need.
