### ISSUE TITLE
Legend on testnet?

### ISSUE THREAD

**Issue by xeverse** [lnbits/lnbits#1704]
is there another pub/demo Legend instance for tBtc?

**Comment by bitkarrot** [comment]
Same here. Would be great to be able to test lnbits without using real sats.

**Comment by bitkarrot** [comment]
Although, now that i think of it, if you really want signet, we do have a version of LNBits already inside of https://github.com/PLEBNET-PLAYGROUND/plebnet-playground-docker. I'll need to update LNBits to latest tho

**Comment by xeverse** [comment]
@bitkarrot how can one run this playground in sandbox-hypervisor-virtbox quickly? {btw, cool ava..}

**Comment by talvasconcelos** [comment]
Someone did a testnet deploy here: https://ln.testnet.dojo.pt/

**Comment by bitkarrot** [comment]
@talvasconcelos we also have a testnet deploy here (https://testnet.plebnet.dev) that I'm maintaining. The node it runs on has a direct channel to htlc.me

**Comment by bitkarrot** [comment]
In the next few months we plan to run a public 

**Signet LNBits** and **Signet Faucet** 

as part of the https://plebnet.dev resources. 

(Yes, some of its members come from here https://github.com/PLEBNET-PLAYGROUND). 

Will post announcement once its up.

**Comment by xeverse** [comment]
> @bitkarrot we also have a testnet deploy he
re (https://testnet.plebnet.dev) that I'm maintaining. 
can u install the LNdHub ext for Zeus connection..

**Comment by dni** [comment]
2 running testnet instances, nice :)

**Comment by bitkarrot** [comment]
> can u install the LNdHub ext for Zeus connection..
@xeverse , yes its now enabled.
