### ISSUE TITLE
[BUG] /extensions not showing anything in the 0.10.6 version

### ISSUE THREAD

**Issue by CappyTech** [lnbits/lnbits#1705]
**Describe the bug**

**To Reproduce**
Steps to reproduce the behaviour:

1. Go to 'extensions'

**Expected behavior**
List of extensions

**Desktop:**

- LNbits version: 0.10.6

**Additional context**
Blank screen on /extensions, extensions are installed, through the super user.

**Comment by callebtc** [comment]
Do you have an extension manifest added?

Try adding this to your `.env` or the same URL in the `Manage Server` tab, "Extension Sources"

`LNBITS_EXTENSIONS_MANIFESTS="https://raw.githubusercontent.com/lnbits/lnbits-extensions/main/extensions.json`

**Comment by CappyTech** [comment]
Would you know how to add this, for umbrel specifically?

**Comment by talvasconcelos** [comment]
Is this still an issue? Is it an LNbits issue or an Umbrel one?

Consider closing if fixed.

**Comment by stake2grow** [comment]
still a problem in Umbrel

**Comment by arbadacarbaYK** [comment]
> still a problem in Umbrel

@stake2grow Pls check on spelling errors in the manifest and if you change the link dont miss to save afterwards (restart not needed).

You can find some guides on this linked here https://github.com/lnbits/lnbits/wiki/LNbits-Extensions

<img width="789" alt="Bildschirmfoto 2023-07-30 um 21 14 35" src="https://github.com/lnbits/lnbits/assets/63317640/919037ca-ef01-4ac3-b5f0-c7e16f4ddcd6">
