### ISSUE TITLE
[BUG] New wallet bottom bar overlaps on iOS [0.10.7]

### ISSUE THREAD

**Issue by CerebrumCaelum** [lnbits/lnbits#1719]
**Describe the bug**
New wallet bottom bar  (0.10.7) overlaps slightly with wallet information page.

**To Reproduce**

1. Open LNbits wallet on iPhone
2. Scroll the wallet info page to the bottom
3. New Wallet bottom bar overlaps slightly

**Expected behavior**
When scrolling to the bottom of the page there should be additional padding so that all information is visible.

**Screenshots**
![overlap](https://github.com/lnbits/lnbits/assets/84624366/9f3b9042-2ab5-4188-9682-83db8d350899)

**Desktop (please complete the following information):**

- LNbits version: [0.10.7]
- Database sqlite
- iPhone 14 Pro
- Safari
- 

**Additional context**

**Comment by CerebrumCaelum** [comment]
Issue seems a bit more severe since the Extensions buttons can’t be clicked anymore.
![IMG_4361](https://github.com/lnbits/lnbits/assets/84624366/68b2031f-b10b-4513-be68-586a81b6565d)

**Comment by dni** [comment]
this was solved by https://github.com/lnbits/lnbits/pull/1740
