### ISSUE TITLE
Schedule Tasks (cron jobs)

### ISSUE THREAD

**Issue by motorina0** [lnbits/lnbits#1724]
Create a  a Cron-Tab like extension (https://github.com/alseambusher/crontab-ui).

 - one place where all the jobs live
 - monitor, pause or kill jobs
 - cron jobs can be created in the UI by the users
 - or via API by other extensions
 - in case the server is slow, the admin can stop some jobs and see if the cron job was the reason
 - the cron extension can limit what can be scheduled (for example hide the every X seconds part and only allow every X minutes or less)
 - each `cron` job has a REST API endpoint that it must call (GET/PUT/POST/DELETE)

**Comment by arcbtc** [comment]
LNbits can pay 1.5 million sat bounty for such a thing 
hop into https://t.me/lnbits to propose

**Comment by bitkarrot** [comment]
I want this feature. I can also try to implement it as an extension if someone else hasn't already done it.

**Comment by motorina0** [comment]
Not sure how two step scheduled tasks like this could be executed:
 - https://github.com/lnbits/lnbits/pull/881

But it would very cool if that was possible.

**Comment by bitkarrot** [comment]
Initial Draft, will rename to scheduler very soon and fix all the outstanding bugs/issues

https://github.com/bitkarrot/crontabs/releases/tag/v0.0.3

**Comment by motorina0** [comment]
Discussions will continue at: https://github.com/bitkarrot/scheduler

Closing this issue.
