### ISSUE TITLE
Feature Request: Make each wallet/user a PWA

### ISSUE THREAD

**Issue by ozomer** [lnbits/lnbits#173]
Progressive web apps are cool and appear to users as real apps - without the address bar, and in its own window. It allows to run code even when offline (i.e. show last  balance + a warning message).
It could be nice to send someone a fully functional custodial app (with some sats), rather just a link that he needs to bookmark.

Each "usr" id should be a separated app.

**Comment by fiatjaf** [comment]
I like this, but is it possible? My intuition tells me your phone will think all URLs in the same domain will be the same app, no matter what you do. Please let us know if you know how to do this.

**Comment by ozomer** [comment]
@fiatjaf Check out https://web.dev/add-manifest/#link-manifest
I'm sure you can refer to different manifests from different pages in the same domain.

Also, if the usr query parameter was used for the route path (i.e. lnbits.com/{usr}/wallet?...), then the manifest scope field was intended specifically for that - It's not relevant for lnbits because there wouldn't be links between the routes, but it shows that multiple PWAs on the same domain are possible.

**Comment by fiatjaf** [comment]
Interesting, so maybe we can serve a different manifest for each user and shortcuts to each user wallet and each user extension?

**Comment by fiatjaf** [comment]
Ok, I have the manifest in place (in my local LNbits only). How do I test it? How do I install a PWA?

**Comment by ozomer** [comment]
On Android there should be installation button near the address bar (I think).
On iOS you must open the page in Safari, and scroll the menu from the bottom.

**Comment by ozomer** [comment]
And you might need "https", so working with http://localhost might not work.

**Comment by fiatjaf** [comment]
I have a button "Add to home screen" or something like that, but I don't think it is doing the PWA magic.

Can you try it on https://lnbits.bigsun.xyz/?

**Comment by ozomer** [comment]
Here are some examples:

https://github.com/mdn/pwa-examples

Notice that after you add them to Home Screen, you will no longer see the address bar.

**Comment by ozomer** [comment]
Your link works nicely on both iOS and Android. No address bar - just like an app.
Would be nice to add an icon. Also, the root page should not be an app. I think the whole routing should be changed so the usr will be a subroute not a query param (/usr/.../wallet?...), so we are sure each subroute has a its own manifest and scope.
The old routes (i.e. /wallet) could be 301 redirects to the new routes, for backward compatibility.

**Comment by ozomer** [comment]
And as a bonus - show some instructions about how to install it in iOS and Android (add to Home Screen).

Loading some sats to an lnbits app will be a great gift to a nocoiner friend. All these QR codes and having to explain your friend how to install an app from the App Store and scan them... that's to much for nocoiners.

Awesome project, by the way.

**Comment by fiatjaf** [comment]
Ok, but I think that is not the PWA thing, it's just adding a webpage to the home screen. I has an icon for me on Android. Doesn't it have an icon on iOS?

See https://web.dev/add-manifest/#create, it has "shortcuts". What are these shortcuts? I added shortcuts, but I don't know how to test them.

**Comment by ozomer** [comment]
I think app shortcuts are for computers, not smartphones.

**Comment by ozomer** [comment]
I remember that there was some how a way for the worker service to know whether it's running from a browser or after installation - and then show a popup saying "this page can be installed as an app".

But some of the functionalities for computer may not work on phones.

**Comment by arcbtc** [comment]
All this is very easy using full Quasar, but not sure how to do it with our Quart backend. I should be able to generate the correct thumbs though, I shall try

**Comment by fiatjaf** [comment]
@arcbtc I committed this: https://github.com/lnbits/lnbits/commit/0f998419e7b7012c1955665fe2d674d496f0bb6f

It works at least partially. But I have no experience with these PWA things so I don't know exactly.

**Comment by arcbtc** [comment]
Oh nice, I found the tutorial for making all the right sized thumbnails for devices but no idea where they go
I'm always struggling to describe Lnbits, I'll use "Weather forecast information" 😂

**Comment by talvasconcelos** [comment]
I believe there should be a service worker .js file that handles the offline/online states and actions

**Comment by fiatjaf** [comment]
Please no.

LNbits doesn't work while offline, please don't try to trick the user with bloated service workers.
