### ISSUE TITLE
[BUG] payment isn't initiated

### ISSUE THREAD

**Issue by petrkr** [lnbits/lnbits#1734]
**Describe the bug**
Do not know how to reproduce this, but time from time there is payment isn't initiated error, results is empty transaction list.
It seems lnbits have in DB some payments about which LND does not know, will be handy to have atleast some ID how to recognize those payments, investigate and in case of need just delete them from DB

- LNbits version: 0.9 and in 0.10.7 still persist
- Database postgres

**Comment by dni** [comment]
does the error still happen? maybe its a corrupted database table, can you try with a fresh db?

**Comment by callebtc** [comment]
Closing due to lack of details and response.

**Comment by petrkr** [comment]
So it is fixed already ? I will try to pull and test it. I can not test on fresh db as I will lost transaction and wallet data
