### ISSUE TITLE
[BUG] No way to block the creation of users.

### ISSUE THREAD

**Issue by 20a8vnf30** [lnbits/lnbits#1747]
**Describe the bug**
Setting allowed users in the GUI and/or the .env file blocks access to non-allowed users, but does not block the creation of new users through the public frontend page IE lnbits.mydomain.com

**To Reproduce**

1. As admin user, create a new users in the usermanager extension.
2. Set this new user as "allowed user" in the admin GUI and the .env.
3. Restart LNbits.
4. Visit the public frontend and try to create a new user. The GUI states "User not authorized." but the new user is in fact still created, his userID is visible in the URL and the creation is logged.

**Expected behavior**
Setting "allowed users" blocks the creation of new users by anyone other than the admin.
A clear message is displayed that visitors of the frontend are not allowed to create new users.

LNbits version: 0.10.8
Database: sqlite

**Comment by talvasconcelos** [comment]
But can that new user enter his wallet? That's just the way lnbits works, it checks if the user is allowed after it's creation!

**Comment by 20a8vnf30** [comment]
> 

The user can't access the wallet, but the account is still created.
An attacker could create infinite accounts until my disk is full and my machine crashes.
