### ISSUE TITLE
[BUG] TX chart/export

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/lnbits#1754]
**Describe the bug**
- Chart shows negative balance value
- "Export to csv" field "memo" shows date instead message

Bad to reproduce sales. 
For a proper tax report for merchants on top a column with a denominated value at the time of action would be needed here.
Since more merchants just act through LNbits (SaaS/Cloud Setups) it has gotten even more important to deliver a valid report.

**To Reproduce**
Press "Export to csv" or the chart-symbol

**Expected behavior**

Chart
- no negative balance :P  
-Balance should overlap with the blocks

Export
- Shows complete message in "Memo"
- Date in a separate column (than memo to be able to order by messages too)
- only successful transactions are listed 

**Screenshots**

<img width="927" alt="Bildschirmfoto 2023-06-10 um 23 23 39" src="https://github.com/lnbits/lnbits/assets/63317640/863125ba-e2a5-46f0-9e54-8e833c6330a3">

<img width="887" alt="Bildschirmfoto 2023-06-10 um 23 40 19" src="https://github.com/lnbits/lnbits/assets/63317640/63fab413-e88c-4d52-82a7-7c24d3fdda55">

<img width="652" alt="Bildschirmfoto 2023-06-10 um 23 36 44" src="https://github.com/lnbits/lnbits/assets/63317640/5bec86fc-5a6c-418f-8b15-bc1c6b002eca">

<img width="755" alt="Bildschirmfoto 2023-06-10 um 23 31 18" src="https://github.com/lnbits/lnbits/assets/63317640/64115f23-869b-4c15-bd55-1ea9edcd528c">

**Comment by jackstar12** [comment]
This has probably because pagination was moved to the server to increase page performance. The exportCSV and Chart haven't been adjusted to that.

**Comment by jackstar12** [comment]
@talvasconcelos no need, already got it

**Comment by jackstar12** [comment]
saving the corresponding might be a cool addition aswell. Could build on https://github.com/lnbits/lnbits/pull/1748

**Comment by arbadacarbaYK** [comment]
Its a need, not a nice to have actually :P

**Comment by jackstar12** [comment]
@arbadacarbaYK how would you imagine that feature? Maybe as a per-wallet setting where you can set your preferred fiat whose value is then stored per payment?

**Comment by arbadacarbaYK** [comment]
You might not like the answer 😂
I think it makes sense to have the possibility to override in some extensions so e.g.

- per lnurlp
- per lnurldevice > device (so at the atm '€' but 'sats' at the beertap), note that lnurldevice works with lnurlp
- nostrmarket > stall
- invoice 
- satspay
- usermanager > user
- Cashu > Mint  👀

Since you might want to combine some of them they might need a hierachy. 

Id like this

SuperUser Account
- Show a list of all currencies for the instance 
-- all currencies highlighted as "on" but can be turned "off". Just to reduce that list.
-- sats cannot be unclicked, it stays the default for all wallets. - its LNbits not Fiatbits 😅🤣
-- introduce an optional marker for a national currency

DB / Export 
- track all payments in sats + national currency 

Extensions
- Add dropdown to at least those mentioned extensions 


🤠

**Comment by arbadacarbaYK** [comment]
all fixed, even fiat-value :) 
https://github.com/lnbits/lnbits/pull/1852
