### ISSUE TITLE
[BUG] NumericValueOutOfRange on internal payment of 2415550000 sats

### ISSUE THREAD

**Issue by cryptoteun** [lnbits/lnbits#1769]
**Describe the bug**
Today we had to do an internal payment of 2415550000 sats that failed with the following error: psycopg2.errors.NumericValueOutOfRange) integer out of range

Not sure if the external payment has the same behaviour.

**To Reproduce**
1. Try to do an (internal) payment of 2415550000 sats
2. Try to pay from another internal wallet

**Expected behavior**
Payment can be performed succesfully.

**Desktop (please complete the following information):**
- LNbits version: 0.10.8
- Database: postgres

**Additional context**
Complete error:

`
{
    "detail": "(psycopg2.errors.NumericValueOutOfRange) integer out of range\n\n[SQL: \n        INSERT INTO apipayments\n          (wallet, checking_id, bolt11, hash, preimage,\n           amount, pending, memo, fee, extra, webhook, expiry)\n        VALUES (%s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s, %s)\n        ]\n[parameters: ('...', '...', '...', '...', None, 2415550000, True, '...', 0, None, None, '2023-06-17 18:47:48')]\n(Background on this error at: http://sqlalche.me/e/13/9h9h)"
}
`

**Comment by cryptoteun** [comment]
I saw in https://github.com/lnbits/lnbits/blob/main/lnbits/core/migrations.py that amount should be big int. But when I check my model it's an int.
<img width="556" alt="image" src="https://github.com/lnbits/lnbits/assets/73664763/6dee309f-de37-4a7f-a628-cc51d4567302">

I have the issue on multiple instances, all running the same config. Is something change on this over the last half year?

**Comment by cryptoteun** [comment]
Think i have found it. Is this safe to do and is it needed on other places as well?

```
**Remove view:**        
DROP VIEW balances;

**Alter table:**        
ALTER TABLE apipayments ALTER COLUMN amount TYPE BIGINT;

**Create view (taken from https://github.com/lnbits/lnbits/blob/7e1f43933d32d337f15eae6a31b3da52812af972/lnbits/core/migrations.py#LL144C11-L144C47 ):**        
CREATE VIEW balances AS
    SELECT wallet, COALESCE(SUM(s), 0) AS balance FROM (
        SELECT wallet, SUM(amount) AS s  -- incoming
        FROM apipayments
        WHERE amount > 0 AND pending = false  -- don't sum pending
        GROUP BY wallet
        UNION ALL
        SELECT wallet, SUM(amount - abs(fee)) AS s  -- outgoing, sum fees
        FROM apipayments
        WHERE amount < 0  -- do sum pending
        GROUP BY wallet
    )x
    GROUP BY wallet;
```

**Comment by dni** [comment]
it should definitely be bigint, somehow a migration did not run for you. your steps to fix it seems fine, @motorina0 can you confirm?

**Comment by motorina0** [comment]
> Think i have found it. Is this safe to do and is it needed on other places as well?
> ...

@cryptoteun Yes, this is the correct fix. 
The `amount` column must be `BIGINT`

**Comment by cryptoteun** [comment]
Fixed the issue, closed.
