### ISSUE TITLE
Memo shoudn't be required 

### ISSUE THREAD

**Issue by taxmeifyoucan** [lnbits/lnbits#179]
User cannot create an invoice without memo. UI hints it is optional, however error pops up and it is not possible to proceed without filling memo. 

![image](https://user-images.githubusercontent.com/61149543/114613828-bd04bb80-9c9b-11eb-9415-30e9324dfd4b.png)

**Comment by arcbtc** [comment]
Yes, I agree 👍

**Comment by arcbtc** [comment]
Akthough memo is still required. through gui disabled button unless memo exists

**Comment by fiatjaf** [comment]
I think this is good, we should require the memo. It's a forced best practice that I approve even for my own good.
