### ISSUE TITLE
[BUG] Git pull latest module not found error 'slowapi' after lnbits.service restart

### ISSUE THREAD

**Issue by jchames** [lnbits/lnbits#1794]
**Describe the bug**
I have just git pulled the latest version of lnbits to update my install.

Poetry install
Ubuntu 22.04

**To Reproduce**

1. cd lnbits
2. git pull
3. restart lnbits.service
4. Error below
---------------------------------------------------------------
lnbits.service - LNbits
     Loaded: loaded (/etc/systemd/system/lnbits.service; enabled; vendor preset: enabled)
     Active: active (running) since Sat 2023-06-24 19:33:32 UTC; 5 days ago
Main PID: 1528453 (python)
      Tasks: 2 (limit: 4263)
     Memory: 5.3M
        CPU: 2.441s
     CGroup: /system.slice/lnbits.service
             └─1528453 /home/jeremy/.cache/pypoetry/virtualenvs/lnbits-4k-Qg41m-py3.10/bin/python -c "import sys; from importlib import import_module; sys.argv = ['/home/je>

Jun 24 19:33:36 nodebox poetry[1528458]:   File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
Jun 24 19:33:36 nodebox poetry[1528458]:   File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
Jun 24 19:33:36 nodebox poetry[1528458]:   File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
Jun 24 19:33:36 nodebox poetry[1528458]:   File "<frozen importlib._bootstrap_external>", line 883, in exec_module
Jun 24 19:33:36 nodebox poetry[1528458]:   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
Jun 24 19:33:36 nodebox poetry[1528458]:   File "/home/jeremy/lnbits/lnbits/__main__.py", line 1, in <module>
Jun 24 19:33:36 nodebox poetry[1528458]:     from .app import create_app
Jun 24 19:33:36 nodebox poetry[1528458]:   File "/home/jeremy/lnbits/lnbits/app.py", line 20, in <module>
Jun 24 19:33:36 nodebox poetry[1528458]:     from slowapi import Limiter
Jun 24 19:33:36 nodebox poetry[1528458]: ModuleNotFoundError: No module named 'slowapi'

**Expected behavior**
Lnbits loads per normal

**Desktop (please complete the following information):**
Ubuntu 22.04
Bare metal

- LNbits version: latest
- Database: SQLlite

**Comment by jackstar12** [comment]
`slowapi` is a new dependency, you need to do a `poetry install`

**Comment by jchames** [comment]
Ok thanks. That did the trick.
