### ISSUE TITLE
nostr paid relay

### ISSUE THREAD

**Issue by carlostkd** [lnbits/lnbits#1808]
Hi
im trying to integrate lnbits on a nostr relay to make the relay payable but it does not redirect my nostr relay url to the payments gateway.

It simple does not work yet or im doing something wrong?

Thanks in advanved

**Comment by talvasconcelos** [comment]
Could you give some more information?

Are you using the LNbits extension Nostr Relay? 
How are you integrating this payment, how are you integrating?

**Comment by motorina0** [comment]
If this ussue is still present, please report it to https://github.com/lnbits/nostrrelay
