### ISSUE TITLE
Running LNBIts on raspiblitz over LAN for lnurl

### ISSUE THREAD

**Issue by we-do-it-lu** [lnbits/lnbits#181]
I am running LNBIts on my Raspiblitz node in my LAN
Although pay / receive works, the extension PoS too, 

When scanning QR code in extension LNURLw the user gets: `400 BAD REQUEST “checksum is incorrect”` error
When scanning QR code in extension Paywall the user gets: "`500`" error message without extra info

I hear that "lnurl is reliant on GET POST requests" whereas the PoS is generating an _invoice_,  these two are different mechanisms and you might have to use a reverse proxy (e.x. npm localtunnel https://www.npmjs.com/package/localtunnel)
Is this correct? 
This answer surprises me because I am playing around with my local LNBits on my Raspiblitz (using 192.168.0.n range on the local network) to access it... Furthermore the end goal is to have my local LNURLw accessible from WWW eventually...
Note that LNBits is readily available in the Raspiblitz stack, would be great to clarify/get it fixed and documented to prevent other users to come up with the same question

**Comment by we-do-it-lu** [comment]
When scanning QR code in LNURLw the user gets: 400 BAD REQUEST “checksum is incorrect” error

**Comment by arcbtc** [comment]
Localtunnel is good. For a permanent solution Caddy is excellent, although it may require openning port 443 on your router for the ssl, I have not used it outside of a server environment 
Lnurl will work on TOR and I know blitz makes this easy, this might be a nice easy solution https://github.com/fiatjaf/lnurl-rfc#lnurl-lightning-network-ux-protocol

**Comment by we-do-it-lu** [comment]
On Raspiblitz there is the an option to enable IP2TOR subscription for LNBits, I am going try the same use use case (LNURLw/Paywall) this time with IP2TOR subscription using external address provided by IP2TOR (instead of local address)

**Comment by we-do-it-lu** [comment]
OK. Experiment done. This is very odd:
When scanning QR code in extension LNURLw the user gets: 400 BAD REQUEST “checksum is incorrect” error
When scanning QR code in extension Paywall the user gets: **It works**
🤔

**Comment by arcbtc** [comment]
The paywall invoice is not an LNURL, its a regular invoice
