### ISSUE TITLE
Internal endpoint for invoice webhook

### ISSUE THREAD

**Issue by arcbtc** [lnbits/lnbits#182]
Can lnbits invoice api do an internal webhook? 
I have tried this in all different shapes and sizes and I cant get it to hit the endpoint. The endpoint its trying to hit works perfectly. I thought it might be because I am trying to do an internal endpoint?
https://github.com/lnbits/lnbits/blob/05317eb5d6ab8175ee64f6fac935c9afc3d3816f/lnbits/extensions/copilot/lnurl.py#L74

**Comment by fiatjaf** [comment]
Internal endpoints should work if the invoice listeners thing is working. Have you tried sending the webhook to somewhere else to see if it goes? What funding source are you using? If it's LNPay you'll have to manually enable webhooks from the LNPay dashboard. Try using lnbits.com as the funding source for your local LNbits, it works (rebase to `master` before).

Sending webhooks internally it's interesting solution though, I hadn't thought about it -- but I recommend using the internal "listener" thing. See https://github.com/lnbits/lnbits/blob/05317eb5d6ab8175ee64f6fac935c9afc3d3816f/lnbits/extensions/subdomains/tasks.py#L14-L40, for example (similar code also exists on `lnurlp`, `offlineshop`, `livestream`).

**Comment by arcbtc** [comment]
Wow, thanks! I'd hit a wall, this gives me plenty to go on👍
Its the final bug that needs to be squished.
I'm running on lntxbot, which I know handles webhooks out of the box

**Comment by fiatjaf** [comment]
Oh, ok. Then it should be working, but lntxbot is so buggy someone has to complain to their developer.

I recommend testing the webhook to somewhere else first then.

**Comment by arcbtc** [comment]
Tested /api/v1/payments using funding source LNpay with webhooks 100% working, and I can clarify adding an internal link to an invoice webhook does not work :(

**Comment by arcbtc** [comment]
Found a way around it, so closing
