### ISSUE TITLE
Refactor: remove `max_sat` from `pay_invoice`

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#1844]
This should be handled by the callee of `pay_invoice`.

**Comment by jackstar12** [comment]
I considered this in https://github.com/lnbits/lnbits/pull/1816 aswell but didnt go for it as its used multiple times across multiple https://github.com/search?q=org%3Alnbits+NOT+repo%3Alnbits%2Flnbits+NOT+repo%3Alnbits%2Flnbits-legend-1+max_sat%3D&type=code so it would require a bunch of adjustments

**Comment by arbadacarbaYK** [comment]
Understand its about paying an invoice just saying because i dont know if its relevant anyway.
For boltcard withdrawals without invoice it is common practise to set the max higher than your balance is and its also common for normal lnurlw. afaik only Breez is ignoring it.

**Comment by motorina0** [comment]
Better to encapsulate the check inside `pay_invoice()`. Otherwise the caller  would have to decode the `payment_request` and check the amount.
