### ISSUE TITLE
[BUG] Still errors Installing locally under Python 3.11

### ISSUE THREAD

**Issue by rodant** [lnbits/lnbits#1850]
**Describe the bug**
The issue https://github.com/lnbits/lnbits/issues/1755 is closed, but there are still errors under Python 3.11. I think the documentation and the project definition must be adapted to either exclude 3.11 or ensure success under this Python version.

**To Reproduce**

1. Follow the installation guide of the project with poetry and set your poetry env to 3.11.
2. The command poetry install --only main fails with compile errors.

**Expected behavior**
Installation and running the server locally should work.

**Desktop (please complete the following information):**

- LNbits version: 0.10.9
- Database: sqlite

**Additional context**
Running under current Manajaro Linux 6.1.41-1 and zsh.

**Comment by mammadori** [comment]
One of the problems seems to be the dependency of "coincurve" in poetry.lock, needs to be updated from 0.17 to 0.18 (which supports python 3.11)

**Comment by rodant** [comment]
Well, this is a transitive dependency of the project. The task would be to find the explicit dependency in pyproject.toml which brings this setting to poetry.lock.

**Comment by rodant** [comment]
I bump up the version of uvloop to 0.17.0 which supports python 3.11 with `poetry add "uvloop>=0.16.0"`. Then I run the tests and the server successfully with the fake-wallet, boths under 3.10 and 3.11.
The change is tiny, but I can also create a pull request if you want.

**Comment by dni** [comment]
here is the PR incorparating the dep updates, it just takes a bit.
https://github.com/lnbits/lnbits/pull/1609

**Comment by prusnak** [comment]
This is resolved now.
