### ISSUE TITLE
LndHub url shows "404 not found"

### ISSUE THREAD

**Issue by klnit** [lnbits/lnbits#186]
I am using the LndHub feature of LNbits to connect the Bluewallet App. In the newest release 1.7.0 of raspiblitz this connection url shows "404 not found". Everything is working so far except the LndHub urls.

E.g. the admin url is lndhub://admin:1b96.............e5cc66aff@https://example.duckdns.org:30803/lndhub/ext/
The part https://example.duckdns.org:30803/lndhub/ext/ shows 404

Can you reproduce it?

**Comment by klnit** [comment]
It is the same with a local IP address

**Comment by fiatjaf** [comment]
If it's the same with a local IP address it must be because LNbits is not running.
