### ISSUE TITLE
Formatting the LNBits Frontpage Description

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/lnbits#1912]
### **Issue:**
When entering the LNBits Frontpage there is a description like you can see in the following Screenshot:

![Formating lnbits description](https://github.com/lnbits/lnbits/assets/106493492/7b31b841-199e-4096-b2f7-ab6b85383cd8)

This lines have no formating rules. So the lines set just next to next. It would be lovely for reading and serve informaion in a well formatted architecture.

### **Solution:**
My solution would be Rich Text Editors oder WYSIWYG-Editors (What You See Is What You Get). That would allow also the dumpest presumed user to edit the text.

### **Output:**
A well arranged/readable start page with important information about the server

**Comment by arbadacarbaYK** [comment]
![IMG_5582](https://github.com/lnbits/lnbits/assets/63317640/f760a320-0524-457f-9247-64bfa70c8acd)

this can be set in the manage server section

**Comment by DoktorShift** [comment]
in the manage server section i´am able to edit the text. But it´s not displayed like that on the LNBits frontpage.

see screenshots:

![showcase1](https://github.com/lnbits/lnbits/assets/106493492/973e0530-72ae-4bf2-b5a6-24733e54e284)


![showcase2](https://github.com/lnbits/lnbits/assets/106493492/08bda272-3431-4f02-b461-7e3b57a6963c)

**Comment by talvasconcelos** [comment]
Try it with : 
```
<h2Family Bank</h2>
<h4>Playground</h4>
<p>For testing extensions and other stuff</p>
<p>**************************************</p>
<p>Do not store large amounts here</p>
```

**Comment by arbadacarbaYK** [comment]
> Try it with :
> 
> ```
> <h2Family Bank</h2>
> <h4>Playground</h4>
> <p>For testing extensions and other stuff</p>
> <p>**************************************</p>
> <p>Do not store large amounts here</p>
> ```

Ok, this is not nice :) Could it also allow paragraphs ?

**Comment by DoktorShift** [comment]
<h2**>**Family Bank</h2>
<h4>Playground</h4>
<p>For testing extensions and other stuff</p>
<p>**************************************</p>
<p>Do not store large amounts here</p>

If it would work this way it would be a solution for me and a bunch of people. 
On the other hand everybody is well known with simple formatting rules in common programs like gmail, telegram and also here on Github. In my opinion the aim should be to reduce every not needed effort to present a well arranged/readable start page with important information about the server.

**Comment by talvasconcelos** [comment]
It's a simple HTML syntax! Github uses Markdown...

**Comment by bitkarrot** [comment]
Maybe adding Markdown support in the future is an option
 https://markdoc.dev/

**Comment by talvasconcelos** [comment]
I did it here: https://github.com/lnbits/events/pull/10

@arcbtc worth doing it for the frontpage description also?

**Comment by dni** [comment]
i think it worth it, it going to be useful for other extensions aswell

**Comment by arbadacarbaYK** [comment]
Really ? People need to know markdown or html to put in a description ?

**Comment by DoktorShift** [comment]
Thanks for your work. Its now working with ease.


pls close this issue.
