### ISSUE TITLE
[BUG] LndRestWallet: respond to `payment isn't initiated`

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#1913]
**Describe the bug**
If a payment status of a nonexistent (? needs confirmation) payment is looked up, the LND rest interface responds with `payment isn't initiated` or in `lncli`

```
[lncli] rpc error: code = NotFound desc = payment isn't initiated
```

In those cases, a `PaymentStatus(False)` should be returned so that the payment is purged from the database. However, the `get_payment_status` method in `lndrest.py` should explicitly check for this error (dirty pseudocode):

```python
line = json.loads(json_line)
                    if line.get("error"):
                        logger.error(
                            line["error"]["message"]
                            if "message" in line["error"]
                            else line["error"]
                        )
                        # payment does not exist?
                        if error == "rpc error: code = NotFound desc = payment isn't initiated":
                           return PaymentStatus(False)
                        return PaymentStatus(None)
```

**Comment by skrafft** [comment]
@callebtc, I just created PR #2074 to fix this because I had the problem on my own node. Can you review it ?
