### ISSUE TITLE
[Feature request] API Call to create_wallet 

### ISSUE THREAD

**Issue by STCB** [lnbits/lnbits#1915]
**Is your feature request related to a problem? Please describe.**
I'd like to create new wallets in my LNBits session via API but it is only doable by hand, which makes it non-automatisable.

**Describe the solution you'd like**
Make it accessible via API (idk how to call it lol)

**Additional context**
Vlad Stan told me to create thus issue in TG
@motorina0

**Comment by motorina0** [comment]
@STCB 
 - it looks like the functionality you desire is already available if you install the `usermanager` extension
 - can you please try it out and let me know if it works for you
