### ISSUE TITLE
[Feature request] Update button

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/lnbits#1916]
CLI is a problem for most bundle node users and also merchants.  
Even if there is a guide, when things run out of the normal, ppl easily get stuck half way. 

A possibility to "Update" in manage server > server only for the superuser would be very helpful.

- tab Indicates, if there is an update
- (insert magic to fetch and compare latest compatible release)
- If update available show button "New release available" 
-- on click 
-- Change button to "Update Now"
-- show new release # and link to releasenotes 
-- user accepts security warnings 
-- checkmark if db should be backed up before updating
--- on click
--- Backup, update, restart 🚀🌚
--- proper errormessages for cases where not possible

**Comment by dni** [comment]
i am afraid update button is not possible on this level, user would need to update their docker image in their corresponding bundle node. we have no control over that via the python process :(

**Comment by arbadacarbaYK** [comment]
🥹
