### ISSUE TITLE
LNURLp links give errors on WalletofSatoshi and BlueWallet

### ISSUE THREAD

**Issue by wroscoe** [lnbits/lnbits#192]
Using this LNURLp link: https://lnbits.com/lnurlp/212

BlueWallet Error: "Alert: Bad response from server"
Wallet of Satoshi Error: "Error: Could not complete payment, please try again."

**Comment by thecharacter** [comment]
Same

**Comment by rafaelpac** [comment]
This is not related to walletofsatoshi or bluewallet.

It looks like an error on your Success URL set up for that LNURLp.

Check below the Success URL field.

What did you put on your Success URL field?


![image](https://user-images.githubusercontent.com/6444444/119781642-a3ad7c80-bea1-11eb-96b9-c4097bdd0f74.png)

**Comment by rafaelpac** [comment]
This is not related to walletofsatoshi or bluewallet.

It looks like an error on your Success URL set up for that LNURLp.

Check below the Success URL field.

What did you put on your Success URL field?

![image](https://user-images.githubusercontent.com/6444444/119782921-1b2fdb80-bea3-11eb-833a-75e9d3b0ee60.png)
