### ISSUE TITLE
connect lnbits through tor: unable to connect `Client sent an HTTP request to an HTTPS server`

### ISSUE THREAD

**Issue by real-doman** [lnbits/lnbits#193]
I am trying to connect lnbits to my remote node (raspibolt) through tor. So first thing I did was editing my `.env` file.
My `.env` looks like this:
```
LNBITS_BACKEND_WALLET_CLASS=LndRestWallet

# LndRestWallet
LND_REST_ENDPOINT=http://MyOnion.onion:8080
LND_REST_CERT="/my/path/tls.cert"
LND_REST_MACAROON="myHexString"
```
After that I just followed the [installation guide](https://github.com/lnbits/lnbits/blob/master/docs/guide/installation.md). I want to use Tor, so need to run commands with `torify`
```
$ cd lnbits/
$ python3 -m venv venv
$ ./venv/bin/quart assets
$ ./venv/bin/quart migrate
$ torify ./venv/bin/hypercorn -k trio --bind 0.0.0.0:5000 'lnbits.app:create_app()'
```
I got this error:
```
/home/doman/lnbits/lnbits/app.py:61: RuntimeWarning:   × The backend for LndRestWallet isn't working properly: 'Client sent an HTTP request to an HTTPS server.
'
  warnings.warn(

```
On my node the `lnd.conf`:
```
[Application Options]
restlisten=localhost:8080
```
and the `torrc`:
```
HiddenServiceDir /var/lib/tor/lnd_api/
HiddenServiceVersion 3
HiddenServicePort 8080 127.0.0.1:8080
```
Tor is installed on both machines and `systemctl status tor` says it is active and running.

I don't know how to fix this issue. Afaik every LND is TLS encrypted. To be able to connect to `MyOnion.onion:8080` I need to pass my `tls.cert`. Which is exactly what I did in the `lnbits` `.env` file (I set the correct path).

If I try to connect to `https://myOnion.onion` I just get `Unable to connect to https://myOnion.onion` instead of `Client sent an http request to an https server`

**Comment by koodinmies** [comment]
I'm having the same error when trying to connect to a LND node made with Polar (https://lightningpolar.com/)

I've installed ln-bits with the Docker option


.env file
```

LNBITS_BACKEND_WALLET_CLASS=LndRestWallet


LND_REST_ENDPOINT=http://127.0.0.1:8082
LND_REST_CERT="/home/lndfiles/tls.cert"
LND_REST_MACAROON="/home/lndfiles/admin.macaroon"
```

I'm getting these error messages in lnbits docker container logs:

`The backend for LndRestWallet isn't working properly: 'Unable to connect to http://127.0.0.1:8082.'`

Maybe this is related to Docker not being able to ping from one container to another?
