### ISSUE TITLE
[BUG] Example Extension - cannot be updated 

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/lnbits#1938]
On 0.10.9 and v0.2 of Example Extension installed from https://raw.githubusercontent.com/lnbits/lnbits-extensions/main/extensions.json 
the new version v0.3 is offered - but fails to install with "File hash mismatch". 
Others do install / are able to be updated.
Cannot open issues on example repo 😬

<img width="577" alt="Screenshot 2023-09-12 at 22 44 20" src="https://github.com/lnbits/lnbits/assets/63317640/293d5462-784f-4a35-a951-eb3c404f4f28">

<img width="479" alt="Screenshot 2023-09-12 at 22 55 52" src="https://github.com/lnbits/lnbits/assets/63317640/e08af5e2-4c96-4d78-bf0e-ad1c132613d9">

**Comment by dni** [comment]
issues are reenabled here: https://github.com/lnbits/example
but the proper repository if you have a filehash mismatch is probably here: https://github.com/lnbits/lnbits-extensions/

i checked the filehashes, its `v0.3.1` for < 0.11.0 `v0.3.2` > 0.11.0 and should work now, can you check?

**Comment by arbadacarbaYK** [comment]
> issues are reenabled here: https://github.com/lnbits/example but the proper repository if you have a filehash mismatch is probably here: https://github.com/lnbits/lnbits-extensions/
> 
> i checked the filehashes, its `v0.3.1` for < 0.11.0 `v0.3.2` > 0.11.0 and should work now, can you check?

Functionwise it works, but quite weird to get offered a version with the green note that cannot be installed :P 

<img width="433" alt="Screenshot 2023-09-28 at 18 47 04" src="https://github.com/lnbits/lnbits/assets/63317640/ae68f124-c2fd-4816-b4d7-3b76e6ce3e93">
<img width="674" alt="Screenshot 2023-09-28 at 18 46 28" src="https://github.com/lnbits/lnbits/assets/63317640/37f616f4-2149-48d4-ac92-08ae7047eacc">

**Comment by dni** [comment]
![screenshot-1695963464](https://github.com/lnbits/lnbits/assets/1743657/42b2267c-28ac-4a8f-a75a-9d11aba5da07)

is you are on 0.10.10 the 0.3.2 should be red. maybe some cache left?

**Comment by arbadacarbaYK** [comment]
i am on the same version, that most bundles are atm :P 0.10.9
