### ISSUE TITLE
[BUG] deleted wallets still show up in frontend

### ISSUE THREAD

**Issue by dni** [lnbits/lnbits#1939]
![screenshot-1694590265](https://github.com/lnbits/lnbits/assets/1743657/d23b4a1a-95ab-4e79-b61b-8444f0501570)

wallet is still visible, when deleted, discoverd it here.

https://github.com/lnbits/lnbits/pull/1932/files#r1323243651

i think we have to put it into the CRUD aswell

**Comment by talvasconcelos** [comment]
is this on main? dev?

**Comment by talvasconcelos** [comment]
the wallets on the UI are pulled from the user, which uses the CRUD. since there's no filter on there, you get all the wallets. 

we can remove them at the UI level, just frontend sugar.

**Comment by dni** [comment]
its on `dev` its our owrking branch now

**Comment by Perlover** [comment]
> is this on main? dev?

I have same bug
Right now I am at main branch
