### ISSUE TITLE
[Feature request] Harmonize style of "+" with theme

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/lnbits#1948]
Its too much colours otherwise 😵

<img width="240" alt="Screenshot 2023-09-18 at 23 13 11" src="https://github.com/lnbits/lnbits/assets/63317640/b25d4357-a1fe-4f0d-84b5-23d2fb502144">

<img width="144" alt="Screenshot 2023-09-18 at 23 13 02" src="https://github.com/lnbits/lnbits/assets/63317640/a94048d2-dca9-4586-b726-dc13bfff9f76">

<img width="971" alt="Screenshot 2023-09-18 at 23 14 34" src="https://github.com/lnbits/lnbits/assets/63317640/d11169ad-0a4a-44ef-a264-d1cf5c5f476a">

<img width="135" alt="Screenshot 2023-09-18 at 23 13 40" src="https://github.com/lnbits/lnbits/assets/63317640/72030d74-f047-4853-af62-7ddced28d165">

<img width="191" alt="Screenshot 2023-09-18 at 23 13 26" src="https://github.com/lnbits/lnbits/assets/63317640/49e8fc24-9add-40f6-947a-ce984d58ca8c">

<img width="216" alt="Screenshot 2023-09-18 at 23 13 18" src="https://github.com/lnbits/lnbits/assets/63317640/ccd5999a-520a-4ad7-bd09-108d3fa13500">

**Comment by dni** [comment]
its a matter of using the right classes for the colors i think. not specific color classes

**Comment by prusnak** [comment]
This is relevant for these two extensions:
- https://github.com/lnbits/nostrmarket
- https://github.com/lnbits/satspay

Others seem to be fine, but I only checked only the ones I use.

**Comment by dni** [comment]
i think nodemanagement may suffer from this aswell

**Comment by arbadacarbaYK** [comment]
onchain wallet also

**Comment by bitkarrot** [comment]
I hope its okay for me to comment about color contrast and complementary colors. 

some of these color schemes aren't quite balanced, but there is an easy to fix this by using a color palette generation tool such as: https://coolors.co/palettes/palettes

This is also a good tool for checking color contrast, https://coolors.co/contrast-checker/112a46-acc8e5

Also try to avoid red on green as this is difficult for people with color blindness
https://coolors.co/d352d7

**Comment by motorina0** [comment]
Changes implemented in the extensions repos. Check PRs for screenshots:
- https://github.com/lnbits/satspay/pull/33
- https://github.com/lnbits/nostrmarket/pull/92
- https://github.com/lnbits/watchonly/pull/9

**Comment by arbadacarbaYK** [comment]
Great!

**Comment by arbadacarbaYK** [comment]
https://github.com/lnbits/lnbits/issues/2014
