### ISSUE TITLE
Logo in QR code everywhere (also in extensions)

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/lnbits#1949]
Include logo in all QRs generated by the instance 
- or an extension on the instance (tpos, satspay, devices, invoices, ..)
-- or a variety ID from an extension on the instance (stall-ID, device-ID, ..)

Admins should be able to overwrite or turn off.

Default is on and pre-set to the LNbits logo
https://github.com/lnbits/lnbits/blob/3260acbcc7e907fa9c9c60d0582bf974031f917b/docs/logos/lnbits.png

**Comment by prusnak** [comment]
Customizable QR logo has been merged in https://github.com/lnbits/lnbits/pull/1955

So far it is shown only on few place. Let's make it appear everywhere in LNbits and also in all LNbits extensions.

Reopening this issue for now.
