### ISSUE TITLE
[Feature request] Prevent hard refresh requirement on new release

### ISSUE THREAD

**Issue by arbadacarbaYK** [lnbits/lnbits#1954]
Whenever LNbits has a new release, lots of users see only parts of the GUI or none at all / blank page.
Even the advanced users fail to understand immediately, that a hard refresh is needed.

**Describe the solution you'd like**
Cache busting on new release

Possible solution could be to give a version to static files (e.g. /static/js/script.js?v=1.0) on release-build.

**Comment by bitkarrot** [comment]
Good idea. Definitely support. If no cache busting at least tell the user to hard refresh with a pop up or something

**Comment by prusnak** [comment]
> could be to give a version to static files (e.g. /static/js/script.js?v=1.0)

Another option is to use `/static/js/script.js?h=abcdef` where abcdef is the sha256 of the file

I've seen this in some javascript deployments

**Comment by prusnak** [comment]
It seems there is a https://pypi.org/project/fastapi-static-digest/ which does even more advanced thing:
it mounts the file `/static/app.css` as `/static/app.92fede82119d2e012f890e1102080a45.css` where `92fede82119d2e012f890e1102080a45` is the has of `app.css` contents.
