### ISSUE TITLE
[BUG] fiat value broken in outbound transactions

### ISSUE THREAD

**Issue by MichaelAntonFischer** [lnbits/lnbits#1956]
**Describe the bug**
Fiat tracking has a decimal place issue. The decimal place is shifted on outbound transactions and in the csv report.

**To Reproduce**
Set currency to EUR.

**Screenshots**
<img width="1168" alt="Screenshot 2023-09-22 at 10 42 31" src="https://github.com/lnbits/lnbits/assets/93607398/053b5a89-b4ce-45e8-9945-3bf2892ac03f">
<img width="508" alt="Screenshot 2023-09-22 at 10 42 15" src="https://github.com/lnbits/lnbits/assets/93607398/b53b4b77-f169-45dc-9a72-3a8aca8ecf13">

**Desktop (please complete the following information):**

- LNbits version: 0.10.10
- Database tested with both internal and postgres

**Comment by dni** [comment]
this was fixed here, its inside `dev` and will be mergen in `0.11.0` .
https://github.com/lnbits/lnbits/pull/1934
