### ISSUE TITLE
Self funding on Raspiblitz v1.10

### ISSUE THREAD

**Issue by adevoss** [lnbits/lnbits#1967]
Started a discussion on the Raspiblitz github (#4191) about self funding an LNBits wallet.
Created an issue by rootzoll (#4192)

The solution in the FAQ of LNBits does not work for me. Or I did something wrong.

Untill there maybe is a solution in a next release of Raspiblitz, what can I do in the meantime to fund an LNBits wallet from the node itself?

**Comment by dni** [comment]
it is possible to self fund the wallets with the topup functionality as superuser.
![screenshot-1695706414](https://github.com/lnbits/lnbits/assets/1743657/3e6d9070-c0db-4e42-b9d4-44ab90b74063)

or on the wallet page as superuser aswell.

![screenshot-1695706424](https://github.com/lnbits/lnbits/assets/1743657/5f294854-7c9d-4ba4-a688-2b2874822132)

**Comment by adevoss** [comment]
That's easy. Why didn't I figured that out?
Thanks.

Can you explain the FAQ 'Funding my LNbits wallet from my node it doesn't work.'?
- After that change lnd won't start
- Does that perhaps only concern payments to the node itself (not funding)?

**Comment by dni** [comment]
i think self payment arent necessary if you use topup, so i would revert and not use it.

**Comment by arbadacarbaYK** [comment]
> That's easy. Why didn't I figured that out? Thanks.
> 
> Can you explain the FAQ 'Funding my LNbits wallet from my node it doesn't work.'?
> 
>     * After that change lnd won't start
> 
>     * Does that perhaps only concern payments to the node itself (not funding)?

Its in the normal guide for funding a bit up :) https://github.com/lnbits/lnbits/wiki/LNbits-Documentation#funding-sources 
This page has really gotten too long, we will need to change that and make it searchable too
