### ISSUE TITLE
[BUG] Inconsistency in Websocket data format for sent/received payments

### ISSUE THREAD

**Issue by cos-it-is** [lnbits/lnbits#1978]
v0.10.10 - 

There is an inconsistent use of " or ' in the JSON responses of websocket data.

Suggest use " due to Arduinojson recognising this format compared to ' not working.

![image](https://github.com/lnbits/lnbits/assets/111354736/53895986-099a-474b-8fe4-fdbd833bb777)

**Comment by jackstar12** [comment]
I can't reproduce this issue and I can remember fixing this a while a go. What commit are you exactly at?

**Comment by cos-it-is** [comment]
I am using https://wallets.fyoumoneypod.com/ as legend server is not currently working with websockets.

**Comment by jackstar12** [comment]
> I am using https://wallets.fyoumoneypod.com/ as legend server is not currently working with websockets.

This instance is version 0.10.9 and not 0.10.0. If you upgrade to >=0.10.0 it will be fixed

**Comment by cos-it-is** [comment]
OK, thanks
