### ISSUE TITLE
[BUG] When deleting a funded wallet, the LNbits Ballance (Wallet Management) does not change

### ISSUE THREAD

**Issue by tomgithub2018** [lnbits/lnbits#1985]
**Describe the bug**
When deleting a wallet, on the admin page, the "LNbits Ballance" under Wallet Management does not change or correct the total number of sats.

**To Reproduce**

1. Go to ''Lnbits Admin Page"
2. Click on 'delete wallet (with funds on it)'
3. Scroll down to 'Server Management'
4. See the total LNBits Ballance does not change or correct its value

**Expected behavior**
The Database should update, when deleting funded wallets.

**Screenshots**
![photo_2023-10-03_11-44-37](https://github.com/lnbits/lnbits/assets/45449557/dcc9a790-b7dc-4592-9997-fc54fb9bd106)

- LNbits version: 0.10.9 on Umbrel

**Comment by jackstar12** [comment]
> Especially since lnurlw/p from that wallet still work after deletion (right?).. where are those booked if only sats to active wallets are filtered..

a deleted wallet wouldnt work anymore

**Comment by motorina0** [comment]
This has been fixed:

Before wallet delete:
![image](https://github.com/user-attachments/assets/3df9316d-06eb-40fb-aff2-b0f43e9f3920)


After wallet delete:
![image](https://github.com/user-attachments/assets/9055d7d4-76d3-4947-a4bc-46e8b75fa76d)
