### ISSUE TITLE
Create a CI pipeline that installs all extensions from extensions.json

### ISSUE THREAD

**Issue by prusnak** [lnbits/lnbits#2012]
Create a CI pipeline that installs all extensions from [extensions.json](https://github.com/lnbits/lnbits-extensions/blob/main/extensions.json) and tries that they all load without issues.

Quick hack to get a list of extensions for `.env`:

``` shell
curl -s https://raw.githubusercontent.com/lnbits/lnbits-extensions/main/extensions.json | grep '"id":' | sort -u | awk -F '"' '{printf("%s,",$4)}'
```

**Comment by dni** [comment]
we need this string like this
`LNBITS_EXTENSIONS_DEFAULT_INSTALL="jitsi,copilot,gerty,jukebox,lnticket,tpos,usermanager,example,events,lnurldevice,smtp,discordbot,hivemind,boltcards,nostrnip5,splitpayments,boltz,satsdice,offlineshop,subdomains,streamalerts,livestream,lnurlp,deezy,invoices,withdraw,paywall,market,satspay,bleskomat,tipjar,lndhub,scrub,lnaddress,watchonly"`

and export that

**Comment by dni** [comment]
https://github.com/lnbits/lnbits-extensions/blob/main/util.sh#L32

**Comment by dni** [comment]
but i still think this CI pipeline should be trigger in `lnbits-extensions` repository, when an extensions is updated!

**Comment by motorina0** [comment]
This is implemented with JMeter test on the CI.
