### ISSUE TITLE
Consolidate crypto libraries

### ISSUE THREAD

**Issue by prusnak** [lnbits/lnbits#2013]
Currently LNbits and extensions are using the following Python crypto libraries:
- [ecdsa](https://pypi.org/project/ecdsa/)
- [embit](https://pypi.org/project/embit/)
- [pycryptodomex](https://pypi.org/project/pycryptodomex/)
- [secp256k1](https://pypi.org/project/secp256k1/)

It would be great to determine whether we really need to use all 4 and consolidate usages to use maybe one or two of these.

**Comment by dni** [comment]
love it, embst is definitly needed for all the boltz magic

**Comment by prusnak** [comment]
> love it, embit is definitly needed for all the boltz magic, i think it a good library for btc stuff.
> i also think it is the main thing behind the onchain extension if i am not wrong? @motorina0

Yes, embit is used for onchain stuff (transaction builder). I guess this can stay as is.

**Comment by prusnak** [comment]
`pycryptodomex` is used for:

```
from Cryptodome import Random
from Cryptodome.Cipher import AES
```

random is spurious, i think we should replace all calls to `os.random()` and `Cryptodome.Random` with [`secrets.token_bytes()`](https://docs.python.org/3/library/secrets.html#secrets.token_bytes)

that said, this won't help us getting rid of `pycryptodomex`, because we will still need for AES used by core and some of the extensions

**Comment by prusnak** [comment]
This leaves us with `ecdsa` and `secp256k1` where there is a huge overlap and there it would be great if we were able to figure out which of these we want to use. This is basically issue of https://github.com/lnbits/bolt11 which uses both and this usage translates to lnbits using both.

**Comment by prusnak** [comment]
Thinking more about this, I am going to close this in favor of smaller individual issues, which will point back to this issue.
