### ISSUE TITLE
[BUG] Web rounding milisatoshis up

### ISSUE THREAD

**Issue by AugustoResende** [lnbits/lnbits#2031]
**Describe the bug**
balance: 586 in API shows as 1 satoshi in web, but this is not true, and if i try to pay another lnbits invoice 1 sat (zero fee, same node), it fails because no sufficient balance.

**To Reproduce**

1. Deposit any amount
2. Pay anything cheap that gives you milisatoshis (because of fees)
3. Create another lnbits wallet
4. Transfer everything but 1 sat deducted
5. See response of wallet request return an msats amount less than 1 satoshi and interface shows 1 full satoshi.

**Expected behavior**
Show 0 satoshis or show the milisatoshis.

**Screenshots**
![Captura de tela de 2023-10-13 16-08-12](https://github.com/lnbits/lnbits/assets/10731727/66f81ff3-c104-4064-b6d4-a3f36607ea1b)

**Comment by prusnak** [comment]
I think this is the fix (untested yet):

``` patch
diff --git a/lnbits/core/static/js/wallet.js b/lnbits/core/static/js/wallet.js
index d72996bf5..a80505fcf 100644
--- a/lnbits/core/static/js/wallet.js
+++ b/lnbits/core/static/js/wallet.js
@@ -791,7 +791,7 @@ new Vue({
     },
     fetchBalance: function () {
       LNbits.api.getWallet(this.g.wallet).then(response => {
-        this.balance = Math.round(response.data.balance / 1000)
+        this.balance = Math.floor(response.data.balance / 1000)
         EventHub.$emit('update-wallet-balance', [
           this.g.wallet.id,
           this.balance
diff --git a/lnbits/static/js/base.js b/lnbits/static/js/base.js
index 0b676e3dd..73e61271d 100644
--- a/lnbits/static/js/base.js
+++ b/lnbits/static/js/base.js
@@ -196,7 +196,7 @@ window.LNbits = {
         currency: data.currency
       }
       newWallet.msat = data.balance_msat
-      newWallet.sat = Math.round(data.balance_msat / 1000)
+      newWallet.sat = Math.floor(data.balance_msat / 1000)
       newWallet.fsat = new Intl.NumberFormat(window.LOCALE).format(
         newWallet.sat
       )
```

I will wait until https://github.com/lnbits/lnbits/pull/1964 is merged tomorrow (it reorganizes the file structure), then will apply this change, test and send a PR.

**Comment by prusnak** [comment]
Fix in https://github.com/lnbits/lnbits/pull/2070
