### ISSUE TITLE
Add "Save Bookmark" Button on Warning Dialog at First Login

### ISSUE THREAD

**Issue by marimes** [lnbits/lnbits#2033]
**Context**

I am handing out LNURLw vouchers as tips or to orange-pill someone. Usually, the recipient only has a smartphone at hand, and we don't have a ton of time for explanations (street, bar, etc.).

**Current Situation**

After scanning my voucher they get to my LNbits server and claim their sats. After that, they get the greeting/warning message making them understand they need to copy that URL. Sadly, many people don't even know how to store a bookmark on their phone.

**Request**

Instead or in addition to the "Copy Wallet URL" button, it would be fantastic to have a "Save URL" button.
<img width="543" alt="Bildschirmfoto 2023-10-14 um 07 47 31" src="https://github.com/lnbits/lnbits/assets/12594437/20663341-b26e-456c-967c-e1379895a664">

**Comment by dni** [comment]
hi! after looking it up, it seems a bit browser dependent, if that is even possible, not sure how this would react on smartphones. on webkit safari/chrome, it is only an alert that tells you to press `CTRL + D`.

```
<script type="text/javascript">
    $(function() {
        $("#bookmarkme").click(function() {
            // Mozilla Firefox Bookmark
            if ('sidebar' in window && 'addPanel' in window.sidebar) { 
                window.sidebar.addPanel(location.href,document.title,"");
            } else if( /*@cc_on!@*/false) { // IE Favorite
                window.external.AddFavorite(location.href,document.title); 
            } else { // webkit - safari/chrome
                alert('Press ' + (navigator.userAgent.toLowerCase().indexOf('mac') != - 1 ? 'Command/Cmd' : 'CTRL') + ' + D to bookmark this page.');
            }
        });
    });
</script>
```
https://stackoverflow.com/questions/10033215/how-do-i-add-an-add-to-favorites-button-or-link-on-my-website

**Comment by motorina0** [comment]
Is this issue still relevant now that LNbits has a login system?
Please re-open if true.
