### ISSUE TITLE
[BUG] - Wrong reults in fiat conversion

### ISSUE THREAD

**Issue by COA1IMB** [lnbits/lnbits#2037]
**Describe the bug**
When sending only 1 sat the fiat conversion seems to be off as it displays 100€ when sending 1 sat.

**To Reproduce**

1. Send 1 sats

**Expected behavior**
Display correct fiat and value and conversion rate. 

**Screenshots**
![2023-10-16_19h08_39](https://github.com/lnbits/lnbits/assets/11683289/ee100b2c-dc17-4da1-819d-3a6a1e92549a)

- LNbits version: [e.g. 0.11.0 or commit hash]

**Comment by dni** [comment]
thanks, that will be fixed in `0.11.1`.  https://github.com/lnbits/lnbits/pull/1934
