### ISSUE TITLE
Only full numbers allowed as Item Price in OfflineShop

### ISSUE THREAD

**Issue by 3ooabkhxtn** [lnbits/lnbits#204]
Tried to add some items in Offlineshop with two decimal places in a national currency Was not possible, as the frontend told me only full numbers are allowed.

Added step="0.001" and min="0.001" in templates/offlineshop/index.html under <q-input label="`Item price (${itemDialog.data.unit})`"></q-input> and that worked for me now.

Should also be ok for sat currency, as lnurl denominates in msat

**Comment by fiatjaf** [comment]
Fixed in https://github.com/lnbits/lnbits/pull/207/commits/bb5189af5b0d0e88a0ded5024c00cc6fddc2b814
