### ISSUE TITLE
[BUG] api/v1/lnurlauth

### ISSUE THREAD

**Issue by sawrubgupta** [lnbits/lnbits#2069]
this api is not working after passing callback url to this.
please you can check

{
  "detail": "{\"message\":\"Internal error\",\"code\":\"INTERNAL_SERVER_ERROR\"}"
}

I am getting this response.

**Comment by motorina0** [comment]
@sawrubgupta is this issue still relevant?
If yes, can you please add more details on how to reproduce:

 **Steps**
  ...

**Actual Result**:
...

**Expected Result**:
...
