### ISSUE TITLE
[BUG] migration error from sqlite to postgresql

### ISSUE THREAD

**Issue by xtophe632** [lnbits/lnbits#2072]
**Describe the bug**
trying to migrate a sql lite lnbits database to a fresh install of Postgresql. 
run make migration and got the message
Exception: sqlite database version (10) of core doesn't match postgres database version 15
for the record my postgresql version appears to be 14
lnbits version 0.11.2

**Comment by motorina0** [comment]
@xtophe632 is this issue still relevant?
