### ISSUE TITLE
error message when connecting lnbits to cln node on same lan " [Errno 99] error while attempting to bind on address ...

### ISSUE THREAD

**Issue by hdlslm** [lnbits/lnbits#2076]
[Errno 99] error while attempting to bind on address (node ip address, 5000) : cannot assign requested address"

i have tried everything i could possible think of and i still receive the error any ideas? i'm stumped!!

**Comment by prusnak** [comment]
Maybe there is another service already running on port 5000?

Did you try using a different port?

**Comment by hdlslm** [comment]
> It seems you are having a problem starting LNbits server, not connecting to CLN.
> 
> Maybe there is another service already running on port 5000?
> 
> Did you try using a different port?
> 
> Did you try using address 0.0.0.0 as LNbits address?

i finally figured it out, it  was user error. my env file was in shambles to say the least. thanks for the reply
