### ISSUE TITLE
[BUG] Division by zero error on super_user

### ISSUE THREAD

**Issue by matiasim** [lnbits/lnbits#2081]
If you log in to your lnbits node as `super_user` with an LNDRest backend which has no open channels, then you get a series of errors due to not having open channels.

**To Reproduce**

1. Connect your lnbits to a brand new LNDRest backed without open channels
2. Go to `Manage Node` on the lnbits super-user console
4. Note a series of errors pop up.

On the lnbits node, the relevant errors are:
```  
File "/root/.cache/pypoetry/virtualenvs/lnbits-9TtSrW0h-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 190, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/lnbits/core/views/node_api.py", line 80, in api_get_info
    return await node.get_info()
  File "/app/lnbits/nodes/lndrest.py", line 266, in get_info
    public = await self.get_public_info()
  File "/app/lnbits/nodes/lndrest.py", line 262, in get_public_info
    channel_stats=ChannelStats.from_list(channels),
  File "/app/lnbits/nodes/base.py", line 73, in from_list
    avg_size=int(sum(active_channel_sizes) / len(active_channel_sizes)),
ZeroDivisionError: division by zero
```

**Expected behavior**
There should be a check to see if there are open channels first before dividing by the length of channels. As a temporary fix on my end, I have modifed `nodes\base.py` (lines 70+) with:

```
        avg_size=biggest_size=smallest_size=total_capacity=0
        if(len(active_channel_sizes) > 0):
            avg_size=int(sum(active_channel_sizes) / len(active_channel_sizes))
            biggest_size=max(active_channel_sizes)
            smallest_size=min(active_channel_sizes)
            total_capacity=sum(active_channel_sizes)

        return cls(
            counts=counts,
            avg_size=avg_size,
            biggest_size=biggest_size,
            smallest_size=smallest_size,
            total_capacity=total_capacity,
        )
```
I'm sure there is a more elegant solution

**Desktop (please complete the following information):**

- LNbits version: 0.11.2
- Database sqlite

**Comment by prusnak** [comment]
Thanks for the report!

Fix in https://github.com/lnbits/lnbits/pull/2085
