### ISSUE TITLE
Extra and memo is not coming in trx history, while passing while paying invoice[BUG]

### ISSUE THREAD

**Issue by sawrubgupta** [lnbits/lnbits#2082]
When I am paying the invoice and passing extra and memo parameter, its not coming in transaction history.

How to reproduce ? 
Just create a invoice on any website
and paid that invoice and in body pass the memo and extra object
After that hit transaction history, the memo and extra is not going to come

Expected behavior
Extra field should give whatever we pass in it
Memo should give whatever string we passed in it.

**Comment by talvasconcelos** [comment]
`extra` is not passed along when making a payment, ex: `"out: true"`.

https://github.com/lnbits/lnbits/blob/7306df34459714b4b2e21cbf066d582c03b6ffd6/lnbits/core/views/api.py#L334-L338

**Comment by sawrubgupta** [comment]
But I think we need to pass as , it is necessary to have some fields like this
