### ISSUE TITLE
feature request: frontend ui, move manage extensions into 'Admin' area

### ISSUE THREAD

**Issue by dni** [lnbits/lnbits#2088]
if you have many extensions it can be difficult to see where you manage the extensions, so my suggestion is as follows.
move the `extensions` to the `Admin` area and call it `Manage Extensions`.
Rename `Admin` to `Manage` and keep `Extensions` as is.
![screenshot-1699430658](https://github.com/lnbits/lnbits/assets/1743657/b01e96f9-0f14-450e-9dd8-1c694b0a14e4)
![screenshot-1699430653](https://github.com/lnbits/lnbits/assets/1743657/a6aedb3b-6e18-45a3-993d-e6384bcf3c1f)

**Comment by motorina0** [comment]
Doesn't look too bad.
I think it is more consistent this way. The `Extensions` menu item should not be on the same level as regular extensions.
It also has the advantage that it is not hidden below when many extensions are enabled.

![image](https://github.com/lnbits/lnbits/assets/2951406/5e8f4c03-36f8-4b68-8841-a874c324a4de)

**Comment by prusnak** [comment]
When we are at it, maybe we can also change the extensions icon to one of these (which are quite common elsewhere):

[<img width="270" alt="Screenshot 2023-11-08 at 10 56 06" src="https://github.com/lnbits/lnbits/assets/42201/05ccc787-5e73-4b0f-9e4b-5f40cfe30e91">
](https://thenounproject.com/icon/extension-3080128/)
[<img width="270" alt="Screenshot 2023-11-08 at 10 56 03" src="https://github.com/lnbits/lnbits/assets/42201/91a0bb03-fc46-4ad0-8f93-905fa4f3b6c1">
](https://thenounproject.com/icon/puzzle-6096391/)
The current icon always seemed confusing to me.

**Comment by motorina0** [comment]
> When we are at it, maybe we can also change the extensions icon to one of these (which are quite common elsewhere)?

I vote for the first one.

**Comment by prusnak** [comment]
I looked more into the material icons which seem to be used.

There is a puzzle extension icon here: https://fonts.google.com/icons?icon.set=Material+Icons&selected=Material+Icons+Outlined:extension:&icon.query=extension

However there is no icon like the first one, closest to it is probably the "Apps" icon: https://fonts.google.com/icons?icon.set=Material+Icons&icon.query=apps&icon.platform=web&selected=Material+Icons+Outlined:apps: (which is okayish too I guess)

**Comment by dni** [comment]
puzzle!
