### ISSUE TITLE
Cat super_user file in data directory

### ISSUE THREAD

**Issue by Sebastix** [lnbits/lnbits#2114]
According to the docs https://github.com/lnbits/lnbits/blob/main/docs/guide/admin_ui.md the super_user file should be in the root directory. I found out during yesterday installation (following https://github.com/lnbits/lnbits/blob/main/docs/guide/installation.md#option-1-recommended-poetry) the file was located in the data directory. So the docs should instruct to execute `cat data/super_user` instead of `cat super_user`?

**Comment by prusnak** [comment]
Closed via https://github.com/lnbits/lnbits/pull/2115
