### ISSUE TITLE
Consider using Crowdin or Transifex for localization (or add check to detect outdated translation JSON files)

### ISSUE THREAD

**Issue by prusnak** [lnbits/lnbits#2122]
Currently we are using plain JSON files and while this solution is good enough(tm), it has two drawbacks:
1. it is unfriendly for translators who need to understand what JSON is and how GitHub works
2. more importantly: the old JSON files are not updated and some older translations that were added long time ago are missing half of the strings

[Crowdin](https://crowdin.com) and [Transifex](https://www.transifex.com) are friendly for translators, but using them means a non-trivial time investment to get them running and also recurring cost of syncing translation data back and forth.

If we don't want to use one of these tools, maybe we can just add a CI check that checks all i18n JSON files have the same keys and we are not missing any, this should be easy to do.

**Comment by dni** [comment]
i prefer the ci tool that checks the i18n

**Comment by dni** [comment]
@prusnak is this still a concern? i thiink you did an awesome job on the tooling for i18n

**Comment by prusnak** [comment]
Let's close
