### ISSUE TITLE
add a `target="_blank"` to all logos on index

### ISSUE THREAD

**Issue by dni** [lnbits/lnbits#2129]
> hey! can you please add a `target="_blank"` to all the hrefs? i think they should all have one.

_Originally posted by @dni in https://github.com/lnbits/lnbits/pull/2128#discussion_r1407374543_

**Comment by prusnak** [comment]
Maybe even create a component called `a-external` that not only adds `target="_blank"` but also `rel="noopener noreferrer"` for ancient browsers.
