### ISSUE TITLE
Support Ticket doesn't show up in extension, even after payment is confirmed.

### ISSUE THREAD

**Issue by Fittiboy** [lnbits/lnbits#213]
My LNbits transaction history shows a 25 sats payment for a Support Ticket (it has the #lnticket tag), but this ticket doesn't show up in the extension. The webhook was also never dispatched.

**Comment by Fittiboy** [comment]
Restarting (temporarily?) fixes this. I feel like there might still be issues with the nursery. I will keep an eye on any payments I get.

**Comment by Fittiboy** [comment]
The issue might be on the sender side. During normal operation, the site refreshes after the payment is confirmed, and the form is empty again.
For that 25 word ticket, the site never refreshed (it was kept open for several minutes after the payment was confirmed), and the form was still filled out.

**Comment by fiatjaf** [comment]
It is. On this extension the client keeps polling the server tô check for the payment confirmation.

It must be changed to listen for incoming payment notifications on the server side instead.

**Comment by arcbtc** [comment]
Fixed
