### ISSUE TITLE
[SUGGESTION] FORWARDED_ALLOW_IPS Not workin?

### ISSUE THREAD

**Issue by tempo-beme** [lnbits/lnbits#2134]
Hi. 
I was trying to run lnbits with the lnurlp extension on a docker container. I couldn't get the `lnurlp/api/v1/well-known/<lnurlname>` to work. I had seen similar issues where they suggested:
- Setting FORWARDED_ALLOW_IPS="*" in the `.env` file
- Setting `FORWARDED_ALLOW_IPS=*` as a environment variable in the docker-compose file 
- editting `server.py` line 70 `forwarded_allow_ips="*", # forwarded_allow_ips,`. This might actually be a bug since the env vars alone didn't work, unless it can only be set when calling `poetry run lnbits --port $LNBITS_PORT --host $LNBITS_HOST --forwarded-allow-ips="*"` (the latter works).

However, when I ran the `lnurlp/api/v1/well-known/<lnurlname>` endpoint it still gave the following error:
```
2 validation errors for LnurlPayResponse\ncallback\n  URL host invalid, top level domain required (type=value_error.url.host)\ncallback\n  URL scheme not permitted (type=value_error.url.scheme; allowed_schemes={'https'})
```
After a lot of searching, I came across [this](https://docs.gunicorn.org/en/stable/settings.html) which suggested including `X-Forwarded-Proto: https` into the request header. So my request became:

```
curl -X 'GET' \
  'http://<domain>/lnurlp/api/v1/well-known/<lnulp_name>' \
  -H 'accept: application/json' -H 'X-Forwarded-Proto: https'
```

The solution for this certainly wasn't obvious to me. I kept thinking the issue was in my env vars or in my lnbits configuration. 

Suggestion: Add information about this header (`X-Forwarded-Proto: https`) to the `.env.example` file in the section where it has the commented `FORWARDED_ALLOW_IPS="*"`, or if any other header is recommended.

**Comment by dni** [comment]
hey, thakns for the suggestion im gonna add it, today!
