### ISSUE TITLE
[BUG] reserve fee deducted as a fee in case of internal payments

### ISSUE THREAD

**Issue by acurious** [lnbits/lnbits#2142]
**Describe the bug**
Full reserve fee is deducted from the balance if one makes an internal payment

**To Reproduce**
1. Make an internal payment
2. See the reserve fee counted as a fee and deducted from the balance

**Expected behavior**
I'd expect reserve fee not to be considered as final fee that is deducted from the balance in case of internal payments

**Desktop (please complete the following information):**
- LNbits version: 0.11.2
- Database: sqlite

**Comment by prusnak** [comment]
Which config values did you define for `LNBITS_SERVICE_FEE` and `LNBITS_SERVICE_FEE_MAX` and `LNBITS_SERVICE_FEE_IGNORE_INTERNAL` ?

**Comment by acurious** [comment]
In .env file: 
LNBITS_SERVICE_FEE="0.0"
LNBITS_RESERVE_FEE_MIN=2000
LNBITS_RESERVE_FEE_PERCENT=1.0
nothing defined for LNBITS_SERVICE_FEE_IGNORE_INTERNAL 

In admin UI (not enabled in .env file though)
Same parameters + Disable Service Fee for Internal Payments toggle is switched on

**Comment by prusnak** [comment]
Fixed in https://github.com/lnbits/lnbits/pull/2150

Will be pushed via the next release
