### ISSUE TITLE
[Feature request] Balance of wallet in fiat amount too

### ISSUE THREAD

**Issue by Perlover** [lnbits/lnbits#2149]
LNBits has "Fiat tracking" for wallets. But balance of wallet (top amount in "sats") is displayed always in sats only
May be if a wallet has setting of fiat currency to display there a balance in fiat amount too (just for a set fiat currency only or for default global fiat currency if a wallet has not a set fiat unit)?

I as user would like to see there fiat amount too. I think it will be a good UX...

**Comment by prusnak** [comment]
This is how an UI could look like:

<img width="462" alt="Screenshot 2023-12-05 at 22 04 38" src="https://github.com/lnbits/lnbits/assets/42201/5353e60c-70ae-4487-aa33-f505f2e12980">

- on the left wallet list there is just another `<q-item-label>` element
- in the main view, I just added `<h4>` with fiat balance after the `<h3>` that shows sats balance

**Comment by Perlover** [comment]
That would be great! But I wouldn't do the balance on the left panel!

For example, I have more than ten wallets in it and displaying both balances will greatly overload the interface - there will be a lot of numbers and, moreover, in one font.

It seems to me that the balance on the right side, when we open a separate wallet, is more than enough.

What do you think?

**Comment by prusnak** [comment]
I also do have 10+ wallets in the list.

However, the fiat amounts are only shown to accounts that have Fiat tracking enabled, so not necessarily all of them.

Or maybe we can show fiat amounts on hover in the wallet list (as a tooltip)? This won't work for mobile obviously (where there is no hover), but might help to declutter the user interface.

**Comment by Perlover** [comment]
It seems to me that showing when hovering over the mouse will "break out" of the general style. I don't remember it working anywhere in LNBits. Maybe I'm wrong.

In any case, I am for any solution! It seems to me that in all the proposed options it will be better!

Thank you! :)

**Comment by talvasconcelos** [comment]
How does this looks like?

![fiat](https://i.imgur.com/hOODboL.png)

**Comment by dni** [comment]
![screenshot-1701864719](https://github.com/lnbits/lnbits/assets/1743657/a6a2af75-8450-44d1-8850-3c6049dc630a)
can we have it a but faded like the screenshot, a bit smaller and mayve cursive like we have in the payment overview

**Comment by prusnak** [comment]
> Like so? @dni

Love it!

**Comment by dni** [comment]
yes

**Comment by talvasconcelos** [comment]
Probably has to do with the `LNbits.utils.format....` i'm using. the ones in the transaction table come from the extra in payments! 

Since i'm at it, i can change it.... if everyone agrees with it!

**Comment by prusnak** [comment]
> Since i'm at it, i can change it.... if everyone agrees with it!

Consistency is the key. I am not sure if I prefer Kč/€/$ or CZK/EUR/USD, but I know I prefer to have it consistent everywhere in the UI.

**Comment by Perlover** [comment]
Thank you very much! It works awesome!
