### ISSUE TITLE
[BUG] Reserve Percent & LNbits Balance aren't correct after account deletion

### ISSUE THREAD

**Issue by HamishMacEwan** [lnbits/lnbits#2164]
**Describe the bug**
To demonstrate there is no connection between an LNbits instance's "LNbits Balance" and that of its funding source an account was created and "topped up" with 1,000,000 sats and the Funding Source Info changed from:

![image](https://github.com/lnbits/lnbits/assets/388061/8480c618-ae52-4efd-9d05-8be5be2256b5)

to:

![image](https://github.com/lnbits/lnbits/assets/388061/d6eb8ffd-8438-42bd-9868-f03a66793475)

After deleting the account with the 1,000,000 sats in it, and even after restarting the server, the numbers do not correct to the original values.

**To Reproduce**

See description

**Expected behavior**

Deleting an account, should correct the LNbits balance and Reserve Percent.  And it should happen without the requirement to restart the server.

**Screenshots**

See above.

**Desktop (please complete the following information):**

- LNbits version: 0.11.2
- Database: Whatever LNbits SaaS uses.

**Additional context**

**Comment by dni** [comment]
this is because deleted wallets are accounted for. because they still exist in the database, in my usermanager pr https://github.com/lnbits/lnbits/pull/2139 there will be a feature to permanently delete wallets.
