### ISSUE TITLE
On-chain topup

### ISSUE THREAD

**Issue by hosiawak** [lnbits/lnbits#218]
Would it be useful to allow people who have only on-chain funds and end up on an lnbits instance top up their account by sending on-chain ? An opt-in feature.

- Rename "Create invoice" to "Receive"
- Add a checkbox "Receive on-chain" - when checked we get the node on-chain `newaddr` and a QR code
- After 1 conf (default, configurable) the user gets the new balance

Thoughts ?

**Comment by arcbtc** [comment]
More interoperability with onchain would be nice, but this method would then require the admin to manage channels to allow those funds to be accessible on LN.

This could work as an extension that the admin allows users to run, but it couldn't be core feature

**Comment by arcbtc** [comment]
create extension "Solution"
