### ISSUE TITLE
[BUG] docker buildx for amd64,arm64 and arm/v7 ->the later 2 fail

### ISSUE THREAD

**Issue by petzsch** [lnbits/lnbits#2204]
Trying to build lnbits for the above 3 architectures with this command:

```docker buildx build --platform linux/amd64,linux/arm64,linux/arm/v7 -t petzsch/lnbits:0.11.3 --push .```

Fails with the following:

![grafik](https://github.com/lnbits/lnbits/assets/1374810/bc024285-9751-4ad1-80f3-c506806192ba)

Not sure why the poetry install hangs so long and eventuelly fails.

I've tried bumping the python image used in the dockerfile to bookworm but it didn't help. Any ideas would be greatly appreciated.

**Comment by prusnak** [comment]
armv7 is practically dead but it makes sense to fix arm64

**Comment by petzsch** [comment]
must have misread the output, ommitting arm/v7 and i'm able to build it. It's pushing now to docker hub.
will close the issue tomorrow, since armv7 doesn't seem to be relevant to fix.
