### ISSUE TITLE
[Feature request] Allow custom OIDC Providers for SSO

### ISSUE THREAD

**Issue by counterweightoperator** [lnbits/lnbits#2212]
**Is your feature request related to a problem? Please describe.**
LNBits authentication has improved a lot after https://github.com/lnbits/lnbits/pull/2092. But, if an LNBits admin doesn't want to rely on native user and password, their only other options are relying on Github or Google as authentication providers. While that's definitely very user friendly for many people, it makes LNBits instances rely on Microsoft and Google. Not the most censorship resistant setup.

PR #2092 made the effort of implementing [OpenID Connect](https://openid.net/) (OIDC) integration for Github and Google as providers. Things could be taken one step further to allow for open source, self-hosted OIDC authentication providers like [Authentik](https://goauthentik.io/), [Keycloak](https://www.keycloak.org/) or [Authelia](https://www.authelia.com/).

In doing so, we would enable LNBits instance admins to easily use existing open source authentication providers to manage the authentication of their LNBits users with enterprise grade SSO. Communities with existing SSO solutions could also easily adopt LNBits and provide access to their users by simply integrating with their existing SSO provider.

For example, a small local community could provide users with LNBits accounts, Nextcloud accounts, a wiki and Matrix communication, while managing the authentication of all its users in a central service like Authentik.

**Describe the solution you'd like**
- An extension of the existing code for Google and Github SSO to allow custom OIDC providers.
- New environment variables in the `.env.example` file to allow LNBits instance admins to integrate with a custom provider by simply providing the required OIDC parameters (FQDN, client id, client secret, etc).
- Documentation to guide LNBits instance runners through integrating with popular OIDC providers like [Authentik](https://goauthentik.io/), [Keycloak](https://www.keycloak.org/) or [Authelia](https://www.authelia.com/).

**Describe alternatives you've considered**
NA.

**Additional context**
I currently lack the time and knowledge to get this implemented, but might be able to throw in some effort from March onward if it's still not implemented. If someone gives it a shot at implementing, I would be happy to help with testing and documenting the final solution in combination with Authentik.

**Comment by MichaelAntonFischer** [comment]
+1 on Keycloak, am currently looking into adding that capability to LNbits as well

**Comment by counterweightoperator** [comment]
I'm no expert in auth protocols, but from what I see in the code, I think it could easily be generalized to any OIDC provider. That should cover most popular self-hosted SSO solutions AFAIK.

**Comment by MichaelAntonFischer** [comment]
I will look into it next week. @motorina0 wanted to drop some of his implementation advice first.

**Comment by motorina0** [comment]
I have open this PR: https://github.com/lnbits/lnbits/pull/2263
 - refactor the `/auth` endpoint so that any SSO provider can be used
 - add instructions for how to add a new SSO Provider

**Comment by motorina0** [comment]
Keycloak SSO added in this PR https://github.com/lnbits/lnbits/pull/2272
Other SSO providers can follow the example there.
Closing this issue.
