### ISSUE TITLE
Able to send more sats to LNbits wallet than C-Lightning node has balance?

### ISSUE THREAD

**Issue by hellodarkness** [lnbits/lnbits#2215]
**Describe the bug**
I'm not sure if this is an 'intended' feature or a bug, but I'm running Core Lightning v23.11-88 and have a small balance on a node. Say, 80k sats. I've been able to 'send' 150,000 sats to the wallet from my RTL. There's already some balance in that wallet from other funding sources.

**To Reproduce**

1. Go to an LNbits wallet
2. Click on Create Invoice and enter a random amount bigger than the balance on your node.
3. Go to RTL and pay the invoice
4. See RTL claim it's paid it, and LNbits accept the payment

**Expected behavior**
The invoice shouldn't settle because the node doesn't have enough balance to cover it.

**Desktop (please complete the following information):**

- LNbits version: 0.11.1
- Database: SQLite

**Additional context**
I spotted this because of a typo. The wallet in question is one I actively use, and I'm now wondering if there's a graceful way to 'get rid of' the fake sats so the balance is accurate.

Thanks

**Comment by prusnak** [comment]
> The wallet in question is one I actively use, and I'm now wondering if there's a graceful way to 'get rid of' the fake sats so the balance is accurate.

You create a new wallet. Send excess amount there and delete the wallet.

**Comment by hellodarkness** [comment]
> You create a new wallet. Send excess amount there and delete the wallet.

Thank you! I was considering doing that but wanted to make sure it wouldn't have any unexpected consequences.

**Comment by motorina0** [comment]
@hellodarkness can this issue be closed?
