### ISSUE TITLE
[Feature request] Audit feature for wallets

### ISSUE THREAD

**Issue by MichaelAntonFischer** [lnbits/lnbits#2216]
**Is your feature request related to a problem? Please describe.**
I would like to see all wallets with their balances in the audit section. 

**Additional context**
Right now, audit only gives you an overall balance of the node. But as far as I can see, there is no way to know where all that balance is.
If you run an open LNBits instance that is only for demo or noncustodial, it would be handy to see where someone is accumulating sats on your instance.

**Comment by dni** [comment]
hey! https://github.com/lnbits/lnbits/pull/2139
hopefully it going to make it into `0.12.0`

**Comment by MichaelAntonFischer** [comment]
Ah nice.
