### ISSUE TITLE
Extension proposal: Donation page for streamers integrated with Streamlabs/StreamElements

### ISSUE THREAD

**Issue by Fittiboy** [lnbits/lnbits#225]
I've been working on an integration with [Streamlabs](https://streamlabs.com), hoping to integrate [StreamElements](https://streamelements.com) as well. You can see it in action [here](https://twitter.com/Fittiboy/status/1399753700445507590).   
I would love for this to be available as an extension, but I have no front end experience whatsoever.
If anyone wants to help me build this, that'd be amazing: Fittiboy/bitcoin-on-twitch#7

**Comment by arcbtc** [comment]
Those wanting to dicuss/collaborate please go here https://github.com/lnbits/lnbits/pull/227

**Comment by arcbtc** [comment]
PR in so closing
