### ISSUE TITLE
[BUG] own site description disappered

### ISSUE THREAD

**Issue by iWarpBTC** [lnbits/lnbits#2253]
**Describe the bug**
With 0.12.0 there's a new index page which now shows the generic desc regardless the `SITE_TITLE` setting. 

**Expected behavior**
Custom `LNBITS_SITE_DESCRIPTION` shows when `SITE_TITLE` is changed as it was before.

**Comment by motorina0** [comment]
Fixed in: https://github.com/lnbits/lnbits/pull/2254
