### ISSUE TITLE
[BUG] v0.12.1 - Newly created wallet without registration - cannot be opened by URL on another device

### ISSUE THREAD

**Issue by Perlover** [lnbits/lnbits#2266]
**Describe the bug**

A wallet that is created by simply clicking "Create New Wallet", without specifying a username and password - should work on other devices according to the link.

**To Reproduce**

1. Opening the main page of the site with LNBits 0.12.1
2. Create a wallet using the "Create New Wallet" link
3. Copy the wallet link to another browser or try to open it in private mode - we get HTTP 401 error from LNBits.
4. Also, the "Export to Phone with QR Code" section doesn't work for the same reason - the address on the phone shows a 401 error

**Expected behavior**

In early version 0.12.0 (pre-release) you had the following: if a wallet was created from the main page by clicking "Create New Wallet" and specifying a name of wallet, this wallet could be opened in another browser via URL (because no name and password were set, so it was supposed to be an easy way to access via URL). I suppose that's how it was intended. Otherwise, the user loses access to the funds and wallet if they saved the wallet URL address and deleted the cookie (maybe LocalStorage) of the site.

**Desktop (please complete the following information):**

- LNbits version: 0.12.1
- Database: sqlite

**Comment by Perlover** [comment]
[Because of a related problem](https://github.com/lnbits/lnbits/issues/2265#issuecomment-1940787228), I think I understand what this is related to. The QR code has a link with no `usr` parameter. And with the current algorithm, to open a wallet you need to have either a usr parameter or an access token set by the login page by username and password.

**Solution:** if we implement the approach I described in the ["My suggestion" paragraph](https://github.com/lnbits/lnbits/issues/2265#issuecomment-1940787228) and add `usr` directly to the QR code, we will have: for newly created wallets without username and password, we will open the wallet via the link in QR code, and if the user has already set a username and password after creating the wallet, the QR code will take him to the login page with a username and password request.

**Comment by dni** [comment]
this was fixed by: https://github.com/lnbits/lnbits/pull/2340
