### ISSUE TITLE
[BUG] after delete-settings lost admin user name cant be reused

### ISSUE THREAD

**Issue by tlindi** [lnbits/lnbits#2274]
**Describe the bug**
lnbits-cli tool resets settings so they are re-read from .env and first_start is shown.
If one wants to use same super admin username, it is impossible cause username is reserved.

**To Reproduce**

1. Install lnbits and goto first_install. create superuser "lnbits" and password
2. run poetry run -C /home/setup/lnbits lnbits-cli delete-settings
3. restart LNbits
4. goto first_install page and try to create user lnbits
5. You will get error: Username already in exists. 403 FORBIDDEN
If you have lost superuser UID / username&pwd there's no avail.
Even if you create new superadmin, it cant see old super admin with usermanager. And it can not see users the old superuser created.

**Expected behavior**
"delete settings" should set superuser name and password so it is possible to first_install to reset username (not "usr") and password.

**Screenshots**
If needed.

**Desktop (please complete the following information):**

- LNbits version: 0.12.1
- Database: sqlite (this template is missings ":" after "Database")

**Additional context**
(User management is tuff issue to handle.)

**Comment by dni** [comment]
you could just set a new username, login into the old one and change it there then again in the new one... but i agree its not ideal.

**Comment by tlindi** [comment]
> you could just set a new username, login into the old one and change it there then again in the new one... but i agree its not ideal.

I could - but new superuser cant see old superuser on usermanager. And say I did reset settings cause I lost superuser username / password .. this seems not to work at all. I need to use cli to see superuser "usr".

And even with it I can't reset password cause MyAccount can not be accessed with http://IPaddress and there is no existing link to MyAccount page for legacy usr= "authentication".

**Comment by tlindi** [comment]
Would it be good solution on first_install to be able to recover existing superuser by authenticating with superuser usr id?

**Comment by motorina0** [comment]
> Even if you create new superadmin, it cant see old super admin with usermanager. And it can not see users the old superuser created.

This is now possible with the `/users` console. See https://github.com/lnbits/lnbits/pull/2139

Now the new `superuser` can 
 - manage the wallets of the old `superuser` (delete wallet or transfer funds)
 - delete old `superuser` (if it has no wallets)
 - recycle the old `superuser` (not necessarily a best practice)

Closing now. Please re-open the issue if the new `user` feature are not sufficient.

**Comment by tlindi** [comment]
SuperUser "recovery" URL seems to work as expected on 1.0.0-rc9.
lnbits bash -c 'lnbits-cli superuser-url'

Thanks!
