### ISSUE TITLE
0.12.1 docker image

### ISSUE THREAD

**Issue by smolgrrr** [lnbits/lnbits#2275]
Hey looking to update the LNBits app on Umbrel.

In the past you've had tagged images under either lnbitsdocker/lnbits or lnbitsdocker/lnbits-legend. This latest release seems to just sit under `latest`, and also looks like only 0.12.0 has been published not 0.12.1.
Happy to go forward with just the `latest` tag image, but just wanted to let you guys know in case you haven't realised.

**Comment by dni** [comment]
hey, we are now using `lnbits/lnbits. `lnbitsdocker` is deprecated and it was accidently pushed to `lnbitsdocker/lnbits`

**Comment by smolgrrr** [comment]
ah i see, thanks.
sure thing, this is my TG 
![t_me-smolgrrr](https://github.com/lnbits/lnbits/assets/104137257/b4f40f30-e3c8-4829-8b1d-e17170e9dbe3)
