### ISSUE TITLE
[Feature request] Add server url to "API keys and API docs" section

### ISSUE THREAD

**Issue by kilrau** [lnbits/lnbits#2277]
**Is your feature request related to a problem? Please describe.**
When linking lnbits with external services, (e.g. [zaprite](https://zaprite.com/)) one needs to specify two things: node url and invoice key. 

![image](https://github.com/lnbits/lnbits/assets/19181985/64920942-d120-4d50-951f-99aa8e6b1cca)

Invoice key is clearly visible in the "API keys and API docs" section, but it's sometimes unclear what my "LNbits Node URL" is. 

![image](https://github.com/lnbits/lnbits/assets/19181985/9ae7086b-f48b-4b56-b2aa-6f4a3f42fd96)

**Describe the solution you'd like**
Display "LNbits Node URL" in "Node URL, API keys and docs"

**Comment by john-zaprite** [comment]
This is great. Would definitely help our users.
