### ISSUE TITLE
[BUG] 0.12.2 Missing opportunity to delete Users

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/lnbits#2297]
**Describe the bug**
If i want to delete a _admin-user_ or _allowed-user_ in section "Server--> Users" there is no more possibility to do that.

**To Reproduce**

1. Go to section "Server--> Users"
2. Add a user by user id
3. Try to delete it afterwards
4. See missing opportunity

**Screenshots**
![bug](https://github.com/lnbits/lnbits/assets/106493492/8a0a74ac-b97e-4291-8d65-27ed5a7ecb5b)

**Version**
- LNbits version: 0.12.2

**Comment by dni** [comment]
fixed
