### ISSUE TITLE
[BUG] 0.12.2 Failing adding new extension source

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/lnbits#2298]
**Describe the bug**
I want to add an new Extension source. I add the line and press " + " or Enter. Nothing happens

**To Reproduce**

1. Go to section "Server--> Server" 
2. Add extension source 
3. Try to confirm your changes
4. See it´s not been added

**Version**

- LNbits version: 0.12.2
- Desktop: Chrome, Firefox | Mobile android - Chrome, Brave, Opera

**Comment by motorina0** [comment]
fixed!
