### ISSUE TITLE
[BUG] When using payLnUrl, the balance is sufficient, but Insufficient balance An error occurs.

### ISSUE THREAD

**Issue by lsj282** [lnbits/lnbits#2302]
**Describe the bug**
When using payLnUrl, the balance is sufficient, but Insufficient balance. An error occurs.

**To Reproduce**

1. Deposit sat into my LNbit wallet.
2. I try to send the balance to payLnUrl API within 5 minutes after receiving the deposit.
3. The balance is sufficient, but sometimes an Insufficient balance error occurs.

**Expected behavior**
have sufficient balance, the send should always succeed.

**Screenshots**
1. This is the log showing the balance in my wallet as seen on Surge. Since the time is KST, if you change it to UTC, it will be 26 Feb 2024 22:48.
![스크린샷 2024-02-27 오전 10 23 04](https://github.com/lnbits/lnbits/assets/99780455/7e61a3b3-8e8c-41ff-ac17-492123cdc338)

2,3. This is an error message where payLnUrl failed.
26 Feb 2024 I deposited sufficient amount at 22:48, but an insufficient balance error occurred at 22:50.
![스크린샷 2024-02-27 오전 9 44 58](https://github.com/lnbits/lnbits/assets/99780455/5b96cc62-6c83-41f6-b785-033e8b7d2369)
![스크린샷 2024-02-27 오전 10 08 31](https://github.com/lnbits/lnbits/assets/99780455/b1969e14-2665-4acf-8d45-49563baf14fb)

4. This is the code where I send the balance.
![스크린샷 2024-02-27 오전 10 28 17](https://github.com/lnbits/lnbits/assets/99780455/be8904b4-3ada-449e-a894-f42ddd0b4e24)

**Desktop (please complete the following information):**

- LNbits version: 0.11.3 in voltageapp
- Database : sqlite

**Comment by motorina0** [comment]
`0.11.3 ` is quite an old version, does it still reproduce on latest release?

please reopen issue if its still present.
