### ISSUE TITLE
[Feature request] API endpoint "fetch payment hash"

### ISSUE THREAD

**Issue by MichaelAntonFischer** [lnbits/lnbits#2303]
**Is your feature request related to a problem? Please describe.**
Using an ESP32 based pos in online mode, requires that the device fetches the invoice and the accompanying payment hash to verify that a payment has been made. If the node underlying the lnbits has private channels, the routing hints can really blow up the responses from api/v1/payments/decode overwhelming the ram of the pos with the size of the JSON document. 

**Describe the solution you'd like**
It would be nice to have a api/v1/payments/gethash endpoint that returns only the payment hash.

**Additional context**
Bounty 42k sats

**Comment by bitkarrot** [comment]
@motorina0 yes. We can it to the API for decoder extension

**Comment by motorina0** [comment]
Implemented here: https://github.com/lnbits/lnbits/pull/2612
It will be included in the next releases.

@MichaelAntonFischer I hope this helps your calls form the esp32 device

**Comment by MichaelAntonFischer** [comment]
Thanks

**Comment by motorina0** [comment]
PR merged: https://github.com/lnbits/lnbits/pull/2612
