### ISSUE TITLE
[Feature request] Paste LNURLw In Mobile Interface

### ISSUE THREAD

**Issue by pardus79** [lnbits/lnbits#2305]
There is no place to paste an LNURLw on **mobile**, to pull funds from another wallet.

On the desktop browser interface, there is a "Paste Request" button that provides a field for entering such requests. Mobile should have the same. Either as a separate button or somewhere when you click on the "receive" button at the bottom of the page.

The only other way to use a 3rd party's LNURLw on mobile is by scanning a QR. But this requires an additional computer in order to display that QR.

**Comment by prusnak** [comment]
> There is no place to paste an LNURLw on **mobile**, to pull funds from another wallet.

There is. It is available when you click on the "Send" button. 

I agree that it is not very convenient.
