### ISSUE TITLE
[Feature request] save title or ID of items sold in transaction history

### ISSUE THREAD

**Issue by moritz123321** [lnbits/lnbits#2312]
**Is your feature request related to a problem? Please describe.**
Merchants that use the tpos extension want/need an overview of the items sold in a transaction (for management and accounting)

**Describe the solution you'd like**
Add the items (title or ID) sold in a transaction to the transaction history grid and on the export to csv button.

**Describe alternatives you've considered**
none

**Comment by talvasconcelos** [comment]
The information is passed on the extra on the transaction details:

![detail](https://imgur.com/a/dVXCcGP.png)

I'll look into getting that into the CSV export also

**Comment by talvasconcelos** [comment]
Probably needs some reviewing but #2325 should fix this!

Anyway, I'll be working on a more detailed approach! For invoicing for example!
