### ISSUE TITLE
LNURLp extension not enforcing domain constraints on `successAction`

### ISSUE THREAD

**Issue by Fittiboy** [lnbits/lnbits#232]
As @Perlover discovered in Fittiboy/bitcoin-on-twitch#9, it is possible to set a `successAction` url that doesn't match the `callback` url used during the payment flow. This is not allowed according to [the spec](https://github.com/fiatjaf/lnurl-rfc/blob/master/lnurl-pay.md):
```
{
   tag: 'url'
   description: 'Thank you for your purchase. Here is your order details' // Up to 144 characters
   url: 'https://www.ln-service.com/order/<orderId>' // url domain must be the same as `callback` domain at step 3
}
```
It is enforced by at least BLW, and potentially other wallets.

Changing `success_url` to `success_path`, and appending this to the domain used during the payment flow would solve this problem.

**Comment by fiatjaf** [comment]
Can we change the spec instead?

**Comment by fiatjaf** [comment]
Alternatively we could have a default-redirect endpoint built in LNURLp that would be used as the default `success_action` URL and always redirect from that to whatever `success_url` the user have specified.

The fact that we can do this and bypass the spec means to me that that arbitrary restriction of the spec is worthless. What do you think?

**Comment by Fittiboy** [comment]
> Can we change the spec instead? :roll_eyes:

This is something I've thought about too.
I've been trying to find out why this is required by the spec in the first place, and couldn't find a strong reason. Even when enforcing matching domain names, the `successAction` url could just redirect to any other domain either way. This is in fact how I fixed Fittiboy/bitcoin-on-twitch#9.
I use an nginx reverse proxy that points some paths to a different server than LNbits, and redirects https://fitti.io/live to my Twitch stream. That fixed it the issue.

**Comment by Fittiboy** [comment]
> The fact that we can do this and bypass the spec means to me that that arbitrary restriction of the spec is worthless. What do you think?

My thoughts exactly!

**Comment by Perlover** [comment]
ping @btcontract ;-)

**Comment by btcontract** [comment]
initial reasons for this were:
- better privacy (wallet ever uses the single domain which was displayed to user and approved by user and no other domain).
- better liability (if anything goes wrong an LNURL provider can't say they did not know what was done on other domain because it's out of their control).

I see no reason to change this, that no one else follows this is unresponsible.

**Comment by Perlover** [comment]
> > The fact that we can do this and bypass the spec means to me that that arbitrary restriction of the spec is worthless. What do you think?
> 
> My thoughts exactly!

But the redirect was still from the domain that was shown to the user originally? (point #3 of specification?)
If I correctly argue - it is though bypass from the specification, but at the same time the redirect was undertaken by the initial side by owning the original domain. Right?

**Comment by Fittiboy** [comment]
> the redirect was undertaken by the initial side by owning the original domain.

This is correct, yes.
But I _do_ actually see the point now. When the spec is enforced, a user could not go to a service like https://lnbits.com and create a lnurl-pay link with a malicious `successAction` url.

**Comment by btcontract** [comment]
> If the spec is enforced, the site owner has full control over whether or not redirects are allowed.

Following redirects apparently can be disabled on client side which BLW does not do currently, but it will.

**Comment by Fittiboy** [comment]
> Following redirects apparently can be disabled on client side

That too, yes. Wallets could decide whether to issue a warning to the user if the URL is a redirect, or block it completely.
(Or just open it, which is somewhat irresponsible).

**Comment by Fittiboy** [comment]
This makes me think my originally proposed fix might be the way to go:
> Changing success_url to success_path, and appending this to the domain used during the payment flow would solve this problem.

This way, redirects are only possible when specifically allowed by the site owner.
There could even be an extension that is disabled by default (like amilk), which simply creates redirect urls (like `/redirects/api/v1/some_hash_here/ -> https://duckduckgo.com/`). Then each LNbits host can decide for themselves whether or not they want to allow their users to use redirects.
