### ISSUE TITLE
[BUG] auth/register does not return admin key

### ISSUE THREAD

**Issue by rleed** [lnbits/lnbits#2328]
**Describe the bug**
When creating a new wallet via auth/admin API, no admin key is returned. This makes it impossible to use the newly registered wallet.

**To Reproduce**
1. POST to /api/v1/auth/register with headers
                Accept: application/json
                Content-Type: application/json
and data such as:
                {"email":"","username":"username","password":"password","password_repeat":"password"}

2. Inspect the response and see that only an access token is returned, but no admin key. The access token does not give access to the existing prior generation of APIs, and there is no way to retrieve the admin key from the access token.

**Expected behavior**
The admin key for the newly created wallet should be returned.

**Desktop (please complete the following information):**

- LNbits version: 0.12.0
- Database sqlite

**Comment by motorina0** [comment]
The wallets get be fetchd using this endpoint:
```
GET http://localhost:5000/api/v1/auth
```

If the server allows `user_id_only` then the request is of this form:
```curl
curl --location 'http://localhost:5000/api/v1/auth?usr=3210165a00844a38962853c1a8e2facf'
```

or with the access token in the header:
```curl
curl --location 'http://localhost:5000/api/v1/auth?=null' \
--header 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1MjEiLCJ1c3IiOm51bGwsImVtYWlsIjpudWxsLCJleHAiOjE3NTM1MzIwOTZ9.UHp-lZ-Q4CYvemhW59p8SVbrBwuhJgXlFbtOS6c8wE0'
```
