### ISSUE TITLE
Saving wallet to localstorage, download wallet file, login system, UI

### ISSUE THREAD

**Issue by arcbtc** [lnbits/lnbits#233]
Eventually for saving wallets we want a number of options:

- Account as URL
- Save to local storage
- Download wallet file 
- Login user account
- LNURL-auth

Then in the wallet we can have a few icons for the different options:
![image](https://user-images.githubusercontent.com/33088785/123623050-ed70e600-d804-11eb-9e0b-b1252b7c9ae3.png)

On the frontpage we can have:
![image](https://user-images.githubusercontent.com/33088785/123622665-6cb1ea00-d804-11eb-91ff-156816824610.png)

In .env, the admin can delete to limit options
![image](https://user-images.githubusercontent.com/33088785/123623674-a59e8e80-d805-11eb-95c5-94f5c8cc4c69.png)

**Comment by talvasconcelos** [comment]
Login and Admin extension will bring these features.
