### ISSUE TITLE
Wallet recovery

### ISSUE THREAD

**Issue by viperperidot** [lnbits/lnbits#235]
This isn't an issue but I didn't see any other communication options to discuss lnbits, if I missed it please post here and let me know. I think a Telegram group or something would be a good thing to have, I could make one if people are interested.

Anyway I have a question about wallet recovery, if you have the seed and channel backup for your lightning node that lnbits is connected to, is that enough to recover your funds?

Thanks

**Comment by lc0des** [comment]
Telegram Group: https://t.me/lnbits
Recover: Yes, with wallet seed you can recover your btc wallet and with the channel.backup you can recover your channels. But be careful, the latest channel.backup is necessary.
