### ISSUE TITLE
[BUG] No live payment success confirmation with certain funding sources

### ISSUE THREAD

**Issue by pretyflaco** [lnbits/lnbits#2357]
**Describe the bug**
Observed with funding source OpenNodeWallet, BlinkWallet - reported to be the case as well with ZBD funding source by @bitkarrot 

**To Reproduce**

1. Go to Create invoice in LNBits Wallet and pay invoice
2. Payment settles but does not get picked up live (no payment confirmation checkmark and balance doesn't update) 

**Expected behavior**
When payment settles, invoice should indicate that it was paid and balance should update without refresh

version 0.12.2

**Comment by tlindi** [comment]
Noticed same occationally on 0.12.4 with lnd as funding source.

Sure it was on Android Chrome as UI. Can't remember where payment came from.

**Comment by motorina0** [comment]
Payment notification works fine with `BlinkWallet` now.
However it is not implemented for `OpenNodeWallet`

**Comment by bitkarrot** [comment]
@motorina0  also not implemented for `ZBDWallet`, also it appears zbd doesn't have a wss endpoint

**Comment by motorina0** [comment]
Closing the issue. There is nothing we can do if the 3rd party does not offer the API.

The LNbits user must refresh the page in order for the payment to be checked again.

**Comment by prusnak** [comment]
> Closing the issue. There is nothing we can do if the 3rd party does not offer the API.

We can still do polling, no?

Question is whether we want to poll ...

**Comment by motorina0** [comment]
Yes, we can do polling in two ways:
  1. On the funding source level. But this would make a request for each pending invoice on the server. A server with many users could potentially have thousands of pending invoices. As a result the funding source might get IP blocked.
  2. On the UI level.  If the wallet page is open then the browser can make requests at regular time intervals to update that particular wallet. This means we need a flag on the funding sources to know if they support `paid_invoices_stream` and only then poll.

Option 2 could be implemented if there is demand.
