### ISSUE TITLE
Minor issues in API documentation of lnurlp extension

### ISSUE THREAD

**Issue by cryptoteun** [lnbits/lnbits#238]
During implementation of the lnurlp extension in my app I ran into two issues in the documentation of lnurlp.

1. url isn't correct: it's stating '/api/v1/links' but it should be '/lnurlp/api/v1/links'
2. fields in create paylink fields not complete (missing comment, max, min)

**Comment by cryptoteun** [comment]
Working on a PR right now.

**Comment by arcbtc** [comment]
Merged
