### ISSUE TITLE
Extensions selection

### ISSUE THREAD

**Issue by Praexor** [lnbits/lnbits#243]
How can I delete or prevent to appear some extensions card on the lnbits UI? (extensions.html), can I delete the entire extension folder from extensions directory without broke the app? sorry I am newbie :) on LNbits. Thank you!

**Comment by talvasconcelos** [comment]
disable them in the .env file
![extension](https://i.imgur.com/39hTdKu.png)

**Comment by Praexor** [comment]
LNBITS_DISABLED_EXTENSIONS="amilk, captcha, lnticket, subdomains, withdraw" <---- Can I use this way?

**Comment by Praexor** [comment]
> disable them in the .env file
> ![extension](https://camo.githubusercontent.com/991206fdffafd60a033489d550a87adc463a23653db832e24a568339e2cada99/68747470733a2f2f692e696d6775722e636f6d2f33396854644b752e706e67)

LNBITS_DISABLED_EXTENSIONS="amilk, captcha, lnticket, subdomains, withdraw" <---- Can I use this way?

**Comment by talvasconcelos** [comment]
yes, i think that should work! I'll take a look at it in more depth. it didn't work for you?

**Comment by Praexor** [comment]
This is working fine, THANK YOU!, do you know is anybody did a login and admin extensions?

**Comment by arcbtc** [comment]
Admin extensions are right at the top of the list. The login system is also something we should be addressing soon. If you can contribute please do! All help VERY much appreciated

**Comment by arcbtc** [comment]
Op fixed
