### ISSUE TITLE
My wallets are not receiving payments

### ISSUE THREAD

**Issue by Praexor** [lnbits/lnbits#244]
I did payments  from  external wallets (Blue and Wallet of Satoshi) to pay invoice and TPOS but I am not receiving any satoshis in my lnbits wallets, all transaction still pending, It was working fine but stop suddenly, all the satoshis are in my LNPay wallet, but the lnbits UI doesn't show it. What can be happening? transactions between lnbits wallets are working fine.

**Comment by Praexor** [comment]
4 hours was necessary to complete the TXs, I received now!

**Comment by fiatjaf** [comment]
Did you set up webhooks from LNPay to your LNbits instance?

**Comment by oriolpont** [comment]
@fiatjaf what do you propose instead? It's true that check_pending_**payments**() should be watching pending payments, not pending invoices, but as things are now LNPayWallet doesn't work; it doesn't seem to get the invoice stream most of the times and you need to force it to check get_invoice_status to make it work.

Can you detail that webhooks workaround?

**Comment by fiatjaf** [comment]
It is not a workaround, it's a necessary part of the setup. It's written somewhere in the docs (can't lookup now, I'm on my phone).

**Comment by oriolpont** [comment]
@Praexor see:
![image](https://user-images.githubusercontent.com/3428488/126779563-d3abecff-0d24-494b-bcde-25d3221646dc.png)

https://lnbits.org/guide/wallets.html#lnpay

We might still want to have an alternative way of forcing periodic get_invoice_status() checks for e.g., when Lnbits is not web facing, but that'd be both less elegant and less robust
