### ISSUE TITLE
Issue 520

### ISSUE THREAD

**Issue by Cicibus** [lnbits/lnbits#2451]
What does it mean "error 520"?

I cannot make invoice or cannot pay.

Before works properly... is it because last Umbrel update?

**Comment by arbadacarbaYK** [comment]
SaaS produces 520 while Legend produces this

<img width="902" alt="Screenshot 2024-04-21 at 11 38 07" src="https://github.com/lnbits/lnbits/assets/63317640/89478e62-d3b1-45db-a954-f1c3f8653cbd">

**Comment by motorina0** [comment]
Cannot reproduce the issue.
If it still reproduces please re-open this issue with the following details:
 - LNbits version
 - funding source
 - logs if possible
