### ISSUE TITLE
[BUG] LNURLp lnaddress broken with ZBD wallet

### ISSUE THREAD

**Issue by BrunswickBTC** [lnbits/lnbits#2457]
Installation works with LND and Alby backends

**To Reproduce**

1. Set up ZBD wallet
2. Send payment from external wallet that supports lnaddress

* Wallet yields message: "unable to fetch invoice information" or "Failed to call on the given LNURL." Or other error
* Lnbits log yields: "lnbits.wallets.base.Unsupported: description_hash" and "Exception: description_hash"

- LNbits version: 0.12.5
- Database postgres

Note: could have something to do with https://github.com/lnbits/lnbits/blob/8d3b156738f5d957bed2207084f0db2ce289642c/lnbits/wallets/zbd.py#L67-L68
I'm unclear why this can't be done:
https://github.com/lnbits/lnbits/blob/8d3b156738f5d957bed2207084f0db2ce289642c/lnbits/wallets/fake.py#L67-L75

According to this (https://zbd.dev/api-reference/charges/create) there is no description_hash field, but does have a description field. the ZBD backend uses '''memo''' to fill this field. It appears the error is not coming from description_hash, but from unhashed_description in the LNURLp plugin.

https://github.com/lnbits/lnurlp/blob/18f230c611df40cbc569418d50dcb103d330cd96/lnurl.py#L89-L97

**Comment by bitkarrot** [comment]
see PR https://github.com/lnbits/lnbits/pull/2609

cc:  @BrunswickBTC

**Comment by bitkarrot** [comment]
PR merged, can we close this now? @BrunswickBTC

**Comment by BrunswickBTC** [comment]
> PR merged, can we close this now? @BrunswickBTC 

Yes, thank you!
