### ISSUE TITLE
"IP Blocker" Can not delete ip´s

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/lnbits#2471]
After entering an IP adress inside the "blocked" or "allowed" IP´s i am not able to delete them after. The "X" symbol is missing.

I already looked inside the .env file if i could delete them there but they are not saved there.

![ip](https://github.com/lnbits/lnbits/assets/106493492/8a3bab19-5356-44b6-977a-270cde5ca13b)

**Comment by arcbtc** [comment]
Nice catch. Will work on it
