### ISSUE TITLE
[BUG] User not allowed when logging in with URL. 

### ISSUE THREAD

**Issue by O-Glenn** [lnbits/lnbits#2476]
Can't log in to wallet.
I'm using URL to log in: "https://**legend**.lnbits.com/wallet?usr=xxxxx...".
When using this URL, the URL gets changed to: https://**demo**.lnbits.com/wallet?usr=xxxxx..." 
getting this error: 

![image](https://github.com/lnbits/lnbits/assets/161635560/19c48392-edc0-47ea-bded-c5f7a01180bd)

**Comment by statusquont** [comment]
+1 same issue.

I've also tried taking the 'xxxxxx' value of the usr parameter from the 'https://legend.lnbits.com/wallet?usr=xxxxx...' URL and tried to login with it on https://demo.lnbits.com/ but get back an error: "User ID does not exist. 401"

**Comment by prusnak** [comment]
Legend is gone forever

New testing server is demo.lnbits.com and users have not been migrated

**Comment by statusquont** [comment]
Understood. Is there a plan to eventually migrate the users?

**Comment by notnout** [comment]
Is there a way to get back the sats from legend?

**Comment by O-Glenn** [comment]
@prusnak Do you know if there is a plan to eventually migrate the users from Legend to demo? Or is there any other way to get back the sats from Legend?

**Comment by arcbtc** [comment]
This was a demo and testing server that should never have been using for anything in production. We had many disclaimers and warnings to this end, and reminded user repeatedly. Some people choose to ignore these warnings and used the server in production, which is a responsibility they must shoulder.

As a testing server, we tested on it, a hacker stole the funds, so we closed the server and created a new one. The new server is far more explicit to try and discourage users using in production.

PLEASE DO NOT USE THE DEMO SERVER IN PRODUCTION OR FOR FUNDS YOU ARE NOT WILLING TO USE.

We will run the server at some point with voidwallet so users can access info and for any users who were using wallets for lnurlauth, but the funds are gone. This was a demo and testing server running insecure software for testing only.

Closing as this is not an issue for the LNbits software.
