### ISSUE TITLE
[ISSUE] ERROR in core invoice payment with PHOENIXD as funding source

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/lnbits#2479]
### **Describe the Issue**
When i create an invoice and pay it i can see an error in the logs. Mention that this payment gets setteled. No error in UI.

### **To Reproduce**

1. Create an invoice with your phoenixd backed lnbits
2. pay the invoice
3. See setteled amount
4. See logs
5. See  payment received AND the ERROR output

```
INFO | XXXXXXX - "GET /api/v1/wallet HTTP/1.1" 200
May 08 01:20:03 2016-XXX poetry[2073268]: 2024-05-08 01:20:03.65 | INFO | payment-received: eb3fa50b874e41a3dcb0fb1XXXXXXXXXXXX5f4611113e4e152388b08a76e
May 08 01:20:03 2016-XXX poetry[2073268]: 2024-05-08 01:20:03.65 | INFO | > got a payment notification
May 08 01:20:04 2016-XXX poetry[2073268]: 2024-05-08 01:20:04.07 | ERROR | failed sending push notification: {"code":401,"errno":109,"error":"Unauthorized","message":"VAPID public key mismatch","more_info":"http://autopush.readthedocs.io/en/latest/http.html#error-codes"}
```

### **System:**
- - LNbits version: commit 0076a85fdb557552f51c5ec11e0f8ff8df2e17de
- - Database sqlite
- - Phoenixd barebone on my vps. No Docker.

**Comment by motorina0** [comment]
This is a push notification error (if the user did not enable it). It is not related to the actual funding source.
