### ISSUE TITLE
Legacy LNbits wallet/API integration done ~2 years ago... what happened to account?

### ISSUE THREAD

**Issue by turtlenice** [lnbits/lnbits#2482]
Hello,
I created a lightning ATM a long time ago (maybe 2 years, give or take) and had an account on lnbits with a user ID and wallet ID (I still have the URL in my code, luckily!).  I just tested the ATM and it wasn't working so after some digging, I went back to lnbits and found out that the whole site has changed.

I can't figure out how to access my old account... when I try to log in with user ID, it says this user doesn't exist.

Is there any way for me to access my old wallet/account? And are there directions somewhere for updating my code to use this new LNbits?

Thanks

**Comment by arcbtc** [comment]
You were using the demo/testing server, which was made clear with the disclaimers. The demo/testing server was hacked and is now dead.
