### ISSUE TITLE
Feature Request: Tor address generation even when on local address

### ISSUE THREAD

**Issue by BenGWeeks** [lnbits/lnbits#2507]
If you are managing your node locally, and not via Tor, you will sometimes receive errors that you need to be either on HTTPS or Tor. Umbrel (for example) does not run on HTTPS.

It would be great to access LNBits using a local address, but (optionally) generate LNUrl addresses that are Tor addresses still. Rather than LNBits assumes the address relates to the current browser address.

Workaround currently is to jump to a Tor browser for some functions, then jump back again to local address.

**Comment by prusnak** [comment]
This does not sound like an LNbits issue but like an issue with its deployment.

How do you deploy LNbits (ideally share your config)?

How does the error actually look like? Maybe post a screenshot?
