### ISSUE TITLE
LND_REST Documentation for Authentication invalid

### ISSUE THREAD

**Issue by lc0des** [lnbits/lnbits#251]
From [docs/guide/wallets.md](https://github.com/lnbits/lnbits/blob/master/docs/guide/wallets.md)

> LND (REST)
> 
>     LNBITS_BACKEND_WALLET_CLASS: LndRestWallet
>     LND_REST_ENDPOINT: ip_address
>     LND_REST_CERT: /file/path/tls.cert
>     LND_GRPC_MACAROON: /file/path/admin.macaroon
> 

LND_GRPC_MACAROON is only valid for LND_GRPC but not LND Rest, instead usage of
LND_REST_MACAROON="HEXSTRING" must be used.

**Comment by arcbtc** [comment]
Added hexstring option in desc

**Comment by lc0des** [comment]
When i was testing it, it was not working, also the variable says: LND_GRPC_MACAROON, while it should say LND_REST_MACAROON if supported.

**Comment by dni** [comment]
this is fixed
