### ISSUE TITLE
[BUG] pydantic.error_wrappers.ValidationError

### ISSUE THREAD

**Issue by HaosGames** [lnbits/lnbits#2535]
**Describe the bug**
I get the following Error after updating to 0.12.6. It get's spammed every 5 seconds in the log

```
Mai 24 11:54:37 benno lnbits[2485199]: 2024-05-24 11:54:37.37 | ERROR | exception in background task `unnamed`:
Mai 24 11:54:37 benno lnbits[2485199]: 2024-05-24 11:54:37.37 | ERROR | pydantic.error_wrappers.ValidationError: 1 validation error for Proof
Mai 24 11:54:37 benno lnbits[2485199]: Y
Mai 24 11:54:37 benno lnbits[2485199]:   none is not an allowed value (type=type_error.none.not_allowed)
Mai 24 11:54:37 benno lnbits[2485199]: 2024-05-24 11:54:37.37 | ERROR | will restart the task in 5 seconds.
```

**To Reproduce**
Update from 0.12.5 to 0.12.6 and run clightning v24.02.2 backend. 

**Expected behavior**
No Error

- LNbits version: 0.12.6
- Database sqlite,

**Comment by dni** [comment]
hotfix release 0.12.7 should fix this

**Comment by HaosGames** [comment]
I updated to 0.12.8 but this error spam is still there

**Comment by tiker** [comment]
Are you running the cashu extension?  This looks like https://github.com/lnbits/cashu/issues/69.

**Comment by HaosGames** [comment]
Yes, that must be it. Thank you
I will monitor that issue from now on
