### ISSUE TITLE
[Feature request] Link to "Copy wallet data" for backup

### ISSUE THREAD

**Issue by AxelHamburch** [lnbits/lnbits#2541]
Since the latest version of LNbits, simply saving the wallet as a favorite link in the browser is no longer sufficient to gain access to the wallet. The users have to obtain the wallet ID in a cumbersome way. All important data is available under “Export to Phone with QR Code”. However, they have to scan the QR code. For a quick backup of the wallet and ID data, a “Copy wallet data” link would be appropriate, which stores the QR code data in the clipboard for the user to save. A “Copy data link” under “My Account / Account Settings” would also be possible. This would make it much easier for users to save their wallet / ID data.

![image](https://github.com/lnbits/lnbits/assets/84231978/cb14a52f-1b2e-4347-b296-c711760c3537)

![image](https://github.com/lnbits/lnbits/assets/84231978/26f977a6-0fd7-44b1-a83c-f9ea9d322202)

**Comment by thespielplatz** [comment]
Thanks, perfect 🙌

**Comment by AxelHamburch** [comment]
🙏
