### ISSUE TITLE
[BUG]  Websockets API no longer sending data.

### ISSUE THREAD

**Issue by santyr** [lnbits/lnbits#2545]
Lnbits v 0.12.8

Updated to 0.12.8 and websockets no longer sends data.  Reproduced using the demo site wss://demo.lnbits.com/api/v1/ws/2ec7f696f0854d88aed3279cdc08a907 and a websocket tester. (https://piehost.com/websocket-tester)

Websocket connects fine, but does not send any data regarding payments.  (Now all my websocket listeners are broken)

**Comment by motorina0** [comment]
The websocket path was changed from wallet id to wallet `inkey`.
Wallet ID is public (can be seen in the URL) so it is considered unsafe (someone could listen to your wallet if it knows its ID)

https://github.com/lnbits/lnbits/pull/2516/files#r1615868255

Please try to use the wallet `inkey` and let me know if it works.

**Comment by ray-bun** [comment]
> The websocket path was changed from wallet id to wallet `inkey`. Wallet ID is public (can be seen in the URL) so it is considered unsafe (someone could listen to your wallet if it knows its ID)
> 
> https://github.com/lnbits/lnbits/pull/2516/files#r1615868255
> 
> Please try to use the wallet `inkey` and let me know if it works.

Are you able to give me an example to how I could use websocket to listen to wallet activities(payment sent and payment received) please? What do i need to send in {data}?

**Comment by motorina0** [comment]
On the right side of your wallet you can find the invoice key (`inkey`). Use that one for the wrbsocket connection instead of the wallet ID.

![image](https://github.com/lnbits/lnbits/assets/2951406/31bfc55b-0e06-456f-9964-b7e3fec502c7)


![image](https://github.com/lnbits/lnbits/assets/2951406/5940965c-d99d-4023-b7b6-eef7703506ab)

**Comment by santyr** [comment]
Thanks for the update.  The invoice key works great.

**Comment by santyr** [comment]
Here's one of the ways I'm using it:

`#!/usr/bin/env python3
import asyncio
import websockets
import json
import logging
import os
import httpx
import time
from typing import Dict, Any
from dataclasses import dataclass
from asyncio import Task

logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(name)s - %(levelname)s - %(message)s')
logger = logging.getLogger(__name__)

@dataclass
class Config:
    WS_CYBERHERD: str
    WS_HERD: str
    ENDPOINT_URL: str
    IGNORE_NPUBS: list[str]

def load_config() -> Config:
    return Config(
        WS_CYBERHERD=os.getenv('WS_CYBERHERD', "wss://lnb.bolverker.com/api/v1/ws/"), # add invoice key
        WS_HERD="wss://lnb.bolverker.com/api/v1/ws/", # add invoice key
        ENDPOINT_URL="http://127.0.0.1:8090/messages/cyberherd_treats",
        IGNORE_NPUBS=["Sat", "Unknown"]
    )

config = load_config()

class WebSocketClient:
    def __init__(self, uri: str, identifier: str):
        self.uri = uri
        self.identifier = identifier
        self.websocket = None
        self.http_client = httpx.AsyncClient(http2=True, limits=httpx.Limits(max_keepalive_connections=10))
        self.reconnect_task: Task | None = None

    async def connect(self):
        backoff = 1
        max_backoff = 60
        while True:
            try:
                self.websocket = await websockets.connect(self.uri)
                logger.info(f"Connected to WebSocket ({self.identifier}): {self.uri}")
                return
            except (websockets.exceptions.ConnectionClosedError, websockets.exceptions.InvalidURI) as e:
                logger.error(f"WebSocket connection error ({self.identifier}): {e}")
            except Exception as e:
                logger.error(f"Unexpected error during connection ({self.identifier}): {e}")
            
            logger.info(f"Reconnecting in {backoff} seconds ({self.identifier})...")
            await asyncio.sleep(backoff)
            backoff = min(backoff * 2, max_backoff)

    async def send_to_endpoint(self, pubkey: str, amount: float):
        payload = {"pubkey": pubkey, "amount": amount}
        try:
            response = await self.http_client.post(config.ENDPOINT_URL, json=payload, timeout=10.0)
            response.raise_for_status()
            logger.info(f"Sent to endpoint: {payload}")
        except httpx.HTTPError as exc:
            logger.error(f"Error sending to endpoint: {exc}")

    def extract_pubkey(self, memo: str) -> str | None:
        words = memo.split()
        if len(words) > 0 and words[-1] not in config.IGNORE_NPUBS:
            return words[-1]
        return None

    async def process_herd_message(self, data: Dict[str, Any]):
        if "wallet_balance" in data:
            wallet_balance = data["wallet_balance"]
            amount = data["payment"]["amount"] / 1000
            wallet_fiat_rate = data["payment"]["extra"]["wallet_fiat_rate"]
            logger.info(f"[Herd] Wallet balance: {wallet_balance}, Amount: {amount}, Wallet Fiat Rate: {wallet_fiat_rate}")

    async def process_cyberherd_message(self, data: Dict[str, Any]):
        if "payment" in data and data["payment"].get("amount", 0) < 0:
            amount = abs(data["payment"]["amount"]) / 1000
            memo = data["payment"]["memo"]
            pubkey = self.extract_pubkey(memo)
            if pubkey:
                await self.send_to_endpoint(pubkey, amount)

    async def process_messages(self):
        while True:
            try:
                message = await self.websocket.recv()
                data = json.loads(message)
                
                if self.identifier == 'herd':
                    await self.process_herd_message(data)
                elif self.identifier == 'cyberherd':
                    await self.process_cyberherd_message(data)
            except websockets.exceptions.ConnectionClosed:
                logger.warning(f"WebSocket connection closed ({self.identifier}). Reconnecting...")
                break
            except json.JSONDecodeError:
                logger.error(f"Failed to decode JSON message ({self.identifier})")
            except Exception as e:
                logger.error(f"Error processing message ({self.identifier}): {e}")

    async def run(self):
        while True:
            await self.connect()
            await self.process_messages()

    async def start(self):
        self.reconnect_task = asyncio.create_task(self.run())

    async def stop(self):
        if self.reconnect_task:
            self.reconnect_task.cancel()
            try:
                await self.reconnect_task
            except asyncio.CancelledError:
                pass
        if self.websocket:
            await self.websocket.close()
        await self.http_client.aclose()

async def main():
    clients = [
        WebSocketClient(config.WS_CYBERHERD, 'cyberherd'),
        WebSocketClient(config.WS_HERD, 'herd')
    ]

    for client in clients:
        await client.start()

    try:
        await asyncio.gather(*(client.reconnect_task for client in clients))
    except asyncio.CancelledError:
        logger.info("Main task cancelled. Shutting down...")
    finally:
        await asyncio.gather(*(client.stop() for client in clients))

if __name__ == "__main__":
    try:
        asyncio.run(main())
    except KeyboardInterrupt:
        logger.info("WebSocket listener stopped.")`

**Comment by santyr** [comment]
An html / javascript example:

`<!DOCTYPE html>
<html>
<head>
    <title>js overlay</title>
    <meta charset="UTF-8">
    <link rel="icon" href="data:," type="image/x-icon">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/gsap/3.10.4/gsap.min.js"></script>
    <style>
        /* Existing CSS */
        #container {
            position: absolute;
            width: 1280px;
            height: 720px;
            margin: auto;
            top: 0;
            left: 0;
        }
        #qr-code {
            position: absolute;
            top: 0;
            right: 0;
            background-color: white;
            width: 120px;
            height: 120px;
            border-top-left-radius: 12px;
            border-top-right-radius: 12px;
            z-index: 3;
        }
        #sats_left {
            position: absolute;
            top: 117px;
            right: 0;
            width: 120px;
            padding-bottom: 6px;
            text-align: center;
            font-size: 12px;
            font-weight: bold;
            font-family: 'Arial', sans-serif;
            background-color: white;
            border-bottom-left-radius: 12px;
            border-bottom-right-radius: 12px;
            z-index: 3;
        }
        #content {
            position: absolute;
            bottom: 0;
            left: 0;
            width: 100%;
        }
        #progress-container {
            width: 1278px;
            height: 11px;
            background-color: #ccc;
            border-radius: 7px;
            position: relative;
            margin: 0 auto;
            z-index: 2;
        }
        #progress-fill {
            height: 100%;
            background-color: #e6b800;
            border-radius: 7px;
            width: 0%; /* Ensure initial width is 0 */
        }
        p {
            font-size: 18px;
        }
        #goal-banner {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            background-color: #e6b800;
            padding: 10px;
            font-size: 24px;
            font-weight: bold;
            border: 2px solid black;
            border-radius: 12px;
        }
        .scrolling-comment {
            font-size: 12px;
            font-family: 'Arial', sans-serif;
            font-weight: bold;
            color: #FFF;
            padding: 2px;
            position: absolute;
            white-space: nowrap;
            bottom: 0px;
            right: 0;
            z-index: 1;
        }
        #progress-text {
            position: absolute;
            top: 0px; /* Adjusted to be above the progress bar */
            width: 100%;
            text-align: center;
            font-size: 9px;
            font-family: 'Arial', sans-serif;
            font-weight: bold;
            line-height: 11px;
            color: #000;
            z-index: 3;
        }
        #goal-achieved-layer {
            position: absolute;
            top: 0;
            left: 0;
            width: 100%;
            height: 100%;
            background-color: #e6b800;
            opacity: 0.6;
            z-index: 1;
        }
        #feeder-triggered {
            position: absolute;
            top: 50%;
            left: 50%;
            transform: translate(-50%, -50%);
            font-size: 32px;
            font-weight: bold;
            font-family: 'Arial', sans-serif;
            color: #FFF;
            background-color: rgba(0, 0, 0, 0.6);
            padding: 10px;
            border-radius: 12px;
            z-index: 2;
        }
        #time-temperature-container {
            position: absolute;
            bottom: 0px;
            left: 0px;
            display: block;
            align-items: center;
            color: white;
            background-color: #e33502;
            border-radius: 7px;
            padding: 2px;
            padding-left: 14px;
            font-size: 12px;
            font-weight: bold;
            font-family: 'Arial', sans-serif;
            z-index: 2;
        }
        #current-time, #current-temperature {
            display: inline-block;
            margin-right: 10px;
        }
        #bottom-container {
            background-color: #e33502;
            padding: 4px;
            position: absolute;
            bottom: 0;
            left: 0;
            margin: auto;
            height: 26px;
            width: 1281px;
            z-index: 0;
        }
        @keyframes scroll {
            0% {
                transform: translateX(0);
            }
            100% {
                transform: translateX(calc(-100% - 1280px));
            }
        }
        .scroll-animation {
            animation: scroll linear forwards;
        }

        /* New CSS for Horizontal Accordion */
        #accordion-container {
            position: absolute;
            top: 5px;
            left: 5px;
            bottom: 5px;
            background-color: #e33502;
            display: flex;
            overflow: hidden; /* Hide overflow to prevent scroll bars */
            z-index: 10;
            opacity: 0; /* Initially hidden */
            transform: translateX(-100%); /* Initially off-screen to the left */
        }
        .accordion-item {
            margin-right: 5px;
            background-color: #e33502;
            width: 136px;
            height: 136px; /* Fixed size */
            position: relative; /* Add relative positioning */
        }
        .accordion-content {
            background-color: #e33502;
            height: 100%; /* Adjust height to fill the container */
            display: flex; /* Use flexbox for layout */
            flex-direction: column; /* Arrange items in a column */
            justify-content: flex-end; /* Align items at the bottom */
            opacity: 0; /* Hide opacity initially */
        }
        .accordion-content img {
            height: 120px;
            width: 120px;
            display: block;
            margin: auto;
        }
    </style>
</head>
<body>
<div id="container">
    <div id="goal-achieved-layer" style="display: none;"></div>
    <div id="feeder-triggered" style="display: none;">Feeder Triggered</div>
    <div id="qr-code">
        <img src="https://lnb.bolverker.com/api/v1/qrcode/LNURL1DP68GURN8GHJ7MRWVGHXYMMVWEJHY6M9WGHXXMMD9AKXUATJD3CZ7M240PGHGMCN94Q2E" width='120' height='120' style="border-radius: 12px;">
        <img id="lightning-img" src="./images/lightninggoatslogo1.png" width='125' height='125' style="border-radius: 12px; display: none;">
    </div>
    <div id="sats_left"></div>
    <div id="content">
        <div id="bottom-container">
            <div id="progress-container">
                <div id="progress-fill"></div>
                <div id="progress-text"></div>
            </div>
            <div id="time-temperature-container">
                <div id="current-time"></div>
                <div id="current-temperature"></div>
            </div>
            <div id="scrolling-comment"></div>
        </div>    
    </div>
    
    <div id="accordion-container" style="display: none;"></div>
</div>

<script>
    let balance = 0;
    let goal = 0;
    let lastSuccessfulGoal = 0;
    let lastSuccessfulBalance = 0;
    let goalAchieved = false;
    let messageQueue = [];
    let isScrolling = false;
    let accordionTimeout = null;
    const reconnectInterval = 30000;
    const bottomContainer = document.getElementById('bottom-container');

    // Goat information
    const goats = {
        "Newton": { img: "images/newton.png" },
        "Nova": { img: "images/nova.png" },
        "Cosmo": { img: "images/cosmo.png" },
        "Dexter": { img: "images/dexter.png" },
        "Rowan": { img: "images/rowan.png" }
    };

    function fetchConversionRate() {
        return fetch('https://lightning-goats.com/convert/0.01')
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! status: ${response.status}`);
                }
                return response.text();
            })
            .catch(error => {
                console.error('Error fetching conversion rate:', error);
            });
    }

    function fetchAndDisplayMessages(info = false) {
        let url = "https://lightning-goats.com/messages";
        if (info === true) {
            url += "/info";
        }

        fetch(url)
            .then(response => response.json())
            .then(data => {
                if (Array.isArray(data)) {
                    data.forEach(message => {
                        addMessageToQueue(message.content);
                    });
                    resetAllMessages(); // Reset messages after adding to queue
                } else {
                    console.log("Unexpected data format received:", data);
                }
            })
            .catch(error => {
                console.log("Error fetching messages: ", error);
            });
    }

    function resetAllMessages() {
        return fetch('https://lightning-goats.com/messages/reset')
            .then(response => {
                if (!response.ok) {
                    throw new Error(`HTTP error! status: ${response.status}`);
                }
                return response.text();
            })
            .catch(error => {
                console.error('Error resetting messages:', error);
            });
    }

    function periodicallyUpdate() {
        checkFeederStatus().then(isFeederOn => {
            if (!isFeederOn) {
                Promise.all([fetchBalance(), fetchGoal()])
                    .then(() => {
                        updateSatsLeftText();
                        updateProgressBar();

                        if (Math.random() < 0.1) {
                            fetchAndDisplayMessages(true);
                        }
                    })
                    .catch(error => {
                        console.log("Error updating sats left and goal: ", error);
                    });
            }
        });
        fetchTemperature();
    }

    function checkFeederStatus() {
        return fetch('https://lightning-goats.com/feeder_status')
            .then(response => response.text())
            .then(isFeederOn => {
                const feederStatus = isFeederOn.trim() === 'true';
                const satsLeftElem = document.getElementById('sats_left');
                if (feederStatus) {
                    satsLeftElem.innerText = "Feeder paused";
                }
                return feederStatus;
            })
            .catch(error => {
                console.error('Failed to fetch feeder status:', error);
                document.getElementById('sats_left').innerText = "Status error! Check connection.";
                return false;
            });
    }

    function initWebSocket() {
        const ws = new WebSocket('wss://lnb.bolverker.com/api/v1/ws/036ad4bb0dcb4b8c952230ab7b47ea52');

        ws.onopen = function() {
            console.log("WebSocket connection opened.");
        };

        ws.onerror = function(error) {
            console.log("WebSocket connection error: ", error);
            setTimeout(initWebSocket, reconnectInterval);
        };

ws.onmessage = function(event) {
    console.log("Payment received event: ", event.data);
    const data = JSON.parse(event.data);

    checkFeederStatus().then(isFeederOn => {
        if (!isFeederOn) {
            const receivedAmount = Math.round(data.payment.amount / 1000);

            if (data.payment.checking_id && data.payment.checking_id.startsWith("internal")) {
                setTimeout(() => {
                    updateProgressBar();
                    updateSatsLeftText();
                }, 1500);
                return;
            }

            fetchBalance().then(() => {
                const currentSatsLeft = Math.round(goal - balance);

                if (receivedAmount > 0) {
                    updateSatsLeftElem(receivedAmount, currentSatsLeft, true);
                    toggleQRCodeImage(); // Call the new function here

                    updateProgressBar();

                    fetchConversionRate().then(limit => {
                        setTimeout(() => {
                            updateSatsLeftElem(receivedAmount, currentSatsLeft, false);
                        }, 2000);

                        fetchAndDisplayMessages(); // Fetch messages when payment is received
                    }).catch(error => {
                        console.error('Error fetching conversion rate:', error);
                    });
                }
            }).catch(error => {
                console.error('Error fetching balance:', error);
            });
        }
    });
};


        ws.onclose = function() {
            console.log("WebSocket connection closed. Reconnecting...");
            setTimeout(initWebSocket, reconnectInterval);
        };
    }

    document.addEventListener('DOMContentLoaded', function() {
        Promise.all([fetchGoal(), fetchBalance()])
            .then(() => {
                updateProgressBar();
                updateSatsLeftText();
            })
            .catch(error => {
                console.log("An error occurred:", error);
            });

        initWebSocket();  // Initialize the WebSocket connection
        const updateInterval = 30000;
        setInterval(periodicallyUpdate, updateInterval);
        setInterval(updateCurrentTime, 1000);
        setInterval(checkFeederStatus, 1000);
        fetchTemperature();
        setInterval(fetchTemperature, updateInterval);
        fetchAndDisplayMessages(); // Fetch messages initially
        setInterval(fetchAndDisplayMessages, 10000);  // Fetch messages every 10 seconds
    });

    function fetchGoal() {
        return new Promise((resolve, reject) => {
            fetch("https://lightning-goats.com/trigger_amount")
                .then(response => response.json())
                .then(data => {
                    const newGoal = parseFloat(data.trigger_amount);
                    if (!isNaN(newGoal)) {
                        lastSuccessfulGoal = newGoal;
                        goal = newGoal;
                        resolve();
                    } else {
                        reject(new Error("Invalid trigger amount received"));
                        console.error("Invalid trigger amount received");
                        goal = lastSuccessfulGoal;
                    }
                })
                .catch(error => {
                    reject(new Error("Failed to fetch trigger amount"));
                    console.error('Error fetching goal:', error);
                    goal = lastSuccessfulGoal;
                });
        });
    }

    function fetchBalance() {
        return new Promise((resolve, reject) => {
            fetch("https://lightning-goats.com/balance")
                .then(response => response.text())
                .then(data => {
                    const newBalance = parseFloat(data);
                    if (!isNaN(newBalance)) {
                        lastSuccessfulBalance = Math.round(newBalance / 1000);
                        balance = Math.round(newBalance / 1000);
                        resolve();
                    } else {
                        reject(new Error("Invalid balance received"));
                        console.error("Invalid balance received");
                        balance = lastSuccessfulBalance;
                    }
                })
                .catch(error => {
                    reject(new Error("Failed to fetch balance"));
                    console.error('Error fetching balance:', error);
                    balance = lastSuccessfulBalance;
                });
        });
    }

    function updateSatsLeftElem(receivedAmount, currentSatsLeft, toggle) {
        const satsLeftElem = document.getElementById('sats_left');
        if (toggle) {
            satsLeftElem.innerText = `${receivedAmount} sats received`;
        } else {
            if (currentSatsLeft > 0) {
                satsLeftElem.innerText = `${currentSatsLeft} sats to go`;
            }
        }
    }

    function updateSatsLeftText() {
        let satsLeft = Math.round(Math.max(goal - balance, 0));
        if (satsLeft === 0) {
            if (lastSuccessfulBalance > 0 && lastSuccessfulGoal > 0) {
                satsLeft = Math.round(Math.max(lastSuccessfulGoal - lastSuccessfulBalance, 0));
            }
        }
        document.getElementById('sats_left').innerText = `${satsLeft} sats to go`;
    }

    function updateProgressBar() {
        if (goal === 0) {
            return;
        }

        const progress = Math.min(Math.max((balance / goal) * 100, 0), 100);
        gsap.to("#progress-fill", { width: `${progress}%`, duration: 1 });
        document.getElementById('progress-text').innerText = `${Math.round(progress)}%`;

        if (progress >= 100 && !goalAchieved) {
            goalAchieved = true;

            gsap.to("#goal-achieved-layer", { display: 'block', opacity: 0.7, duration: 0.25 });
            gsap.to("#feeder-triggered", { display: 'block', opacity: 1, duration: 0.5 });

            setTimeout(() => {
                gsap.to("#goal-achieved-layer", { display: 'none', opacity: 0, duration: 0.5 });
                gsap.to("#feeder-triggered", { display: 'none', opacity: 0, duration: 0.5 });
            }, 500);

            setTimeout(() => {
                goalAchieved = false;
            }, 3000);
        }
    }

    function fetchTemperature() {
        fetch('https://lightning-goats.com/get_received_data')
            .then(response => response.json())
            .then(data => {
                if (data && data.AmbientWeatherWS2902A_WeatherDataWs2902a_Temperature) {
                    let temperature = data.AmbientWeatherWS2902A_WeatherDataWs2902a_Temperature.toString();
                    document.getElementById('current-temperature').innerText = `${temperature}°F`;
                } else {
                    console.error('Invalid temperature data received:', data);
                }
            })
            .catch(error => {
                console.error('Error fetching temperature:', error);
            });
    }

    function updateCurrentTime() {
        const now = new Date();
        const formattedTime = now.toLocaleTimeString();
        document.getElementById('current-time').innerText = `${formattedTime}`;
    }

    function addMessageToQueue(messageText) {
        messageQueue.push(messageText);
        if (!isScrolling) {
            displayNextMessage();
        }
    }

    function displayNextMessage() {
        if (messageQueue.length > 0 && !isScrolling) {
            const messageText = messageQueue.shift();
            addScrollingComment(messageText);
        }
    }

    function addScrollingComment(commentText) {
        if (isScrolling) {
            return;
        }

        isScrolling = true;
        const commentDiv = document.createElement('div');
        commentDiv.className = 'scrolling-comment';
        commentDiv.innerText = commentText;

        const bottomContainer = document.getElementById('bottom-container');
        bottomContainer.appendChild(commentDiv);

        commentDiv.style.right = `-${commentDiv.offsetWidth}px`;

        const commentWidth = commentDiv.offsetWidth;
        const containerWidth = bottomContainer.offsetWidth;
        const totalTranslation = commentWidth + containerWidth;

        const scrollSpeed = 80;
        const scrollDuration = totalTranslation / scrollSpeed;

        // Show accordion while message scrolls
        const hasGoatNames = checkForGoatNames(commentText);

        gsap.to(commentDiv, {
            x: -totalTranslation,
            duration: scrollDuration,
            ease: "linear",
            onComplete: () => {
                bottomContainer.removeChild(commentDiv);
                isScrolling = false;
                if (messageQueue.length > 0) {
                    displayNextMessage();
                }
                if (!hasGoatNames && accordionTimeout === null) {
                    gsap.to("#accordion-container", {
                        x: '-100%',
                        opacity: 0,
                        duration: 1,
                        onComplete: () => {
                            gsap.set("#accordion-container", { display: 'none' });
                        }
                    }); // Retract accordion when scrolling ends
                }
            }
        });
    }
    
    function toggleQRCodeImage() {
    const qrCode = document.querySelector('#qr-code img:first-child');
    const lightningImg = document.getElementById('lightning-img');
    
    // Hide the QR code and show the lightning image
    gsap.to(qrCode, { duration: 0.5, opacity: 0, onComplete: () => {
        qrCode.style.display = 'none';
        lightningImg.style.display = 'block';
        gsap.to(lightningImg, { duration: 0.5, opacity: 1 });
    }});

    // Hide the lightning image and show the QR code after 2 seconds
    setTimeout(() => {
        gsap.to(lightningImg, { duration: 0.5, opacity: 0, onComplete: () => {
            lightningImg.style.display = 'none';
            qrCode.style.display = 'block';
            gsap.to(qrCode, { duration: 0.5, opacity: 1 });
        }});
    }, 2000);
}

function updateTextWithGSAP(element, newText, duration = 0.5) {
    gsap.to(element, {
        duration: duration / 2,
        opacity: 0,
        onComplete: () => {
            element.innerText = newText;
            gsap.to(element, { duration: duration / 2, opacity: 1 });
        }
    });
}


    function checkForGoatNames(messageText) {
        const goatNames = Object.keys(goats);
        const matchedGoats = [];

        // Extract the order of goat names as they appear in the message
        goatNames.forEach(name => {
            if (messageText.includes(name)) {
                const index = messageText.indexOf(name);
                matchedGoats.push({ name, index });
            }
        });

        // Sort the matched goats based on their order in the message
        matchedGoats.sort((a, b) => a.index - b.index);

        const accordionContainer = document.getElementById('accordion-container');
        accordionContainer.innerHTML = ""; // Clear previous content

        if (matchedGoats.length > 0) {
            matchedGoats.forEach(({ name }) => {
                const goat = goats[name];
                const item = document.createElement('div');
                item.className = 'accordion-item';

                const content = document.createElement('div');
                content.className = 'accordion-content';

                const img = document.createElement('img');
                img.src = goat.img;
                img.alt = name;

                content.appendChild(img);
                item.appendChild(content);

                accordionContainer.appendChild(item);

                // Only change opacity of the content
                gsap.to(content, { opacity: 1, duration: 1 }); // Slower animation
            });

            // GSAP animation for sliding in the accordion container from the left
            gsap.set(accordionContainer, { display: 'flex', x: '-100%' });
            const containerWidth = accordionContainer.scrollWidth;
            gsap.to(accordionContainer, { x: 0, opacity: 1, duration: 1, width: containerWidth });

            // Clear any previous accordion timeout
            if (accordionTimeout !== null) {
                clearTimeout(accordionTimeout);
                accordionTimeout = null;
            }

            // Ensure accordion stays visible for a fixed duration
            accordionTimeout = setTimeout(() => {
                gsap.to(accordionContainer, {
                    x: '-100%',
                    opacity: 0,
                    duration: 1,
                    onComplete: () => {
                        gsap.set(accordionContainer, { display: 'none' });
                    }
                });
                accordionTimeout = null;
            }, 15000); // Duration set to 15 seconds
            return true;
        }
        return false;
    }

</script>
</body>
</html>
`
