### ISSUE TITLE
[BUG] LNURL Device LNURLw doesn't work in 0.12.8

### ISSUE THREAD

**Issue by f321x** [lnbits/lnbits#2550]
**Describe the bug**
When using a LNBits instance in Version 0.12.8 the LNURLw links generated by Devices using an LNURL Device String (e.g. offline ATM) are not working properly. When scanning them with a wallet they return the correct information (amount, callback url etc.) but when trying to redeem them the LNBits backend returns that the lnurlw is already redeemed. In the LNBits interface they are shown as pending for withdrawl. 
This is reproducible on my own instance and on the lnbits demo instance. Downgrading to 0.12.7 fixed the issue for me. I was using the newest version (0.6.5) of the LNURLDevice extension.

**To Reproduce**

1. Install LNBits 0.12.8
2. Activate LNURLDevice Extension
3. Load created LNURLDevice ATM string in compatible ATM
4. Generate LNURLw url on the ATM
5. Scan with any Lightning Wallet
6. See it not working

**Expected behavior**
When requesting the LNURLw the LNBits backend shouldnt mark it as redeemed before it has in fact been redeemed.

**Desktop (please complete the following information):**

- LNbits version: 0.12.8
- Database: sqlite
- poetry on fedora

**Additional context**
I made a tool to generate LNURLw codes from the LNURLDevice string without building an ATM first. Nearly done but there is still some bug with HMAC i couldn't fix yet: https://github.com/f321x/PoS-tester 
This could be helpful debugging this issue.

**Comment by Perlover** [comment]
I can definitely refute that it doesn't work in version 0.12.8!

Until today I had version 0.12.8.

And just yesterday I showed kids a working Bloskomat that uses LNURLw. It is connected to my own LNBits.

I also have a fork of the **tip-cards** project and it is also connected to LNBits 0.12.8 and has always worked consistently - funds can be withdrawn. That project also uses LNURLw on 0.12.8.

The problem is somewhere on your side, IMHO.

**Comment by f321x** [comment]
Ok weird, downgrading to 0.12.7 immediately fixed the issue for me. Maybe it's related to some settings or the backend (I use Alby).

**Comment by f321x** [comment]
Seems to be fixed in 12.10, works fine now after updating to 12.10 and updating the LNURLw extension

**Comment by f321x** [comment]
Apparently the bug is not fixed for everyone with 0.12.10, seems to work with some setups while not working on others.
@AxelHamburch

**Comment by AxelHamburch** [comment]
Thanks for reopening, I think I have found the error. I was able to fix the error by installing the Withdraw Links extension in addition to the LNURLDevice extension. No idea why, but it works with it.

look here: https://github.com/lnbits/lnurldevice/issues/49#issuecomment-2302738252
