### ISSUE TITLE
[BUG] (!) The Toggle Admin switch for user is enabled again and again after restarting LNBits.

### ISSUE THREAD

**Issue by Perlover** [lnbits/lnbits#2598]
**Describe the bug**

Once, being an admin, I decided to make a "Toggle Admin" button for a regular user (also myself). After that I disabled that user. But the most annoying thing is that the toggle is enabled again and again by myself for this user after every restart of LNBits. 

This is very dangerous, because if admin makes a mistake and enables some third-party user as admin, that user will become admin of the whole server for life. **Even worse, there is no warning when this option is enabled**, which only exacerbates the problem of human error.

**To Reproduce**

1. Go to admin login
2. Click on 'Users' menu item in left panel
3. Click 3rd button "Togle Admin" by any user (better by your own non-admin user) and check that new admin user works.
4. Restart LNBits
5. You will see enabled again the "Toggle Admin" button for this user. He will have admin privileges again.

**Expected behavior**

If I disable a user as admin, it should be a regular user all the time regardless of rebooting!

**Desktop (please complete the following information):**

- LNbits version: 0.12.10
- Database sqlite

**Additional context**

**We should be sure to add an alert with the user's name or ID that will show up when we click on the "Toggle Admin" button to enable the user!**

Without this warning, it is enough for the admin to miss the mouse and the consequences will be fatal! (**another user will be able to withdraw all the node's funds and generally do whatever he wants!**)

**Comment by Perlover** [comment]
Maybe this bug weaves in the fact that this was done just in case a real admin accidentally turns himself off as an adinistrator, so that after a restart he can restore himself as an admin again. But if that's the case - clearly it should be solved in a different way!

**Comment by dni** [comment]
that was a bad one :) thanks for reporting!  it only saved when you added one :facepalm:
