### ISSUE TITLE
[BUG] VoidWallet selected if started at the same time than LND

### ISSUE THREAD

**Issue by JaviLib** [lnbits/lnbits#2621]
**Describe the bug**
Because I have a LND node with dozens of channels, it takes several minutes to start. As a consecuence, LNBits timeouts and VoidWallet gets selected if both LNBits and LND are started at the same time.

**To Reproduce**
Delay the aperture of LND somehow, and LNBits will select VoidWallet.

**Expected behavior**
Constantly check that LND is available and change from VoidWallet to LND rest as soon as LND is available. Do not ever stop trying.

**Comment by motorina0** [comment]
There is an [environment setting](https://github.com/lnbits/lnbits/blob/dev/.env.example#L37-L38):

```props
# How many times to retry connectiong to the Funding Source before defaulting to the VoidWallet
# FUNDING_SOURCE_MAX_RETRIES=4
```



Setting this to a higher value should solve your problem.
Note that the wait time increases exponentially and not linearly.

**Comment by JaviLib** [comment]
Thanks, I have selected `LNBITS_ADMIN_UI=true`, will that take effect?

**Comment by motorina0** [comment]
> Thanks, I have selected `LNBITS_ADMIN_UI=true`, will that take effect?

yes

**Comment by prusnak** [comment]
Also, you could configure your systemd service file to not start LNbits before LND is started:

```
[Unit]
Description=LNbits
Wants=lnd.service
After=lnd.service

...
```
