### ISSUE TITLE
[BUG] Incorrect amount conversion for unit `msat` POST `/api/v1/payments`

### ISSUE THREAD

**Issue by steepdawn974** [lnbits/lnbits#2642]
**Describe the bug**
When specifying the unit `msat` in the Create Invoice POST API call the converted sat amount it inorrect. It divides the `amount` by 100, instead of 1000.

**To Reproduce**
1. Run `curl -X POST https://<your_domain>/api/v1/payments -d '{"out": false, "amount": 10000, "unit": "msat",  "memo": "test api create"}' -H "X-Api-Key: <your_invoice_key>" -H "Content-type: application/json"` 
2. Scan the resulting BOLT11 invoice with any wallet
3. The payable amount is 100sat, but should be 10sats

**Expected behavior**
- When unit == msat, then `amount` should be divided by 1000
- If `msat` is not a supported Unit, then it should throw an error. 
- Also, the api docs https://demo.lnbits.com/docs#/Payments/api_payments_create_api_v1_payments_post should list what are supported values for `unit`

**Environment**
- LNbits version: LNbits version: 0.12.9 (7d1e22c7de7e628c637938b8420fdc6dd8e98026)
- Database: sqlite
- env: https://github.com/steepdawn974/lnbits-phoenixd/blob/main/lnbits/env.txt

**Comment by steepdawn974** [comment]
Ok, apparently it accepts any string as `unit` even garbage, and then by default divides by 100.

```
curl -X POST https://<your_domain>/api/v1/payments -d '{"out": false, "amount": 1000, "unit": "idonotexist",  "memo": "test api create"}' -H "X-Api-Key: <your_invoice_key>" -H "Content-type: application/json"
```

**Comment by dethos** [comment]
This should be fixed in the `dev` branch.
