### ISSUE TITLE
[BUG] Deactivating an extension for users disables it for Super User

### ISSUE THREAD

**Issue by pycanis** [lnbits/lnbits#2659]
Just started using LNbits so maybe I'm not understanding the feature well.

**To Reproduce**

https://github.com/user-attachments/assets/34080f72-86f8-4b69-be56-8aa1b3ba8f5c

**Expected behavior**
The extension remains enabled after deactivation for users.

**Desktop (please complete the following information):**

- LNbits version: 0.12.10
- Database sqlite

I'm open to attempting to fix the bug, just need a confirmation I'm not misunderstanding something and it's indeed an issue.

**Comment by motorina0** [comment]
**Deactivate** - reserved for admins, it deactivates the extension without un-installing it. This means it is deactivated for users too.

**Enable** - any user can enable or disable an extension for its own use.

If you want an extension to be accessible only by admins then you can
 - go to Server > Server (tab)
 - make the extension admin only
![image](https://github.com/user-attachments/assets/7c757112-e7de-4983-8fec-71be663e9eb3)
