### ISSUE TITLE
[BUG] Unused packages "bitstring" and "bitarray"?

### ISSUE THREAD

**Issue by helpau** [lnbits/lnbits#2679]
1. Go to repo search
2. Find "bitstring"
3. See no entries of [bitstring](https://github.com/search?q=repo%3Alnbits%2Flnbits+bitstring&type=code)

**Expected behavior**
Usages of package in .py files

**Comment by prusnak** [comment]
bitstring is a dependency of bolt11
bitarray is a dependency of bitstring
