### ISSUE TITLE
[BUG] Rephrase "Get user wallet" to "Get user wallets" in API

### ISSUE THREAD

**Issue by BenGWeeks** [lnbits/lnbits#2689]
**Describe the bug**
Minor: Rephrase the "Get user wallet" to "Get user wallets" to be clear it is returning an array

**Screenshots**

![image](https://github.com/user-attachments/assets/acd8daec-c4de-4389-8f85-929806cc0018)

Additional context

LNbits version: 0.12.10

**Comment by talvasconcelos** [comment]
usermanager is deprecated for v1
