### ISSUE TITLE
[BUG] Unable to delete wallet (created via API) in User Manager

### ISSUE THREAD

**Issue by BenGWeeks** [lnbits/lnbits#2692]
**Describe the bug**
When trying to delete a wallet that was created using the API, we get `none is not an allowed value` although the wallet does seem to get deleted.

![image](https://github.com/user-attachments/assets/f7e4bce1-d48b-459a-9c98-c45c6a43a1b9)

In the above example, I was deleting wallet `86f89a1a666047339048014f3287e825`. Calling `/usermanager/api/v1/wallets` returns the following properties for this wallet:

```
    {
        "id": "86f89a1a666047339048014f3287e825",
        "admin": "66eea1dbbec24deea5acd980efd01b0b",
        "name": "Private",
        "user": "56b310d0539841c29f2c190fc4a341d0",
        "adminkey": "913d71be04ea461b8cda560f42b07efa",
        "inkey": "67e388bfdf86430fbcc792846a6d8ff8"
    }
```

**To Reproduce**

Create a wallet via the API using the following properties (NB admin key is blank, not sure if an issue):

```
    // Prepare the request body
    const requestBody = {
      user_id: userId,
      wallet_name: walletName,
    };

    //const accessToken = await getAccessToken(`${userName}`, `${password}`);
    const response = await fetch(`${lnbiturl}/usermanager/api/v1/wallets`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        //Authorization: `Bearer ${accessToken}`,
        'X-Api-Key': adminKey,
      },
      body: JSON.stringify(requestBody), // Stringify the request body
    });
```

Try and delete the wallet through the interface.

NB Wallet seems to be deleted still.

**Expected behavior**
Wallet should be deleted without error.

**See also:**

#2695

**Server (please complete the following information):**

-  LNbits version: 0.12.10

**Comment by talvasconcelos** [comment]
usermanager extension is deprecated in V1

can it be closed?

**Comment by motorina0** [comment]
yes

The functionality is present in core now.
