### ISSUE TITLE
[Feature request] Add balance to User Manager Wallet screen

### ISSUE THREAD

**Issue by BenGWeeks** [lnbits/lnbits#2693]
**Is your feature request related to a problem? Please describe.**
It is not possible to see the `deleted` or `balance` (`balance_msat/100`) on the User Manager extension.

**Describe the solution you'd like**
This should be possible to view on the User Manager extension.

![image](https://github.com/user-attachments/assets/16e659dd-be7d-4056-bab1-c0b62f662c93)

Additional context

LNbits version: 0.12.10

**Comment by talvasconcelos** [comment]
usermanager deprecated on V1.

Can it be closed?

**Comment by motorina0** [comment]
Yes. See https://github.com/lnbits/lnbits/pull/2777
