### ISSUE TITLE
[Feature request] Add ability to edit the user on the User Manager screen

### ISSUE THREAD

**Issue by BenGWeeks** [lnbits/lnbits#2694]
**Is your feature request related to a problem? Please describe.**
I would like to be able to update (edit) users on the User Manager screen.

**Describe the solution you'd like**
Add an edit icon next to each user.

![image](https://github.com/user-attachments/assets/659fae63-0835-4f83-af8d-6938c29113f1)

Extra points for the ability to add `extra {}` information.

Currently we have to do through Postman.

**See also:**

#2695

**Additional context**

LNbits version: 0.12.10

**Comment by motorina0** [comment]
This feature is supported in v1 PR: https://github.com/lnbits/lnbits/pull/2777

Please note that the `usermanager` extension will be retired with the v1 of LNbits.

However, the core now has `users` API which support all the operations of `usermanager` and more.
