### ISSUE TITLE
[Feature request] Improve UX around User Management

### ISSUE THREAD

**Issue by BenGWeeks** [lnbits/lnbits#2695]
**Is your feature request related to a problem? Please describe.**
There are some inconsistencies with **Manager** > **Users** and the **User Manager** extension. Issues as follows:

- When a user first opens the instance, they have **Manager** > **Users** but no obvious way to create a new user, and no apparent that you need to add **User Manager** for what I would deem core functionality.
- Within **User Manager**, they have no way to edit a user.
- The `username` in **User Manager** does not seem to be the same as `username` in **Manager** > **Users**.

**Describe the solution you'd like**
Merge the solutions, either move the User Manager functionality into the Core, or make the User Manager extension that is installed by default.

**See also**
#2557
#2694
#2692
#2696
#2697
#2699
#2700

**Additional context**

LNbits version: 0.12.10

**Comment by talvasconcelos** [comment]
Can we close all the related issues? user manager is to be deprecated in V1.

There's a new User tab on core for user management

**Comment by BenGWeeks** [comment]
Are these covered out of interest in v1? FYI @arcbtc

**Comment by motorina0** [comment]
Yes, they are covered.
v1 is on dev, can be tested (not released yet though)
