### ISSUE TITLE
[BUG] "Email" does not appear in Manage > Users when specified in User Manager

### ISSUE THREAD

**Issue by BenGWeeks** [lnbits/lnbits#2696]
**Describe the bug**
We specify the e-mail address when creating/editing a user in **User Manager** by calling the relevant API. However, this is not displayed in 

**To Reproduce**

1. Create a new user via the API (or update existing user)
2. Confirm email address is displayed in the **User Manager**
3. Go to the **Manage** > **Users**
4. See error (no email displayed)

**Expected behavior**
Email should be displayed in **Manage** > **Users**

**Screenshots**

![image](https://github.com/user-attachments/assets/a3943285-85c0-4d58-a04d-fc719a7bc051)

vs

![image](https://github.com/user-attachments/assets/458f5e84-e8d2-4a46-886d-47834c696f31)

**Also see**

#2695

**Additional context**

LNbits version: 0.12.10

**Comment by motorina0** [comment]
Please note that the `usermanager` extension will be retired with the v1 of LNbits.

However, the core now has `users` API which support all the operations of `usermanager` and more.

See PR: https://github.com/lnbits/lnbits/pull/2777
