### ISSUE TITLE
[BUG] User unable to login after being created with a username/email and a password

### ISSUE THREAD

**Issue by BenGWeeks** [lnbits/lnbits#2697]
**Describe the bug**
We are creating users with the API. But even though we set username / email and a password, they are unable to login. They need to login using their ID, then set their own password.

**To Reproduce**

1. Create a user using the `/usermanager/api/v1/users` with a `user_name`, `email` and `password`
2. Open LNBits in a different browser instance, and try and login with those credentials
4. User is unable to login with `user_name`/`password` or `email`/`password`.

**Expected behavior**
User should be able to login with these credentials.

**See also:**

#2695

**Additional context**

- LNbits version: 0.12.10

**Comment by motorina0** [comment]
`usermanager` will be retired with v1
The user management features are now available in core.
See: https://github.com/lnbits/lnbits/pull/2777
