### ISSUE TITLE
Buggy display in Firefox / Tor browser if self-hosted LNbits on RaspiBlitz

### ISSUE THREAD

**Issue by openoms** [lnbits/lnbits#27]
Running the latest version of the script on RaspiBlitz 1.5 RC1

Left is in Brave (same in Brave Tor window an Chromium)
Right is Tor Browser (same in Firefox) appears buggy.
![image](https://user-images.githubusercontent.com/43343391/80530742-5e163b80-8991-11ea-8773-e1eba01e3572.png)

How could this be fixed?

Tried lnbits.com does not have the issue.

Here is the Hidden Service address of this test node:  
`kyxohflrrkotuxnlkannazbzzaiihbn5l2gnnrvcj256fbenggssxvad.onion`

**Comment by arcbtc** [comment]
Looks like its the icon set, I'm sure we can overcome that. It must be how they are loaded. I once had the same issue for a moment in a regular browser, on a very overloaded system, over a crappy internet connection, which makes sense as you're experiencing the issue over TOR running off a pi. I'll look into it. Thanks for the heads up

**Comment by sgeisler** [comment]
If it's a font thing fixing it might be hard since the TOR Browser is quite restrictive when it comes to webfonts (at least at high security levels).

**Comment by eillarra** [comment]
We could self host it? https://google.github.io/material-design-icons/#icon-font-for-the-web

**Comment by eillarra** [comment]
@openoms `master`now includes a self hosted icon font. Can you try it?

**Comment by openoms** [comment]
Yes, works great. Thank you!
