### ISSUE TITLE
[Question] How to Retrieve LNBits Server-Side Fees and Understand Handling of LN Network Fees from Funding Sources (my Case LND)

### ISSUE THREAD

**Issue by DoktorShift** [lnbits/lnbits#2709]
Hello LNBits Team,

I am currently working on a web application that utilizes LNBits as its payment backbone for managing Bitcoin Lightning transactions. LNBits is essential for my application's payment infrastructure, and understanding its fee structures is crucial for accurate integration and providing a transparent user experience.

I have the following questions regarding LNBits:

1. **Retrieving Server-Side Fees:**
   - **How can I programmatically retrieve the server-side fees configured in LNBits?**
   - I have examined the `/api/v1/payments` endpoint, which returns a `fee` field in each payment object. However, I am unsure if this `fee` represents the server-side fee set within LNBits or if it refers to something else. Could you please clarify what the `fee` field in the payments API represents and guide me on how to accurately retrieve the server-side fee?

   **API Response Example:**
   ```json
   [
     {
       "checking_id": "string",
       "pending": true,
       "amount": 0,
       "fee": 0,
       "memo": "string",
       "time": 0,
       "bolt11": "string",
       "preimage": "string",
       "payment_hash": "string",
       "expiry": 0,
       "extra": {},
       "wallet_id": "string",
       "webhook": "string",
       "webhook_status": 0
     }
   ]
   ```
   In the above response, there is a `fee` field, but I am unsure if it refers to the server-side fee or something else.

2. **Handling of LN Network Fees from Funding Sources:**
   - **How does LNBits handle LN network fees associated with attached funding sources?**
   - When funding a wallet or processing transactions, how are the LN network fees calculated and deducted? Is this process managed automatically by LNBits, or do I need to implement additional logic in my application to account for these fees?

Any guidance, documentation, or examples you can provide on these topics would be greatly appreciated. This would help me offer a transparent payment experience to users.

Thank you for your time and assistance.

Cheers,  
Dr. Shift ⚡

**Comment by DoktorShift** [comment]
I have made some progress on the first part of my question. I found out that the /api/v1/payments endpoint provides the network fee in the "fee" field of the response. This fee represents the Lightning Network's fee a processed transaction.

However, I am still looking for the location or parameter where the "LNBits service fee" is stored. The fee set by the LNBits admin for outgoing transactions. I need to identify how to retrieve this specific fee programmatically.

**Comment by motorina0** [comment]
You can fetch the settings of the server as admin and find the fee info there:
```curl
GET http://localhost:5000/admin/api/v1/settings?usr=d5ccb5ed11c6427e887890bbd050e95d
```


```json

{
   ...
    "lnbits_reserve_fee_min": 2000,
    "lnbits_reserve_fee_percent": 1.0,
    "lnbits_service_fee": 0.0,
    "lnbits_service_fee_ignore_internal": true,
    "lnbits_service_fee_max": 0,
    "lnbits_service_fee_wallet": null,
   ...
}
```

**Comment by DoktorShift** [comment]
Thanks🙏🏼 that's it.
