### ISSUE TITLE
[BUG] The git tags for 0.12.11 are missing.

### ISSUE THREAD

**Issue by 20a8vnf30** [lnbits/lnbits#2720]
The git tags for 0.12.11 are missing.

```
$ git clone https://github.com/lnbits/lnbits.git /lnbits0.12.11
$ cd /lnbits0.12.11/
$ git fetch --tags
$ git checkout 0.12.11
error: pathspec '0.12.11' did not match any file(s) known to git
```

Checking out 0.12.10 has no such problem.
I don't want to build the Master branch, I want to build the 0.12.11 release. How do I do that without the proper version tags?

**Comment by prusnak** [comment]
git checkout v0.12.11


@dni do we also want to tag 0.11.11 or are we using "v" prefix from now on?

**Comment by dni** [comment]
i think the time is right we switch to `v` prefix

**Comment by prusnak** [comment]
Ok, closing then.
