### ISSUE TITLE
[BUG] User Manager API does not update e-mail address

### ISSUE THREAD

**Issue by EdiWeeks** [lnbits/lnbits#2721]
**Describe the bug**
Ran the `User Manager` API to update a user, but their e-mail address is not updated in LNbits `User Manager` extension.

**To Reproduce**

1. Update the user using Postman (`PUT` to `/usermanager/api/v1/users/{userId}`.
2. Click `Send`.
4. E-mail address is not updated in `User Manager`.

**Expected behavior**
E-mail address should get updated in `User Manager`.

**Screenshots**

![image](https://github.com/user-attachments/assets/d2cff81c-e30d-4d80-9927-097617f74de9)

![image](https://github.com/user-attachments/assets/9eb6a59d-20ff-494d-bc91-072090b35d98)

**Additional context**
- LNbits version: 0.12.10

**Comment by motorina0** [comment]
Please note that the `usermanager` extension will be retired with the v1 of LNbits.

However, the core now has `users` API which support all the operations of `usermanager` and more.

**Comment by motorina0** [comment]
https://github.com/lnbits/lnbits/pull/2777
