### ISSUE TITLE
LNURLw: updating a withdraw, results in error because of is_unique conversion from bool to int on s.lnbits.com

### ISSUE THREAD

**Issue by cryptoteun** [lnbits/lnbits#273]
When running the postman test on s.lnbits.com I ran into an issue when updating a withdraw link.

When updating the withdraw with the following body (which is running smoothly on lnbits.com):
`{
   "title": "LNRULw updated",
    "min_withdrawable": 5,
    "max_withdrawable": 5,
    "uses": 1,
    "wait_time": 60,
    "is_unique": true
}`

I run into the following issue:

> LNbits internal error!
Traceback (most recent call last):
  File "/root/lnbits/venv/lib/python3.8/site-packages/sqlalchemy/engine/base.py", line 1276, in _execute_context
    self.dialect.do_execute(
  File "/root/lnbits/venv/lib/python3.8/site-packages/sqlalchemy/engine/default.py", line 608, in do_execute
    cursor.execute(statement, parameters)
psycopg2.errors.DatatypeMismatch: value type bool doesn't match type int of column "is_unique"
HINT:  you will need to rewrite or cast the expression

During the creation of the test it occured to me already a int is returned, were I would expect a boolean based on the (forced) input.

**Comment by fiatjaf** [comment]
See if it's fixed on 2b82985d36119e906eeb89a2044f3db03358d809 please.

**Comment by cryptoteun** [comment]
Is it already deployed to s.lnbits.com? Because it didnt occur on master against lnbits.com.

**Comment by fiatjaf** [comment]
Sorry, it is deployed now.

**Comment by cryptoteun** [comment]
It's fixed indeed, Will close this one.
