### ISSUE TITLE
[BUG] Funding Stream is not working for Phoenixd

### ISSUE THREAD

**Issue by RGPankO** [lnbits/lnbits#2749]
**Describe the bug**
You have to refresh the page of the wallet in oder for a paid invoice to register as paid.

**To Reproduce**

1. Go to 'Server' and then Funding
2. Click on the dropdown and then choose Phoenixd
3. Save, Restart
4. Generate and Pay invoice.

**Expected behavior**
Funding stream will not work, need a refresh of the page to force status update for payments.

**Screenshots**

**Desktop (please complete the following information):**

- LNbits version: [e.g. 0.12.12 or commit hash]
- Phoenixd 0.4.0 and 0.4.2

**Additional context**
As per the discussion over Telegram

**Comment by arcbtc** [comment]
Found it, thank you. 
It was our funding source connector assuming the connection was local. Added to the v1 update 
https://github.com/lnbits/lnbits/commit/873433885af823a28a727a4b2b0609df205c61cc
