### ISSUE TITLE
[Feature request] Allow Superuser reset passwords without know current password

### ISSUE THREAD

**Issue by jjmmbb** [lnbits/lnbits#2762]
**Is your feature request related to a problem? Please describe.**
When an user forgot the password, Superuser can not change the user's password even logging as the user because lnbits is asking for current password. There is no way to reset password.

**Describe the solution you'd like**
Allow Superuser to change any password including himself.

**Describe alternatives you've considered**
Improve the features from user management.

**Comment by motorina0** [comment]
> Improve the features from user management.
See PR: https://github.com/lnbits/lnbits/pull/2777

> Allow Superuser to change any password including himself.
 - if `super_user` is compromised then allowing it to change its own password would only help the attacker
 - if `super_user` is compromised then the system admin (with `ssh` access to `lnbits`) should change the `super_user` by updating this flag:
```properties
# ID of the super user. The user ID must exist.
# SUPER_USER="xxxxxxxxxxxxxxxxxxxxxxxxx"

```
