### ISSUE TITLE
[BUG] Dangerous bug with custom badge

### ISSUE THREAD

**Issue by AxelHamburch** [lnbits/lnbits#2763]
The input field for “Custom Badge” under “Theme” does not seem to catch invalid characters. I have entered the simple phrase “Eine Demo für Pelb's” and selected Color “orange”.

![image](https://github.com/user-attachments/assets/11bafaa6-f995-4e23-a09e-8c2a85a05809)

After saving and refreshing the browser, I was not shown any content from the LNbits site. It is completely empty.

![image](https://github.com/user-attachments/assets/a0f98728-7ba5-4883-a1f9-144a0806e468)

Updating and accessing other accounts also shows the same. I have completely lost access to LNbits. 

I suspect that it is due to the  ` ' ` character. Maybe something else, but the special character would be obvious. 

As I have only just set up the instance, this is just annoying. I could just reinstall LNbits. But for other users this could be disastrous. 

Ubuntu 22.04 LTS, LNbits 0.12.12.

**Comment by motorina0** [comment]
Thanks!
We will include a fix for this in v1.

**Comment by dni** [comment]
probably single quotes

**Comment by motorina0** [comment]
Fixed in: 
https://github.com/lnbits/lnbits/pull/2827


![image](https://github.com/user-attachments/assets/201b64f6-32fb-43da-a1fc-62526ca4e51c)
