### ISSUE TITLE
Some wallets with negative balance

### ISSUE THREAD

**Issue by gb000** [lnbits/lnbits#277]
![image](https://user-images.githubusercontent.com/64491875/127161594-b59da831-ca0c-4e09-8bf7-02b77defd002.png)

I've looking at balances table inside the LNbits SQLITE3 database, and some wallets have negative balance.

I think that this can be a "bug", where all the funds of the wallet be spent, the routing fee is counted after the balance be spent.

Now I'm using one of the latest versions through master branch, this issues happenned when I was running the version tag 0.3.0

**Comment by guibressan** [comment]
I'm using LNBITS with C-lightning v 0.10.0
