### ISSUE TITLE
[BUG] RuntimeError - Future Attached to a Different Loop

### ISSUE THREAD

**Issue by redimongo** [lnbits/lnbits#2786]
After performing a fresh install of LNbits and configuring it to use LND with Litecoin Lightning Network, I encountered the following error when attempting to start the server:

```
Traceback (most recent call last):
  File "/home/USER/Downloads/lnbits/lnbits/tasks.py", line 79, in catch_everything_and_restart
    return await func()
  File "/home/USER/Downloads/lnbits/lnbits/tasks.py", line 122, in internal_invoice_listener
    checking_id = await internal_invoice_queue.get()
  File "/usr/local/lib/python3.9/asyncio/queues.py", line 166, in get
    await getter
RuntimeError: Task <Task pending name='Task-13' coro=<catch_everything_and_restart() running at /home/USER/Downloads/lnbits/lnbits/tasks.py:87>> got Future <Future pending> attached to a different loop

```

To Reproduce

1. Perform a fresh install of LNbits.
2. Configure LNbits to use LND with Litecoin Lightning Network.
3. Start the LNbits server using the provided instructions.

![image](https://github.com/user-attachments/assets/99fb73dc-4de4-4e17-bb79-2fc8f2257aa0)

**Desktop (please complete the following information):**

- LNbits version: 1.0.0rc5
- Database sqllite

**Comment by prusnak** [comment]
Which LND version do you use?

Litecoin support has been removed from LND in version 0.18

**Comment by prusnak** [comment]
> I am using https://github.com/ltcsuite/lnd

I don't think that is supported.

**Comment by dni** [comment]
@arcbtc had that same issue, i think python3.9 support is compromised, can you update to python3.10? @redimongo
