### ISSUE TITLE
Can't access my wallet - Page loads indefinitely

### ISSUE THREAD

**Issue by lacksfish** [lnbits/lnbits#279]
Recently, accessing my wallet doesn't work:

Accessing an URL which looks like this: https://lnbits.com/wallet?usr=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx&wal=111111111111111111111111111111

It just loads infinitely... It's been happening multiple times in the last week. The wallet is often down for hours on end ...

Considering switching to LNpay unless this is a temporary situation. I need to access my funds !

**Comment by talvasconcelos** [comment]
@fiatjaf and @arcbtc can this be related to lnbits.com being somewhat slugish and down latelly?
