### ISSUE TITLE
[BUG] Can't install lnbits

### ISSUE THREAD

**Issue by soc7** [lnbits/lnbits#2793]
Trying to install lbits 012.12 on ubuntu server 24.04 on arm running LND and python 3.12.
After the comand : 
`$ poetry install --only main
Installing dependencies from lock file

Package operations: 1 install, 0 updates, 0 removals

  - Installing secp256k1 (0.14.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  'pkg-config' is required to install this package. Please see the README for details.
  

  at ~/.local/share/pypoetry/venv/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with secp256k1 (0.14.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "secp256k1 (==0.14.0)"'.

`
`$ poetry add setuptools wheel
Using version ^75.6.0 for setuptools
Using version ^0.45.1 for wheel

Updating dependencies
Resolving dependencies... (1.8s)

Package operations: 1 install, 0 updates, 0 removals

  - Installing secp256k1 (0.14.0): Failed

  ChefBuildError

  Backend subprocess exited when trying to invoke get_requires_for_build_wheel
  
  'pkg-config' is required to install this package. Please see the README for details.
  

  at ~/.local/share/pypoetry/venv/lib/python3.12/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with secp256k1 (0.14.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "secp256k1 (==0.14.0)"'.

`

**Comment by soc7** [comment]
The as suggest I tried the above command:
`$ pip wheel --no-cache-dir --use-pep517 "secp256k1 (==0.14.0)"
Collecting secp256k1==0.14.0
  Downloading secp256k1-0.14.0.tar.gz (2.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.4/2.4 MB 9.5 MB/s eta 0:00:00
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error
  
  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      'pkg-config' is required to install this package. Please see the README for details.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by prusnak** [comment]
Do what the error output is telling you to do - install pkg-config.

sudo apt install pkg-config

**Comment by soc7** [comment]
It worked! Thanks
