### ISSUE TITLE
"Own Node", add own funding source extension

### ISSUE THREAD

**Issue by arcbtc** [lnbits/lnbits#28]
An extension for a user to add their own LND invoice macaroon and endpoint so they can use their own node on a service like lnbits.com

This is an ambitious extension and will likely require an additional "own_node" bool field in the core user DB, which if set True, will fetch the invoice macaroon hex string and endpoint from the users "Own Node" extension, and use those for invoice generation.

**Comment by fiatjaf** [comment]
If they want to use their own node shouldn't they be running their own lnbits installation? Otherwise a single installation would now have to support all kinds of backends (c-lightning, lnpay.co, lntxbot etc.) for each wallet, and it's a push into centralizing all accounts from people everywhere into a single lnbits.com domain, which goes against the idea of decentralizing the custodians.

Maybe if someone wants to use their own node but don't have a public IP, for example, we can find a way to help these people access their lnbits from elsewhere using Tor or IPv6 or zerotier.com or some other way.

**Comment by arcbtc** [comment]
Its giving people another option, who knows what will come out of it. 

For example, some LNURL functions will be easier with a public frontend. Or maybe a user needs to access the PoS extension but doesn't want to install lnbits.

I would be interested in how people use the service, and what use cases they discover.

**Comment by Kixunil** [comment]
@fiatjaf raised some good points. What I would be interested in (including collaboration) would be spawning a new torified instance of node running on the same machine. The intent is to protect privacy of users by not using same node for each operation. [Related issue in my project](https://github.com/Kixunil/cryptoanarchy-deb-repo-builder/issues/21)

So far the high-level idea is for all services that can have multiple instances to provide a simple API for creating, connecting to and deleting the instances. To be precise, it should be the job of their related packages, not themselves. Further, I'd love to provide automated mixing at later stage to move the funds around safely.

**Comment by ChuckNorrison** [comment]
Hey, first of all a very great project i would love to implement as a modern solution in my company to get our coffees and snacks paid. 

Currently this is done with cash or paypal. A big excel sheet without much of fun. I want to add lightning to make it a bit more comfortable. Nobody knows about Lightning Network and Bitcoin. The solution to host a lnbits for that seems to be legit, cause nobody wants to install anything on private devices at work. For independency, privacy and security reasons i want to be in full control of the underlying wallets and the system which is needed to get it running.

**Comment by nanda77** [comment]
If lnbits extensions lets user to add their own invoice, that will automatically let anyone with their own node to use any extension. Basically they will create an invoice from their own funding source and pass on to lnbits extension using api. or a simple solution would be to add LNURLp address into lnbits admin panel so extensions can use that to ask for invoice when creating lets say Tpos charge. Just a suggestion, I feel like this needs lot of changes.
