### ISSUE TITLE
Spotify Jukebox - songs play more than once

### ISSUE THREAD

**Issue by SamSamskies** [lnbits/lnbits#282]
When you pay to play a song, it should only play once, right?

**Comment by lukedevj** [comment]
> When you pay to play a song, it should only play once, right?

Yes!

**Comment by talvasconcelos** [comment]
@SamSamskies you mean the song loops, it keeps playing the same song? Could you elaborate a bit more on the issue? 
Maybe you have a loop setting somewhere in Spotify?

**Comment by SamSamskies** [comment]
@talvasconcelos yeah it kept playing the same song. I eventually realized I could control the queue in Spotify, so you could probably close this issue. It would be helpful to mention that the creator of the Jukebox can control the queue from in Spotify though. Took me a while to figure that out.
