### ISSUE TITLE
[BUG]LNURLp / LNaddress not working in v0.12.12 in combi with lnurlp extension v0.5.6

### ISSUE THREAD

**Issue by Satoshi-Samourai** [lnbits/lnbits#2830]
I am running LNBits on v0.12.12 with LNURLp extension v0.5.6.

The Lightning address seems to be broken. I can scan the lightning adress from LNBits PayLinks extension and pay to it but :

testuser@lnbits.btc-payserver.eu returns an "address not existing". Decoder confirms issue, too. 

Not sue if this is a LNBits v0.12.12 issue, as with earlier versions my LNaddresses worked just fine.

I have tried this: 

https://lnbits.btc-payserver.eu/lnurlp/api/v1/well-known/testuserwallet

returns propper json:

{
  "tag": "payRequest",
  "callback": "https://lnbits.btc-payserver.eu/lnurlp/api/v1/lnurl/cb/FGgzTb",
  "minSendable": 1000,
  "maxSendable": 100000,
  "metadata": "[[\"text/plain\", \"Payment to testuser\"], [\"text/identifier\", \"testuser@lnbits.btc-payserver.eu\"]]",
  "commentAllowed": 200,
  "allowsNostr": true,
  "nostrPubkey": "e1585e0db30c182c52c6fd18a2b1b0fdb4ee73ddfdee873d23aaf77977310e4d"
}

------------------------------------------------------------

https://lnbits.btc-payserver.eu/.well-known/lnurlp/testuserwallet

returns error:

{
  "status": "ERROR",
  "reason": "Address not found."
}
_________________________________________________________________

There seem to be more people having the same issue as discussed in LNBits Telegram Group.

Thanks for looking into this. It would be nice if it could get a quick fix.

Greets

**Comment by motorina0** [comment]
Can you please confirm that it is not this issue: https://github.com/lnbits/lnbits/issues/2540#issuecomment-2260544749

> I believe the issue is caused by a conflict between `lnaddress` and `lnurlp` in mapping the same route:
> 
>     * lunrlp: https://github.com/lnbits/lnurlp/blob/main/__init__.py#L20
> 
>     * lnaddress: https://github.com/lnbits/lnaddress/blob/main/__init__.py#L21
> 
> 
> There is no deterministic way in which the extensions are loaded, therefore the unpredictable behavior.
> 
> Suggestion: remove `lnaddress`.

Note: the extension conflict has been handled in `v1`

**Comment by Satoshi-Samourai** [comment]
Yes, the conflict between lnaddress and lnurlp was the issue. Had to uninstall lnaddress extension to make lnurlp work.
