### ISSUE TITLE
User manager API not returning initial wallet information 

### ISSUE THREAD

**Issue by gohumble** [lnbits/lnbits#286]
Hello, 

I don't know if the user manager api is maintained in this repository. Sorry, if this Issue was created is in the wrong repository.
 
I noticed, that the `POST "user + initial wallet"` endpoint won't return any wallet information.

# What did you do?
Send a HTTP request to `POST /usermanager/api/v1/users` to create a new user with an initial wallet. 

# What did you expect? 
HTTP response (201), containing user as well as wallet information 

# What did you see instead?
HTTP response (201), containing only user information
` {"id": <string>, "name": <string>, "admin": <string>, "email": <string>, "password": <string>} ` 

My solution to this was creating a user + initial wallet and fetch the wallet information afterwards. Thats not best practice imho. 

Is there any chance to include the wallet information to the `POST /usermanager/api/v1/users` resource? 
Something like this response would be very useful:

` {"id": <string>, "name": <string>, "admin": <string>, "email": <string>, "password": <string>,"wallet_id": <string>, "wallet_admin": <string>, "wallet_name": <string>, "adminkey": <string>, "inkey": <string>}`

The `wallet_admin` is probably redundant in this case.

**Comment by bezysoftware** [comment]
Should this issue be closed?
