### ISSUE TITLE
Bug: Cannot send to internet identifier with subdomain

### ISSUE THREAD

**Issue by Fittiboy** [lnbits/lnbits#298]
I tried sending to fitti@ln.fitti.io (that's where I run satsdress), which worked fine with lntxbot, but gave me an "invalid lnurl" error with LNbits. Sending to fitti@fitti.io (my manual implementation) was no problem.

**Comment by arcbtc** [comment]
I love this address thing but have not had time to investigate. 
If anyone out there can implement into LNbits properly please do! (as I understand it we're only partly implemented)

**Comment by Fittiboy** [comment]
This is fixed with #312, which also takes care of another issue.
