### ISSUE TITLE
Suggestion: Don't require a TLS Certificate for LND

### ISSUE THREAD

**Issue by gkrizek** [lnbits/lnbits#299]
Currently it seems like a TLS Certificate is required when connecting to LND. Even if I leave it blank or don't define it, it looks in some default location. However, if my LND node is using a TLS Certificate that's signed by a trusted Certificate Authority, then the system's certificate chain would be able to validate it.

I'm proposing that if the TLS Cert fields are left blank in the .env file that we use the system's certificate chain instead.

**Comment by arcbtc** [comment]
Ahhhh, is that why When I ngroked my LND I didnt need a TLS, it was using Ngroks?

**Comment by dni** [comment]
i think this can be solved by just using the path of the system certificate for the `.env` setting. closing the issue for now, feel free to reopen it, if that does not work.
