### ISSUE TITLE
Installation fails to build wheel for several packages

### ISSUE THREAD

**Issue by 634-5789** [lnbits/lnbits#303]
On Ubuntu 20.04.2 LTS the installation process fails to build bitstring blinker embit pyngrok pypng pyqrcode pyscss with the same error: 'invalid command 'bdist_wheel'. Here's an example for bitstring:

```
Building wheel for bitstring (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/user/lnbits/venv/bin/python3 -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-fufznll9/bitstring/setup.py'"'"'; __file__='"'"'/tmp/pip-install-fufznll9/bitstring/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-i1r0g155
       cwd: /tmp/pip-install-fufznll9/bitstring/
  Complete output (6 lines):
  usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
     or: setup.py --help [cmd1 cmd2 ...]
     or: setup.py --help-commands
     or: setup.py cmd --help
  
  error: invalid command 'bdist_wheel'
  ----------------------------------------
  ERROR: Failed building wheel for bitstring
  Running setup.py clean for bitstring
```

`pip3 install wheel` did not solve the issue, nor did installing `gcc libpq-dev python-dev  python-pip python3-dev python3-pip python3-venv python3-wheel`.

What else could be the matter here?

Thank you kindly for your suggestions.

**Comment by arcbtc** [comment]
Dont worry about it, its just pip error handling in a dramatic way. 

Pip wants to build a wheel for it, but cant so then has to install directly.

Stoopid ugly pip making our install look scary 😂
