### ISSUE TITLE
NoneType Exception on some payments

### ISSUE THREAD

**Issue by ChuckNorrison** [lnbits/lnbits#305]
We closed this exception last time, cause it was a payment from clearnet lnbits to a tor running node. It happens again on a regular payment on public with my lnbits wallet.

I received an invoice from coingate, i switched to lightning transaction and tried to send via lnbits webinterface and paste Request. I received some funds on this lnbits wallet via lightning from an eclair wallet successful but as i want to pay my coingate invoice it stucks. Second try ends on 500. 

I was able to send some funds to lntxbot without any issues after this failure. Also i was able to send back funds to eclair which has a channel open with my node.

Used environment ist the latest RaspiBlitz Release on 1.7.0 from April 2021 with lnbits installation

Here are some logs:

> Aug 19 16:12:29 raspberrypi sh[12206]: [2021-08-19 16:12:29 +0100] [12207] [INFO] Running on http://0.0.0.0:5000 (CTRL + C to quit)
Aug 19 16:14:13 raspberrypi sh[12206]: [2021-08-19 16:14:13,749] ERROR in app: Exception on request POST /api/v1/payments
Aug 19 16:14:13 raspberrypi sh[12206]: Traceback (most recent call last):
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 131, in handle_request
Aug 19 16:14:13 raspberrypi sh[12206]:     return await self.full_dispatch_request(request_context)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 153, in full_dispatch_request
Aug 19 16:14:13 raspberrypi sh[12206]:     result = await self.handle_user_exception(error)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 166, in handle_user_exception
Aug 19 16:14:13 raspberrypi sh[12206]:     return await super().handle_user_exception(error)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/app.py", line 1104, in handle_user_exception
Aug 19 16:14:13 raspberrypi sh[12206]:     raise error
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart_trio/app.py", line 151, in full_dispatch_request
Aug 19 16:14:13 raspberrypi sh[12206]:     result = await self.dispatch_request(request_context)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/venv/lib/python3.7/site-packages/quart/app.py", line 1933, in dispatch_request
Aug 19 16:14:13 raspberrypi sh[12206]:     return await handler(**request_.view_args)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 55, in wrapped_view
Aug 19 16:14:13 raspberrypi sh[12206]:     return await view(**kwargs)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/core/views/api.py", line 149, in api_payments_create
Aug 19 16:14:13 raspberrypi sh[12206]:     return await api_payments_pay_invoice()
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 28, in wrapped_view
Aug 19 16:14:13 raspberrypi sh[12206]:     return await view(**kwargs)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 55, in wrapped_view
Aug 19 16:14:13 raspberrypi sh[12206]:     return await view(**kwargs)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/core/views/api.py", line 131, in api_payments_pay_invoice
Aug 19 16:14:13 raspberrypi sh[12206]:     raise exc
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/core/views/api.py", line 124, in api_payments_pay_invoice
Aug 19 16:14:13 raspberrypi sh[12206]:     payment_request=g.data["bolt11"],
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/core/services.py", line 153, in pay_invoice
Aug 19 16:14:13 raspberrypi sh[12206]:     payment: PaymentResponse = await WALLET.pay_invoice(payment_request)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/home/lnbits/lnbits/lnbits/wallets/lndrest.py", line 116, in pay_invoice
Aug 19 16:14:13 raspberrypi sh[12206]:     preimage = base64.b64decode(data["payment_preimage"]).hex()
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/usr/lib/python3.7/base64.py", line 80, in b64decode
Aug 19 16:14:13 raspberrypi sh[12206]:     s = _bytes_from_decode_data(s)
Aug 19 16:14:13 raspberrypi sh[12206]:   File "/usr/lib/python3.7/base64.py", line 46, in _bytes_from_decode_data
Aug 19 16:14:13 raspberrypi sh[12206]:     "string, not %r" % s.__class__.__name__) from None
Aug 19 16:14:13 raspberrypi sh[12206]: TypeError: argument should be a bytes-like object or ASCII string, not 'NoneType'

// some more logs, i spoofed them a bit

> admin@raspberrypi:~ $ sudo tail -f /var/log/nginx/error_lnbits.log
2021/08/19 01:26:12 [crit] 716#716: *245043 SSL_do_handshake() failed (SSL: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share) while SSL handshaking, client: 123.218.123.66, server: 0.0.0.0:443
2021/08/19 02:06:53 [crit] 716#716: *245061 SSL_do_handshake() failed (SSL: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share) while SSL handshaking, client: 123.142.345.43, server: 0.0.0.0:443
2021/08/19 13:35:41 [crit] 716#716: *245284 SSL_do_handshake() failed (SSL: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share) while SSL handshaking, client: 123.241.678.215, server: 0.0.0.0:443
2021/08/19 15:17:25 [crit] 716#716: *245309 SSL_do_handshake() failed (SSL: error:141CF06C:SSL routines:tls_parse_ctos_key_share:bad key share) while SSL handshaking, client: 123.105.678.67, server: 0.0.0.0:5001
2021/08/19 15:58:04 [error] 716#716: *245323 upstream timed out (110: Connection timed out) while reading response header from upstream, client: 123.240.456.196, server: _, request: "POST /api/v1/payments HTTP/1.1", upstream: "http://127.0.0.1:5000/api/v1/payments",

related to this
https://github.com/lnbits/lnbits/issues/166

**Comment by PrinzMonty** [comment]
Yes i have the same Error when i use LndRestWallet. But i run LnBits with Docker and a Tor Proxy & connected to my raspiblitz node (not the LnBits Raspiblitz Package).

```
lnbits-legend |   File "./lnbits/core/views/api.py", line 375, in api_payment
lnbits-legend |     await check_invoice_status(payment.wallet_id, payment_hash)
lnbits-legend | AttributeError: 'NoneType' object has no attribute 'wallet_id'
lnbits-legend | ERROR:    Exception in ASGI application
```

```
lnbits-legend |   File "./lnbits/core/views/api.py", line 375, in api_payment
lnbits-legend |     await check_invoice_status(payment.wallet_id, payment_hash)
lnbits-legend | AttributeError: 'NoneType' object has no attribute 'wallet_id'
```
