### ISSUE TITLE
Offlineshop error

### ISSUE THREAD

**Issue by richardelima** [lnbits/lnbits#315]
Giving the price other than sats, doesn't retrieve the correct price. Not even in usd. 
The result is a price in sats that doesn't match value in btc when scan on bluewallet. And secondary error

**Comment by richardelima** [comment]
![Screenshot_20210822_222658](https://user-images.githubusercontent.com/47503856/130386110-d4165046-2699-485f-adf6-3d4d0a40bb00.jpg)

**Comment by fiatjaf** [comment]
That's a BlueWallet bug, at least the second thing you mentioned.

**Comment by richardelima** [comment]
I don't think so. Even in other lnbits wallet it shows error.

**Comment by richardelima** [comment]
![Screenshot_20210823_071934](https://user-images.githubusercontent.com/47503856/130445944-237ea4f1-f8d7-491c-a9c6-4c3ab5f1e841.jpg)

**Comment by richardelima** [comment]
LNURL1DP68GURN8GHJ7MRWVF5HGUEWVDHK6TM0VENXC6TWV4EKSMMS9AKXUATJDSHNJWQLDDS03

**Comment by richardelima** [comment]
Seems like main problem is the currency data feed.
Closing the issue to change it.
