### ISSUE TITLE
What about using lighter?

### ISSUE THREAD

**Issue by St333p** [lnbits/lnbits#32]
### Proposal
[lighter](https://gitlab.com/inbitcoin/lighter) is a lightning node wrapper written in python that would allow you to quickly support 4 LN implementations at once: c-lightning, eclair, electrum and lnd; it exposes a gRPC interface with macaroon authentication, quite similar to the one exposed by lnd.

*Disclaimer:* I'm a contributor of lighter, feel free to reach out if I can help in your integration process.

**Comment by arcbtc** [comment]
An excellent project that. It's definitely something we should consider. 
Do you have redundancy support, can lighter attach to multiple nodes at a time?

**Comment by St333p** [comment]
We don't currently handle that complexity, but it was already considered among future updates. Could you please open an issue on lighter's gitlab, perhaps giving a couple of details more on how you would require it to be?

Anyways, while this is not supported by lighter you can also have one lighter instance per underlying node and handle them internally.
