### ISSUE TITLE
How to make backend funds accessible in a wallet? 

### ISSUE THREAD

**Issue by jpentland** [lnbits/lnbits#322]
I am using LND as a backend, which has balance available to send to other wallets. When I create a new wallet in a lnbits instance which uses this as a backend, it begins empty. However it is not possible to send payments from LND to this wallet using a normal invoice, since this would be a self payment. Therefore I would have to send funds to another lightning wallet, and then send them back?

**Comment by talvasconcelos** [comment]
That's exactly the point of lnbits!! Insulate your node... and your funds!

Try with `--allow_self_payment` flag on LND .

**Comment by jpentland** [comment]
Hmm ok, I was using RTL to pay the invoice and so could not choose the "--allow_self_payment" option that lncli provides.

Still, it seems unnecessary to make a lightning transaction to add balance to a wallet. Perhaps there could be a command line tool to just update balances in the database?

**Comment by talvasconcelos** [comment]
Admin users can add balance to wallets
