### ISSUE TITLE
"Not your pay link. 403"

### ISSUE THREAD

**Issue by HamishMacEwan** [lnbits/lnbits#325]
When I edit an LNURLp pay link and change the receiving account (from the drop down) the service complains:

```
Not your pay link.
403
```

https://github.com/lnbits/lnbits/blob/05139b330586d6ebe1528bbb7852a31f1070fd46/lnbits/extensions/lnurlp/views_api.py#L61

Seems that test should test inclusion in list of accounts.

**Comment by dni** [comment]
it worked fine for me on latest legend server, does this still happen for you?
