### ISSUE TITLE
API Method to create accounts

### ISSUE THREAD

**Issue by TheCherry** [lnbits/lnbits#344]
Hi,

I want create user accounts over the API, I know this is possible with the user management extension. But the impotent part is that I just wana give my end users the keys and then delete everything except the invoice key on my side. But the user management extension keep all that information. Do I need now to write my own API / Extension? I don't want create the account over the regular html and parse the information out of it.

**Comment by talvasconcelos** [comment]
I don't get what you're asking. What is it that you want to discard?

**Comment by arcbtc** [comment]
Yeah, I get it. Makes sense for accountability.
If you delete a record from usermanager, does the wallet still exist?

**Comment by talvasconcelos** [comment]
@TheCherry I've added a parameter on DELETE to allow the users to keep the wallets, on PR #1117 

`curl -X DELETE https://lnbits_endpoint/usermanager/api/v1/users/<user_id>?**delete_core=false** -H "X-Api-Key: 86537d610ce1470d90c2ee9f77a7d120"`
