### ISSUE TITLE
lnd default invoice expiry is 10 minutes

### ISSUE THREAD

**Issue by pseudozach** [lnbits/lnbits#352]
Is there any reason why default lnd default invoice expiry time is 10 minutes? can it be changed to 1 hour?
https://github.com/lnbits/lnbits/blob/19d432b404ede4ecc5206e14c24f40d42346ebc1/lnbits/wallets/lndgrpc.py#L129

I can also send a PR, just wanted to check if there's any justification. Short invoice expiry time like 10 minutes is bad UX. Unless there's any good reason, it could even be 1 day?

**Comment by arcbtc** [comment]
Most people seem to like invoices failing after a shorter period of time, as when the invoice is pending the funds are not available

**Comment by pseudozach** [comment]
right but in some use-cases:
- submarine swaps that may take more than 10 minutes (multiple block confirmation time)
- non-interactive/emailed payment request: sender/receiver may be in different timezones so the response may be up to 24 hours.
10 minute expiry time causes inconvenience, and since by default lnd creates 24hour valid invoices but lnbits artificially reduces that. 
Could it be at least configurable? Would you be open to it? Default can still stay at 10 minutes.

**Comment by sawrubgupta** [comment]
We need to set a parameter by which user can enter whatever expiry time he wants. That is going to be more convenient.

**Comment by Semisol** [comment]
> non-interactive/emailed payment request: sender/receiver may be in different timezones so the response may be up to 24 hours.

You could also use LNURLp.

> Could it be at least configurable? Would you be open to it? Default can still stay at 10 minutes.

For user configurable: That would be nice, but have a hard limit on maximum. Too much time may result in invoices that won't be used for days.
For admin configurable: I'm all for it.

**Comment by dni** [comment]
custom expiry is merged
