### ISSUE TITLE
Lightning decode api Failed to decode

### ISSUE THREAD

**Issue by Dolu89** [lnbits/lnbits#370]
Hi

Calling `POST https://demo.lnbits.com/api/v1/payments/decode` with the body
```
{
    "data": "lnbc1u1psh...q8t3wp2"
}
```
 return "message": "Failed to decode"

**Comment by talvasconcelos** [comment]
Can you please try sending the invoice in a query parameter? `?data=lnbc1u1psh...q8t3wp2` and see if that solves it?

**Comment by theborakompanioni** [comment]
Hey @arcbtc, I think this is still an issue - can this potentially be reopened?

The response code is `200 OK` even if the invoice could not be decoded.
I don't think it is a breaking change to adapt it and send 4xx or 5xx depending on what the underlying issue is. 
What do you think?
