### ISSUE TITLE
IP2TOR Rasiblitz support

### ISSUE THREAD

**Issue by arcbtc** [lnbits/lnbits#46]
Christian Rootzoll gave a great talk at this weekend's Hacksprint on the IP2TOR update for the Raspiblitz, which means a blitz can run behind TOR and pay a small amount for a public-facing URL, a sort of built-in reverse SSH. 

As it's behind TOR, will LNbits will need a variable added to .env that overrides the base URL with a chosen URL?
An Ngrok reverse SSH works for extensions without it.

![image](https://user-images.githubusercontent.com/33088785/84663359-f3a36580-af14-11ea-8cb2-282763612851.png)

**Comment by frennkie** [comment]
What is meant by `base URL`? 

I just setup IP2TOR access to LNbits running on my RaspiBlitz. I can open https://my-name.duckdns.org:51234/ and get the homepage. But when I enter a wallet name a redirect occurs that strips the port (51234) away.

**Comment by frennkie** [comment]
I was able to fix it by changing the nginx setting from

```
proxy_set_header Host $host;
``` 

to

```
proxy_set_header Host $http_host;
``` 

https://stackoverflow.com/questions/15414810/whats-the-difference-of-host-and-http-host-in-nginx

**Comment by frennkie** [comment]
Too fast.. the `LNURLw` withdrawal links don't work... I guess this is something that needs to be fixed in the `LNbits` code.

**Comment by joelklabo** [comment]
Does anyone have a link to the talk referenced in the initial comment here? @rootzoll

**Comment by rootzoll** [comment]
@joelklabo the IP2Tor is explained in a bit more detail at the beginning of this video: https://www.youtube.com/watch?v=0Bt3tHULAnw
