### ISSUE TITLE
Add support for custom root path

### ISSUE THREAD

**Issue by iBobik** [lnbits/lnbits#466]
In some deployments apps like LNbits are in subfolder to fit then on one hostname, most common are [btcpayserver-docker](https://github.com/btcpayserver/btcpayserver-docker) and [cryptoanarchy-deb-repo-builder](https://github.com/debian-cryptoanarchy/cryptoanarchy-deb-repo-builder) (#33).

It is easy to alter routing in Flask by root_path option, but it will be required to add this variable to all links in whole app.

Is PR welcome?

**Comment by arcbtc** [comment]
Is it possible in FastAPI, as we have switched out Quart now?

**Comment by talvasconcelos** [comment]
It has 1 year, has been inactive, with no further replies from the OP!

**Comment by Kixunil** [comment]
I'm still interested in this though.

**Comment by prusnak** [comment]
Let's close this in favor of https://github.com/lnbits/lnbits/issues/1941 which contains more info.
