### ISSUE TITLE
Admin area

### ISSUE THREAD

**Issue by arcbtc** [lnbits/lnbits#47]
To make management and funding of an LNbits install easier it would be nice to have an admin area.

I propose an extension, which only the first user or the user specified in a .env variable can access.
The Admin Extension DB can be used for the variables we are currently collecting form .env.
The user will then have the option of using .env or the extension to configure their install

The area could include:
- Setting up a funding source
- Some basic funding source info
- Funding wallets via the DB, rather than a transaction. 
- Basic theming
- User overview/wallet overview 
...

All ideas will be gratefully received

**Comment by ChuckNorrison** [comment]
I would like to see all wallets created by users and their amounts. 

Iam new to this lightning network and all the projects in... was missing a wallet backup solution especially for lnbits wallets. How do you backup your lnbits environment?
