### ISSUE TITLE
Force LNURLp to encode LNURL using https

### ISSUE THREAD

**Issue by rsandrade** [lnbits/lnbits#470]
I have a LNBits instance in a LXD container behind a NGINX and Cloudflare reverse proxies and for any reason the LNURLp extension do not encode LNURLs using https.

It encode using http and even forcing https through reverse proxies, the LNBits refuse to make it works.

My best idea for now is to have LNURLp forcing the https for any LNURL. Since the LNURLp need to use https it will be perfect to fix any LNBits error like that mine.

**Comment by dni** [comment]
i'm experiences the same issue, getting errors like ""LNURLs need to be delivered over a publically accessible `https` domain or Tor." despite running over https behind the proxy.

**Comment by dni** [comment]
wow thank you very much, im gonna try that, tonight, that sounds good.

i think security wise it should be completly fine

**Comment by dni** [comment]
```
./venv/bin/uvicorn lnbits.__main__:app --port 5000 --proxy-headers --forwarded-allow-ips '*'
```
getting still the same issue

**Comment by cryptoteun** [comment]
Proxy headers is in docker not needed. Did you try without the ' '

**Comment by dni** [comment]
without the ' its an error because * will get expanded.
i tried \* same result, also without proxy headers... 
so like maybe my apache setup is messing something up. hmmm 

no idea

**Comment by cryptoteun** [comment]
I run in docker, behind cloudflare and traefik. So a little different config.

**Comment by cryptoteun** [comment]
I added it this way to my compose: 
`command: ["uvicorn", "lnbits.__main__:app", "--port", "5000", "--host", "0.0.0.0", "--forwarded-allow-ips", "*"]`

**Comment by dni** [comment]
ok, tried that command, still same issue.

i guess docker is takes care of the escaping for us here.

**Comment by BitcoinQnA** [comment]
Bumping this one up to say I'm also experiencing the same issue.

**Comment by qecez** [comment]
Same

**Comment by iBobik** [comment]
Setting env variable also works:
`FORWARDED_ALLOW_IPS: "*"`

**Comment by mikeziri** [comment]
> Setting env variable also works: `FORWARDED_ALLOW_IPS: "*"`

Where are you setting it?
I'm running lnbits under umbrel and tried adding it to docker-compose.yml under environment on both services app_proxy and web.
Still have the same error:
> Error: 2 validation errors for LnurlPayResponse callback URL host invalid, top level domain required (type=value_error.url.host) callback URL scheme not permitted (type=value_error.url.scheme; allowed_schemes={'https'})

<img width="683" alt="image" src="https://user-images.githubusercontent.com/551167/223604849-3bccd78d-d172-47c4-9cc1-08520d585201.png">

**Comment by schneimi** [comment]
Here are two comments that could help.
https://github.com/getumbrel/umbrel/issues/1428#issuecomment-1383228537
https://github.com/lnbits/lnbits/issues/1475#issuecomment-1436038676

**Comment by mikeziri** [comment]
That did the trick. Thank you very much!
