### ISSUE TITLE
LNURLp does not check the return value of webhook call

### ISSUE THREAD

**Issue by we-do-it-lu** [lnbits/lnbits#489]
One can configure webhook URL to trigger when payment is made on LNURLp.
The URL is called but the return code (expected 200 all being well) is not checked, which means that is the URL is erroneous or the server down it happens silently (the payment has not triggered what the user paid for).

**Comment by fiatjaf** [comment]
What should LNbits do if the target server is down?

**Comment by we-do-it-lu** [comment]
Propagate the code from the response from the server.
If server not reachable -> 500 (mean there was a server-side error — think of something like the database server going down or perhaps running out of disk space, whatever).

**Comment by we-do-it-lu** [comment]
(No appropriate code is like passing hot potatoe without following up that all went well 🙏)

**Comment by fiatjaf** [comment]
Propagate to where? This is an asynchronous job. There will be no one to read.

But I thought we were storing at least the status code along with the payment.

**Comment by talvasconcelos** [comment]
Closed for inactivity!
