### ISSUE TITLE
Documentation error on API LNURL-withdraw extension 

### ISSUE THREAD

**Issue by bitkarrot** [lnbits/lnbits#496]
Docs for all API methods on LNURL-withdraw extension 

curl -X GET https://fast.laisee.org/api/v1/links

Should be corrected to read: 
curl -X GET https://fast.laisee.org/withdraw/api/v1/links -H

**Comment by arcbtc** [comment]
Are you on an older version of lnbits? 
As this looks okay https://github.com/lnbits/lnbits-legend/blob/a7c65d5d6071430eeec19e7e46e5278d82e56a42/lnbits/extensions/withdraw/templates/withdraw/_api_docs.html#L15

**Comment by bitkarrot** [comment]
I made a pull request to fix it here : https://github.com/lnbits/lnbits-legend/pull/497

**Comment by bitkarrot** [comment]
If you look at the  main line and the diff with my pull request and the current main branch of lnbits, you will see the part  that is missing in the docs, starting with line #25

**Comment by bitkarrot** [comment]
red underline part missing /withdraw/

<img width="391" alt="Screen Shot 2022-02-07 at 2 10 25 PM" src="https://user-images.githubusercontent.com/73979971/152880778-064106f0-dbb7-4901-b491-ebcef07ef8e0.png">
