### ISSUE TITLE
LNUrl withdrawal links generated with LNPay are invalid

### ISSUE THREAD

**Issue by SteliosRammos** [lnbits/lnbits#50]
I've cloned LNBits and run it locally with LNPay as a wallet. Whereas the invoices work properly (both generate and get status), the LNUrl withdrawal links generated are invalid, even though the link looks fine (ie: LNURL1DP68GU...). Not sure if this is an issue with LNBits or LNPay though. Have you guys had any luck getting LNPay to generate valid LNUrls?

**Comment by arcbtc** [comment]
LNURLS need to be served over HTTPS or else the wallets will reject it. 

Try using ngrok to make a reverse https proxy ```./ngrok http https://127.0.0.1:5000```, then make an LNURL and try it

If you run LNbits yourself you'll need HTPPS, either through something like certbot or some reverse ssh tunnel service
