### ISSUE TITLE
Add missing description_hash argument that is required for Lightning Address

### ISSUE THREAD

**Issue by john-zaprite** [lnbits/lnbits#511]
I'm not sure if this is the same as #76 or not, but I'm trying to implement Lightning Address (allowing users to connect to their own nodes: MyNode, Umbrel, etc.) and it looks like LNbits is not including the `description_hash` in the raw data when generating an invoice.

As per the LNurl-pay spec:
> `pr` must have the `h` tag (`description_hash`) set to `sha256(utf8ByteArray(metadata))`.
https://github.com/fiatjaf/lnurl-rfc/blob/legacy/lnurl-pay.md

Is it possible to add this into the data?
Is this a bigger issue, where it depends on the underlying lightning implementation?

**Comment by dni** [comment]
have you tested it this merge solved your issue?
