### ISSUE TITLE
LNBits wrong URL format when running on Raspiblitz

### ISSUE THREAD

**Issue by hermanlim** [lnbits/lnbits#52]
At the moment, on Raspiblitz, attempting to add a wallet opens the wrong URL, one that is missing the correct port number. Insertion of the correct port number in the URL results in the correct behaviour.

Eg. 192.168.1.2:5001 opens LNBits Page. Entering wallet name 'test' wrongly opens https://192.168.1.2/wallet?usr=[...] when it should open https://192.168.1.2:5001/wallet?usr=[...]

Raspiblits 1.6RC2

**Comment by arcbtc** [comment]
Hmmm, 
There is a PR for this, will try fixing today https://github.com/lnbits/lnbits/pull/51

**Comment by frennkie** [comment]
@hermanlim please check https://github.com/rootzoll/raspiblitz/pull/1339

**Comment by hermanlim** [comment]
Thanks @frennkie, looks like the same issue!

**Comment by hermanlim** [comment]
@arcbtc Arc, thanks for looking into problem. I was initially unsure where to post the issue and also posted on raspiblitz github where the issue has been resolved.
