### ISSUE TITLE
Support for lightning addresses on subdomains

### ISSUE THREAD

**Issue by rembobtc** [lnbits/lnbits#530]
Paying to lightning addresses hosted on subdomains is currently not possible using lnbits because the validation rules prevent it. 

**Steps to reproduce**
1. Open lnbits, click on "paste request"
2. Enter a lightning address hosted on a subdomain (name@subdomain.example.com)
3. See error "invalid lnurl"

**Analysis**
[lnbits/core/views/api.py:](https://github.com/lnbits/lnbits-legend/blob/main/lnbits/core/views/api.py#L396)
```if len(name_domain) == 2 and len(name_domain[1].split(".")) == 2:```

The second part of this validation could probably be removed to allow lightning addresses on subdomains, too. 

Happy to prepare a PR if you agree with this change.

**Comment by talvasconcelos** [comment]
Fixed by #914
