### ISSUE TITLE
Issue getting wallet to process LNURLw invoices

### ISSUE THREAD

**Issue by nolim1t** [lnbits/lnbits#552]
# Info on install

*LNBits version* 0.6.0 (built from the tag). Also used 0.7.0 which didn't seem to work too
*Wallets used* Blixt / Muun
* backend* LND
*LND version*  0.14.2-beta

### Logs

```
INFO:     127.0.0.1:43274 - "GET /withdraw/api/v1/lnurl/cb/callback?k1=k1value&pr=paymentrequestfromwallet HTTP/1.1" 200 OK
```

On the LND side nothing paid out as it seems the callback URL is failing

### JSON response if I try to replay the above on console

```
{"status":"ERROR","reason":"Link not working"}
```

**Comment by arcbtc** [comment]
Have you tried latest? Could you make an lnurlwithdraw on legend.lnbits.com and see if that works

**Comment by nolim1t** [comment]
tried on latest too and didnt work. let me try on legend

**Comment by darthginger** [comment]
Same. I'm using git version: 120952614772c85e118e44646d784230c6e0b25e with LndRestWallet and every external wallet says something like "Link not working".
If i create a "user2" on my lnbits and try to redeem the LNRULw from "user1" it works!

Additional info:
Everything is over clearnet https and i use nginx as reverse proxy with this config as a template: https://community.getumbrel.com/t/how-to-configure-umbrel-lnbits-app-without-tor/604

and this command to start lnbits:
`./venv/bin/uvicorn lnbits.__main__:app --host 0.0.0.0 --port 5000 --forwarded-allow-ips \*`

PostgresQL 14
lnd 0.14.2

**Comment by nolim1t** [comment]
Created another user and still not working.

Setup is behind nginx and building docker image from source

**Comment by darthginger** [comment]
Ok it is actually working. This was my problem: All the wallets say "Link not working" but what they actually mean is: "Source wallet can't be drained by 100%, you need to have reserves for fees". VERY confusing.

**Comment by ademar111190** [comment]
I'm getting the same problem:

```bash
curl -X GET https://legend.lnbits.com/withdraw/api/v1/lnurl/cb/jq6XzeWyRPWUEFyhMQJmF5\?k1\=GvpjZdsdBUxHoiEgRG5bgH\&pr\=lnbc100n1p3vt36app54xj4qrm94nuwvtv3v8vt9mj8cm9q7rrvwzvllzvdehywvcqzp36qd2hyp7q55rjd9hxxetnd9hxscfqyp7zq6r5w3c8xw309aehgmmjv9nk2tn8dahkwmr9v9cxjuewvdhk6tmydamkumr0v9jz7um5daexzem99amrztmz9a38yet90gkhgetrdphx7mr0vaujuctswpehqmm59e3k7mf0duhnsvmrxqjny33hxcunyffjgcmxyerz8y6nqepcxqun2vpev56x2drrxvmngcfkxq6rjenp8pjrxetyxs6xzctp89jrxwphvsungcfnv9nrqvnyv9jzuurwvulkwetwv4exzarfdahr6vfkx56ngwfj8qungwp4x56rgvexv9k8g0tdv4jxjcgcqzpgxqrrssrzjqvgptfurj3528snx6e3dtwepafxw5fpzdymw9pj20jj09sunnqmwqz60fuqq4vgqqqqqqqlgqqqqqqgq9qsp522vd0x9x4f3scs3kryf2jnr58tkvkw6rafxdgl25hg4hlprmgwlq9qyyssqhhmg697za7fmqk722vn8gx970hejug3aacnkge0j04v3sugn44gn89ccn8fxh8sxrqemwlk3awf6n9nyfz20uekvud38rd999z55t9qp7g67m6
```

It is retuning a 200 with the following body:

```json
{"status":"ERROR","reason":"Link not working"}
```

> Ok it is actually working. This was my problem: All the wallets say "Link not working" but what they actually mean is: "Source wallet can't be drained by 100%, you need to have reserves for fees". VERY confusing.

If that is the case I think lnbit should return that message as reason on error body, it would make clear to the user.

**Comment by ok300** [comment]
Getting the same error on the latest https://legend.lnbits.com at commit https://github.com/lnbits/lnbits-legend/commit/d96ac5f3ef29142f082e4dd80849736203eabd64

@darthginger said:

> All the wallets say "Link not working" but what they actually mean is: "Source wallet can't be drained by 100%, you need to have reserves for fees". VERY confusing.

Checked, not the case here. Had a test wallet with 100 sats, made a withdraw link for exactly 10 sats, failed with that error.

**Comment by BenGWeeks** [comment]
Also seeing this. Any progress on this?
