### ISSUE TITLE
Stuck payments with temp_ checking ID

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#571]
Some outgoing payments (observed with LndRestWallet) get stuck (due to "no route" error from the backend?) but the temp_ netries are not deleted from the database. 

These entries will stay in the database forever since they are not checkable.

**Comment by talvasconcelos** [comment]
Related to #558 ?

**Comment by motorina0** [comment]
This kind of issue is deprecated with this PR https://github.com/lnbits/lnbits/pull/2537
