### ISSUE TITLE
LnUrl-Auth no longer working

### ISSUE THREAD

**Issue by decentropy** [lnbits/lnbits#585]
I've been using LnBits to authenticate with LnUrl-Auth, but it no longer works.

I can replicate the issue at https://legend.lnbits.com/ 
(I'm using Umbrel app, and I noticed after upgrading to Umbrel 0.4.17)

I have tested with:
- https://lnmarkets.com/
- https://pro.kollider.xyz/
- https://lnurl-toolbox.degreesofzero.com/

These used to process the LNURL, then prompt for login... but now it just shows a red bar and does nothing.
Were there any changes to LnBits causing this? (I didn't see in release logs)

Appreciate any help... because _this issue means my funds are locked on third parties_.

**Comment by Darth-Coin** [comment]
Did you tried with Alby? For me for example works nice with Alby.

I have some kind of same situation, but I didn't updated umbrel to 4.17 I am still on 4.15.
What I have is my lnbits from umbrel in clearnet, behind a nginx proxy.
All works fine, I can make invoices, pay them, but none of LNURL or QR code can be scanned, it return wrong host, like lnbits.domain.com/IP/api/etc.... so is adding that IP after the domain.

**Comment by dni** [comment]
i tried it and i get `'types.SimpleNamespace' object has no attribute 'wallet'`

**Comment by talvasconcelos** [comment]
Fixed in #757
