### ISSUE TITLE
lnbits.org link in README.md returns 404

### ISSUE THREAD

**Issue by kristapsk** [lnbits/lnbits#598]
![image](https://user-images.githubusercontent.com/4500994/163711558-ba07c163-f4c4-4075-92ab-6674a0a16e2d.png)

**Comment by GlenCooper** [comment]
Still seeing the same.  Was about to open an issue for it, but checked for any others already reporting it, found this.  Holy.  This was first reported in April.  It's now July.

What can we do to help get this fixed up?
![Screenshot from 2022-07-02 16-24-06](https://user-images.githubusercontent.com/967793/177008809-2f01bade-e61f-4156-a2f3-4b17f31d0c20.png)

If the github pages link cannot be fixed for whatever reason, where else can one find the lnbits API documentation?
Proof that the https://lnbits.org/ site was 404'ing: https://archive.ph/2dAkf
