### ISSUE TITLE
c-lightning listinvoices uses wrong argument

### ISSUE THREAD

**Issue by losnappas** [lnbits/lnbits#60]
Alright, I think I found it this time.

https://github.com/lnbits/lnbits/blob/master/lnbits/wallets/clightning.py#L25

C-lightning uses `label` with `listinvoices`: https://lightning.readthedocs.io/lightning-listinvoices.7.html , and the current thing is trying to fetch the invoice by using `checking_id` which is `payment_hash` (I think), which returns nothing. I changed
```python
return InvoiceResponse(ok, checking_id, payment_request, error_message)
```
to
```python
return InvoiceResponse(ok, label, payment_request, error_message)
```
and things started to work correctly.

**Comment by losnappas** [comment]
It looks like `listsendpays` uses `payment hash`, not `label`, so the change I suggested breaks payments...

**Comment by fiatjaf** [comment]
Should have been fixed here: https://github.com/lnbits/lnbits/pull/43
Please let me know if not.
