### ISSUE TITLE
Some payments do not deduct the routing fees from the wallet balance

### ISSUE THREAD

**Issue by mrbitcoiner** [lnbits/lnbits#611]
I've sent some transactions from my lnbits instance, using Spark wallet (sparko plugin c-lightning) as funding source.
Some of the transactions in the LNBITS database has the fee field empty. 
Checking the invoice in the Spark I can see that my node paid the routing fees. This can be used to 'steal' funds from the server.
I don't know if the problem is in the LNBITS payment checking or in the spark wallet.

Observation: The invoices were paid using the lnbits api.

The commit version that I'm using is: 2f381960a07d62e5da16e721bedd77e881095b82

**Comment by callebtc** [comment]
Hey! You say that only _some_ payments are affected. Do you know why? 

I checked the code and the fee subtraction looks ok. @fiatjaf might have an idea what's going on.

**Comment by mrbitcoiner** [comment]
> Hey! You say that only _some_ payments are affected. Do you know why?
> 
> I checked the code and the fee subtraction looks ok. @fiatjaf might have an idea what's going on.

I really don't know the reason, but the invoices were paid sequentially, in a interval of ~ 1 hour. The first three payments (between 100K - 200K sats) do not deducted fees from the balance. The last three payments (<20K sats) deducted the routing fees normally.

After this, I've paid some invoices between 100K - 200K sats and the fee was deducted from the wallet balance normally. This is not a problem that happens every time.

**Comment by mrbitcoiner** [comment]
I really suggest for the ones that are using spark/sparko as funding source to verify this. If you're running LNBITS in a dedicated node, the difference between the sum of the wallet balances and node outbound capacity must keep equal when receiving and sending payments from the LNBITS instance. If the sum of the wallet balances increase and the node outbound decrease, there's a signal that some lnbits transactions does not deducted the fees from the wallet balances.

**Comment by mrbitcoiner** [comment]
Example: 

day 1: the node have 1 000 000 sats outbound and the sum of wallet balances is 500 000 sats; Difference of 500 000 sats

day 2: the node have 900 000 sats outbound and the sum of the wallet balances is 395 000 sats; Difference of 505 000 sats;

In the day 2, probably 5K sats of routing fees were not contabilized in the lnbits apipayments.fee field, if it keeps happening, you will become insolvent.

**Comment by mrbitcoiner** [comment]
> @mrbitcoiner can you post some screenshots of you transactions as they show in your LNbits wallet and the outputs from `listpays` for each of them on `lightning-cli`?

Attaching the prints. Note that the fees inside red rectangle I've changed manually because the value was null.
<img width="1099" alt="Screen Shot 2022-05-03 at 11 21 51" src="https://user-images.githubusercontent.com/91642036/166478694-ed80f925-562a-479c-b991-92e7e234407e.png">
<img width="311" alt="Screen Shot 2022-05-03 at 11 54 16" src="https://user-images.githubusercontent.com/91642036/166478712-d7364026-5c90-4e91-b29b-b4f8ca32ec05.png">
<img width="315" alt="Screen Shot 2022-05-03 at 11 54 27" src="https://user-images.githubusercontent.com/91642036/166478717-5c0ea010-b5ce-4e6c-a6ba-b29dbde519f1.png">
<img width="340" alt="Screen Shot 2022-05-03 at 11 54 38" src="https://user-images.githubusercontent.com/91642036/166478723-23744cc8-609c-46fa-9b7a-b4263fc37b29.png">

**Comment by fiatjaf** [comment]
Interesting. Thank you for that. `null` is different than zero. That's the hint.

**Comment by fiatjaf** [comment]
But actually I have no idea. In none situation at all that field was permitted to be null from what I'm seeing.

**Comment by mrbitcoiner** [comment]
Correcting. When this issue happens, the apipayment.fee is set 0, and not null. You're right, there are different things.

Another example in attach.
<img width="1087" alt="Screen Shot 2022-05-03 at 14 32 54" src="https://user-images.githubusercontent.com/91642036/166508158-6283b4c5-37c8-4022-aee3-ade15467f373.png">
<img width="290" alt="Screen Shot 2022-05-03 at 14 36 29" src="https://user-images.githubusercontent.com/91642036/166508162-0671479a-de34-4600-8fc5-0de2639544d0.png">

**Comment by mrbitcoiner** [comment]
@fiatjaf I think I found the reason. When the node is trying to pay the invoice, the LNBITS change the fee of the pendent payment from 1% of the invoice amount to 0. After the settlement of the payment, the pendent field changes to false but the fee field keeps at 0.

**Comment by mrbitcoiner** [comment]
This happened again two times in the last three hours.

**Comment by mrbitcoiner** [comment]
<img width="495" alt="Screen Shot 2022-05-06 at 15 44 07" src="https://user-images.githubusercontent.com/91642036/167199728-bebcc66b-65a5-454d-a79e-799ca491e035.png">
<img width="974" alt="Screen Shot 2022-05-06 at 15 45 32" src="https://user-images.githubusercontent.com/91642036/167199732-76148768-cdf3-42a6-86a8-5add3b48824c.png">
<img width="272" alt="Screen Shot 2022-05-06 at 15 48 01" src="https://user-images.githubusercontent.com/91642036/167199735-d8aaf76b-0b88-4755-8297-de0864e37f41.png">

**Comment by fiatjaf** [comment]
What version of c-lightning are you running?

**Comment by fiatjaf** [comment]
436c3dd51ab9347fd399328aaadd7c1f9681aabb might fix it at least partially.

**Comment by mrbitcoiner** [comment]
The issue persists. The problem is that when the payment have a huge delay to settle, the fee is not updated when the payment is set to completed (pending = false). But now, at least when the bug happens, the fee field will be 1% of the payment, which is the limit for the routing fee. Anyway, we have to fix this.
