### ISSUE TITLE
Feature request: LNBits webhook should be able to send to a tor address

### ISSUE THREAD

**Issue by mach5mach** [lnbits/lnbits#615]
Please see the description at this link.

https://github.com/getumbrel/umbrel-apps/issues/589

**Comment by mach5mach** [comment]
https://github.com/lnbits/lnbits-legend/blob/a00e46f629696e054321ce03fa1c91b3a2fe832f/lnbits/core/tasks.py#L51

Here is the section where the webhook is dispatched.  It looks like the httpx.AsyncClient() does not specify a proxy so it cannot send to a tor address.

According to the documentation here, it's trivial to add a proxy to this request call.
https://www.python-httpx.org/advanced/#http-proxying

**Comment by mach5mach** [comment]
Change ```async with httpx.AsyncClient() as client:``` to
```proxies = {
    "all://*.onion*": "http://torproxy:8030",
}
async with httpx.AsyncClient(proxies=proxies)
```

**Comment by mach5mach** [comment]
This should allow all clearnet calls to pass through without using the proxy but make the .onion requests use the torproxy docker service.  We'll need to know the torproxy port number but I'm not sure how to retrieve that.  Can someone help me find how to get the torproxy docker service specified port?

**Comment by mach5mach** [comment]
looks like the proxy address and port can be retrieved from environment variables per the docker-compose.yml
https://github.com/getumbrel/umbrel/blob/c630cd9f27ac955631ba1f4570e24ab319fadc63/docker-compose.yml#L130

TOR_PROXY_IP: "${TOR_PROXY_IP}"
TOR_PROXY_PORT: "${TOR_PROXY_PORT}"

**Comment by mach5mach** [comment]
so with that in mind the full code should look like this
```
...
import os
async def dispatch_webhook(payment: Payment):
proxies = {
    "all://*.onion*": "http://{}:{}".format(os.getenv('TOR_PROXY_IP'), os.getenv('TOR_PROXY_PORT')),
}
async with httpx.AsyncClient(proxies=proxies)
...
```

**Comment by callebtc** [comment]
I'm currently working on [PR #678](https://github.com/lnbits/lnbits-legend/pull/678) which would easily enable this via Tor (almost out-of-the box). I will add webhooks to the todo list!

You could test it already if you want, just `git checkout wallets/tor` and adjust the lines you've mentioned above:

> Change `async with httpx.AsyncClient() as client:` to
> 
> ```
> proxies = {
>     "all://*.onion*": "http://torproxy:8030",
> }
> async with httpx.AsyncClient(proxies=proxies)
> ```

Btw, I didn't know that you could filter for proxies given a URL pattern, very cool, I should think about whether this makes sense for the PR above as well!

**Comment by mach5mach** [comment]
Hey thanks for working on this.  Can't wait for the release.
