### ISSUE TITLE
REDACTED

### ISSUE THREAD

**Issue by thecharacter** [lnbits/lnbits#621]
REDACTED

**Comment by thecharacter** [comment]
Awesome thanks a lot, you all are killing it with this open source project and my Bitcoin t-shirts with this urls really gets kids excited about learning about Bitcoin.

The attached URL is the one that is on the t-shirt and get the attached error. That's the url that needs to be forwarded to legend.lnbits.com. Its still pointing to the old withdraw link https://lnbits.com/withdraw/XzUFDSC8DsWkwxfGE7fq6Q



Thanks a lot I really appreciate it. Let me know if you need additional information.



________________________________

**Comment by talvasconcelos** [comment]
Can it be closed? @thecharacter ?

**Comment by thecharacter** [comment]
Hi,
Not yet, the LNURLw QR still link to the old lnbits.com. It needs to be forwarded to legend.lnbits.com
![Original LNBits com QR Code](https://user-images.githubusercontent.com/70460811/198704798-09f7148f-244d-44c7-b504-69a476c0ad26.png)

Here's the error when scanned from my Zeus wallet
![IMG_E6A9731DE9BB-1](https://user-images.githubusercontent.com/70460811/198705815-0ab772ff-3f01-4f7c-b844-6886e81532c8.jpeg)

Here was the original LNURLw link
https://lnbits.com/withdraw/XzUFDSC8DsWkwxfGE7fq6Q   

I can give the wallet info if you need it. Let me know if you need anything else.

Thanks

**Comment by talvasconcelos** [comment]
@arcbtc ?

**Comment by prusnak** [comment]
This is not really a LNbits bug or issue, it's an issue with the deployment at lnbits.com.

Also it seems there is very little will to get this fixed. I suggest you print a new QR code @thecharacter 

Let's close it here.
