### ISSUE TITLE
Latest version does not support LndWallet as back end wallet.

### ISSUE THREAD

**Issue by trbouma** [lnbits/lnbits#626]
I get this error when starting up a Docker container built with the latest version.

 File "./lnbits/settings.py", line 14, in <module>
   wallets_module, env.str("LNBITS_BACKEND_WALLET_CLASS", default="VoidWallet")
AttributeError: module 'lnbits.wallets' has no attribute 'LndWallet'

It worked and continues to work with a version I had built a Docker container with a few months ago (I just confirmed).

Is the LndWallet (gRPC) still supported or is this an error?

Thanks!

**Comment by callebtc** [comment]
Hi! `LndWallet` was disabled for the time being because the RPC for LND was stupid and didn't allow us to (easily) add a fee reserve. Maybe this has changed? @fusion44 do you think we can add it back?

I would suggest you use the `LndRestWallet` if you can.

**Comment by trbouma** [comment]
Thanks. I couldn't get LndRestWallet to work with my Voltage node or my local instance, so I hacked backed in LndWallet libraries. I also added to my Docker image that I use for Heroku. It also works fine. 

If I can get LndRestWallet working, I would be happy (maybe a stupid config error on my part), but in the meantime it would be great to add back in and acknowledge there is an issue with the fee reserve.

**Comment by fusion44** [comment]
I'll take a look at this over the coming weekend.

**Comment by talvasconcelos** [comment]
@callebtc this is fixed now, right? Can it be closed?

**Comment by jr21M** [comment]
it's working for me

**Comment by dni** [comment]
yes LndWallet works an runs in regtest. https://github.com/lnbits/lnbits/actions/runs/6108558519/job/16577888901
