### ISSUE TITLE
Installation Fails on myNode

### ISSUE THREAD

**Issue by tehelsper** [lnbits/lnbits#65]
I've got a request and a bug.

First, can you tag releases separately? It looks like the raspiblitz tag was updated to a new version but kept the same name. That made myNode automatically pull it in during an upgrade without explicitly bumping the version.

Second, the new version seems to have an installation issue. A user reported it and I was able to reproduce the issue.

Here is the log:

```
Installing initially failed dependencies…
[InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/cli/command.py", line 252, in install
[InstallError]:       site_packages=state.site_packages
[InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 2062, in do_install
[InstallError]:       keep_outdated=keep_outdated
[InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 1314, in do_init
[InstallError]:       pypi_mirror=pypi_mirror,
[InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 901, in do_install_dependencies
[InstallError]:       retry_list, procs, failed_deps_queue, requirements_dir, **install_kwargs
[InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 796, in batch_install
[InstallError]:       _cleanup_procs(procs, failed_deps_queue, retry=retry)
[InstallError]:   File "/usr/local/lib/python3.7/site-packages/pipenv/core.py", line 703, in _cleanup_procs
[InstallError]:       raise exceptions.InstallError(c.dep.name, extra=err_lines)
[pipenv.exceptions.InstallError]: Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
[pipenv.exceptions.InstallError]: Collecting gevent==20.6.2
[pipenv.exceptions.InstallError]:   Using cached gevent-20.6.2.tar.gz (5.8 MB)
[pipenv.exceptions.InstallError]: ERROR: Disabling PEP 517 processing is invalid: project specifies a build backend of setuptools.build_meta:__legacy__ in pyproject.toml
ERROR: Couldn't install package: gevent
 Package installation failed...
```

**Comment by arcbtc** [comment]
We should make a separate mynode tag.
When it upgrades is it running "flask migrate"? I added a couple of exensions that need the DBs to be built

**Comment by tehelsper** [comment]
Here are the upgrade steps. Ideally, I would like a consistent solution where none of the commands fail in the normal successful case. Even the flask migrate step has a tendency to fail and I've had to run it multiple times.

It was failing on the 3rd line.

sudo -u bitcoin pipenv --python 3.7 install
sudo -u bitcoin pipenv run pip install python-dotenv
sudo -u bitcoin pipenv run pip install -r requirements.txt
sudo -u bitcoin pipenv run flask migrate || true

**Comment by arcbtc** [comment]
Ah, 
I see @eillarra  has changed the requirements.txt, https://github.com/lnbits/lnbits/commit/bc984ab0dbb56030c4c40ce0c2aef2ef22af9c6a
Then I updated the tag.

**Comment by eillarra** [comment]
@tehelsper give me a day to check this. I will look into it tomorrow

**Comment by arcbtc** [comment]
Any luck @eillarra ?

**Comment by arcbtc** [comment]
Thanks @eillarra! 
I updated the raspiblitz tag as well, so we should be good to go. I'm not running mynode, so if you could test @tehelsper that would be great. 
Once you tell us its working well, we can make a mynode tag, and give you plenty of warning before updating

**Comment by tehelsper** [comment]
Looks good! The install went smoothly and the app launched to the point I can access the UI and add a wallet.

**Comment by arcbtc** [comment]
Ace! I'll make a Mynode tag later today, and it gives me an excellent excuse to run Mynode!
