### ISSUE TITLE
LNURLDevice: Callback URL scheme

### ISSUE THREAD

**Issue by dennisreimann** [lnbits/lnbits#656]
I'm running LNbits v0.8.0 with the LNURDevice extension and am using the latest LNPoS version to connect to it.

I noticed that the LNURL callback URL scheme is `http`, though the LNURL API request is called with `https`. [Example](https://lnbits.decentralbank.eu/lnurldevice/api/v1/lnurl/3roJrW4RFzFRuT5kxG2MFK?p=AQhJhptjtHNfYgUQgw0awhojxMs6hNfi)

Also the resulting `successAction.url` is `http`, even when called with `https`, see this [example](http://lnbits.decentralbank.eu/lnurldevice/api/v1/lnurl/cb/4mWHAnvA8xwvi59KGVddcV).

Same is true for the LNURL-Withdraw URLs.

**Comment by schneimi** [comment]
Hi, there is an env var that must be set true. Unfortunately I cannot look it up right now and I don't remember it fully, something like FREE and IP. Sorry, but maybe that gives you a hint in the right direction.

**Comment by dennisreimann** [comment]
The [example env](https://github.com/lnbits/lnbits-legend/blob/main/.env.example) doesn't contain anything along those lines, but it has a `LNBITS_FORCE_HTTPS` setting. I'm running LNbits as an app on Umbrel, will need to dig a bit to find how this is configurable there.

However, I think the proper way to solve it is to pick up the scheme, host, port and basepath of the incoming request and respond with the same. I'd be willing to do a PR, but it seems to be a bit more involved and I'd appreciate more pointers on how to handle this properly.

**Comment by schneimi** [comment]
Ok , found it in #470. It's not a LNBITS env.
`FORWARDED_ALLOW_IPS: "*"`

Yes, it would help alot if there would be better HTTPS support by default. Had a hard time as well to find out about this.
