### ISSUE TITLE
Frontent: LNURLp fiat amount with 0.2f decimal precision

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#676]
![telegram-cloud-photo-size-2-5303456549911509482-y](https://user-images.githubusercontent.com/93376500/175007844-bd6ea344-68e6-4999-b927-0c194e68d8a3.jpg)

Dirty fiat likes to be denominated in 2 digit decimal precision. Would be nice to have.

**Comment by callebtc** [comment]
Bumping this tiny issue. Anyone wanna have a look at this? @fusion44 or @talvasconcelos?

**Comment by talvasconcelos** [comment]
Fixed in #663
