### ISSUE TITLE
Extension to create a multi usage QR code

### ISSUE THREAD

**Issue by ChuckNorrison** [lnbits/lnbits#68]
It could be possible to create a common QR code and everytime this code gets scanned, a lnbits url gets opened with a freshly generated invoice to pay with an amount configured to the multi usage QR code

**Comment by ChuckNorrison** [comment]
This code can be printed and used for longer time periods to get stuff paid like coffee and snacks :)

**Comment by arcbtc** [comment]
Lovely idea, and exactly what lnurl-pay is for. @fiatjaf is working on an extension for LNURL-pay, and says it will be ready next monthish

**Comment by ChuckNorrison** [comment]
oh great, i did not started yet. Thanks for your response, i will close that :)

**Comment by fiatjaf** [comment]
Done here: https://github.com/lnbits/lnbits/pull/43

**Comment by ChuckNorrison** [comment]
Tested this with 500 Internal Server Error after enable LNURLp extension. After form got filled and CREATE PAY LINK was pressed, 500 is thrown

> admin@raspberrypi /home/lnbits/lnbits $ sudo systemctl status lnbits 
> ● lnbits.service - lnbits
>    Loaded: loaded (/etc/systemd/system/lnbits.service; enabled; vendor preset: enabled)
>    Active: active (running) since Sat 2020-08-29 19:46:27 BST; 1min 17s ago
>  Main PID: 9434 (sh)
>     Tasks: 4 (limit: 4915)
>    CGroup: /system.slice/lnbits.service
>            ├─9434 /bin/sh -c cd /home/lnbits/lnbits && pipenv run gunicorn -b 127.0.0.1:5000 lnbits:app -k gevent
>            ├─9436 /home/lnbits/.local/share/virtualenvs/lnbits-xqYMrTZ5/bin/python3.7m /home/lnbits/.local/share/virtualenvs/lnbits-xqYMrTZ5/bin/gunicorn -b 127.0.0.1:5000 lnbits:app -k gevent
>            └─9593 /home/lnbits/.local/share/virtualenvs/lnbits-xqYMrTZ5/bin/python3.7m /home/lnbits/.local/share/virtualenvs/lnbits-xqYMrTZ5/bin/gunicorn -b 127.0.0.1:5000 lnbits:app -k gevent
> 
> Aug 29 19:47:34 raspberrypi sh[9434]:     return self.view_functions[rule.endpoint](**req.view_args)
> Aug 29 19:47:34 raspberrypi sh[9434]:   File "/home/lnbits/lnbits/lnbits/decorators.py", line 24, in wrapped_view
> Aug 29 19:47:34 raspberrypi sh[9434]:     return view(**kwargs)
> Aug 29 19:47:34 raspberrypi sh[9434]:   File "/home/lnbits/lnbits/lnbits/extensions/lnurlp/views_api.py", line 33, in api_links
> Aug 29 19:47:34 raspberrypi sh[9434]:     jsonify([{**link._asdict(), **{"lnurl": link.lnurl}} for link in get_pay_links(wallet_ids)]),
> Aug 29 19:47:34 raspberrypi sh[9434]:   File "/home/lnbits/lnbits/lnbits/extensions/lnurlp/crud.py", line 47, in get_pay_links
> Aug 29 19:47:34 raspberrypi sh[9434]:     rows = db.fetchall(f"SELECT * FROM pay_links WHERE wallet IN ({q})", (*wallet_ids,))
> Aug 29 19:47:34 raspberrypi sh[9434]:   File "/home/lnbits/lnbits/lnbits/db.py", line 23, in fetchall
> Aug 29 19:47:34 raspberrypi sh[9434]:     self.cursor.execute(query, values)
> Aug 29 19:47:34 raspberrypi sh[9434]: sqlite3.OperationalError: no such table: pay_links

**Comment by fiatjaf** [comment]
You must run `flask migrate` first to create the table.

I'm not sure how is your setup there but maybe there, but I'm hoping you'll know how to do this. Is that the raspiblitz?

**Comment by ChuckNorrison** [comment]
thats right, iam using the raspiblitz 1.6. The flask migrate command was not found. Flask seems to work.

**Comment by fiatjaf** [comment]
That is a bug, sorry, will fix it soon.

**Comment by fiatjaf** [comment]
_Now_ it should be good.

**Comment by ChuckNorrison** [comment]
Thanks the 500 throws are gone and i was able to create that LNURLp. Seems the format is not accepted, herre my LNURLp:

> LNURL1DP68GURN8GHJ7MRFVA58GMNFDENHWCTVDDJHYTNYW43KKERWWVHX7UN89AKXUATJD3CZ7CTSDYHHVVF0D3H82UNV9UCSLETSVY

**Comment by ChuckNorrison** [comment]
Another finding: LNURLw extension results in an empty html response if Enabled and clicked from Extension list

**Comment by ChuckNorrison** [comment]
Wallets tested with this LNURLp QR code:
- ZAP Android can read invoice correctly 
- Phoenix Invalid
- Eclair Invalid
- Lightning Android can read (with wrong memo!)
- Wallet of Satoshi Invalid
