### ISSUE TITLE
pagination in all api's

### ISSUE THREAD

**Issue by sawrubgupta** [lnbits/lnbits#702]
I think we have to we have to add pagination on dashboard side and to all list api also, because I think without pagination dashboard data loads slower than usual.
what we are gonna do when are about to load half million list of transactions. maybe it will lot of time if you go through current approach !

**Comment by callebtc** [comment]
Absolutely agreed. There is one already for `/api/v1/payments` btw, with `limit` and `offset`.

**Comment by dni** [comment]
i just found something
https://uriyyo-fastapi-pagination.netlify.app/
i think i try to implement that one.

**Comment by sawrubgupta** [comment]
calle if we have pagination in `/usermanager/api/v1/transactions/{wallet_id}` in this, let me know, thank you !

**Comment by dni** [comment]
this has been solved by by the `class Filters` in db.py, a PR from @jackstar12   https://github.com/lnbits/lnbits/pull/1557
