### ISSUE TITLE
Add `tag` field to payments to link them with extensions

### ISSUE THREAD

**Issue by fiatjaf** [lnbits/lnbits#72]
What do you think of adding a "tag" field to payments -- incoming or outgoing -- for extensions to fill in themselves, so in the main payments table view we could should the extension icon along with each invoice/payment and improve the user experience?

Should we also have an `extra` field that would support extra metadata in each payment or something like that?

**Comment by ChuckNorrison** [comment]
i would love to see a hashtag like filter on my payments list or some grouping based on tags or memo... maybe a bubble with most frequent tags/memos to filter the incoming/outgoing payments? 

Its hard to implement those things without destroying that slick interface. It needs to be clean, but maybe it could be possible to get those features on a bit hidden expand icons somewhere.

**Comment by fiatjaf** [comment]
Actually this is being done in an informal way already by extensions, it's probably better to not mess with it and instead rely on it.

But other use-cases for tags are possible now that we have an `extra` field with arbitrary data in it.

**Comment by eillarra** [comment]
I wanted to have this but @arcbtc said it was not needed :) he might have some hidden reason for it...
My idea was just the same, so transactions generated by the extensions could show some tag/icon and we could use filters in the main table... I ended up using a "#hashtag" in the memo itself, as a convention.

**Comment by ChuckNorrison** [comment]
Iam fine with the history, its great with csv export and the use case to analyze your mikro transaktions backwards is not as common. The interface should kept slick and easy as possible in my opinion. Each additional feature should be a bit hidden to not distract new users on the first try

**Comment by fiatjaf** [comment]
@eillarra I will implement this and merge it without him seeing it. And wreak havoc in this repository until my commit powers are forcibly removed.
