### ISSUE TITLE
/api/v1/wallet doesn't show updated balance after making a payment

### ISSUE THREAD

**Issue by blackcoffeexbt** [lnbits/lnbits#726]
Detailed for @callebtc 

This has been experienced on Voltage's LNbits install and has not been reproduced on legend.lnbits.com. Not tested elsewhere.

After making a LN payment, querying a wallet's balance does not show the updated balance until either the Web UI has been refreshed or a call to /api/v1/payments has been made.

**Steps to reproduce**
1. View balance `curl -X GET https://38095bf851.d.voltageapp.io/api/v1/wallet -H "X-Api-Key: b9acb5b6716d4a5f8c66f080178cbe05"`
2. Pay this LNURLp `LNURL1DP68GURN8GHJ7VECXQUN2CNX8Q6NZTNY9EMX7MR5V9NK2CTSWQHXJME0D3H82UNVWQHKZURF9AMRZTMVDE6HYMP0XGUTR9M7`
3. View balance unchanged `curl -X GET https://38095bf851.d.voltageapp.io/api/v1/wallet -H "X-Api-Key: b9acb5b6716d4a5f8c66f080178cbe05"` 
4. Request payments API endpoint `curl -X GET https://38095bf851.d.voltageapp.io/api/v1/payments -H "X-Api-Key: b9acb5b6716d4a5f8c66f080178cbe05"`
5. View updated balance `curl -X GET https://38095bf851.d.voltageapp.io/api/v1/wallet -H "X-Api-Key: b9acb5b6716d4a5f8c66f080178cbe05"`

**Comment by blackcoffeexbt** [comment]
Voltage released an update for lnbits which I applied and it seems to have resolved this issue. Closing for now...

**Comment by diskbuster** [comment]
Can you tell what you applied to fix this?

**Comment by blackcoffeexbt** [comment]
This is still an issue on main as reported by @diskbuster

**Comment by diskbuster** [comment]
Issue is solved! when using lnbits as an backend for lnbits, the backend should also be at least the latest version also!

**Comment by blackcoffeexbt** [comment]
Now resolved.

**Comment by sutt** [comment]
Just replicated this running "LNbits version: 0.11.3" on Voltage.
As @blackcoffeexbt described, hitting the `/api/v1/payments/` endpoint finally made the updated balance show up.
Oddly, the balance _would_ update for invoices paid from another lnbits wallet (on the same node as wallet creating invoice). But balance would _not_ update when paid from Breeze mobile wallet (even though payment success is confirmed by both mobile wallet and LND node).

**Comment by prusnak** [comment]
> Just replicated this running "LNbits version: 0.11.3" on Voltage.
> 
> As @blackcoffeexbt described, hitting the `/api/v1/payments/` endpoint finally made the updated balance show up.
> 
> Oddly, the balance _would_ update for invoices paid from another lnbits wallet (on the same node as wallet creating invoice). But balance would _not_ update when paid from Breeze mobile wallet (even though payment success is confirmed by both mobile wallet and LND node).

0.11.3 is very old

Try reproducing with recent version. If this is still issue with the latest, please reopen.

**Comment by edwalpca** [comment]
I have a issue with my LNbits solution under SaaS, integrated with OpenNode. I can give you more details. When I send money to a wallet like CoinBase or BitJungle, the money is credited to those wallets, and the withdrawal is registered in OpenNode, but in LNbits (the SaaS solution - which is not self-hosted), that transaction appears in LNbits as **failed**, and therefore it is not deducted from the wallet balance in LNbits. Another important detail is the following: OpenNode does not have individual accounts; it has a single general balance, whereas LNbits has the wallets for each user. How can this situation be solved?

**Comment by motorina0** [comment]
This GitHub issue is very old and unrelated to the problem.

@edwalpca please join the official LNbits Telegram channel and do an @motorina0 (same ID as this github one)
