### ISSUE TITLE
click on LNURLw extension results in a blank page

### ISSUE THREAD

**Issue by ChuckNorrison** [lnbits/lnbits#73]
After update to the current version (LNURLp was added), the LNURLw Extension might be broken.

I observed a reference error in my web-console:

> ReferenceError: simplecloseFormDialog is not defined
>     VueJS 10
>         anonymous
>         _render
>         r
>         get
>         fn
>         mount
>         $mount
>         $mount
>         _init
>         wn
>     <anonymous> https://xxx.xxx.org/static/__bundle__/withdraw/index.js?81aae472:11
> vue.js:12:11752

> ReferenceError: simplecloseFormDialog is not defined
>     VueJS 15
>     getWithdrawLinks https://xxx.xxx.org/static/__bundle__/withdraw/index.js?81aae472:12
>     promise callback*getWithdrawLinks https://xxx.xxx.org/static/__bundle__/withdraw/index.js?81aae472:12
>     checker https://xxx.xxx.org/static/__bundle__/withdraw/index.js?81aae472:29
> vue.js:12:11752
.

**Comment by fiatjaf** [comment]
Oops, it seems I did something very wrong this time.
