### ISSUE TITLE
Fix `api_payment` key check

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#734]
Fix this abomination:

```python
async def api_payment(payment_hash, X_Api_Key: Optional[str] = Header(None)):
    # We use X_Api_Key here because we want this call to work with and without keys
    # If a valid key is given, we also return the field "details", otherwise not
    wallet = None
    try:
        if X_Api_Key.extra:
            print("No key")
    except:
        wallet = await get_wallet_for_key(X_Api_Key)
```

Notes:

* Tal: `X_Api_Key is probably never None, this is what I'm getting with print("X_Api_Key", X_Api_Key): X_Api_Key extra={}`
* Me: Change code in screenshot to `X_Api_Key.get("extra") is None`
* Type? Optional[str] is definitely wrong, what's the type of `Header(None)`?

Previous fix

![telegram-cloud-document-4-5900168914372922358](https://user-images.githubusercontent.com/93376500/178772642-88f16990-fb3a-4ff4-b723-132503bd3c04.jpg)

**Comment by talvasconcelos** [comment]
Closeable, @callebtc ?

**Comment by talvasconcelos** [comment]
closed for inactivity
