### ISSUE TITLE
Code health: Refactor LNURL operations into separate files

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#756]
LNURL functions are scattered all around the code base. Ideally they should be refactored out of 

```
lnbits/tasks.py
lnbits/core/models.py
lnbits/core/services.py
lnbits/core/views/api.py
lnbits/core/views/public_api.py
lnbits/core/views/generic.py
```

This would also present an excellent opportunity to write integration tests for LNURL.

**Comment by motorina0** [comment]
@dni you have done this, correct?

**Comment by dni** [comment]
soon :) https://github.com/lnbits/lnbits/pull/2536
