### ISSUE TITLE
remove websockets module from lnbits/wallets/eclair.py

### ISSUE THREAD

**Issue by dni** [lnbits/lnbits#764]
after discussion with @callebtc we wonder why websockets is used there, it would be best to remove it.

it throws mypy errors because of https://github.com/aaugustin/websockets/issues/940

[lnbits/wallets/eclair.py](https://github.com/lnbits/lnbits-legend/blob/main/lnbits/wallets/eclair.py#L10)

**Comment by talvasconcelos** [comment]
Eclair uses the API to listen to the wallet! 

Can I close this, as there's a `TODO` note already in the code?
