### ISSUE TITLE
Transfers between wallets of the same user

### ISSUE THREAD

**Issue by fiatjaf** [lnbits/lnbits#82]
If you are a user that has many wallets for different purposes, it could be useful to have a way to distribute your money across your wallets.

Maybe a screen that shows all your wallets with levers for controlling the balance of them all, and then it updates the state internally somehow using a magic trick.

Something like:

```
Total funds: 10000

WalletA |--------------------[]---------| 6000
WalletB |---[]--------------------------| 1000
WalletC |-----------[]------------------| 3000
```

**Comment by ChuckNorrison** [comment]
This could act like the reblance feature in the RTL or Thunderhub. Iam missing that feature too :)

**Comment by fiatjaf** [comment]
No, this one here would be just internal balance readjustment. These other tools are for managing your Lightning node. They're out of the scope of LNbits in my opinion.

**Comment by ChuckNorrison** [comment]
for sure i dont want to balance real channels with lnbits, just the same view like the thunderhub in example shows up how to balance between two points. Select wallet A and Wallet B whyl holding STRG in example will make a "balance" icon visible which can balance the two wallets. 

To make usage of shortcuts for this could be a real usability advantage if touch is supported for mobile. Thats just a try to keep the interface slick and clean

**Comment by fiatjaf** [comment]
Oh, right. So, do you know how to build that UI using Vue and Quasar? I have no idea, but if you write it I can do the backend -- or you do everything if you prefer :)

**Comment by ChuckNorrison** [comment]
I did some research, never heard of the frameworks you are using here, anyway i like it. 

After i found the wallets.html with the mentioned framework in, i did not see much work on that html struct. I would solve this with a javascript part. This should solve the multi selection based on shortcuts/touch and than show a div/view with some interaction to balance the selected wallets. i dont know which way is best to send the desired balance values to the backend and in reverse get out some feedback.

This javascript could handle a shortcut for ctrl key:
```
document.addEventListener('ctrl', function (event) {
    if (event.ctrlKey) {
        
        var element = document.getElementById('balance-wallets');
        element.style.display = 'block';
    }
});
```

Further i found an interesting library for shortcut handling if this project wants to further support some shortcuts.
https://github.com/jeresig/jquery.hotkeys

Touch seems a bit more different and here is a good approach:
https://api.jquerymobile.com/taphold/

Is this some kind of what you would expect?

**Comment by fiatjaf** [comment]
I'm also not well-versed in these frameworks, but I think jQuery stuff won't play well with it.
I also don't understand the "ctrl" stuff well, since I never used RTL or this other app you mentioned.

Anyway, I will try to get this extension done without the cool UI you're suggesting because I'm too dumb for it an it would take me two years, but later someone can come and improve the experience.
