### ISSUE TITLE
Cliché wallet issues

### ISSUE THREAD

**Issue by fiatjaf** [lnbits/lnbits#827]
I see 2 potential issues with [the cliché wallet](https://github.com/lnbits/lnbits-legend/blob/1374aabf926944ebe740eb9833eeaae704711c49/lnbits/wallets/cliche.py):

1. It is using the "human-readable" command format, which makes the implementation bloated  and more error-prone. Probably not a big deal, but the invoice descriptions will break. Instead there is the JSON-RPC interface, in which you instead of `create-invoice --msatoshi 12 --description bla` you write `{"method": "create-invoice", "params": {"msatoshi": 12, "description": "bla"}}`.
2. It is opening a websocket, writing a  command and reading the response immediately after. That is not safe if other commands are being called simultaneously. Cliché will write _all responses_ and also _event notifications_ to _all_ websockets that are open at _anytime_. So to filter for the response you want you must check the id in the response object.

Proposed fix:
- Open a single websocket.
- Write commands to it, Assign a random id to each command called (`{"method": "...", "params": {...}, "id": "892173"}`). Keep track of the id and wait.
- Listen to everything that comes from it. If it has an id that is known, wake up the method that was waiting for it so it can proceed. If it is an invoice paid notification, wake up the paid invoices listener.

I actually also do not know how to do this. I was trying just now, but I realized it would take me about 6 months to learn how to implement the flow above using `asyncio`, so I decided to just open this issue.

**Comment by fusion44** [comment]
FWIW, I've implemented something like this in [Dart](https://github.com/fusion44/dart-ln/blob/master/lib/src/implementations/ln_core/core_rpc/core_rpc_implementation.dart) for Core Lightning. It should not be that hard to do translate to Python asyncio, but can't do it myself at the moment. Most interesting function is the [_sendRequest](https://github.com/fusion44/dart-ln/blob/51aee70dd0e87b98f7f7e8d3bc5ab604bf1a2e13/lib/src/implementations/ln_core/core_rpc/core_rpc_implementation.dart#L304) function. Basically what I do is return a future for each request that will be completed once [_eventStream](https://github.com/fusion44/dart-ln/blob/51aee70dd0e87b98f7f7e8d3bc5ab604bf1a2e13/lib/src/implementations/ln_core/core_rpc/core_rpc_implementation.dart#L67) finds an existing request ID.
