### ISSUE TITLE
LNURL "Uses Left" Not Syncing w/ Wallet Value 

### ISSUE THREAD

**Issue by thecharacter** [lnbits/lnbits#83]
I'm using LNBits.com. In the LNURL "Time Between Withdrawals" field I put 384 hours and now the Withdraw Link "uses left" vs the sats in the wallet is off. I change the "Time Between Withdrawals" back to 1 second but the "uses left" is still off. 

From the images below I should have 11 uses left after I hit the Update Withdrawal button but the "uses left" field only says 3. I would like to continue using this LNURL. Any clues as to why this may be happening? 

![Screen Shot 2020-09-02 at 6 09 38 PM](https://user-images.githubusercontent.com/70460811/94751773-33fce700-033e-11eb-8864-0048046e558e.png)

![Screen Shot 2020-09-02 at 6 10 06 PM](https://user-images.githubusercontent.com/70460811/92061628-a1235980-ed4b-11ea-90ba-84295f296dd8.png)

**Comment by arcbtc** [comment]
I know it sounds silly, but did you refresh the page?

**Comment by thecharacter** [comment]
Yeap, also added more funds too. The withdrawal instance is stuck and will not refresh when I hit update withdrawal link. Every time I withdraw the number is stuck at the amount of times the LNurl has been withdrawn. In the example above the number of times withdrawn is stuck at 8 and will not change when I update the link.
