### ISSUE TITLE
Docs: install guide and Debian service for poetry

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#846]
* Check install guide again, why does the click error appear for some users?
* Debian service for poetry.

**Comment by decentropy** [comment]
click error on ubuntu 20.04.6 LTS

```
$ poetry add click
$ poetry run lnbits
ModuleNotFoundError: No module named 'click'
```

**Comment by dni** [comment]
```poetry install``` add is not needed anymore, can i see some logs? 

it builds just fine in our ubuntu bullseye Dockerfile.
https://github.com/lnbits/lnbits/blob/main/Dockerfile#L1C23-L1C31

**Comment by dni** [comment]
i think the initial issue ETA, aug 2022 is resolved.
