### ISSUE TITLE
Webhooks needed for Paywalls, Tpos, SplitPayments, ....

### ISSUE THREAD

**Issue by nanda77** [lnbits/lnbits#859]
Can we get webhooks for some important extensions like Paywalls, Tpos, SplitPayments, ....?

**Comment by sawrubgupta** [comment]
we merged changes ?

**Comment by dni** [comment]
extension are seperated from core now, can you maybe open feature requests in the corresponding extensions? and close this issue?

**Comment by prusnak** [comment]
Closing.

@nanda77 if you need webhooks in some extension, please open an issue in the repository of that extension.
