### ISSUE TITLE
CLN: invoice status check

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#893]
For CLN only: Incoming invoices that haven't been paid return "Failed" (status `False`) while they should return "In-flight" (status `None`). Failed should be used for invoices that do not exist or are expired.

**Comment by motorina0** [comment]
Handled here: https://github.com/lnbits/lnbits/pull/2396

`get_invoice_status()` returns Failed only if `invoice_resp["status"] == "expired"`
