### ISSUE TITLE
Fix main wallet view layout for mobile screen sizes

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#897]
No comment.

<img src="https://user-images.githubusercontent.com/93376500/185116072-f6741bf2-29c5-456d-8a4d-22b0edcf3837.jpg" width="400" height="790">

**Comment by callebtc** [comment]
in LNURLp view, move pink buttons (NFC and printing)

<img src="https://user-images.githubusercontent.com/93376500/185368901-5ba9425f-fadb-4a05-aaa7-f5844c41e078.jpg" width="400" height="790">

**Comment by dni** [comment]
> in LNURLp view, move pink buttons (NFC and printing)
> 
> <img alt="" width="400" height="790" src="https://user-images.githubusercontent.com/93376500/185368901-5ba9425f-fadb-4a05-aaa7-f5844c41e078.jpg">

this one got fixed by you right?

**Comment by dni** [comment]
> No comment.
> 
> <img alt="" width="400" height="790" src="https://user-images.githubusercontent.com/93376500/185116072-f6741bf2-29c5-456d-8a4d-22b0edcf3837.jpg">

my solution for that would be do not let memo break and give it the space it needs for 1 line, that means you just need to scroll to the right more, but it is 10 times more clear.

![screenshot-1660985475](https://user-images.githubusercontent.com/1743657/185737176-0dcc1d5a-fc19-4281-bc82-f69fc00afd60.jpg)

**Comment by dni** [comment]
another addition, don' t use columns for payment-details

![screenshot-1660988731](https://user-images.githubusercontent.com/1743657/185740073-292adad3-821a-41de-98e3-450d5712fdc1.jpg)
![screenshot-1660988722](https://user-images.githubusercontent.com/1743657/185740074-3817fbec-d34b-4919-8cad-efd396747ffa.jpg)

i leave this pr as is, i think its subjectively better than before, but i do not want get into any design discussion :).

**Comment by dni** [comment]
https://github.com/lnbits/lnbits/pull/1732
