### ISSUE TITLE
Allow free lightning addresses

### ISSUE THREAD

**Issue by cos-it-is** [lnbits/lnbits#901]
On the lightning addresses extension. This should allow for free lightning addresses. Currently the value per day MUST be > 0

**Comment by talvasconcelos** [comment]
Actually the value is set to `greater or equal` to 0!! There's something else going on, as you can have zero value invoices.

I'll take a look into it

**Comment by skrafft** [comment]
Probably linked to this: https://github.com/lnbits/lnbits/issues/549

I just tried to have free lightning addresses as well and it's not possible to pay because we can't pay zero invoices

**Comment by skrafft** [comment]
@schneimi  indeed, I just made a pull request that avoids going in the db by adding a min invoice amount of 1 sat. It's almost free. This pull request includes bug fixes as well and optional cloudflare identifiers: https://github.com/lnbits/lnbits/pull/1060

**Comment by cos-it-is** [comment]
I personally do not think that is the right way to fix this. A user will want to provision these for free to users without the need of any payment at all.

It isn't about making it cheap, it's about the usability of being able to create them for free.
