### ISSUE TITLE
Frontend: Do not show NFC button if browser doesn't support it

### ISSUE THREAD

**Issue by callebtc** [lnbits/lnbits#907]
JS should be able to check whether the browser supports NFC or not before the users presses the button. Applies to tpos, lnurlp, lnurlw extensions. Does this make sense @leesalminen?

<img width="400" alt="image" src="https://user-images.githubusercontent.com/93376500/185422250-5714ab2c-9cb5-4334-a2d8-d04a82f5481c.png">

**Comment by leesalminen** [comment]
Yes.

**Comment by leesalminen** [comment]
Can you assign this to me

**Comment by leesalminen** [comment]
PR opened.

**Comment by arcbtc** [comment]
This error is fine. Users know the thing does NFC, but the their device does not support it

**Comment by arcbtc** [comment]
Its a good error. Getting rid of the button doesnt make sense
