### ISSUE TITLE
High Availability Setup - Redundancy Support

### ISSUE THREAD

**Issue by jaro2k** [lnbits/lnbits#92]
First of all, this is so useful project. Thanks to all contributors!

Intro: We plan to use this layer to manage virtual accounts on large number of users. Because of that we need some stack redundancy.

Question: Is it possible to run this stack in active-active setup where Data directory will be located on shared storage accessible from multiple active LNbits instances?

Note: We would add load-balancer with sticky session setup at the front of the LNBits stack.

Thanks!

**Comment by arcbtc** [comment]
I don't see why it wouldn't work. You can set the data directory in .env. 
Try running two separate LNbits on the same machine and share the same directory
Good luck, feedback how you get on

**Comment by fiatjaf** [comment]
An SQLite database can't be written simultaneously by two processes.
In the near future we may add optional support for other databases, then it will be certainly possible.

**Comment by jaro2k** [comment]
yes, please do so.. if you going to use other db platform and make proper transaction handling.. committing transactions as frequent as possible.. having active-active setup should not be a problem.
