### ISSUE TITLE
Unable to navigate to extensions on mobile version

### ISSUE THREAD

**Issue by BenGWeeks** [lnbits/lnbits#948]
Might be being daft, but I don't see a way to navigate to the extensions on a mobile.

In the mobile version you see:

![image](https://user-images.githubusercontent.com/5950171/188997669-5ce67a9d-848b-4f2b-8f99-3d931a464692.png)

In the desktop version you see:

![image](https://user-images.githubusercontent.com/5950171/188997629-d6336275-1c5b-497b-8a75-2cee8314fa1b.png)

Specifically, I was trying to open it on the mobile, to easily copy the LNUrl addresses into NFC Tools on the mobile device.

In addition, the burger menu (top left) does not seem to do anything when clicked (I presume this should display the extensions)

Make: Apple
Model: iPhone 13 Pro Max
iOS: v15.6.1
Browser: Onion Browser v2.8.1

**Comment by BenGWeeks** [comment]
I can confirm that the burger menu does work in Edge (and presumably Chrome), however, if I use an HTTP address (not HTTPS, which is currently the norm for Umbrel) then the withdrawal links are not available (and not possible to create).

**Comment by callebtc** [comment]
Can someone else confirm that the burger menu doesn't work in iOS? I don't have a device i could test this with.

**Comment by Liongrass** [comment]
I was able to access the extensions menu by clicking on the burger menu at the top left using Safari in iOS 15.7.

**Comment by jchames** [comment]
I can confirm hamburger menu plus extensions accessible. IOS 16.0, iPhone 12 mini.![image](https://user-images.githubusercontent.com/32820389/190923599-2f7ce3e2-4fd3-481d-ac26-dd36790889bd.png)

**Comment by talvasconcelos** [comment]
Can we assume it's a browser bug? 
@BenGWeeks could you try either with another Tor browser, or other browsers using Orbot or something? I don't have an iOS device to test this!

**Comment by exorcist-transfix-welsh** [comment]
Similar issue now present in 0.9.4, on both mobile and desktop Firefox: extensions list doesn’t display

**Comment by BenGWeeks** [comment]
I was specifically using the Onion Browser for iOS (basically on iOS you have a choice of 1 recommended [Onion](https://apps.apple.com/us/app/onion-browser/id519296448) browser). It sounds like this browser has some issue with dynamic content such as ReCAPTCHA so probably not a code issue with LnBits specifically, just using something that is not well supported. Hoping you guys can implement a workaround as iOS users don't really have many options for browsing via Tor. (I can't see a way to get to the developer console to give you better info either from the Onion Browser).

**Comment by talvasconcelos** [comment]
Fixed in #1836
