### ISSUE TITLE
Languages/Localization

### ISSUE THREAD

**Issue by as-schug** [lnbits/lnbits#959]
Is there any translation/localization in lnbits project?
Any roadmap?

**Comment by callebtc** [comment]
There has been discussions about this just recently. @arcbtc @fusion44 sis you come to a conclusion which tools would be most appropriate for localizing LNbits?

**Comment by fusion44** [comment]
I'd use [Weblate](https://weblate.org/) to translate the actual files.  On the python side there is a nice library called [python-i18n](https://pypi.org/project/python-i18n/). Seems to be easy to implement.

**Comment by fusion44** [comment]
Just stumbled across this library:
https://babel.pocoo.org/en/latest/

Looks like a solid option.

**Comment by talvasconcelos** [comment]
Closed as it's being done in #1608
