### ISSUE TITLE
LNBits as Service

### ISSUE THREAD

**Issue by normandmickey** [lnbits/lnbits#96]
I'm trying to use LNBits independently from the Raspiblitz.  How do I start it as a service?  I copied the systemd service file from my Blitz and changed location of the LNBits folder but get the following error when trying to start the service.

[2020-09-20 14:55:40 +0100] [1478] [INFO] Starting gunicorn 20.0.4
[2020-09-20 14:55:40 +0100] [1478] [INFO] Listening at: http://127.0.0.1:5000 (1478)
[2020-09-20 14:55:40 +0100] [1478] [INFO] Using worker: gevent
[2020-09-20 14:55:40 +0100] [1489] [INFO] Booting worker with pid: 1489
Failed to find attribute 'app' in 'lnbits'.
[2020-09-20 14:55:41 +0100] [1489] [INFO] Worker exiting (pid: 1489)
[2020-09-20 14:55:41 +0100] [1478] [INFO] Shutting down: Master
[2020-09-20 14:55:41 +0100] [1478] [INFO] Reason: App failed to load.

**Comment by fiatjaf** [comment]
What version of LNBits are you running?

**Comment by normandmickey** [comment]
The latest.  Just git cloned and ran install.

**Comment by fiatjaf** [comment]
Run it with `python -m lnbits`.

Or replace the gunicorn line on the systemd file with `hypercorn --bind 0.0.0.0:5000 lnbits:app`, but I think systemd won't like work if lnbits is installed on a local directory with a virtualenv. It will need some tweaking.

**Comment by ChuckNorrison** [comment]
Hi, iam running the same issue on the raspiblitz after pull from master:

```
*** LAST 20 LNbits LOGS ***
sudo journalctl -u lnbits -b --no-pager -n20
-- Logs begin at Mon 2020-09-21 02:01:25 BST, end at Mon 2020-09-21 08:57:14 BST. --
Sep 21 08:56:32 raspberrypi sh[5857]: [2020-09-21 08:56:32 +0100] [5887] [INFO] Worker exiting (pid: 5887)
Sep 21 08:56:32 raspberrypi sh[5857]: [2020-09-21 08:56:32 +0100] [5858] [INFO] Shutting down: Master
Sep 21 08:56:32 raspberrypi sh[5857]: [2020-09-21 08:56:32 +0100] [5858] [INFO] Reason: App failed to load.
Sep 21 08:56:32 raspberrypi systemd[1]: lnbits.service: Main process exited, code=exited, status=4/NOPERMISSION
Sep 21 08:56:32 raspberrypi systemd[1]: lnbits.service: Failed with result 'exit-code'.
Sep 21 08:57:02 raspberrypi systemd[1]: lnbits.service: Service RestartSec=30s expired, scheduling restart.
Sep 21 08:57:02 raspberrypi systemd[1]: lnbits.service: Scheduled restart job, restart counter is at 5.
Sep 21 08:57:02 raspberrypi systemd[1]: Stopped lnbits.
Sep 21 08:57:02 raspberrypi systemd[1]: Started lnbits.
Sep 21 08:57:05 raspberrypi sh[6869]: Loading .env environment variables…
Sep 21 08:57:06 raspberrypi sh[6869]: [2020-09-21 08:57:06 +0100] [6870] [INFO] Starting gunicorn 20.0.4
Sep 21 08:57:06 raspberrypi sh[6869]: [2020-09-21 08:57:06 +0100] [6870] [INFO] Listening at: http://127.0.0.1:5000 (6870)
Sep 21 08:57:06 raspberrypi sh[6869]: [2020-09-21 08:57:06 +0100] [6870] [INFO] Using worker: gevent
Sep 21 08:57:06 raspberrypi sh[6869]: [2020-09-21 08:57:06 +0100] [7420] [INFO] Booting worker with pid: 7420
Sep 21 08:57:06 raspberrypi sh[6869]: Failed to find attribute 'app' in 'lnbits'.
Sep 21 08:57:06 raspberrypi sh[6869]: [2020-09-21 08:57:06 +0100] [7420] [INFO] Worker exiting (pid: 7420)
Sep 21 08:57:06 raspberrypi sh[6869]: [2020-09-21 08:57:06 +0100] [6870] [INFO] Shutting down: Master
Sep 21 08:57:06 raspberrypi sh[6869]: [2020-09-21 08:57:06 +0100] [6870] [INFO] Reason: App failed to load.
Sep 21 08:57:06 raspberrypi systemd[1]: lnbits.service: Main process exited, code=exited, status=4/NOPERMISSION
Sep 21 08:57:06 raspberrypi systemd[1]: lnbits.service: Failed with result 'exit-code'.
```

We use this ExecStart, seems :app gets lost in development? Whats the right way for ExecStart?
```

[Service]
WorkingDirectory=/home/lnbits/lnbits
ExecStart=/bin/sh -c 'cd /home/lnbits/lnbits && pipenv run gunicorn -b 127.0.0.1:5000 lnbits:app -k gevent'
```

**Comment by arcbtc** [comment]
Thats what the raspiblitz tag is for.
You have updated to an unstable version (as far as the blitz is concerned)
Once it has been tested properly and the install scripts updated, the tag will be updated

**Comment by ChuckNorrison** [comment]
I want to give some feedback. The raspiblitz tag got updated with huge improvements, iam very happy with the current LNBits state. Awesome work.
