### ISSUE TITLE
SPARK INTEGRATION: subtraction of strings in the get_payment_status method

### ISSUE THREAD

**Issue by mrbitcoiner** [lnbits/lnbits#966]
This is the error:
![image](https://user-images.githubusercontent.com/91642036/190179137-4dacc832-b599-44be-9950-3d437ddac5ce.png)

Happening because spark returns the values with msat suffix (string, not integer).

**Comment by mrbitcoiner** [comment]
I think that's all.

**Comment by callebtc** [comment]
Fixed in #967.
