### ISSUE TITLE
install instructions does not work No module named 'scss'

### ISSUE THREAD

**Issue by pseudozach** [lnbits/lnbits#969]
running `poetry install --no-dev` leads to

>  • Installing websocket-client (1.3.3)
  • Installing websockets (10.0)
Preparing build environment with build-system requirements poetry-core>=1.0.0
Traceback (most recent call last):
  File "/root/pz-lnbits-legend/build.py", line 105, in <module>
    build()
  File "/root/pz-lnbits-legend/build.py", line 100, in build
    transpile_scss()
  File "/root/pz-lnbits-legend/build.py", line 79, in transpile_scss
    from scss.compiler import compile_string  # type: ignore
ModuleNotFoundError: No module named 'scss'
Installing the current project: lnbits (0.1.0)

**Comment by irusensei** [comment]
I just had the same problem. If you try to run the program it runs but page shows no styling. I ran build.py directly without poetry and it worked.

Ah, also make sure you are absolutely using Python 3.9. Documentation doesn't state it but you also need python3.9-dev for for dependencies.

**Comment by pseudozach** [comment]
I think that was the problem as well. Probably need to make the instructions to explicitly say to use python3.9 and not python or python3 as those might be other versions.

**Comment by HamishMacEwan** [comment]
Same problem installing on a bitlaunch instance:

```
~/bin/lnbits/lnbits-legend$ uname -a
Linux 62cdea8a78d79d00011a3849 5.4.0-1009-kvm #9-Ubuntu SMP Mon Apr 20 20:23:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
Initial install output contained, among other things:

`Installing pyscss (1.3.7)`

Despite that:

```
File "/root/pz-lnbits-legend/build.py", line 79, in transpile_scss
from scss.compiler import compile_string # type: ignore
ModuleNotFoundError: No module named 'scss'
```

Tried the suggestions above.
```
sudo apt install python3.9-dev
poetry install --no-dev
```

Still errors.

`python3.9 /home/user/bin/lnbits/lnbits-legend/build.py`

Still errors.

**Comment by dni** [comment]
there is a fix now https://github.com/lnbits/lnbits/pull/989/files

**Comment by dni** [comment]
fix is merged.
