### ISSUE TITLE
Memo unused when description_hash or unhashed_description is set

### ISSUE THREAD

**Issue by Bashy** [lnbits/lnbits#974]
Anytime payments api (route `/api/v1/payments`) is called with `description_hash` or `unhashed_description` in the payload, `memo` is not used, `metadata` content is not used to fill any `memo` information, that leads to empty `memo` value.

Context: I'm developing a php script that allows to provide a lightning address with lnbits as a backend, and trying to use the `comment` feature with `commentAllowed > 0`.

It seems to be a normal behavior if we read the code [here](https://github.com/lnbits/lnbits-legend/blob/e7a6e86e7add238dce56f438aab491893e329a7e/lnbits/core/views/api.py#L153)
```go
async def api_payments_create_invoice(data: CreateInvoiceData, wallet: Wallet):
    if data.description_hash:
        try:
            description_hash = binascii.unhexlify(data.description_hash)
        except binascii.Error:
            raise HTTPException(
                status_code=HTTPStatus.BAD_REQUEST,
                detail="'description_hash' must be a valid hex string",
            )
        unhashed_description = b""
        memo = ""
    elif data.unhashed_description:
        try:
            unhashed_description = binascii.unhexlify(data.unhashed_description)
        except binascii.Error:
            raise HTTPException(
                status_code=HTTPStatus.BAD_REQUEST,
                detail="'unhashed_description' must be a valid hex string",
            )
        description_hash = b""
        memo = ""
    else:
        description_hash = b""
        unhashed_description = b""
        memo = data.memo or LNBITS_SITE_TITLE
    if data.unit == "sat":
        amount = int(data.amount)
    else:
        assert data.unit is not None, "unit not set"
        price_in_sats = await fiat_amount_as_satoshis(data.amount, data.unit)
        amount = price_in_sats
```

Is the `memo = ""` a wanted behavior?

ln request description field is also left unused.

**Comment by callebtc** [comment]
Hi, yes, this is wanted behaviour. You cannot set a memo for bolt11 invoices and a description hash at the same time. In fact, part of the reason why description hash exists is to avoid having to fit the data into a (short) memo.

**Comment by Bashy** [comment]
@callebtc I don't get how lnbits can retrieve the provided `comment` in the case of a lightning address payment.
