### ISSUE TITLE
LNDhub Invoice URL permissions

### ISSUE THREAD

**Issue by vv01f** [lnbits/lnbits#975]
commit version 41a9689014e40e2830bce53e519248172e56a53d

expected behavior:
* invoice URL should only give permissions to create invoices and list payments
* only admin URL should be able to send payments 

unexpected behaviour:
* invoice URL gives rights to spend funds, this tested positive unfortunately 

test setup
* created wallet, copied LNDhub "invoice URL", not the "admin URL"
* imported wallet as LNDhub "invoice URL" with Bluewallet
* funded wallet
* spent funds with Bluewallet successfully

the naming (for me) suggests that the invoice URL will give permissions to charge but not spend funds. this limitation is not the case.

maybe this in intended and could be clarified (fixing the descitpion, that reads "Invoice URLs mean the mobile wallet will only have the authorization to read your payments and invoices and generate new invoices." here) or it is not intended and should be fixed (maybe wrong macaroon?).

I am glad to look up anything to find the reason, just let me know what you deem to be done.
calle is in contact and got credentials to test yourself.

**Comment by ngutech21** [comment]
* imported a wallet with the "invoice URL" in BlueWallet like you described
* created an invoice in Wallet of satoshi
* payed the invoice in BlueWallet
* BlueWallet shows the screen that the invoice was paid successfully 
-> but there is no transaction in BlueWallet and the invoice wasn't paid in Wallet of satoshi.

Did your invoice really got paid or is this just a UI issue?

**Comment by vv01f** [comment]
@ngutech21 I also was surprised to say the least, but funds moved and I also reproduced with a new wallet which is available for insection to @callebtc already. You can find me in the Telegram group for direct contact.

**Comment by callebtc** [comment]
Thank you for reporting, will look into this.

**Comment by vv01f** [comment]
This is not about bluewallet or any other one that might import the invoice code.

As I wrote via DM… payment with invoice (not admin!) account (imported to bluewallet, not their fault) actually pays the invoices, so the sats do arrive and payments are finalized. Version 0.7.0 (sais git), commit 41a9689014e40e2830bce53e519248172e56a53d (sais web ui footer) as mentioned in opening post (this version was delivered with raspiblitz 1.7.2). Calle still has the invoice URL for the lndHub to test and verify himself. No alterations to the code have been done by me – git would tell me if I did accidentally.

I reconfirmed with two more payments on two different devices to 1) phoenix (payment arrived) and 2) another lnbits wallet (payment arrived).

**Comment by talvasconcelos** [comment]
@vv01f first of all, sorry for the inconvenience!

LNbits is on version 0.9.4, you should update Raspiblitz to latest 1.8, that packs LNbits v0.9.1! That was probably a bug on lndhub that got fixed in between. I can't reproduce what you describe on the latest version.

@callebtc we can probably close this issue?

**Comment by vv01f** [comment]
@callebtc @talvasconcelos seems the update fixed it (after backups for userdir, tor-keys and app-data  I uninstalled lnbits with the provided script and manually set the reinstall parameteters to 0.9.1 as delivered with the most recent raspiblitz image without updating the host itself) 

then the payment was rejected, right before update that was completing without any issue

`curl --socks5-hostname 127.0.0.1:9050 -X POST http://$onion/api/v1/payments -d '{"out": true, "bolt11": "'$invoice'"}' -H "X-Api-Key: $key" -H "Content-type: application/json"`

returns: `{"detail":"Invoice (or Admin) key required."}` – btw. the error message on bluewallet is more specific on admin key only – I like that.

I close as fixed by update… just thought it would be nice to know the fundamental reason.
