### ISSUE TITLE
Wallet not handling LNURLp redirects

### ISSUE THREAD

**Issue by bilalanees98** [lnbits/lnbits#976]
I have configure the LNURL https://btc.us/.well-known/lnurlp/bilall to redirect to https://getalby.com/lnurlp/bilall with the status code 301.
This means that is bilall@btc.us is added as recipient in the wallet, the wallet should send the payment to bilall@getalby.com.

However, adding bilall@btc.us throws a 503 error. Adding bilall@getalby.com works perfectly though.

Note: I was using the Legend demo server for this: https://legend.lnbits.com/

These screenshots show the btc.us redirect not working.
![lnbits btc 1](https://user-images.githubusercontent.com/62988673/190961753-f1a65774-74ab-42eb-b96d-32623b17c12e.jpeg)
![lnbits btc 2](https://user-images.githubusercontent.com/62988673/190961759-a3ba194b-2952-42a8-a1b0-a442d4fbee24.jpeg)

These show the getalby.com address working.
![lnbits getalby 1](https://user-images.githubusercontent.com/62988673/190961763-6756ef7c-6fdc-4782-aff7-45159cfde07a.jpeg)
![lnbits getalby 2](https://user-images.githubusercontent.com/62988673/190961741-db4f193c-427a-4ef6-95e8-ac06562bdd91.jpeg)

**Comment by pseudozach** [comment]
I think it makes sense to follow redirects for lightning addresses as domains should be able to redirect to other valid lightning addresses. I can volunteer to write a fix for this.

**Comment by pseudozach** [comment]
@talvasconcelos is it fixed? I haven't tested recently or is the spec updated to disallow following redirects?

**Comment by talvasconcelos** [comment]
Was asking because you mentioned a fix!

**Comment by pseudozach** [comment]
no I haven't fixed it. why should it be closed? it should either be fixed or it can be closed as spec compliant.
