### ISSUE TITLE
Export CSV button in wallet is broken

### ISSUE THREAD

**Issue by TrezorHannes** [lnbits/lnbits#977]
### Issue
Clicking on CSV doesn't prompt for a download, but adds new columns

### Screenshot
![image](https://user-images.githubusercontent.com/35168804/191066016-d3c3f502-770b-430e-8e98-678f1e4f2461.png)

### Version
- git pulled the latest version yesterday
- running via `/home/lnbits/lnbits-legend/venv/bin/uvicorn lnbits.__main__:app --port XXXX`

**Comment by ngutech21** [comment]
I can not reproduce this issue. When I click on export csv, the csv is downloaded as expected. 

Tested with multiple browsers on MacOS:
Firefox 105.0 (64-Bit)
Chromium 104.0.5080.0
Safari Version 16.0 (17614.1.25.9.10, 17614)

Git version: c5cc65a736606a6906a2e17adcfbceb33ddfedb6

Which browser are you using?

**Comment by TrezorHannes** [comment]
Thanks for coming back to me.

We've done some minor tweaks in `app.py` to ensure logging is disabled
```
    uvicorn_access = logging.getLogger("uvicorn.access")
    uvicorn_access.disabled = True
```
other than that, we're on the latest.
```
git status
HEAD detached at 0.9.2
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
        modified:   lnbits/app.py
```

Chrome Laptop: Version 105.0.5195.112 (Official Build) (64-bit)
Just tried exporting CSV on Chrome Android phone and can't reproduce the error there.
So it might be a browser issue. I'm updating now and check next if the console can provide some more insights. Keeping you posted

**Comment by TrezorHannes** [comment]
After the update and reboot, it's resolved and CSV downloads successfully.

However, I've validated on 2 other browsers and another user, that once every time you click on "Export", another ghost column gets added. See attached screenshot in OP. 
You mind verifying this in your setup @ngutech21?

**Comment by ngutech21** [comment]
@TrezorHannes the export works fine, but as you mentioned there is a column added everytime someone hits the button. I fixed it by copying the array first, so the column doesn't get added to the paymentsTable, but is only visible in the export

**Comment by dni** [comment]
thanks for reporting my PR fixes the issue, was an oversight on my part, sorry! will be merged soon.
