### ISSUE TITLE
LNBITS_ALLOWED_USERS allows creation of new users

### ISSUE THREAD

**Issue by fiatjaf** [lnbits/lnbits#98]
Is that its original intent?

I would think it would forbid anyone from creating new users.
It's an easy fix, I think, but I'm not sure if that is the expected behavior.

**Comment by arcbtc** [comment]
Its a list of user IDs who who can access an LNbits install, so a LNbits owner could limit who has access to their install

**Comment by arcbtc** [comment]
Its actually a useful feature, for someone who wants LNbits functionality, but doesn't want to become a custodian for the rest of the world
