### ISSUE TITLE
Button Padding Strange - different bundle.css compilations

### ISSUE THREAD

**Issue by rootzoll** [lnbits/lnbits#99]
When I installed the latest master of lnbits on my RaspiBlitz U was seeing that all Buttons had a strange padding and also some other graphocal elements were slightly misplace:
![Bildschirmfoto 2020-09-28 um 16 15 47](https://user-images.githubusercontent.com/2472225/94460116-8f9d6800-01b8-11eb-8b50-a6f286258f14.png)

On Bens local install it looked fine when running the master branch .. whe compared our two instances and found that we have a difference in our `bundle.css` files.

Mine broken looked like:
![Bildschirmfoto 2020-09-28 um 18 27 43](https://user-images.githubusercontent.com/2472225/94460255-bd82ac80-01b8-11eb-9f34-a50efe274762.png)

Bens OK one looked like:
![Bildschirmfoto 2020-09-28 um 18 27 06](https://user-images.githubusercontent.com/2472225/94460335-dc813e80-01b8-11eb-92e9-c6f9cf47bd43.png)

Why did we eneded up with different `bundle.css`files? How can I get on the RaspiBlitz the same result as Ben?

For background: Here is the latest LNbits install scrip we use on the RaspiBlitz (just in case it has something todo with dependencies or other methods of install): https://github.com/rootzoll/raspiblitz/blob/aa1a0dcc53236542bcfd12ad893814354be7613e/home.admin/config.scripts/bonus.lnbits.sh#L176

**Comment by arcbtc** [comment]
I think this is a Blitz specific issue due to the chart css breaking the quasar CSS. Not sure how the bundle thing works, maybe @eillarra could take a look

**Comment by fiatjaf** [comment]
So it seems the issue was that the new bundle assets weren't being generated because the new command to generate assets was missing. This was fixed on https://github.com/lnbits/lnbits/pull/100.

(The command must be run if you're going to run the app with `hypercorn`. If you do it with `python -m lnbits` the command is ran automatically before the app starts.)

**Comment by rootzoll** [comment]
OK I got it now running with `hypercorn` and I am doing the `quart migrate` and `quart assets` on installation - see here in my testing branch: https://github.com/rootzoll/raspiblitz/blob/cd4fa705e67d7d718e0d42cb0b9d7638bc3934e7/home.admin/config.scripts/bonus.lnbits.sh#L291

But the css is still the one with the broken one with `chart.min.css` in beginng and buttons still look funky. Open for any further idea to try.

**Comment by fiatjaf** [comment]
Can you delete the `bundle.css` then regenerate and see what happens? My only hypothesis here is that it isn't being generated after all, because the generation process is literally just concatenating file contents.

**Comment by fiatjaf** [comment]
@rootzoll said:

> OK cool ... now its loading again and it does not look broken anymore :) It still has the button css thing #99  but thats makeup.
> 
> ![Bildschirmfoto 2020-10-05 um 19 46 33](https://user-images.githubusercontent.com/2472225/95113983-86297800-0743-11eb-89cf-45df8b74669d.png)
> 
> I tested the voucher fallback call and the "hanging forever" is gone. After I press "Claim Bitcoin" I get to a LNbits wallet on my mobile phone that is a "balance of zero". When I enter the wallet I see shortly "processing transaction" but after that it stays at balance zero. Tested another voucher before with Wallet of Satoshi - that one worked.
> 
> ![Screenshot_20201005-194800_Samsung Internet](https://user-images.githubusercontent.com/2472225/95114361-19fb4400-0744-11eb-983c-6783660891fd.jpg)
> 
> How can I help to debug this further?

**Comment by fiatjaf** [comment]
I still don't know. I would ask you to check again if `bundle.css` is matching one generated in a normal computer. It could be that. I realized the asset concatenation function isn't deterministic. I had manually pinned which assets should come first and last, but I didn't do that for every. Maybe I should make it deterministic, let's see.

**Comment by rootzoll** [comment]
When I build and open it in my laptop buttons look OK and if I compare the `bundle.css` I can see the same difference between it running on my RaspBlitz as discribed in opening post on this issue.

**Comment by fiatjaf** [comment]
Well, it doesn't seem to be anything related to CSS. I tried reordering, deleting CSS files and got nothing. I think the CSS for these buttons is entirely controlled by Quasar and all Quasar CSS ships in a single immutable CSS file anyway.

I have no idea of what to try next.

**Comment by rootzoll** [comment]
I added debug output to `bundle_vendored` and you can see here that it builds the CSS in a different order on my RaspiBlitz than on my Laptop:

Laptop:
![Bildschirmfoto 2020-10-07 um 14 37 49](https://user-images.githubusercontent.com/2472225/95337029-b2630700-08b1-11eb-829c-975cbb0222e0.png)

RaspiBlitz:
![Bildschirmfoto 2020-10-07 um 15 21 11](https://user-images.githubusercontent.com/2472225/95337045-b8f17e80-08b1-11eb-8675-f7d33a5087b4.png)

@fiatjaf is there a way to make this the same just to rule out that this is the source of the difference?

**Comment by fiatjaf** [comment]
Ok, we're now pre-sorting the paths so it should be the same order everywhere. It wasn't sorted here previously but now it is, and the styles still work, so hopefully they will work everywhere now.

GitHub closed the issue automatically because I mentioned it in the commit message, please reopen if this doesn't fix it.

I'm also interested in knowing where exactly you were logging up there, because we shouldn't be bundling repeated versions of the same file (minified and non-minified etc.) like it seems to be the case above. If that is happening then that is the problem, probably.

**Comment by rootzoll** [comment]
I just used the latest master branch to build/install LNbits again on the RaspiBlitz - css was sadly still broken. I now changed to a quickfix, shipping a correctly build `bundle.css` with the RaspiBlitz and overwriting the broken one after build ... so that this will no longer hold up the release of the v1.6.1 release of RaspiBlitz.

I marked for v1.7 RaspiBlitz to further analyse this problem and replace this quick fix with a real solution ... but for now I think we have to work with this.

**Comment by fiatjaf** [comment]
And it worked fine when you did that?

**Comment by rootzoll** [comment]
yes .. just replacing that one file worked. Looks good now.

**Comment by fiatjaf** [comment]
I have finally faced this issue on my local installation.
It happens when the Chart.js CSS is loaded before the Quasar CSS.
