### ISSUE TITLE
Broken features when LNbits has LNbits as funding source

### ISSUE THREAD

**Issue by cryptoteun** [lnbits/lnbits#991]
I ran into a few issues when using LNbits as funding source. Up until now I have tested items below:

**Issues**
- Payment of regular invoice: webhook not send after payment is received
- Payment of LNURLp: webhook not send after payment is received
- Split payments: split is not triggered

**Working fine**
- TipJar: call to url after payment
- Scrub: forward to LNAddress
- LNURLw: webhook after withdraw is send

**Comment by dni** [comment]
i am planning on putting lnbits funding source into our integration tests, which should shed lights on those issues, but at the moment i am too busy with other tasks :/

**Comment by talvasconcelos** [comment]
Fixed with #1205

**Comment by cryptoteun** [comment]
Can confirm it's working in the current version 🎉
